###############################################################
# Makefile.config
# Platform-specific settings
# 请根据编译的平台架构和依赖更改!
#
###############################################################
# 目录名作为库名字
MODULE_DIR := $(shell basename "$$PWD")

# 编译标志
# 设置用于编译一个多线程安全的、启用严格警告、并遵循ISO C标准的程序(-pedantic)。
# 共享库必须包含: -fPIC
# _DEFAULT_SOURCE: 使用GNU C库的默认定义
CFLAGS += -D_REENTRANT -D_DEFAULT_SOURCE -std=gnu99 -Wall -fPIC

# 根据构建类型设置编译选项
BUILD_TYPE ?= $(DEFAULT_BUILD_TYPE)
ifeq ($(BUILD_TYPE),debug)
    CFLAGS += -g -O0 -DDEBUG
else
    CFLAGS += -O2 -DNDEBUG
endif

# 链接标志
LDFLAGS += -L. -L/usr/lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/local/lib -L$(TARGET_PREFIX)/libs -lpthread -lm

INCLUDES += -I. -I..

# 平台特定文件
MINGW_CSRCS :=

# 静态链接
TARGET_LDFLAGS += $(TARGET_PREFIX)/libs/libcommon.a $(TARGET_PREFIX)/libs/libconvd.a

# MinGW/Cygwin/Linux
ifeq ($(MINGW_FLAG),1)
    # MinGW
    # 链接标志
    LDFLAGS += -L/mingw64/lib -L/mingw64/lib/mimalloc-2.2 -l:libmimalloc.a -ltcl86 -lclogger

    # !! 不可以包含: /usr/include (因为实际指向：$MSYS2_ROOT/usr/include/inttypes.h)
    # 包含 MinGW 路径
    INCLUDES += -I/mingw64/include

    # Windows 版本目标 - 确保足够新
    CFLAGS += -D_WIN32_WINNT=0x0601 -DWINVER=0x0601 -DNTDDI_VERSION=0x06010000

    # 链接 Windows 库，确保被依赖的库放在后面
    TARGET_LDFLAGS += -lws2_32 -ladvapi32 -luser32 -lkernel32 -lpsapi

else ifeq ($(CYGWIN_FLAG),1)
    LDFLAGS += -lrt -ltcl8.6 -l:libclogger.so -l:liblog4tcl.so

    # 包含路径：使用Cygwin的/usr/include，避免MinGW的路径
    INCLUDES += -I/usr/include -I/usr/local/include
else
    LDFLAGS += -lrt -ltcl8.6 -lclogger -llog4tcl

    INCLUDES += -I/usr/include -I/usr/local/include -I/usr/include/tcl
endif

# 需要排除的 C 源文件
EXCLUDE_CSRCS :=