/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file loggermgr.h
 * @brief logger manager
 *
 * @author Liang Zhang <350137278@qq.com>
 * @copyright © 2024-2025 mapaware.top All Rights Reserved.
 * @version 1.1.8
 *
 * @since 2019-12-17 21:53:05
 * @date 2025-11-29 18:27:57
 */
#ifndef LOGGER_MGR_H__
#define LOGGER_MGR_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <common/unitypes.h>
#include <common/cstrbuf.h>
#include <common/rtclock.h>

#include <common/ringbufst.h>
#include <common/ringbuf.h>
#include <common/emerglog.h>

#ifdef CLOGGER_SHMGR_HANDLE
# include <common/shmipc.h>
#endif

#include <common/md5sum.h>
#include <common/smallregex.h>   /* https://gitlab.com/relkom/small-regex */
#include <common/uthash_incl.h>

#include <common/rwlock.h>
#include <common/unsema.h>
#include <common/uatomic.h>

/* using pthread or pthread-w32 */
#include <sched.h>
#include <pthread.h>

#if defined(PLATFORM_WINDOWS)
    // MSVC required: syslog-client.c
    #include <common/win32/syslog.h>
#else
    #include <syslog.h>
#endif

#include "clogger_api.h"

#define LOGGERS_NUM_MAX  255
struct clogger_version_mgr_t
{
    struct {
        ub2 major_version;
        ub2 minor_version;
        ub2 patch_version;
    };

    struct {
        char build_date[14];
        char build_time[10];
    };

    int pid;
    UAtomicPtr pvmgr;
};


struct logger_manager_t
{
    UAtomicInt64 refcount;

    /* default logger if not null */
    clog_logger default_logger;

    ThreadRWLock_t rwlock;

    rtclock_t rtclock;

    /* logger by id */
    clog_logger idloggers[256];

    cstrbuf workdir;  // cwd - current work dir
    cstrbuf procdir;  // cpd - current process dir

    cstrbuf cfgfile;
    struct clogger_ident_t *loggers;
};


struct clogger_ident_t
{
    clog_logger logger;

    /* makes this structure hashable */
    UT_hash_handle hh;

    /* key name for clogger */
    int idlen;
    char ident[];
};

#ifdef    __cplusplus
}
#endif

#endif /* LOGGER_MGR_H__ */
