/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/*
** @file logger_helper.h
**  clogger api helper functions.
**
** @author Liang Zhang <350137278@qq.com>
** @version 1.0.2
** @since 2019-12-17 21:53:05
** @date 2025-02-15 22:54:11
**
** @note
**   This file is NOT a part of libclogger.
**   You can change it as your will.
*/
#ifndef LOGGER_HELPER_API_H_
#define LOGGER_HELPER_API_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "clogger_api.h"

#ifndef CLOG_TRACE_MSGWAIT
# define CLOG_TRACE_MSGWAIT  CLOG_MSGWAIT_NOWAIT
#endif

#ifndef CLOG_DEBUG_MSGWAIT
# define CLOG_DEBUG_MSGWAIT  CLOG_MSGWAIT_NOWAIT
#endif

#ifndef CLOG_INFO_MSGWAIT
# define CLOG_INFO_MSGWAIT  CLOG_MSGWAIT_INSTANT
#endif

#ifndef CLOG_WARN_MSGWAIT
# define CLOG_WARN_MSGWAIT  CLOG_MSGWAIT_INSTANT
#endif

#ifndef CLOG_ERROR_MSGWAIT
# define CLOG_ERROR_MSGWAIT  CLOG_MSGWAIT_INFINITE
#endif

#ifndef CLOG_FATAL_MSGWAIT
# define CLOG_FATAL_MSGWAIT  CLOG_MSGWAIT_INFINITE
#endif


#if defined(_MSC_VER) // MSVC (Windows) =>

#define CLOG_TRACE(logger, message, ...)  do { \
                if (clog_logger_level_enabled((logger), CLOG_LEVEL_TRACE)) { \
                    clog_logger_log_format((logger), CLOG_LEVEL_TRACE, CLOG_TRACE_MSGWAIT, __FILE__, __LINE__, __FUNCTION__, message, ##__VA_ARGS__); \
                } \
            } while(0)


#define CLOG_DEBUG(logger, message, ...)  do { \
                if (clog_logger_level_enabled((logger), CLOG_LEVEL_DEBUG)) { \
                    clog_logger_log_format((logger), CLOG_LEVEL_DEBUG, CLOG_DEBUG_MSGWAIT, __FILE__, __LINE__, __FUNCTION__, message, ##__VA_ARGS__); \
                } \
            } while(0)


#define CLOG_INFO(logger, message, ...)  do { \
                if (clog_logger_level_enabled((logger), CLOG_LEVEL_INFO)) { \
                    clog_logger_log_format((logger), CLOG_LEVEL_INFO, CLOG_INFO_MSGWAIT, __FILE__, __LINE__, __FUNCTION__, message, ##__VA_ARGS__); \
                } \
            } while(0)


#define CLOG_WARN(logger, message, ...)  do { \
                if (clog_logger_level_enabled((logger), CLOG_LEVEL_WARN)) { \
                    clog_logger_log_format((logger), CLOG_LEVEL_WARN, CLOG_WARN_MSGWAIT, __FILE__, __LINE__, __FUNCTION__, message, ##__VA_ARGS__); \
                } \
            } while(0)


#define CLOG_ERROR(logger, message, ...)  do { \
                if (clog_logger_level_enabled((logger), CLOG_LEVEL_ERROR)) { \
                    clog_logger_log_format((logger), CLOG_LEVEL_ERROR, CLOG_ERROR_MSGWAIT, __FILE__, __LINE__, __FUNCTION__, message, ##__VA_ARGS__); \
                } \
            } while(0)


#define CLOG_FATAL(logger, message, ...)  do { \
                if (clog_logger_level_enabled((logger), CLOG_LEVEL_FATAL)) { \
                    clog_logger_log_format((logger), CLOG_LEVEL_FATAL, CLOG_FATAL_MSGWAIT, __FILE__, __LINE__, __FUNCTION__, message, ##__VA_ARGS__); \
                } \
            } while(0)


#define CLOG_FATAL_EXIT(logger, message, ...)  do { \
                if (clog_logger_level_enabled((logger), CLOG_LEVEL_FATAL)) { \
                    clog_logger_log_format((logger), CLOG_LEVEL_FATAL, CLOG_FATAL_MSGWAIT, __FILE__, __LINE__, __FUNCTION__, message, ##__VA_ARGS__); \
                } \
                exit(EXIT_FAILURE); \
            } while(0)

#else  // GCC (Linux, MingW)

#define CLOG_TRACE(logger, message, args...)  do { \
                if (clog_logger_level_enabled((logger), CLOG_LEVEL_TRACE)) { \
                    clog_logger_log_format((logger), CLOG_LEVEL_TRACE, CLOG_TRACE_MSGWAIT, __FILE__, __LINE__, __FUNCTION__, message, ##args); \
                } \
            } while(0)


#define CLOG_DEBUG(logger, message, args...)  do { \
                if (clog_logger_level_enabled((logger), CLOG_LEVEL_DEBUG)) { \
                    clog_logger_log_format((logger), CLOG_LEVEL_DEBUG, CLOG_DEBUG_MSGWAIT, __FILE__, __LINE__, __FUNCTION__, message, ##args); \
                } \
            } while(0)


#define CLOG_INFO(logger, message, args...)  do { \
                if (clog_logger_level_enabled((logger), CLOG_LEVEL_INFO)) { \
                    clog_logger_log_format((logger), CLOG_LEVEL_INFO, CLOG_INFO_MSGWAIT, __FILE__, __LINE__, __FUNCTION__, message, ##args); \
                } \
            } while(0)


#define CLOG_WARN(logger, message, args...)  do { \
                if (clog_logger_level_enabled((logger), CLOG_LEVEL_WARN)) { \
                    clog_logger_log_format((logger), CLOG_LEVEL_WARN, CLOG_WARN_MSGWAIT, __FILE__, __LINE__, __FUNCTION__, message, ##args); \
                } \
            } while(0)


#define CLOG_ERROR(logger, message, args...)  do { \
                if (clog_logger_level_enabled((logger), CLOG_LEVEL_ERROR)) { \
                    clog_logger_log_format((logger), CLOG_LEVEL_ERROR, CLOG_ERROR_MSGWAIT, __FILE__, __LINE__, __FUNCTION__, message, ##args); \
                } \
            } while(0)


#define CLOG_FATAL(logger, message, args...)  do { \
                if (clog_logger_level_enabled((logger), CLOG_LEVEL_FATAL)) { \
                    clog_logger_log_format((logger), CLOG_LEVEL_FATAL, CLOG_FATAL_MSGWAIT, __FILE__, __LINE__, __FUNCTION__, message, ##args); \
                } \
            } while(0)


#define CLOG_FATAL_EXIT(logger, message, args...)  do { \
                if (clog_logger_level_enabled((logger), CLOG_LEVEL_FATAL)) { \
                    clog_logger_log_format((logger), CLOG_LEVEL_FATAL, CLOG_FATAL_MSGWAIT, __FILE__, __LINE__, __FUNCTION__, message, ##args); \
                } \
                exit(EXIT_FAILURE); \
            } while(0)

#endif // <= GCC
///////////////////////////////////////////////////////////////////////


#ifdef __cplusplus
}
#endif
#endif /* LOGGER_HELPER_API_H_ */
