/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file loggermgr.c
 * @brief logger manager
 *
 * @author Liang Zhang <350137278@qq.com>
 * @copyright © 2024-2025 mapaware.top All Rights Reserved.
 * @version 1.1.7
 *
 * @since 2019-12-11 10:34:05
 * @date 2025-11-29 18:27:57
 */
#include "loggermgr.h"
#include "loggerconf.h"

#include <common/pathlib.h>


#if defined(PLATFORM_WINDOWS)
# define CLOG_DEFAULT_PATHPREFIX   "C:\\var\\log\\clogger\\"
#elif defined (PLATFORM_CYGWIN)
# define CLOG_DEFAULT_PATHPREFIX   "/cygdrive/c/var/log/clogger/"
#else
# define CLOG_DEFAULT_PATHPREFIX   "/var/log/clogger/"
#endif


// 定义版本常量
#define CLOGGER_VERSION_MAJOR   2
#define CLOGGER_VERSION_MINOR   2
#define CLOGGER_VERSION_PATCH   1

static const char clogger_version_string[] = "2.2.1";

static pthread_mutex_t init_mutex = PTHREAD_MUTEX_INITIALIZER;


#ifdef CLOGGER_SHMGR_HANDLE
static shmhandle_t shmgr_handle = shmipc_invalid_handle;
#endif


static struct clogger_version_mgr_t clogger_singleton = {
    {CLOGGER_VERSION_MAJOR, CLOGGER_VERSION_MINOR, CLOGGER_VERSION_PATCH},
    {__DATE__, __TIME__},
    0,
    NULL
};


const char* libclogger_version(int* major_verno, int* minor_verno, int* patch_verno)
{
    if (major_verno) {
        *major_verno = CLOGGER_VERSION_MAJOR;
    }
    if (minor_verno) {
        *minor_verno = CLOGGER_VERSION_MINOR;
    }
    if (patch_verno) {
        *patch_verno = CLOGGER_VERSION_PATCH;
    }
    return clogger_version_string;
}


static void initialize_manager(void)
{
    clogger_singleton.pid = getprocessid();
    clogger_singleton.pvmgr = mem_calloc(1, sizeof(struct logger_manager_t));

#ifdef CLOGGER_SHMGR_HANDLE
    shmkey_t shmkey;
#if defined(PLATFORM_WINDOWS) || defined(PLATFORM_CYGWIN)
    char keybuf[128];
    shmkey = shmipc_keygen(".clogger-shared-manager.shm", getprocessid(), keybuf, sizeof(keybuf));
#else
    cstrbuf keyfile = get_proc_pathfile();
    shmkey = shmipc_keygen(keyfile->str, getprocessid());
    if (shmkey == -1) {
        char errmsg[ERROR_STRING_LEN_MAX];
        emerglog_exit("libclogger", "shmipc_keygen error(%d): %s",
            errno, format_posix_syserror(errno, errmsg, sizeof(errmsg)));
    }
    cstrbufFree(&keyfile);
#endif

    shmgr_handle = shmipc_create(shmkey, &clogger_singleton, sizeof(clogger_singleton), 0, 0);
    if (shmgr_handle == shmipc_invalid_handle) {
        char errmsg[ERROR_STRING_LEN_MAX];
#if defined(PLATFORM_WINDOWS) || defined(PLATFORM_CYGWIN)
        emerglog_exit("libclogger", "shmipc_create error(%d): %s",
            errno, format_win32_syserror(errno, errmsg, sizeof(errmsg)));
#else
        emerglog_exit("libclogger", "shmipc_create error(%d): %s",
            errno, format_posix_syserror(errno, errmsg, sizeof(errmsg)));
#endif
    }
#endif
}


static logger_manager get_logger_manager_shared()
{
#ifdef CLOGGER_SHMGR_HANDLE
    struct clogger_version_mgr_t outmgr = { 0 };
    shmkey_t shmkey;

#if defined(PLATFORM_WINDOWS) || defined(PLATFORM_CYGWIN)
    char keybuf[128];
    shmkey = shmipc_keygen(".clogger-shared-manager.shm", getprocessid(), keybuf, sizeof(keybuf));
#else
    cstrbuf keyfile = get_proc_pathfile();
    shmkey = shmipc_keygen(keyfile->str, getprocessid());
    if (shmkey == -1) {
        char errmsg[ERROR_STRING_LEN_MAX];
        emerglog_exit("libclogger", "shmipc_keygen error(%d): %s",
            errno, format_posix_syserror(errno, errmsg, sizeof(errmsg)));
    }
    cstrbufFree(&keyfile);
#endif

    if (shmipc_read(shmkey, &outmgr, sizeof(outmgr), 0) == -1) {
        emerglog_exit("libclogger", "shmipc_read error(%d)", errno);
    }

    /* check libclogger version and build time and pid */
    clogger_singleton.pid = getprocessid();
    if (!memcmp(&clogger_singleton, &outmgr, 32)) {
        return (logger_manager)outmgr.pvmgr;
    }
    return NULL;
#endif

    return (logger_manager) clogger_singleton.pvmgr;
}


static clog_logger  logger_manager_load_shared(logger_manager mgr, const char* ident)
{
    if (!ident) {
        return mgr->default_logger;
    }

    if (RWLockAcquire(&mgr->rwlock, RWLOCK_STATE_READ, 0) != 0) {
        emerglog_error_exit("libclogger", "RWLockAcquire");
    }

    if (! mgr->cfgfile) {
        RWLockRelease(&mgr->rwlock, RWLOCK_STATE_READ);
        emerglog_error_exit("libclogger", "config file not found");
    }

    clog_logger logger = NULL;
    struct clogger_ident_t* elt;

    /* uthash is not threads-safety! */
    HASH_FIND_STR(mgr->loggers, ident, elt);
    if (elt) {
        logger = elt->logger;
        RWLockRelease(&mgr->rwlock, RWLOCK_STATE_READ);
        /* success get an existed logger */
        return logger;
    }

    /* not found, reload config file to find logger */
    RWLockRelease(&mgr->rwlock, RWLOCK_STATE_READ);

    /* re-lock for write */
    if (RWLockAcquire(&mgr->rwlock, RWLOCK_STATE_WRITE, 0) != 0) {
        emerglog_error_exit("libclogger", "RWLockAcquire");
    }

    /* refind logger again */
    HASH_FIND_STR(mgr->loggers, ident, elt);
    if (elt) {
        logger = elt->logger;
        RWLockRelease(&mgr->rwlock, RWLOCK_STATE_WRITE);
        /* success get an existed logger */
        return logger;
    }

    /* logger not found and we got write lock here */
    int maxloggerid = PtrToInt(mgr->idloggers[0]);
    if (maxloggerid < LOGGERS_NUM_MAX) {
        clogger_conf_t conf = { 0 };
        logger_conf_init_default(&conf, ident, CLOG_DEFAULT_PATHPREFIX, 0);
        elt = (struct clogger_ident_t*)mem_calloc(1, sizeof(struct clogger_ident_t) + conf.ident->len + 1);
        elt->idlen = conf.ident->len;
        memcpy(elt->ident, conf.ident->str, elt->idlen);
        if (logger_conf_load_config(mgr->cfgfile->str, elt->ident, &conf) != 0) {
            logger_conf_final_release(&conf);
            mem_free(elt);
            RWLockRelease(&mgr->rwlock, RWLOCK_STATE_WRITE);
            return NULL;
        }

        /* create a new logger and add into uthash */
        conf.loggerid = maxloggerid + 1;
        logger = clog_logger_create(&conf, mgr);
        if (logger) {
            elt->logger = logger;
            maxloggerid = clog_logger_get_loggerid(elt->logger);
            mgr->idloggers[maxloggerid] = elt->logger;
            mgr->idloggers[0] = (clog_logger)IntToPtr(maxloggerid);
            HASH_ADD_STR_LEN(mgr->loggers, ident, elt->idlen, elt);
        }
    }
    RWLockRelease(&mgr->rwlock, RWLOCK_STATE_WRITE);
    return logger;
}


static clog_logger logger_manager_get_shared(logger_manager mgr, int loggerid)
{
    clog_logger logger = NULL;

    if (! RWLockAcquire(&mgr->rwlock, RWLOCK_STATE_READ, 0)) {
        if (loggerid == 0) {
            // get the first logger
            logger = mgr->idloggers[1];
            goto return_logger;
        }

        if (loggerid == -1) {
            // get the last logger
            int lastid = PtrToInt(mgr->idloggers[0]);
            logger = mgr->idloggers[lastid];
            goto return_logger;
        }

        if (loggerid > 0 && loggerid <= LOGGERS_NUM_MAX) {
            // get logger by id
            logger = mgr->idloggers[loggerid];
            goto return_logger;
        }

    return_logger:
        RWLockRelease(&mgr->rwlock, RWLOCK_STATE_READ);
    }

    return logger;
}


///////////////////////////////////////////////////////////////////////
// logger manager api

/**
 * @brief 初始化日志管理器
 *
 * 此函数用于初始化日志管理器，接受一个日志配置字符串和一系列标识符。
 * 标识符列表以可变参数形式传递，并以NULL指针结尾。
 * logger_manager_init 与 logger_manager_uninit 必须成对调用
 *
 * @param clogger_cfg_dir 日志配置文件 clogger.cfg 所在的目录全路径（可以为 NULL，自动搜索配置文件）
 * @param idents 日志 ident 名称数组
 * @param count 数组元素个数
 * @return 无返回值，必须成功
 *
 * @example
 *   const char *idents[] = {
 *       "app",
 *       "test",
 *       0
 *   };
 *   logger_manager_init(NULL, idents);
 *
 * 配置文件 clogger.cfg 搜索次序：
 *   1）当前进程工作目录
 *   2）当前进程工作目录/conf
 *   3）CLOGGER_CFG_DIR
 *   4）/etc/clogger/
 */
clog_errcode_t logger_manager_init(const char* clogger_cfg_dir, const char* idents[])
{
    clog_errcode_t errcode = CLOG_ERRCODE_NO_ERROR;

    pthread_mutex_lock(&init_mutex);

    logger_manager mgr = get_logger_manager();
    if (! mgr) {
        initialize_manager();
        mgr = get_logger_manager();
        emerglog_check_nullptr(mgr, "libclogger", "get_logger_manager");

        mgr->workdir = get_proc_cwd(1);
        emerglog_check_nullptr(mgr->workdir, "libclogger", "get_proc_cwd");

        mgr->procdir = get_proc_abspath(1);
        emerglog_check_nullptr(mgr->procdir, "libclogger", "get_proc_abspath");

        mgr->rtclock = rtclock_init(RTCLOCK_FREQ_SEC);

        RWLockInit(&mgr->rwlock);
        if (RWLockAcquire(&mgr->rwlock, RWLOCK_STATE_WRITE, 0) != 0) {
            emerglog_error_exit("libclogger", "RWLockAcquire");
        }

        char message[256];
        int messagelen;

    #if defined(PLATFORM_WINDOWS) || defined(PLATFORM_CYGWIN)
        mgr->cfgfile = find_config_file(clogger_cfg_dir, "clogger.cfg", "CLOGGER_CFG_DIR", "C:/var/log");
    #else
        mgr->cfgfile = find_config_file(clogger_cfg_dir, "clogger.cfg", "CLOGGER_CFG_DIR", "/etc/clogger");
    #endif

        RWLockRelease(&mgr->rwlock, RWLOCK_STATE_WRITE);

        if (! file_exists(CBSTR(mgr->cfgfile))) {
            messagelen = snprintf(message, sizeof(message),
                "(loggermgr.c:%d %s) config file not exists: `%.*s`",
                __LINE__, __func__,
                CBSTRLEN(mgr->cfgfile), CBSTR(mgr->cfgfile));
            emerg_syslog_message(0, 0, "libclogger", message, messagelen);
            errcode = CLOG_ERRCODE_CFGFILE_NOT_EXISTS;
            goto return_errcode;
        }

        int i = 0;
        while (idents) {
            if (i >= LOGGERS_NUM_MAX) {
                messagelen = snprintf(message, sizeof(message),
                    "(loggermgr.c:%d %s) too many idents",
                    __LINE__, __func__);
                emerg_syslog_message(0, 0, "libclogger", message, messagelen);
                errcode = CLOG_ERRCODE_TOO_MANY_IDENTS;
                goto return_errcode;
            }

            const char *ident = idents[i++];
            int identlen = cstr_length(ident, CLOG_IDENT_LEN_MAX + 1);
            if (!identlen) {
                break;
            }
            if (identlen > CLOG_IDENT_LEN_MAX) {
                messagelen = snprintf(message, sizeof(message),
                    "(loggermgr.c:%d %s) ident is too long: `%.*s`",
                    __LINE__, __func__, identlen, ident);
                emerg_syslog_message(0, 0, "libclogger", message, messagelen);
                errcode = CLOG_ERRCODE_IDENT_TOO_LONG;
                goto return_errcode;
            }

            clog_logger logger = logger_manager_load_shared(mgr, ident);
            if (! logger) {
                messagelen = snprintf(message, sizeof(message),
                    "(loggermgr.c:%d %s) ident not found: `%s`",
                    __LINE__, __func__, ident);
                emerg_syslog_message(0, 0, "libclogger", message, messagelen);
                errcode = CLOG_ERRCODE_IDENT_NOT_FOUND;
                goto return_errcode;
            }

            if (! mgr->default_logger) {
                // 设置默认 logger
                mgr->default_logger = logger;
            }
        }
    }

    // 成功返回: 0
    // 增加引用计数
    UAtomicInt64Add(&mgr->refcount);
    pthread_mutex_unlock(&init_mutex);
    return CLOG_ERRCODE_NO_ERROR;

return_errcode:
    pthread_mutex_unlock(&init_mutex);
    return errcode;
}


void logger_manager_uninit(void)
{
    pthread_mutex_lock(&init_mutex);

    logger_manager mgr = get_logger_manager();
    if (mgr) {
        if (UAtomicInt64Sub(&mgr->refcount) == 1) {
            RWLockAcquire(&mgr->rwlock, RWLOCK_STATE_WRITE, 0);

            // delete all loggers
            struct clogger_ident_t* curr, * tmp;
            HASH_ITER(hh, mgr->loggers, curr, tmp) {
                HASH_DEL(mgr->loggers, curr);
                clog_logger_destroy(curr->logger);
                mem_free(curr);
            }

            rtclock_uninit(mgr->rtclock);

            cstrbufFree(&mgr->workdir);
            cstrbufFree(&mgr->procdir);

            cstrbufFree(&mgr->cfgfile);

            RWLockUninit(&mgr->rwlock);

            bzero_fast(&clogger_singleton, sizeof(clogger_singleton));
            mem_free(mgr);

    #ifdef CLOGGER_SHMGR_HANDLE
            shmipc_destroy(&shmgr_handle);
    #endif
            emerg_syslog_message(0, 0, "libclogger", "logger_manager_uninit!", -1);
        }
    }

    pthread_mutex_unlock(&init_mutex);
}


// process-wide logger manager
logger_manager get_logger_manager()
{
    logger_manager mgr = (logger_manager) UAtomicPtrGet(&clogger_singleton.pvmgr);
    if (! mgr) {
        mgr = get_logger_manager_shared();
        (void) UAtomicPtrSet(&clogger_singleton.pvmgr, mgr);
    }
    return mgr;
}


clog_logger  logger_manager_load(const char* ident)
{
    logger_manager mgr = get_logger_manager();
    return (mgr ? logger_manager_load_shared(mgr, ident) : NULL);
}


clog_logger logger_manager_get(int loggerid)
{
    logger_manager mgr = get_logger_manager();
    return (mgr ? logger_manager_get_shared(mgr, loggerid) : NULL);
}


int logger_manager_get_stampid(char* stampidfmt, int fmtsize)
{
    struct timespec ts;

    logger_manager mgr = get_logger_manager();
    rtclock_ticktime(mgr->rtclock, &ts);
    return snprintf(stampidfmt, fmtsize, "{%"PRId64".%09d}", (int64_t)ts.tv_sec, (int)ts.tv_nsec);
}

const char * logger_manager_get_workdir()
{
    logger_manager mgr = get_logger_manager();
    if (mgr) {
        return CBSTR(mgr->workdir);
    }
    return NULL;
}

const char * logger_manager_get_procdir()
{
    logger_manager mgr = get_logger_manager();
    if (mgr) {
        return CBSTR(mgr->procdir);
    }
    return NULL;
}

const char * logger_manager_get_cfgfile()
{
    logger_manager mgr = get_logger_manager();
    if (mgr) {
        return CBSTR(mgr->cfgfile);
    }
    return NULL;
}


int logger_manager_update_loglevel()
{
    // TODO:
    return -1;
}