/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file rollingfile.h
 * @brief api for rolling file writting
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 mapaware.top All Rights Reserved.
 * @version 0.0.63
 *
 * @since 2019-12-15 16:49:10
 * @date 2025-11-29 18:27:57
 *
 */
#ifndef ROLLINGFILE_H_
#define ROLLINGFILE_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <common/pathlib.h>

// 常量定义: 不可更改

#define ROF_SYMBOL_DATE    "<DATE>"
#define ROF_SYMBOL_IDENT   "<IDENT>"
#define ROF_SYMBOL_PID     "<PID>"

#define ROF_SYMBOL_DATE_LEN    6 //   strlen("<DATE>")
#define ROF_SYMBOL_IDENT_LEN   7 //   strlen("<IDENT>")
#define ROF_SYMBOL_PID_LEN     5 //   strlen("<PID>")

#define ROF_PATH_SIZE_MAX      256

#define ROF_PATHPREFIX_LEN     120

// 20250821-1655
#define ROF_DATEMIN_SIZE       16

// max file size is up to: 64 GB
#define ROF_FILESIZE_MAX            ((uint64_t)68719476736UL)

// max count of files is up to: 1,000,000
#define ROF_FILECOUNT_MAX           1000000


///////////////////////////////////////////////////////////////
// 类型定义

typedef enum {
    ROLLING_TM_NONE   = 0,
    ROLLING_TM_MIN_1  = 1,
    ROLLING_TM_MIN_5  = 2,
    ROLLING_TM_MIN_10 = 3,
    ROLLING_TM_MIN_30 = 4,
    ROLLING_TM_HOUR   = 5,
    ROLLING_TM_DAY    = 6,
    ROLLING_TM_MON    = 7,
    ROLLING_TM_YEAR   = 8
} rollingtime_t;


typedef struct _rollingfile_t
{
    /* how to rolling file by time */
    rollingtime_t timepolicy;

    /* max size of a single file in bytes */
    ub8 maxfilesize;

    /* max files for log files in pathprefix */
    ub4 maxfilecount;

    /* path prefix like: "/var/log/applog/" */
    cstrbuf pathprefix;

    /* /var/log/applog/LOGLEVEL */
    cstrbuf loglevelfile;

    /* name prefix like: "myapp.log." */
    cstrbuf nameprefix;

    /* path file for logging: "/var/log/applog/myapp.log.0" */
    cstrbuf pathname;
    cstrbuf datesuffix;

    /* logging path file name */
    cstrbuf loggingfile;

    /* append logging file no.: 0, 1, 2, 3, ..., maxfilecount - 1 */
    int appendfileno;

    /* currently logging file handle */
    filehandle_t fhlogging;

    /* currently written bytes in logging file */
    ub8 offsetbytes;

    /* push append (not default) */
    int rollingappend;
} rollingfile_t;


///////////////////////////////////////////////////////////////
// rollingfile api

void rollingfile_init(rollingfile_t *rof, const char *pathprefix, const char *nameprefix);

void rollingfile_uninit(rollingfile_t *rof);

int rollingtime_from_string(const char *rostr, rollingtime_t *rotime);

void rollingfile_apply(rollingfile_t *rof, const char *dateminfmt, int datelen);

void rollingfile_set_timepolicy(rollingfile_t *rof, rollingtime_t timepolicy);

void rollingfile_set_sizepolicy(rollingfile_t *rof, ub8 maxfilesize, ub4 maxfilecount, int rollingappend);

int rollingfile_write(rollingfile_t *rof, const char *dateminfmt, int dateminlen, const void *message, size_t msglen);

#ifdef __cplusplus
}
#endif

#endif /* ROLLINGFILE_H_ */
