/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file rollingfile.c
 * @brief api for rolling file writting
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 mapaware.top All Rights Reserved.
 * @version 0.0.63
 *
 * @since 2019-12-15 16:49:10
 * @date 2025-11-29 18:27:57
 *
 */
#include <common/pathlib.h>
#include <common/emerglog.h>

#include "rollingfile.h"

static filehandle_t rollingfile_create(const cstrbuf pathname)
{
#if defined(PLATFORM_WINDOWS) || defined(PLATFORM_CYGWIN)
    return file_create(pathname->str, GENERIC_WRITE, FILE_ATTRIBUTE_NORMAL);
#else
    /* mode = S_IRUSR|S_IWUSR|S_IRGRP|S_IROTH (0644) */
    return file_create(pathname->str, O_WRONLY, S_IRUSR|S_IWUSR|S_IRGRP|S_IROTH);
#endif
}

static int rollingfile_exists (const cstrbuf pathname)
{
    return file_exists(CBSTR(pathname));
}


int rollingtime_from_string(const char *rostr, rollingtime_t *rotime)
{
    static const char * rots[] = {
        "min", "1min",
        "5m",  "5min",
        "10m", "10min",
        "30m", "30min",
        "hour",
        "day",
        "mon",
        "year"
    };
    static const rollingtime_t rotm[] = {
        ROLLING_TM_MIN_1,  ROLLING_TM_MIN_1,
        ROLLING_TM_MIN_5,  ROLLING_TM_MIN_5,
        ROLLING_TM_MIN_10, ROLLING_TM_MIN_10,
        ROLLING_TM_MIN_30, ROLLING_TM_MIN_30,
        ROLLING_TM_HOUR,
        ROLLING_TM_DAY,
        ROLLING_TM_MON,
        ROLLING_TM_YEAR
    };
    for (int i = 0; i < sizeof(rots)/sizeof(rots[0]); i++) {
        int cstr_compare(const char *s1, size_t l1, const char *s2, size_t l2, int caseignore);

        if (!cstr_compare(rostr, -1, rots[i], -1, 1)) {
            /* success */
            *rotime = rotm[i];
            return 1;
        }
    }

    /* failed as default */
    return 0;
}


static void rollingfile_update(rollingfile_t *rof)
{
    file_close(&rof->fhlogging);

    if (rof->rollingappend) {
        rof->appendfileno = (rof->appendfileno + 1) % rof->maxfilecount;

        cstrbuf nextloggingfile = cstrbufNew(rof->loggingfile->len + 20, rof->loggingfile->str, rof->loggingfile->len);

        if (rof->appendfileno > 0) {
            nextloggingfile = cstrbufCat(nextloggingfile, ".%d", rof->appendfileno);
        }

        /* remove and create next log file */
        file_remove(CBSTR(nextloggingfile));

        rof->fhlogging = rollingfile_create(nextloggingfile);
        rof->offsetbytes = 0;

        cstrbufFree(&nextloggingfile);
    } else {
        int i = (int) rof->maxfilecount;

        while (i-- > 1) {
            cstrbuf filefrom = (i > 1? cstrbufCat(0, "%.*s.%d", CBSTRLEN(rof->loggingfile), CBSTR(rof->loggingfile), i-1) : rof->loggingfile);

            if (rollingfile_exists(filefrom)) {
                cstrbuf fileto = cstrbufCat(0, "%.*s.%d", CBSTRLEN(rof->loggingfile), CBSTR(rof->loggingfile), i);
                if (rollingfile_exists(fileto)) {
                    file_remove(fileto->str);
                }
                file_move(filefrom->str, fileto->str);
                cstrbufFree(&fileto);
            }
            if (filefrom != rof->loggingfile) {
                cstrbufFree(&filefrom);
            }
        }

        /* remove and create log file */
        file_remove(CBSTR(rof->loggingfile));
        rof->fhlogging = rollingfile_create(rof->loggingfile);
        rof->offsetbytes = 0;
    }
}


/* check and rolling file name */
void rollingfile_apply(rollingfile_t *rof, const char *dateminfmt, int datelen)
{
    char pathfile[ROF_PATH_SIZE_MAX];

    if (datelen) {
        /* timepolicy valid */
        if (! rof->loggingfile ||
            ! cstr_startswith(rof->loggingfile->str + rof->pathname->len, rof->loggingfile->len - rof->pathname->len, dateminfmt, datelen)) {
            ub4 pathlen = 0;

            /* first time make full name of path file OR rolling log file */
            size_t pathsize = rof->pathname->len + datelen + (rof->datesuffix? rof->datesuffix->len : 0) + 20;
            emerglog_check_condition(pathsize < sizeof(pathfile), "libclogger", "pathsize(=%d) is too much", (int)pathsize);

            pathlen = cstrbufCopyTo(rof->pathname, pathfile, 0);

            memcpy(pathfile + pathlen, dateminfmt, datelen);
            pathlen += datelen;

            pathlen = cstrbufCopyTo(rof->datesuffix, pathfile, pathlen);
            pathfile[pathlen] = 0;

            if (! rof->loggingfile) {
                rof->loggingfile = cstrbufNew((ub4)pathsize, pathfile, (ub4)pathlen);
            } else {
                file_close(&rof->fhlogging);
                rof->loggingfile = cstrbufDup(rof->loggingfile, pathfile,(ub4) pathlen);
            }

            rof->fhlogging = rollingfile_create(rof->loggingfile);
            rof->offsetbytes = 0;

            if (rof->fhlogging == filehandle_invalid && rollingfile_exists(rof->loggingfile)) {
                rollingfile_update(rof);
            }
        }
    } else {
        /* sizepolicy */
        if (! rof->loggingfile) {
            ub4 pathlen = 0;

            size_t pathsize = rof->pathname->len + 1 + (rof->datesuffix? rof->datesuffix->len : 0) + 20;
            emerglog_check_condition(pathsize < sizeof(pathfile), "libclogger", "pathsize(=%d) is too much", (int)pathsize);

            pathlen = cstrbufCopyTo(rof->pathname, pathfile, 0);
            if (rof->datesuffix) {
                pathfile[pathlen++] = '0';
                pathlen = cstrbufCopyTo(rof->datesuffix, pathfile, pathlen);
            }
            pathfile[pathlen] = 0;

            rof->loggingfile = cstrbufNew((ub4)pathsize, pathfile, pathlen);

            rof->fhlogging = rollingfile_create(rof->loggingfile);
            rof->offsetbytes = 0;

            if (rof->fhlogging == filehandle_invalid && rollingfile_exists(rof->loggingfile)) {
                rollingfile_update(rof);
            }
        }
    }

    /* check rolling size */
    if (rof->offsetbytes >= rof->maxfilesize) {
        rollingfile_update(rof);
    }
}


void rollingfile_init(rollingfile_t *rof, const char *pathprefix, const char *nameprefix)
{
    static char pathsep[] = {PATH_SEP_CHR, '\0'};

    rof->pathprefix = cstrbufNew(ROF_PATHPREFIX_LEN + 8, pathprefix, -1);
    rof->nameprefix = cstrbufNew(ROF_PATHPREFIX_LEN + 8, nameprefix, -1);

    if (! cstr_endswith(rof->pathprefix->str, rof->pathprefix->len, pathsep, 1) &&
        ! cstr_endswith(rof->pathprefix->str, rof->pathprefix->len, "/", 1)) {
        rof->pathprefix = cstrbufCat(rof->pathprefix, pathsep);
    }

    const char * datestr = cstr_findchild(rof->nameprefix->str, rof->nameprefix->len, ROF_SYMBOL_DATE, ROF_SYMBOL_DATE_LEN);
    if (datestr) {
        rof->datesuffix = cstrbufNew(ROF_PATHPREFIX_LEN, datestr + ROF_SYMBOL_DATE_LEN, -1);
        rof->pathname = cstrbufCat(0, "%.*s%.*s", rof->pathprefix->len, rof->pathprefix->str,
            rof->nameprefix->len - rof->datesuffix->len - ROF_SYMBOL_DATE_LEN, rof->nameprefix->str);
    }
    else {
        rof->datesuffix = NULL;
        rof->pathname = cstrbufCat(NULL, "%.*s%.*s", rof->pathprefix->len, rof->pathprefix->str, rof->nameprefix->len, rof->nameprefix->str);
    }

    rof->loglevelfile = cstrbufCat(NULL, "%.*sLOGLEVEL", rof->pathprefix->len, rof->pathprefix->str);
}


void rollingfile_uninit(rollingfile_t *rof)
{
    file_close(&rof->fhlogging);

    cstrbufFree(&rof->pathprefix);
    cstrbufFree(&rof->nameprefix);
    cstrbufFree(&rof->datesuffix);
    cstrbufFree(&rof->pathname);
    cstrbufFree(&rof->loggingfile);
    cstrbufFree(&rof->loglevelfile);
}


void rollingfile_set_timepolicy(rollingfile_t *rof, rollingtime_t timepolicy)
{
    rof->timepolicy = timepolicy;
}


void rollingfile_set_sizepolicy(rollingfile_t *rof, ub8 maxfilesize, ub4 maxfilecount, int rollingappend)
{
    rof->maxfilesize = maxfilesize;
    rof->maxfilecount = maxfilecount;

    rof->rollingappend = (rollingappend? 1 : 0);
    rof->appendfileno = 0;
}


int rollingfile_write(rollingfile_t *rof, const char *dateminfmt, int dateminlen, const void *message, size_t msglen)
{
    int err;
    rollingfile_apply(rof, dateminfmt, dateminlen);
    err = file_writebytes(rof->fhlogging, (const char *) message, (ub4)msglen);
    if (!err) {
        rof->offsetbytes += msglen;
    }
    return err;
}
