/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file shmmaplog.c
 * @brief shared memory map file log api
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 mapaware.top All Rights Reserved.
 * @version 1.0.20
 *
 * @since 2020-04-30 13:50:10
 * @date 2025-11-29 18:27:57
 */
#include "shmmaplog.h"

#include <common/memapi.h>

#define SHMMBUF_IMPLEMENT
#include <common/shmmbuf.h>

#include "platforms.h"

static char * _replace_chr(char * str, char ch, char rpl)
{
    char *p = str;
    while (p && *p) {
        if (*p == ch) {
            *p = rpl;
        }
        p++;
    }
    return str;
}

/**
 * @brief Shared memory logger context structure
 *
 * This structure holds the context for a shared memory based logger instance.
 * It contains the shared memory buffer handle and path information.
 */
typedef struct _shmmaplog_t
{
    /** @brief Handle to the underlying shared memory buffer */
    shmmap_buffer shmbuf;

    /** @brief Path prefix for shared memory file (Windows/Cygwin specific) */
    char pathprefix[SHMM_PATHPREFIX_SIZE];

    /** @brief Flexible array member for storing shared memory name
     *
     * This is a zero-length array that will be allocated with additional
     * space to store the full shared memory name string.
     */
    char shmname[0];
} shmmaplog_t;

/**
 * @brief Initialize a shared memory logger instance
 *
 * This function creates and initializes a shared memory logger with the
 * specified parameters. It handles platform-specific path formatting
 * and creates the underlying shared memory buffer.
 *
 * @param[in] pathprefix Directory path prefix for shared memory file
 * @param[in] filename Base filename for shared memory object
 * @param[in] maxsizebytes Maximum size of the shared memory buffer in bytes
 * @param[in] token Cryptographic token for secure access (must be at least 8 bytes)
 * @param[out] pshmlog Pointer to receive the initialized logger handle
 *
 * @return 0 on success, -1 on failure
 *
 * @note On Windows/Cygwin, paths are converted to Windows format
 * @note On Linux, special characters in filename are replaced with hyphens
 * @note The token is used for cryptographic verification of shared memory access
 */
int shmmaplog_init(const char *pathprefix, char *filename, size_t maxsizebytes, unsigned char *token, shmmaplog_hdl *pshmlog)
{
    int err;

    char shmname[256] = {0};
    int shmnamelen = 0;

#if defined(PLATFORM_WINDOWS) || defined(PLATFORM_CYGWIN)
    if (pathprefix) {
        // TODO:
        // [/cygdrive/c/var/log/clogger]
        if (strstr(pathprefix, "/cygdrive/") == pathprefix) {
            _replace_chr(filename, '\\', '/');

            // c:/var/log/clogger
            shmnamelen = snprintf(shmname, sizeof(shmname), "%c:%c%.*s/%s",
                    pathprefix[10], pathprefix[11],
                    (int) strnlen(&pathprefix[12], SHMM_PATHPREFIX_SIZE),
                    &pathprefix[12], filename);
        } else {
            _replace_chr(filename, '\\', '/');
            shmnamelen = snprintf(shmname, sizeof(shmname), "%.*s/%s",
                (int) strnlen(pathprefix, SHMM_PATHPREFIX_SIZE), pathprefix, filename);
        }
    } else {
        _replace_chr(filename, '\\', '/');
        shmnamelen = snprintf(shmname, sizeof(shmname), "C:/TEMP/clogger/%s", filename);
    }
#else /* Linux: default is "/dev/shm/..." */
    _replace_chr(filename, '/', '-');
    _replace_chr(filename, '\\', '-');
    shmnamelen = snprintf(shmname, sizeof(shmname), "%s", filename);
#endif

    shmmaplog_t *shmlog = mem_calloc(1, sizeof(*shmlog) + shmnamelen + 1);

    union {
        ub8token_t tkval;
        char tkbuf[8];
    } tmptoken;

    memcpy(tmptoken.tkbuf, token, sizeof(tmptoken));

    err = shmmap_buffer_create(&shmlog->shmbuf, shmname, SHMMBUF_FILEMODE_DEFAULT, maxsizebytes, &tmptoken.tkval, 0, 0);
    if (err) {
        perror("shmmap_buffer_create");
        mem_free(shmlog);
        return -1;
    }

    /* success */
    memcpy(shmlog->shmname, shmname, shmnamelen);
    *pshmlog = shmlog;
    return 0;
}

/**
 * @brief Uninitialize and free a shared memory logger instance
 *
 * This function closes the shared memory buffer and frees all resources
 * associated with the logger instance.
 *
 * @param[in] shmlog Logger handle to uninitialize
 *
 * @note After calling this function, the handle becomes invalid
 * @note This function is safe to call with NULL or already freed handles
 */
void shmmaplog_uninit(shmmaplog_hdl shmlog)
{
    if (shmlog && shmlog->shmbuf) {
        shmmap_buffer_close(shmlog->shmbuf);
    }
    mem_free(shmlog);
}

/**
 * @brief Write a message to the shared memory logger
 *
 * This function writes a message to the shared memory ring buffer and
 * signals any waiting consumers about the new data.
 *
 * @param[in] shmlog Logger handle
 * @param[in] msg Message data to write
 * @param[in] msgsz Size of the message data
 *
 * @return Write status code (SHMMBUF_WRITE_* constants)
 *
 * @note If write is successful, a semaphore signal is sent to notify consumers
 * @note The return value indicates whether the write was successful, should be retried, or failed
 */
int shmmaplog_write(shmmaplog_hdl shmlog, const char *msg, size_t msgsz)
{
    int wok = shmmap_buffer_write(shmlog->shmbuf, (const void *) msg, msgsz);

    if (wok == SHMMBUF_WRITE_SUCCESS) {
        shmmap_buffer_post(shmlog->shmbuf, SHMMBUF_TIMEOUT_NOWAIT);
    }

    return wok;
}
