/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file log4tcl_cmd.h
 * @brief 扩展命令声明 (liblog4tcl.so)
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 mapaware.top All Rights Reserved.
 * @version 0.0.18
 *
 * @since 2025-08-27 17:21:10
 * @date 2025-11-29 18:27:57
 *
 * @note
 */
#ifndef LOG4TCL_CMD_H
#define LOG4TCL_CMD_H

#ifdef _MSC_VER
# pragma warning (disable : 4996)
#endif

#ifdef    __cplusplus
extern "C" {
#endif

#include <tcl.h>
#include <pthread.h>
#include <common/cstrbuf.h>
#include <common/pathlib.h>
#include <common/emerglog.h>

#include <clogger/clogger_helper.h>  // 日志库

#include "log4tcl.h"

static const char libname[] = "liblog4tcl";
static const char libstate[] = "log4tcl_state";

// 独立于解释器的进程内线程锁
extern pthread_mutex_t tcl_mutex;


#define CheckGetLogger(ident) do { \
        if (!logger) { \
            logger = logger_manager_load(ident); \
            emerglog_check_nullptr(logger, libname, "logger_manager_load failed"); \
        } \
    } while(0)

#define CheckGetInterpState(interp)  \
    InterpState *istate = GetInterpState(interp); \
    if (!istate) { \
        emerglog_check_nullptr(istate, libname, "GetInterpState failed"); \
    } \
    ((void)0)


// 解释器状态结构
typedef struct
{
    Tcl_HashTable loggersTable;
    char buffer[256];
} InterpState;


int initCmd(ClientData data, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]);

int setloggerCmd(ClientData data, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]);

int traceCmd(ClientData data, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]);

int debugCmd(ClientData data, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]);

int infoCmd(ClientData data, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]);

int warnCmd(ClientData data, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]);

int errorCmd(ClientData data, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]);

int fatalCmd(ClientData data, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]);

#ifdef    __cplusplus
}
#endif

#endif /* LOG4TCL_CMD_H */