/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file log4tcl_cmd.c
 * @brief 扩展日志命令实现
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 mapaware.top All Rights Reserved.
 * @version 1.0.18
 *
 * @since 2025-08-27 17:21:12
 * @date 2025-11-29 18:27:57
 */
#include "log4tcl_cmd.h"

static bool clogger_initialized = false;
static clog_logger logger = NULL;

pthread_mutex_t tcl_mutex = PTHREAD_MUTEX_INITIALIZER;

static void Tcl_Lock() {
    pthread_mutex_lock(&tcl_mutex);
}

static void Tcl_Unlock() {
    pthread_mutex_unlock(&tcl_mutex);
}

static void OnExitHandler(ClientData clientData)
{
    Tcl_Lock();

    logger_manager_uninit();

    emerg_syslog_message(0, 0, libname, "log4tcl exit", -1);
    Tcl_Unlock();
}


int initCmd(ClientData data, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[])
{
    Tcl_Lock();
    if (clogger_initialized) {
        Tcl_SetResult(interp, "warn: clogger already initialized", TCL_STATIC);
        Tcl_Unlock();
        return TCL_OK;
    }

    if (objc > 2) {
        Tcl_WrongNumArgs(interp, 1, objv, "?clogger_cfg_dir?");
        Tcl_Unlock();
        return TCL_ERROR;
    }

    clog_errcode_t errcode;
    if (objc == 2) {
        errcode = logger_manager_init(Tcl_GetString(objv[1]), NULL);
    } else {
        errcode = logger_manager_init(NULL, NULL);
    }

    if (errcode != CLOG_ERRCODE_NO_ERROR) {
        Tcl_SetObjResult(interp, Tcl_NewStringObj("ERR: logger_manager_init failed", -1));
        Tcl_Unlock();
        return TCL_ERROR;
    }

    // 注册退出处理函数
    Tcl_CreateExitHandler(OnExitHandler, NULL);
    clogger_initialized = true;

    Tcl_SetObjResult(interp, Tcl_NewStringObj("OK", -1));
    Tcl_Unlock();
    return TCL_OK;
}


int setloggerCmd(ClientData data, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[])
{
    if (objc != 2) {
        Tcl_WrongNumArgs(interp, 1, objv, "logger");
        return TCL_ERROR;
    }

    Tcl_Lock();

    if (! clogger_initialized) {
        clog_errcode_t errcode = logger_manager_init(NULL, NULL);
        if (errcode != CLOG_ERRCODE_NO_ERROR) {
            Tcl_SetObjResult(interp, Tcl_NewStringObj("ERR: logger_manager_init failed", -1));
            Tcl_Unlock();
            return TCL_ERROR;
        }
        // 注册退出处理函数
        Tcl_CreateExitHandler(OnExitHandler, NULL);
        clogger_initialized = true;
    }

    logger = logger_manager_load(Tcl_GetString(objv[1]));
    if (! logger) {
        Tcl_SetObjResult(interp, Tcl_NewStringObj("ERR: logger_manager_load", -1));
        Tcl_Unlock();
        return TCL_ERROR;
    }

    Tcl_SetObjResult(interp, Tcl_NewStringObj(clog_logger_get_ident(logger), -1));
    Tcl_Unlock();
    return TCL_OK;
}


int traceCmd(ClientData data, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[])
{
    if (objc != 2) {
        Tcl_WrongNumArgs(interp, 1, objv, "message");
        return TCL_ERROR;
    }
    CheckGetLogger(NULL);

    const char *message = Tcl_GetString(objv[1]);
    CLOG_TRACE(logger, "%s", message);
    Tcl_ResetResult(interp);
    return TCL_OK;
}


int debugCmd(ClientData data, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[])
{
    if (objc != 2) {
        Tcl_WrongNumArgs(interp, 1, objv, "message");
        return TCL_ERROR;
    }
    CheckGetLogger(NULL);

    const char *message = Tcl_GetString(objv[1]);
    CLOG_DEBUG(logger, "%s", message);
    Tcl_ResetResult(interp);
    return TCL_OK;
}


int infoCmd(ClientData data, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[])
{
    if (objc != 2) {
        Tcl_WrongNumArgs(interp, 1, objv, "message");
        return TCL_ERROR;
    }
    CheckGetLogger(NULL);

    const char *message = Tcl_GetString(objv[1]);
    CLOG_INFO(logger, "%s", message);
    Tcl_ResetResult(interp);
    return TCL_OK;
}


int warnCmd(ClientData data, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[])
{
    if (objc != 2) {
        Tcl_WrongNumArgs(interp, 1, objv, "message");
        return TCL_ERROR;
    }
    CheckGetLogger(NULL);

    const char *message = Tcl_GetString(objv[1]);
    CLOG_WARN(logger, "%s", message);
    Tcl_ResetResult(interp);
    return TCL_OK;
}


int errorCmd(ClientData data, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[])
{
    if (objc != 2) {
        Tcl_WrongNumArgs(interp, 1, objv, "message");
        return TCL_ERROR;
    }
    CheckGetLogger(NULL);

    const char *message = Tcl_GetString(objv[1]);
    CLOG_ERROR(logger, "%s", message);
    Tcl_ResetResult(interp);
    return TCL_OK;
}


int fatalCmd(ClientData data, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[])
{
    if (objc != 2) {
        Tcl_WrongNumArgs(interp, 1, objv, "message");
        return TCL_ERROR;
    }
    CheckGetLogger(NULL);

    const char *message = Tcl_GetString(objv[1]);
    CLOG_FATAL(logger, "%s", message);
    Tcl_ResetResult(interp);
    return TCL_OK;
}