/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file log4tcl.c
 * @brief libclogger for tcl extension (liblog4tcl.so)
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 mapaware.top All Rights Reserved.
 * @version 1.0.11
 *
 * @since 2025-08-27 17:21:05
 * @date 2025-11-29 18:27:57
 */
#define EMERGLOG_IMPLEMENT
#define PATHLIB_IMPLEMENT
#define CSTRBUF_IMPLEMENT
#include <common/cstrbuf.h>
#include <common/pathlib.h>
#include <common/emerglog.h>

#include "log4tcl_cmd.h"

static struct TclCommandNode
{
    const char* cmdName;
    Tcl_ObjCmdProc* cmdFunc;
} tcl_commands[] = {
    { "log4tcl::init", (Tcl_ObjCmdProc *) initCmd },
    { "log4tcl::setlogger", (Tcl_ObjCmdProc *) setloggerCmd },
    { "log4tcl::trace", (Tcl_ObjCmdProc *) traceCmd },
    { "log4tcl::debug", (Tcl_ObjCmdProc *) debugCmd },
    { "log4tcl::info", (Tcl_ObjCmdProc *) infoCmd },
    { "log4tcl::warn", (Tcl_ObjCmdProc *) warnCmd },
    { "log4tcl::error", (Tcl_ObjCmdProc *) errorCmd },
    { "log4tcl::fatal", (Tcl_ObjCmdProc *) fatalCmd },
    { NULL, NULL }
};


static InterpState* CreateInterpState(Tcl_Interp *interp)
{
    InterpState *istate = (InterpState *) ckalloc(sizeof(InterpState));
    bzero_fast(istate, sizeof(InterpState));
    return istate;
}


static void DestroyInterpState(ClientData clientData, Tcl_Interp *interp)
{
    InterpState *istate = (InterpState *) clientData;

    // TODO:

    // 释放解释器状态
    ckfree(istate);
}


int Log4tcl_Init(Tcl_Interp* interp)
{
    // 要求 tcl 最低版本
    if (! Tcl_InitStubs(interp, TCL_VERSION, 0)) {
        emerg_syslog_message(0, 0, libname, "Tcl_InitStubs failed", -1);
        return TCL_ERROR;
    }

    // 分配解释器状态将状态关联到解释器
    InterpState *istate = CreateInterpState(interp);

    // 将状态关联到解释器
    Tcl_SetAssocData(interp, libstate, DestroyInterpState, (ClientData) istate);

    // 注册所有命令
    for (int i = 0; tcl_commands[i].cmdName != NULL; i++) {
        Tcl_CreateObjCommand(interp, tcl_commands[i].cmdName, tcl_commands[i].cmdFunc, NULL, NULL);
    }

    // 注册包卸载函数（如果支持）
    if (Tcl_PkgProvideEx(interp, LOG4TCL_PACKAGE, LOG4TCL_VERSION, (ClientData) Log4tcl_Unload) != TCL_OK) {
        const char *errorMsg = Tcl_GetStringResult(interp); // 不会返回 NULL
        emerg_syslog_message(0, 0, libname, errorMsg, -1);
        return TCL_ERROR;
    }

    return TCL_OK;
}


int Log4tcl_Unload(Tcl_Interp *Interp, int flags)
{
    // 删除关联数据，触发清理函数: DestroyInterpState
    Tcl_DeleteAssocData(Interp, libstate);
    return TCL_OK;
}
