/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file log4tcl.h
 * @brief libclogger for tcl extension (liblog4tcl.so)
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 mapaware.top All Rights Reserved.
 * @version 1.0.9
 *
 * @since 2025-08-27 17:21:02
 * @date 2025-11-29 18:27:57
 *
 * @note
 *   tcl8.6+
 */
#ifndef LIB_LOG4TCL_H_
#define LIB_LOG4TCL_H_

#define LOG4TCL_PACKAGE   "log4tcl"
#define LOG4TCL_VERSION   "1.0"

#ifdef    __cplusplus
extern "C" {
#endif

#include <tcl.h>

#if defined(LOG4TCL__DLL)
/* win32 dynamic dll */
# ifdef LOG4TCL__EXPORTS
#   define LOG4TCL_API __declspec(dllexport)
# else
#   define LOG4TCL_API __declspec(dllimport)
# endif
#else
/* static lib or linux so */
# define LOG4TCL_API  extern
#endif

/* 扩展初始化和卸载函数 */

LOG4TCL_API int Log4tcl_Init(Tcl_Interp *interp);

LOG4TCL_API int Log4tcl_Unload(Tcl_Interp *interp, int flags);

#ifdef __cplusplus
}
#endif

#endif /* LOG4TCL_API */