/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file cstrbuf.h
 * @brief C String Buffer Functions.
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 anomura.cc All Rights Reserved.
 * @version 0.0.78
 *
 * @since 2017-08-28 11:12:10
 * @date 2025-12-06 22:02:59
 */
#ifndef CSTRBUF_INCLUDED
#define CSTRBUF_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

#include "unitypes.h"
#include "memapi.h"

#include <time.h>
#include <ctype.h>   // 使用标准大小写转换
#include <math.h>

#define TM_YEAR_IS_LEAP(year)   ((year) % 4? 0 : ((year) % 100? 1 : ((year) % 400? 0 : 1)))

#define CSTR_DATE_BSIZE  32

#define CSTR_ERR_SIZE  ((size_t)(-1))

typedef struct
{
    /* date fields: if year = -1, date is invalid */
    int year;
    int month;
    int day;

    /* time fields: if hour = -1, time is invalid */
    int hour;
    int minute;
    int second;

    /* millisecond: if millisecond = -1, millisecond is invalid */
    int millisecond;

    /**
     * -1 : timezone is invalid
     *
     * 800 = +08:00, -800 = W08:00
     */
    int timezone;
} cstr_datetime_t;


typedef struct
{
    union {
        ub8 __maxszlen;
        struct {
            ub4 maxsz;
            ub4 len;
        };
    };
    char str[];  // C99
} cstrbuf_t, *cstrbuf;


int vsnprintf_chkd(char *outbuf, size_t bufsize, const char *format, ...);

/**********************************************************************
 * ANSI C string helper API
 *********************************************************************/

#define cstr_return_error(err_code_, err_string_)    return ((int)(err_code_))

#define cstr_invalid_size(si)      ((size_t)(si)==CSTR_ERR_SIZE)

#define cstr_block_size            16

#define cstr_length_max            16777215

#define cstr_bool_true              1
#define cstr_bool_false             0

#define cstr_length(str, maxlen)    ((int)((str)==NULL? 0: ((int)(maxlen)==(-1)? strlen(str) : strnlen(str, (int)(maxlen)))))

#define cstr_copybuf(dstbuf, src)   vsnprintf_chkd(dstbuf, sizeof(dstbuf), "%.*s", (int)strnlen(src, sizeof(dstbuf) - 1), (const char *)(src))

#define cstr_copybuf_len(dstbuf, src, srclen)  vsnprintf_chkd(dstbuf, sizeof(dstbuf), "%.*s", (int)(((int)(srclen)) < ((int)sizeof(dstbuf))? (srclen) : (sizeof(dstbuf) - 1)), (const char *)(src))

#define cstr_LRtrim_chr(str, c, outlen)  cstr_Rtrim_chr(cstr_Ltrim_chr((str), (c)), (c), (outlen))


/**********************************************************************
 * cstrbuf Api
 *********************************************************************/

#define cstrbuf_error_size      ((ub4)(-1))

#define cstrbuf_len_invalid     cstrbuf_error_size
#define cstrbuf_len_max         134217727   /* max size is 128 MB */
#define cstrbuf_size_max        (cstrbuf_len_max + 1)

#define cstrbuf_alignsize(len)  ((ub4) (((len + cstr_block_size - 1) / cstr_block_size)  * cstr_block_size))

#define cstrbufGetLen(s)        ((s)? (int)(s)->len : 0)
#define cstrbufGetMaxsz(s)      ((s)? (int)(s)->maxsz : 0)
#define cstrbufGetStr(s)        ((s)? (s)->str : 0)

#define cstrbufCharAt(s, i)     ((char *)(s->str+(i)))

#define CBSTR(s)                cstrbufGetStr(s)
#define CBSTRLEN(s)             cstrbufGetLen(s)

#define cstrFormat(s)           CBSTRLEN(s), CBSTR(s)
#define cstrbufPrint(s)         printf("%.*s", cstrFormat(s))

#define CSBFREE(s)              cstrbufFree(&s)


void cstr_varray_free(char** varr, int maxnum);

char* cstr_toupper(char* s, int num);

char* cstr_tolower(char* s, int num);

char * cstr_remove_chr(char* s, char c);

char * cstr_remove_chrs(char * str, const char * chrs, int num);

char* cstr_Ltrim_chr(char* str, char ch);

char* cstr_Rtrim_chr(char* str, char ch, int* outlen);

char* cstr_Lfind_chr(char* str, int len, char c);

char* cstr_Rfind_chr(char* str, int len, char c);

char * cstr_find_chrs(char * str, int len, const char *chrs, int nch);

char * cstr_Ltrim_whitespace(char *str);

int cstr_Rtrim_whitespace(char *str, int len);

char * cstr_LRtrim_whitespace(char *str);

int cstr_non_whitespace_range(const char *str, int *start, int *end);

char * cstr_trim_whitespace(char * s);

char * cstr_replace_chr(char * str, char ch, char rpl);

int cstr_replace_new(const char *original, const char *pattern, const char *replacement, char **outresult);

const char* cstr_to_digits(char *numstr, int maxwidth);

int cstr_to_sb8(int base, const char *str, size_t slen, sb8 *outval, char buf[], size_t blen);

int cstr_to_ub8(int base, const char *str, size_t slen, ub8 *outval, char buf[], size_t blen);

int cstr_to_dbl(const char *str, size_t slen, double *outval, char buf[], size_t blen);

const char * cstr_split_chr_next(const char *start, const char *end, char sep,
    const char **next, int *nextlen, int *escapes);

int cstr_split_chr_num(const char *start, const char *end, char sep,
    const char *subs[], int sublens[], int escapes[], int maxsubs);

const char * cstr_split_chrs_next(const char *start, const char *end, const char *seps,
    const char **next, int *nextlen, int *escapes);

int cstr_split_chrs_num(const char *start, const char *end, const char* seps,
    const char *subs[], int sublens[], int escapes[], int maxsubs);

int cstr_unescape_chr(const char *str, int len, char chr, char *copybuf);

const char * cstr_split_str_next(const char *start, const char *end, const char* sepstr, int sepslen,
    const char **next, int *nextlen);

int cstr_split_str_num(const char *start, const char *end, const char* sepstr, int sepslen,
    const char *subs[], int sublens[], int maxsubs);

int cstr_neq(const char *s1, const char *s2);

int cstr_neq_len(const char *s1, size_t l1, const char *s2, size_t l2);

int cstr_compare(const char *s1, size_t l1, const char *s2, size_t l2, int caseignore);

int cstr_startswith(const char *str, size_t len, const char *start, size_t startlen);

int cstr_endswith(const char *str, size_t len, const char *end, size_t endlen);

const char* cstr_findchild(const char * str, size_t len, const char * child, size_t childlen);

int cstr_findfirst_array(const char *str, size_t len, const char *array[], int arraylen, int caseignore);

int cstr_isdigit(const char *str, size_t len);

int cstr_readline(FILE *fp, char line[], size_t maxlen, int ignore_whitespace);

const char * cstr_datetime_print(const cstr_datetime_t *dt, char outfmt[CSTR_DATE_BSIZE]);

int time_is_valid(int year, int mon, int day, int hour, int min, int sec);

int cstr_parse_timezone(char *tz);

ub8 cstr_parse_timestamp(char *timestr, cstr_datetime_t *outdt);

const char * cstr_timestamp_to_datetime(char *stampms, size_t mslen, char timestr[24]);

/**
 * seed = [131], 1313, 13131, 131313 ... (must be prime)
 * table_size = 0, 256, 1024, 2048, ... (must be power of 2 if > 0)
 */
unsigned int cstr_bkdr_hash(const char *str, unsigned int seed, unsigned int table_size);

/**********************************************************************
 * cstrbuf Api
 *********************************************************************/

char * cstrbufCharAtSafe(cstrbuf csb, int at);

cstrbuf cstrbufNew(ub4 maxsz, const char *str, ub4 len);

cstrbuf cstrbufNew2(const char* str, ub4 maxlen);

void cstrbufFree(cstrbuf *csb);

cstrbuf cstrbufCopyFrom(cstrbuf dst, const char *fmt, ...);

ub4 cstrbufCopyTo(const cstrbuf src, void *dstbuf, ub4 offcb);

cstrbuf cstrbufCat (cstrbuf dst, const char *fmt, ...);

cstrbuf cstrbufTrunc (cstrbuf s, int offset);

cstrbuf cstrbufConcat (const cstrbuf start, ...);

cstrbuf cstrbufDup (cstrbuf dst, const char *source, ub4 sourcelen);

cstrbuf cstrbufSub (const char *source, int startindex, int length, const char *substr, int sublen);

cstrbuf cstrbufPushBack (cstrbuf dst, char ch);

#ifdef __cplusplus
}
#endif

#endif /* CSTRBUF_INCLUDED */
