/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file cstrbuf.c
 * @brief C String Buffer Functions.
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 anomura.cc All Rights Reserved.
 * @version 0.0.78
 *
 * @since 2017-08-28 11:12:10
 * @date 2025-12-06 22:02:59
 */
#include "cstrbuf.h"

/**
 * @brief 安全的可变参数格式化函数（缓冲区安全）
 *
 * @param outbuf 输出缓冲区（必须非空且足够大）
 * @param bufsize 输出缓冲区大小（字节数）
 * @param format 格式化字符串（遵循 printf 格式规范）
 * @param ... 可变参数列表（匹配格式化字符串）
 * @return int 格式化结果：
 *             >=0: 实际需要的字符数（不包括终止符）
 *             <0: 发生错误
 *
 * @note 此函数保证：
 *   1. 输出缓冲区始终以 null 结尾
 *   2. 不会发生缓冲区溢出
 *   3. 正确处理所有边界情况
 *   4. 跨平台兼容（Windows/Linux/macOS/MinGW/Cygwin）
 *
 * 行为说明：
 *   - 如果 outbuf == NULL || bufsize == 0: 返回 -1（无效参数）
 *   - 如果 bufsize == 1: 设置 outbuf[0] = '\0'，返回 0
 *   - 如果 format == NULL: 设置 outbuf[0] = '\0'，返回 0
 *   - 如果格式化失败: 设置 outbuf[0] = '\0'，返回 -1
 *   - 如果输出被截断: 确保缓冲区正确终止，返回实际需要的字符数
 *
 * 错误处理：
 *   - 返回负值表示错误
 *   - 截断时设置 errno = ENOBUFS（如果平台支持）
 *   - 使用断言帮助调试（NDEBUG 定义时自动禁用）
 *
 * 设计原理：
 *   1. 优先进行参数验证，确保基础安全
 *   2. 处理所有边界情况（零缓冲区、单字节缓冲区等）
 *   3. 调用系统 vsnprintf 并检查返回值
 *   4. 显式确保缓冲区终止，避免平台差异
 *   5. 设置 errno 帮助调用者诊断截断情况
 *
 * 与标准 vsnprintf 的区别：
 *   - 保证缓冲区始终以 null 结尾
 *   - 处理 format == NULL 的边界情况
 *   - 统一错误返回值为 -1
 *   - 设置 errno 标识截断
 *   - 更严格的参数验证
 *
 * 使用示例：
 *   char buf[32];
 *   int len = vsnprintf_chkd(buf, sizeof(buf), "Value: %d", 42);
 *   if (len < 0) {
 *       // 处理错误
 *   } else if ((size_t)len >= sizeof(buf)) {
 *       // 处理截断
 *   }
 */
int vsnprintf_chkd(char *outbuf, size_t bufsize, const char *format, ...)
{
    /* 参数验证：空指针或零缓冲区大小 */
    if (!outbuf || bufsize == 0) {
        /* 调试断言（NDEBUG 定义时自动禁用） */
        DEBUG_ASSERT(outbuf != NULL && bufsize > 0 && "Invalid buffer (NULL or zero size)");
        return -1;
    }

    /* 边界情况：缓冲区仅能容纳终止符 */
    if (bufsize == 1) {
        DEBUG_ASSERT(bufsize == 1 && "Buffer size is 1 (only null terminator fits)");
        *outbuf = '\0';  /* 强制设置为空字符串 */
        return 0;        /* 返回 0 个写入字符 */
    }

    /* 边界情况：空格式字符串 */
    if (format == NULL) {
        DEBUG_ASSERT(format != NULL && "Format string is NULL (treated as empty string)");
        outbuf[0] = '\0';  /* 输出空字符串 */
        return 0;          /* 返回 0 个写入字符 */
    }

    va_list args;
    va_start(args, format);

    /* 调用系统格式化函数 */
    int len = vsnprintf(outbuf, bufsize, format, args);

    va_end(args);

    /* 处理系统错误（格式化失败） */
    if (len < 0) {
        DEBUG_ASSERT(len >= 0 && "vsnprintf system call failed (negative return value)");
        outbuf[0] = '\0';  /* 确保终止 */
        return -1;         /* 返回统一错误码 */
    }

    /* 处理缓冲区截断（需要空间 > 可用空间） */
    if ((size_t)len >= bufsize) {
        /* 设置截断错误码（平台支持时） */
    #ifdef ENOBUFS
        errno = ENOBUFS;  /* 输出缓冲区不足 */
    #elif defined(ENOMEM)
        errno = ENOMEM;    /* 次优回退 */
    #endif

        DEBUG_ASSERT((size_t)len < bufsize && "Output truncated (formatted data exceeds buffer size)");
        outbuf[bufsize - 1] = '\0';  /* 强制终止缓冲区 */
        return len;                  /* 返回实际需要的字符数 */
    }

    /* 成功路径：显式设置终止符（防御性编程） */
    errno = 0;            /* 清除错误状态 */
    outbuf[len] = '\0';   /* 确保正确终止（处理异常实现） */
    return len;           /* 返回实际写入字符数 */
}

/**
 * @brief 释放动态分配的字符串指针数组及其元素
 *
 * 此函数安全释放一个字符串指针数组（`char**`）中的所有非空字符串元素，
 * 并将每个指针位置置为 NULL。数组容器本身不会被释放（由调用方管理）。
 *
 * - 空安全：接受 NULL 数组指针（静默返回）
 * - 安全处理数组中包含的 NULL 指针
 * - 逆序释放：从数组末尾向开头处理（优化缓存性能）
 * - 防御性编程：释放后立即置空指针（防双重释放）
 *
 * @param varr   字符串指针数组（char** 类型），可为 NULL
 * @param maxnum 数组的实际元素数量（非容量）
 *
 * @warning 重要限制：
 * - 必须传递准确的元素数量（maxnum）
 * - 不会释放数组容器本身（仅处理元素）
 * - 若数组实际元素 > maxnum 会导致内存泄漏
 * - 若数组实际元素 < maxnum 会访问非法内存
 */
void cstr_varray_free(char** varr, int maxnum)
{
    while (varr && maxnum-- > 0) {
        char* p = varr[maxnum];
        if (p) {
            varr[maxnum] = NULL;  // 防御性置空
            mem_free(p);          // 释放字符串内存
        }
    }
}

/**
 * @brief 将字符串的前 num 个字符转换为大写形式
 *
 * 此函数原地修改字符串，将指定数量的字符转换为大写形式。
 * 转换在遇到字符串结束符或达到指定数量时停止。
 *
 * @param s     要转换的字符串（原地修改），必须为有效字符串指针
 * @param num   要转换的最大字符数（实际转换数 = min(num, strlen(s))）
 *
 * @return 返回原始字符串指针（便于链式调用）
 *
 * @note 安全性：
 * - 若 num > 实际长度，转换在遇到 '\0' 时停止
 * - 若 num < 0，函数立即返回（无操作）
 * - 不分配新内存，直接修改原字符串
 *
 * @warning 注意：
 * - 传入 NULL 指针会导致未定义行为
 * - 不会验证字符串边界，调用方需确保内存安全
 */
char* cstr_toupper(char* s, int num)
{
    char* p = s;
    // 同时检查字符计数和字符串结束符
    while (num-- > 0 && *p) {
        *p = toupper((unsigned char)*p);  // 确保无符号转换避免符号扩展问题
        p++;
    }
    return s;
}

/**
 * @brief 将字符串的前 num 个字符转换为小写形式
 *
 * 此函数原地修改字符串，将指定数量的字符转换为小写形式。
 * 转换在遇到字符串结束符或达到指定数量时停止。
 *
 * @param s     要转换的字符串（原地修改），必须为有效字符串指针
 * @param num   要转换的最大字符数（实际转换数 = min(num, strlen(s))）
 *
 * @return 返回原始字符串指针（便于链式调用）
 *
 * @note 特性：
 * - 处理速度：O(n) 时间复杂度，n=min(num, strlen(s))
 * - 支持 Unicode：依赖当前区域设置的 tolower() 行为
 * - 线程安全：无静态变量，但依赖线程安全的 ctype.h 实现
 *
 * @warning 重要限制：
 * - 不检查缓冲区溢出，调用方需确保内存有效性
 * - 负数 num 值会被静默忽略
 */
char* cstr_tolower(char* s, int num)
{
    char* p = s;
    while (num-- > 0 && *p) {             // 同时检查字符计数和字符串结束符
        *p = tolower((unsigned char)*p);  // 强制无符号转换保证正确性
        p++;
    }
    return s;
}

/**
 * @brief 移除字符串中所有指定字符（原地修改）
 *
 * @param s 要处理的字符串（可修改缓冲区）
 * @param c 要移除的字符
 * @return char* 返回处理后的字符串指针
 *
 * @note 特性：
 * - 原地修改字符串，不分配新内存
 */
char * cstr_remove_chr(char* s, char c)
{
    char *f = s, *p = s;
    while (*p) {
        if (*p != c) {
            *f++ = *p;
        }
        ++p;
    }
    *f = 0;
    return s;
}

/**
 * @brief 高效移除字符串中多个指定字符（原地修改）
 *
 * @param str 要处理的字符串（可修改缓冲区）
 * @param chrs 要移除的字符集合
 * @param num 要移除的字符数量
 * @return char* 处理后的字符串指针
 */
char * cstr_remove_chrs(char * str, const char * chrs, int num)
{
    // 创建字符查找表
    unsigned char lookup[UB1MAX + 1] = {0};

    // 标记要移除的字符=1（从前往后）
    for (int i = 0; i < num; i++) {
        lookup[(unsigned char)chrs[i]] = 1;
    }

    char *dest = str;
    char *src = str;

    while (*src) {
        if (!lookup[(unsigned char)*src]) {
            *dest++ = *src;
        }
        src++;
    }
    *dest = '\0';
    return str;
}

/**
 * @brief 移除字符串左侧（开头）的指定字符
 *
 * 此函数通过移动字符串指针移除开头的连续指定字符。
 * 原始内存不被释放，但返回的指针可能指向原字符串的不同位置。
 *
 * @param str  待处理的字符串（指针可能被修改）
 * @param ch   要移除的字符
 *
 * @return 返回移除左侧字符后的新字符串起始位置
 *
 * @note 重要特性：
 * - 时间复杂度：O(n)（n=左侧连续ch的数量）
 * - 不修改字符串内容，仅调整起始指针
 * - 返回的指针可能指向原字符串中部
 *
 * @warning 使用注意事项：
 * - 返回的新指针必须用于后续访问（原str指针可能失效）
 * - 不会释放或修改原始内存，仅调整起始位置
 * - 对只读内存段调用将导致未定义行为
 */
char* cstr_Ltrim_chr(char* str, char ch)
{
    // 跳过开头的连续指定字符
    while (str && *str && *str == ch) {
        str++;
    }
    return str;  // 返回第一个非ch字符的位置
}

/**
 * @brief 移除字符串右侧（结尾）的指定字符并返回长度
 *
 * 此函数通过截断字符串移除结尾的连续指定字符，
 * 同时可选返回新字符串长度。
 *
 * @param str      待处理的字符串（原地修改）
 * @param ch       要移除的字符
 * @param outlen   可选参数，用于接收新字符串长度
 *
 * @return 返回原始字符串指针（内容已被修改）
 *
 * @note 算法细节：
 * 1. 从字符串末尾向前扫描，跳过连续的指定字符
 * 2. 在第一个非指定字符位置后添加结束符
 * 3. 计算并返回新长度（可选）
 *
 * @warning 重要限制：
 * - 必须确保 str 指向可写内存
 * - 若字符串全由ch组成，结果将为空字符串（长度=0）
 * - outlen 为 NULL 时不计算长度
 */
char* cstr_Rtrim_chr(char* str, char ch, int* outlen)
{
    if (!str || !*str) {
        // 处理空字符串或NULL指针情况
        if (outlen) *outlen = 0;
        return str;
    }

    // 从字符串末尾开始向前扫描
    char* end = str + strlen(str) - 1;

    // 跳过尾部连续的指定字符
    while (end >= str && *end == ch) {
        end--;
    }

    // 在最后一个非ch字符后添加结束符
    *(end + 1) = '\0';

    // 计算新长度
    if (outlen) {
        *outlen = (end >= str) ? (int)(end - str + 1) : 0;
    }

    return str;
}

/**
 * @brief 在字符串的指定长度范围内从左向右查找字符
 *
 * 此函数在字符串的前 `len` 个字节或遇到空终止符前（以先到者为准）查找指定字符，
 * 返回第一个匹配字符的指针。
 *
 * @param str  要搜索的字符串（可为NULL）
 * @param len  要搜索的最大长度（字节数）
 * @param c    要查找的字符
 *
 * @return 找到则返回指向字符的指针，否则返回NULL
 *
 * @note 搜索特性：
 * - 搜索范围：min(len, strlen(str))
 * - 空安全：接受NULL指针（立即返回NULL）
 * - 边界安全：严格限制在[str, str+len)范围内
 *
 * @warning 重要限制：
 * - 不支持多字节字符（按字节搜索）
 * - 长度参数为有符号整数（负值视为无效）
 *
 * @example
 * char str[] = "hello";
 * char *p = cstr_Lfind_chr(str, 3, 'l');  // 在"hel"中查找，返回第一个'l'的位置(&str[2])
 * char *q = cstr_Lfind_chr(str, 2, 'l');  // 在"he"中查找，返回NULL（未找到）
 */
char* cstr_Lfind_chr(char* str, int len, char c)
{
    // 参数有效性检查
    if (!str || len <= 0) {
        return NULL;
    }

    char* p = str;
    // 同时检查长度限制和字符串结束符
    while ((p - str) < len && *p) {
        if (*p == c) {
            return p;  // 找到匹配
        }
        p++;
    }
    return NULL;  // 未找到
}

/**
 * @brief 在字符串的指定长度范围内从右向左查找字符
 *
 * 此函数在字符串的后 `len` 个字节中反向查找指定字符，
 * 返回最后一个匹配字符的指针。
 *
 * @param str  要搜索的字符串（可为NULL）
 * @param len  要搜索的最大长度（字节数）
 * @param c    要查找的字符
 *
 * @return 找到则返回指向字符的指针，否则返回NULL
 *
 * @note 算法特性：
 * - 反向遍历：从 str[len-1] 开始向字符串开头搜索
 * - 不依赖空终止符：严格在指定长度范围内搜索
 * - 性能：O(n) 最坏情况
 *
 * @warning 关键风险：
 * - 若 len > 实际分配内存，可能导致越界访问
 * - 若 str 未以空字符结尾且 len 过大，可能访问非法内存
 *
 * @example
 * char str[] = "hello";
 * char *p = cstr_Rfind_chr(str, 5, 'l');  // 返回第二个'l'的位置(&str[3])
 * char *q = cstr_Rfind_chr(str, 3, 'l');  // 在"hel"中查找，返回第一个'l'的位置(&str[2])
 */
char* cstr_Rfind_chr(char* str, int len, char c)
{
    if (!str || len <= 0) { // 参数有效性检查
        return NULL;
    }
    char* p = str + len - 1;  // 指向最后一个有效字符
    while (len-- > 0) {  // 反向遍历指定长度
        if (*p == c) {
            return p;  // 找到匹配
        }
        p--;
    }
    return NULL;  // 未找到
}

/**
 * @brief 在字符串中查找多个字符中的任意一个（首次出现）
 *
 * 此函数在指定长度范围内搜索字符串，查找字符集中任意字符的首次出现位置。
 *
 * @param str   要搜索的字符串（可为NULL）
 * @param len   要搜索的最大长度（字节数）
 * @param chrs  要查找的字符集合（非字符串，无终止符）
 * @param nch   字符集合中的字符数量
 *
 * @return 找到则返回指向第一个匹配字符的指针，否则返回NULL
 *
 * @note 搜索特性：
 * - 搜索范围：min(len, strlen(str))
 * - 空安全：接受NULL指针（立即返回NULL）
 * - 字符集顺序无关：任意匹配字符都会返回
 *
 * @warning 重要限制：
 * 1. 性能问题：字符集较大时效率低（O(n*m)时间复杂度）
 * 2. 不支持多字节字符（按字节搜索）
 * 3. 若 nch > 实际字符集大小，可能导致越界访问
 *
 * @example
 * char str[] = "Hello_World";
 * const char delims[] = {' ', '_', '-'};
 * char *p = cstr_find_chrs(str, 20, delims, 3);  // 返回 '_' 的位置(&str[5])
 *
 * @remark 对于大字符集，建议使用位图法优化：
 */
char * cstr_find_chrs(char * str, int len, const char *chrs, int nch)
{
    if (! str || len <= 0) {
        return NULL;
    }
    int i;
    char *p = str;
    while ((int)(p - str) < len && *p) {
        for (i = 0; i < nch; i++) {
            if (chrs[i] == *p) {
                return p;
            }
        }
        p++;
    }
    return NULL; // 未找到
}

/**
 * @brief 移除字符串开头的空白字符
 * @param str 要处理的字符串
 * @return 移除空白后的新字符串起始位置
 * @note 空白字符包括:
 *    ' '   (0x20)	space (SPC) arcii=32
 *    '\t'	(0x09)	horizontal tab (TAB)
 *    '\n'	(0x0a)	newline (LF)
 *    '\v'	(0x0b)	vertical tab (VT)
 *    '\f'	(0x0c)	feed (FF)
 *    '\r'	(0x0d)	carriage return (CR)
 */
char * cstr_Ltrim_whitespace(char *str)
{
    char *p = str;
    while (p && isspace((int)*p)) {
        p++;
    }
    return p;
}

/**
 * @brief 移除字符串末尾的空白字符
 * @param str 要处理的字符串(原地修改)
 * @param len 字符串长度
 * @return 新字符串长度
 * @note 从尾部开始移除连续空白字符
 * @see cstr_Ltrim_whitespace
 */
int cstr_Rtrim_whitespace(char *str, int len)
{
    while (len-- > 0) {
        if (isspace((int)str[len])) {
            str[len] = 0;
        } else {
            break;
        }
    }
    return len + 1;
}

/**
 * @brief 移除字符串两端的空白字符
 * @param str 要处理的字符串
 * @return 移除空白后的新字符串起始位置
 * @see cstr_Ltrim_whitespace
 */
char * cstr_LRtrim_whitespace(char *str)
{
    char *p = cstr_Ltrim_whitespace(str);
    cstr_Rtrim_whitespace(p, cstr_length(p, -1));
    return p;
}

/**
 * @brief 计算非空白内容的边界
 * @param str 源字符串
 * @param start 输入起始位置，输出非空白起始位置
 * @param end 输入结束位置，输出非空白结束位置
 * @return 非空白内容长度
 * @note 不修改原字符串，仅计算边界
 * 原函数名 cstr_shrink_whitespace
 */
int cstr_non_whitespace_range(const char *str, int *start, int *end)
{
    int s = *start;
    int e = *end;
    for (; s < *end; s++) {
        if (! isspace((int)str[s])) {
            break;
        }
    }
    *start = s;
    for (; e >= *start; e--) {
        if (! isspace((int)str[e])) {
            break;
        }
    }
    *end = e;
    return (*end - *start + 1);
}

/**
 * @brief 递归移除字符串中的所有空白字符
 * @param s 要处理的字符串(原地修改)
 * @return 处理后的字符串
 * @warning 递归实现，长字符串可能导致栈溢出
 */
char * cstr_trim_whitespace(char * s)
{
    return (*s==0)?s:(((!isspace((int)*s) )?(((cstr_trim_whitespace(s+1)-1)==s)? s : (*(cstr_trim_whitespace(s+1)-1)=*s, *s=32 ,cstr_trim_whitespace(s+1))):cstr_trim_whitespace(s+1)));
}

/**
 * @brief 替换字符串中的所有指定字符
 * @param str 要处理的字符串(原地修改)
 * @param ch 要替换的字符
 * @param rpl 替换后的字符
 * @return 处理后的字符串
 */
char * cstr_replace_chr(char * str, char ch, char rpl)
{
    char *p = str;
    while (p && *p) {
        if (*p == ch) {
            *p = rpl;
        }
        p++;
    }
    return str;
}

/**
 * @brief 替换字符串中所有匹配的子串
 *
 * 此函数在原始字符串中查找所有匹配的模式子串，并用替换字符串替换它们，
 * 将结果存储在动态分配的新字符串中。
 *
 * @param original    原始字符串（不会被修改）
 * @param pattern     要查找的模式子串
 * @param replacement 替换模式子串的字符串
 * @param outresult   输出参数，接收新字符串指针的地址（需调用者释放内存）
 *
 * @return 替换后新字符串的长度（字节数），若未找到匹配则返回0
 *
 * @note 内存管理：
 * - 成功时分配新内存，通过 outresult 返回
 * - 调用者负责使用 mem_free() 释放返回的内存
 * - 未找到匹配时，outresult 保持为 NULL
 *
 * @note 算法特性：
 * 1. 计算模式串出现次数
 * 2. 计算新字符串所需内存：len = orilen + patcnt * (replen - patlen)
 * 3. 遍历原始字符串，复制非匹配段和替换串
 *
 * @warning 重要限制：
 * - pattern 为空字符串时行为未定义
 * - 内存分配失败时返回0（不设置 outresult）
 * - 不支持正则表达式或通配符
 * - 替换串长度变化可能导致内存重新分配
 *
 * @example
 * const char *orig = "I like apples and apples";
 * char *result = NULL;
 * int len = cstr_replace_new(orig, "apples", "oranges", &result);
 * // len = 26, result = "I like oranges and oranges"
 * mem_free(result);
 *
 * @remark 性能说明：
 * - 时间复杂度：O(n*m) 最坏情况（n=原始串长度，m=模式串长度）
 * - 空间复杂度：O(n + k*(r-p))（k=匹配次数，r=替换串长，p=模式串长）
 */
int cstr_replace_new(const char *original, const char *pattern, const char *replacement, char **outresult)
{
    size_t const replen = strlen(replacement);
    size_t const patlen = strlen(pattern);
    size_t const orilen = strlen(original);

    size_t patcnt = 0;

    const char * oriptr;
    const char * patloc;

    *outresult = 0;

    // find how many times the pattern occurs in the original string
    for ((oriptr = original); (patloc = strstr(oriptr, pattern)); (oriptr = patloc + patlen)) {
        patcnt++;
    }

    if (patcnt) {
        // allocate memory for the new string
        size_t len = orilen + patcnt * (replen - patlen);

        char * result = (char *) mem_alloc(sizeof(char) * (len + 1) );

        // copy the original string,
        // replacing all the instances of the pattern
        char * retptr = result;

        for ((oriptr = original); (patloc = strstr(oriptr, pattern)); (oriptr = patloc + patlen)) {
            size_t const skplen = patloc - oriptr;

            // copy the section until the occurence of the pattern: strncpy
            memcpy(retptr, oriptr, skplen);
            retptr += skplen;

            // copy the replacement: strncpy
            memcpy(retptr, replacement, replen);
            retptr += replen;
        }

        // copy the rest of the string.
        strcpy(retptr, oriptr);

        *outresult = result;
        return (int) len;
    }

    return 0;
}

/**
 * @brief 验证并规范化十进制数值字符串
 *
 * 此函数验证输入字符串是否符合基本数值格式要求，并返回规范化后的字符串指针。
 * 函数会去除字符串两端的空白字符，然后检查剩余内容是否符合简单数值格式。
 *
 * @param numstr   待验证的字符串（将被原地修改）
 * @param maxwidth 最大允许长度（<=0 表示无限制）
 *
 * @return
 *   - 符合数值格式：返回规范化后的字符串指针（指向原字符串内）
 *   - 不符合格式：返回 NULL
 *
 * @retval 有效返回值示例：
 *   "8897391"         // 纯整数
 *   "   123.456"      // 带前导空白（处理后为"123.456"）
 *   "+123456.123"     // 带正号
 *   "-100  "          // 带负号和后导空白
 *
 * @retval 返回 NULL 的示例：
 *   ""                // 空字符串
 *   "   "             // 全空白字符
 *   "189 0931"        // 包含空白字符（非两端）
 *   "12.56.89"        // 多个小数点
 *   "+ 1234.556"      // 符号后跟空格
 *   "abc123"          // 包含非数字字符
 *   "123.456.789"     // 多个小数点
 *   (当 maxwidth=5 时) "123456" // 超过最大长度
 *
 * @note 验证规则：
 * 1. 首先调用 cstr_LRtrim_whitespace() 去除两端空白
 * 2. 检查长度：空字符串或全空白 → NULL
 * 3. 检查最大长度限制（maxwidth > 0 时）
 * 4. 允许首字符为 '+' 或 '-'
 * 5. 后续字符必须为数字或小数点
 * 6. 最多允许一个小数点
 *
 * @warning 注意：
 * - 会原地修改输入字符串（去除两端空白）
 * - 不验证数值范围（可能超出类型表示范围）
 * - 不支持科学计数法（如1.23e4）
 * - 不支持千位分隔符（如12,345）
 * - 返回的指针指向修改后的原字符串，生命周期与输入相同
 */
const char* cstr_to_digits(char *numstr, int maxwidth)
{
    int i = 0;
    int dots = 0;

    char *str = cstr_LRtrim_whitespace(numstr);
    int len = cstr_length(str, -1);
    if (len < 1) {
        return NULL; // empty
    }
    if (maxwidth > 0 && len > maxwidth) {
        return NULL; // too much
    }
    if (str[0] == '+' || str[0] == '-') {
        i = 1;
    }
    for (; i < len; i++) {
        if (! isdigit((int)str[i])) {
            if (str[i] == '.') {
                dots++;
                if (dots > 1) {
                    return NULL;
                }
            } else {
                return str;
            }
        }
    }
    return str;
}

/**
 * @brief 将字符串转换为有符号64位整数
 *
 * 此函数将指定长度的字符串转换为64位整数，支持2-36进制。函数会智能处理字符串终止符，
 * 并在可能的情况下避免内存复制，同时严格验证数字格式。
 *
 * @param base     进制（2-36），0表示自动检测进制
 * @param str      要转换的字符串（必须非NULL）
 * @param slen     字符串长度（字节数）
 * @param outval   输出参数，接收转换结果
 * @param buf      调用者提供的缓冲区，用于存储临时字符串
 * @param blen     缓冲区长度（必须≥256）
 *
 * @return 状态码：
 *   - 1：成功转换
 *   - -1：转换失败（无效字符、格式错误或尾部非空白字符）
 *   - -2：数值溢出（超出sb8范围）
 *   - -3：字符串过长（≥blen字符）
 *   - -4：空输入（str为NULL或slen=0）
 *
 * @note 转换规则：
 * 1. 自动跳过前导空白字符
 * 2. 识别可选符号（+/-）
 * 3. 自动检测进制（当base=0时）：
 *    - 0x前缀 → 16进制
 *    - 0前缀 → 8进制
 *    - 否则 → 10进制
 * 4. 允许尾部空白字符，但不允许其他非空白字符
 *
 * @warning 重要限制：
 * - 最大支持blen-1字符（防止缓冲区溢出）
 * - 转换失败时outval可能包含部分结果
 * - 调用者负责提供足够大的缓冲区（建议≥256字节）
 *
 * @example
 * sb8 value;
 * char buffer[256];
 * int ret;
 *
 * // 成功案例
 * ret = cstr_to_sb8(10, "123", 3, &value, buffer, sizeof(buffer)); // ret=1, value=123
 * ret = cstr_to_sb8(0, "  -42  ", 7, &value, buffer, sizeof(buffer)); // ret=1, value=-42
 * ret = cstr_to_sb8(16, "0xFF", 4, &value, buffer, sizeof(buffer)); // ret=1, value=255
 *
 * // 错误案例
 * ret = cstr_to_sb8(10, "abc", 3, &value, buffer, sizeof(buffer)); // ret=-1
 * ret = cstr_to_sb8(10, "99999999999999999999", 20, &value, buffer, sizeof(buffer)); // ret=-2
 * ret = cstr_to_sb8(10, "123abc", 6, &value, buffer, sizeof(buffer)); // ret=-1
 */
int cstr_to_sb8(int base, const char *str, size_t slen, sb8 *outval, char buf[], size_t blen)
{
    *outval = 0;

    if (!str || slen == 0) {
        cstr_return_error(-4, "str is null or empty");
    }

    int needs_copy = 1;
    if (cstr_invalid_size(slen)) {
        slen = strnlen(str, blen);
        needs_copy = 0;  // 此时字符串必然有终止符
    }
    if (slen >= blen) {
        // 长度验证
        cstr_return_error(-3, "str is too long");
    }

    const char *str_0_end;
    if (needs_copy) {
        // 原始字符串可能不是以空字符（'\0'）结尾的，而strtoll要求输入是一个以空字符结尾的字符串。
        memcpy(buf, str, slen);
        buf[slen] = '\0';
        str_0_end = buf;
    } else {
        // 直接使用原字符串（已有终止符）
        str_0_end = str;
    }

    // 执行转换
    sb8 val;
    char *endptr;

    // strtoll会跳过前导空白，但不会跳过尾部的空白。然而，我们的函数要求整个字符串
    //（除了前导空白）必须是有效的数字表示，后面可以跟空白，但不能跟其他非空白字符。
    errno = 0; // to distinguish success/failure after call
    val = strtoll(str_0_end, &endptr, base);
    *outval = val;

    // 检查转换错误
    if (endptr == str_0_end) {
        cstr_return_error(-1, "str is not qualified digits");
    }
    if (errno == ERANGE) {
        // 数值溢出: 可能是LLONG_MIN/LLONG_MAX
        // 如果转换的值超出了可表示范围，则返回`LLONG_MIN`或`LLONG_MAX`并设置`errno`为`ERANGE`。
        // 如果没有发生错误，`strtoll`不会修改`errno`。
        cstr_return_error(-2, "value of str is overflow");
    }

    // 检查尾部无效字符
    const char *p = endptr;  // 使用临时指针，保留endptr位置
    while (*p != '\0') {
        if (!isspace((unsigned char)*p)) {
            return -1;  // 尾部非空白字符
        }
        p++;
    }

    // 成功返回: 如果没有发生错误，`strtoll`不会修改`errno`。
    return 1;
}

/**
 * @brief 将字符串转换为无符号64位整数
 *
 * 此函数将指定长度的字符串转换为64位无符号整数，支持2-36进制。函数会智能处理字符串终止符，
 * 并在可能的情况下避免内存复制，同时严格验证数字格式。
 *
 * @param base     进制（2-36），0表示自动检测进制
 * @param str      要转换的字符串（必须非NULL）
 * @param slen     字符串长度（字节数）
 * @param outval   输出参数，接收转换结果
 * @param buf      调用者提供的缓冲区，用于存储临时字符串
 * @param blen     缓冲区长度（必须≥256）
 *
 * @return 状态码：
 *   - 1：成功转换
 *   - -1：转换失败（无效字符、格式错误或尾部非空白字符）
 *   - -2：数值溢出（超出ub8范围）
 *   - -3：字符串过长（≥blen字符）
 *   - -4：空输入（str为NULL或slen=0）
 *   - -5：无效进制（base不在2-36范围内）
 *
 * @note 转换规则：
 * 1. 自动跳过前导空白字符
 * 2. 识别可选正号（+），但负号（-）视为无效字符
 * 3. 自动检测进制（当base=0时）：
 *    - 0x前缀 → 16进制
 *    - 0前缀 → 8进制
 *    - 否则 → 10进制
 * 4. 允许尾部空白字符，但不允许其他非空白字符
 *
 * @warning 重要限制：
 * - 最大支持blen-1字符（防止缓冲区溢出）
 * - 转换失败时outval可能包含部分结果
 * - 调用者负责提供足够大的缓冲区（建议≥256字节）
 * - 不支持负值输入（负号视为无效字符）
 *
 * @example
 * ub8 value;
 * char buffer[256];
 * int ret;
 *
 * // 成功案例
 * ret = cstr_to_ub8(10, "123", 3, &value, buffer, sizeof(buffer)); // ret=1, value=123
 * ret = cstr_to_ub8(0, "  42  ", 6, &value, buffer, sizeof(buffer)); // ret=1, value=42
 * ret = cstr_to_ub8(16, "0xFF", 4, &value, buffer, sizeof(buffer)); // ret=1, value=255
 * ret = cstr_to_ub8(2, "1010", 4, &value, buffer, sizeof(buffer)); // ret=1, value=10
 *
 * // 错误案例
 * ret = cstr_to_ub8(10, "abc", 3, &value, buffer, sizeof(buffer)); // ret=-1
 * ret = cstr_to_ub8(10, "99999999999999999999", 20, &value, buffer, sizeof(buffer)); // ret=-2
 * ret = cstr_to_ub8(10, "123abc", 6, &value, buffer, sizeof(buffer)); // ret=-1
 * ret = cstr_to_ub8(10, "-123", 4, &value, buffer, sizeof(buffer)); // ret=-1 (负号无效)
 * ret = cstr_to_ub8(1, "123", 3, &value, buffer, sizeof(buffer)); // ret=-5 (无效进制)
 */
int cstr_to_ub8(int base, const char *str, size_t slen, ub8 *outval, char buf[], size_t blen)
{
    *outval = 0;

    if (!str || slen == 0) {
        cstr_return_error(-4, "str is null or empty");
    }

    int needs_copy = 1;
    if (cstr_invalid_size(slen)) {
        slen = strnlen(str, blen);
        needs_copy = 0;  // 此时字符串必然有终止符
    }
    if (slen >= blen) {
        // 长度验证
        cstr_return_error(-3, "str is too long");
    }

    const char *str_0_end;
    if (needs_copy) {
        // 原始字符串可能不是以空字符（'\0'）结尾的，而strtoull要求输入是一个以空字符结尾的字符串。
        memcpy(buf, str, slen);
        buf[slen] = '\0';
        str_0_end = buf;
    } else {
        // 直接使用原字符串（已有终止符）
        str_0_end = str;
    }

    // 执行转换
    ub8 val;
    char *endptr;

    // strtoull会跳过前导空白，但不会跳过尾部的空白。然而，我们的函数要求整个字符串
    //（除了前导空白）必须是有效的数字表示，后面可以跟空白，但不能跟其他非空白字符。
    errno = 0; // to distinguish success/failure after call
    val = strtoull(str_0_end, &endptr, base);
    *outval = val;

    // 检查转换错误
    if (endptr == str_0_end) {
        cstr_return_error(-1, "str is not qualified digits");
    }
    if (errno == ERANGE) {
        // 如果转换的值超出了可表示范围，则设置`errno`为`ERANGE`。
        // 如果没有发生错误，`strtod`不会修改`errno`。
        cstr_return_error(-2, "value of str is overflow");
    }

    // 检查尾部无效字符
    const char *p = endptr;  // 使用临时指针，保留endptr位置
    while (*p != '\0') {
        if (!isspace((unsigned char)*p)) {
            return -1;  // 尾部非空白字符
        }
        p++;
    }

    // 成功返回: 如果没有发生错误，`strtoull`不会修改`errno`。
    return 1;
}

/**
 * @brief 将字符串转换为双精度浮点数
 *
 * 此函数将指定长度的字符串转换为双精度浮点数，支持标准浮点数表示法。
 * 函数会智能处理字符串终止符，并在可能的情况下避免内存复制，同时严格验证数字格式。
 *
 * @param str      要转换的字符串（必须非NULL）
 * @param slen     字符串长度（字节数）
 * @param outval   输出参数，接收转换结果
 * @param buf      调用者提供的缓冲区，用于存储临时字符串
 * @param blen     缓冲区长度（必须≥256）
 *
 * @return 状态码：
 *   - 1：成功转换
 *   - -1：转换失败（无效字符、格式错误或尾部非空白字符）
 *   - -2：数值溢出（超出double范围）
 *   - -3：字符串过长（≥blen字符）
 *   - -4：空输入（str为NULL或slen=0）
 *
 * @note 转换规则：
 * 1. 支持标准浮点数格式：
 *    - 十进制：123.456
 *    - 科学计数法：1.234e-5
 *    - 特殊值：inf, nan
 * 2. 自动跳过前导空白字符
 * 3. 识别可选符号（+/-）
 * 4. 允许尾部空白字符，但不允许其他非空白字符
 *
 * @warning 重要限制：
 * - 最大支持blen-1字符（防止缓冲区溢出）
 * - 转换失败时outval可能包含部分结果
 * - 调用者负责提供足够大的缓冲区（建议≥256字节）
 * - 精度受double类型限制（约15位有效数字）
 *
 * @example
 * double value;
 * char buffer[256];
 * int ret;
 *
 * // 成功案例
 * ret = cstr_to_dbl("123.45", 6, &value, buffer, sizeof(buffer)); // ret=1, value=123.45
 * ret = cstr_to_dbl("  -1.23e-4  ", 11, &value, buffer, sizeof(buffer)); // ret=1, value=-0.000123
 * ret = cstr_to_dbl("inf", 3, &value, buffer, sizeof(buffer)); // ret=1, value=HUGE_VAL
 * ret = cstr_to_dbl("nan", 3, &value, buffer, sizeof(buffer)); // ret=1, value=NAN
 *
 * // 错误案例
 * ret = cstr_to_dbl("abc", 3, &value, buffer, sizeof(buffer)); // ret=-1
 * ret = cstr_to_dbl("1.23.45", 7, &value, buffer, sizeof(buffer)); // ret=-1
 * ret = cstr_to_dbl("9e999", 5, &value, buffer, sizeof(buffer)); // ret=-2 (溢出)
 * ret = cstr_to_dbl("123abc", 6, &value, buffer, sizeof(buffer)); // ret=-1
 */
int cstr_to_dbl(const char *str, size_t slen, double *outval, char buf[], size_t blen)
{
    *outval = 0;

    if (!str || slen == 0) {
        cstr_return_error(-4, "str is null or empty");
    }

    int needs_copy = 1;
    if (cstr_invalid_size(slen)) {
        slen = strnlen(str, blen);
        needs_copy = 0;  // 此时字符串必然有终止符
    }
    if (slen >= blen) {
        // 长度验证
        cstr_return_error(-3, "str is too long");
    }

    const char *str_0_end;
    if (needs_copy) {
        // 原始字符串可能不是以空字符（'\0'）结尾的，而strtod要求输入是一个以空字符结尾的字符串。
        memcpy(buf, str, slen);
        buf[slen] = '\0';
        str_0_end = buf;
    } else {
        // 直接使用原字符串（已有终止符）
        str_0_end = str;
    }

    // 执行转换
    double val;
    char *endptr;

    // strtod会跳过前导空白，但不会跳过尾部的空白。然而，我们的函数要求整个字符串
    //（除了前导空白）必须是有效的数字表示，后面可以跟空白，但不能跟其他非空白字符。
    errno = 0; // to distinguish success/failure after call
    val = strtod(str_0_end, &endptr);  // strtod 只需两个参数
    *outval = val;

    // 检查转换错误
    if (endptr == str_0_end) {
        cstr_return_error(-1, "str is not qualified digits");
    }
    if (errno == ERANGE) {
        // 如果转换的值超出了可表示范围，则设置`errno`为`ERANGE`。
        // 如果没有发生错误，`strtod`不会修改`errno`。
        cstr_return_error(-2, "value of str is overflow");
    }

    // 检查尾部无效字符
    const char *p = endptr;  // 使用临时指针，保留endptr位置
    while (*p != '\0') {
        if (!isspace((unsigned char)*p)) {
            return -1;  // 尾部非空白字符
        }
        p++;
    }

    // 成功返回: 如果没有发生错误，`strtod`不会修改`errno`。
    return 1;
}

/**
 * @brief 在字符串中查找下一个分隔符分隔的子串（支持转义处理）
 *
 * 此函数在给定字符串范围内查找下一个由指定分隔符分隔的子串，支持处理转义字符。
 * 函数会返回下一个子串的起始位置，并输出当前子串的信息。
 *
 * @param start 当前搜索的起始位置（包含）
 * @param end 字符串结束位置（不包含），若为NULL则搜索到字符串结尾('\0')
 * @param sep 分隔字符
 * @param[out] next 输出当前子串的起始位置
 * @param[out] nextlen 输出当前子串的长度
 * @param[out] escapes 存放当前子串的转义字符计数。若为NULL则忽略转义字符
 *
 * @return const char*
 *   - 返回剩余字符串的起始位置（下一个子串开始的位置）
 *   - 若已到达字符串末尾，返回NULL
 *
 * @note 调用者必须确保start参数指向有效内存，end指向start字符串末尾('\0')或为NULL
 * @note 当escapes参数为NULL时，函数忽略转义处理
 * @note 函数不会修改原始字符串内容
 * @note 当返回NULL时，表示没有更多子串，但此时next可能包含最后一个子串
 *
 * @details 转义处理规则：
 *   1. 仅当 escapes 不为 NULL，才处理转义，否则忽略
 *   2. 反斜杠(\)作为转义字符，使其后的字符（包括分隔符）被视为普通字符
 *   3. 连续转义字符(如\\\\)会被正确处理
 *
 * @see cstr_split_chr_nodup
 */
const char * cstr_split_chr_next(const char *start, const char *end, char sep,
    const char **next, int *nextlen, int *escapes)
{
    const char *s = start;
    const char *p = s;

    *next = NULL;

    if (escapes) {
        // 当需要转义时
        int nescapes = 0;
        const char *escape = 0;

        while (p) {
            if (p == end || *p == 0) {
                *next = s;
                *nextlen = (int)(p - s);
                *escapes = nescapes;
                return NULL; // 有值且完成搜索
            }

            if (*p == sep) {
                if (escape) {
                    escape = 0;
                    p++;
                    continue;
                }
                *next = s;
                *nextlen = (int)(p++ - s);
                *escapes = nescapes;
                return p; // 有值期待下一个搜索
            }

            if (*p == '\\') {
                if (p == escape + 1) {
                    escape = 0;
                } else {
                    escape = p;
                }
                p++;
                nescapes++;
                continue;
            }

            escape = 0;
            p++;
        }
    } else {
        // 当不需要转义时
        while (p) {
            if (p == end || *p == 0) {
                *next = s;
                *nextlen = (int)(p - s);
                return NULL; // 有值且完成搜索
            }

            if (*p == sep) {
                *next = s;
                *nextlen = (int)(p++ - s);
                return p; // 有值期待下一个搜索
            }
            p++;
        }
    }

    // 无值且完成搜索
    return NULL;
}

/**
 * @brief 分割字符串为多个子串（支持转义处理）
 *
 * 此函数将输入字符串分割为多个子串，使用cstr_split_chr_next实现。
 * 支持处理转义字符，可获取每个子串的转义字符计数。
 *
 * @param start 字符串起始位置
 * @param end 字符串结束位置（不包含），若为NULL则处理到字符串结尾('\0')
 * @param sep 分隔字符
 * @param[out] subs 输出子串指针数组
 * @param[out] sublens 输出子串长度数组
 * @param[out] escapes 输出子串转义计数数组。若为NULL则忽略转义
 * @param maxsubs 数组 subs, sublens, escapes 的最小容量（即最多能存储的子串数量）
 *
 * @return int
 *   - 如果maxsubs为0，返回子串数量，不会存贮子串
 *   - 如果maxsubs>0，返回存贮的子串数量，最多为maxsubs
 *
 * @note 当实际子串数量大于maxsubs(maxsubs > 0)时，超出部分不会被存储。
 * @note subs, sublens和escapes数组长度必须至少为maxsubs
 * @note 函数不会修改原始字符串内容
 *
 * @details 转义处理规则：
 *   1. 仅当 escapes 不为 NULL，才处理转义，否则忽略
 *   2. 每个子串的转义计数单独统计
 *
 * @see cstr_split_chr_next
 */
int cstr_split_chr_num(const char *start, const char *end, char sep,
    const char *subs[], int sublens[], int escapes[], int maxsubs)
{
    int i = 0;

    if (escapes) {
        const char *next;
        int nextlen;
        int escape;
        const char *str = start;
        do {
            str = cstr_split_chr_next(str, end, sep, &next, &nextlen, &escape);
            if (next) {
                if (maxsubs > 0) {
                    if (i < maxsubs) {
                        // 存储子串信息
                        subs[i] = next;
                        sublens[i] = nextlen;
                        escapes[i] = escape;
                    } else {
                        // 存储空间已满，立即返回
                        return i;  // 返回当前已存储的子串数量
                    }
                }
                i++; // 增加子串计数
            }
        } while(str);
    } else {
        const char *next;
        int nextlen;
        const char *str = start;
        do {
            str = cstr_split_chr_next(str, end, sep, &next, &nextlen, NULL);
            if (next) {
                if (maxsubs > 0) {
                    if (i < maxsubs) {
                        // 存储子串信息
                        subs[i] = next;
                        sublens[i] = nextlen;
                    } else {
                        // 存储空间已满，立即返回
                        return i;  // 返回当前已存储的子串数量
                    }
                }
                i++; // 增加子串计数
            }
        } while(str);
    }

    // maxsubs>0: 返回实际保存的子串数量
    // 否则返回全部子串数量，并且不保存的任何子串
    return i;
}

/**
 * @brief 在字符串中查找下一个由多个分隔符分隔的子串（支持转义处理）
 *
 * 此函数在给定字符串范围内查找下一个由指定分隔符集合中任意字符分隔的子串，支持处理转义字符。
 * 函数会返回下一个子串的起始位置，并输出当前子串的信息。
 *
 * @param start 当前搜索的起始位置（包含）
 * @param end 字符串结束位置（不包含），若为NULL则搜索到字符串结尾('\0')
 * @param seps 分隔字符集合（C字符串），如"$#&"表示$、#、&都是分隔符
 * @param[out] next 输出当前子串的起始位置
 * @param[out] nextlen 输出当前子串的长度
 * @param[out] escapes 存放当前子串的转义字符计数。若为NULL则忽略转义字符
 *
 * @return const char*
 *   - 返回剩余字符串的起始位置（下一个子串开始的位置）
 *   - 若已到达字符串末尾，返回NULL
 *
 * @note 调用者必须确保start参数指向有效内存，end指向start字符串末尾('\0')或为NULL
 * @note 当escapes参数为NULL时，函数忽略转义处理
 * @note 函数不会修改原始字符串内容
 * @note 当返回NULL时，表示没有更多子串，但此时next可能包含最后一个子串
 * @note 调用者必须确保seps参数不能为NULL，否则行为未定义
 *
 * @details 转义处理规则：
 *   1. 仅当 escapes 不为 NULL，才处理转义，否则忽略
 *   2. 反斜杠(\)作为转义字符，使其后的字符（包括分隔符）被视为普通字符
 *   3. 连续转义字符(如\\\\)会被正确处理
 *   4. 使用strchr(seps, *p)检测分隔符，支持多字符分隔
 *
 * @see cstr_split_chr_next
 */
const char * cstr_split_chrs_next(const char *start, const char *end, const char *seps,
    const char **next, int *nextlen, int *escapes)
{
    int is_sep;
    const char *s = start;
    const char *p = s;

    *next = NULL;

    if (escapes) {
        // 当需要转义时
        int nescapes = 0;
        const char *escape = 0;

        while (p) {
            if (p == end || *p == 0) {
                *next = s;
                *nextlen = (int)(p - s);
                *escapes = nescapes;
                return NULL; // 有值且完成搜索
            }

            is_sep = 0;
            for (const char *sep = seps; *sep; sep++) {
                if (*p == *sep) {
                    is_sep = 1;
                    break;
                }
            }

            if (is_sep) {
                if (escape) {
                    escape = 0;
                    p++;
                    continue;
                }
                *next = s;
                *nextlen = (int)(p++ - s);
                *escapes = nescapes;
                return p; // 有值期待下一个搜索
            }

            if (*p == '\\') {
                if (p == escape + 1) {
                    escape = 0;
                } else {
                    escape = p;
                }
                p++;
                nescapes++;
                continue;
            }

            escape = 0;
            p++;
        }
    } else {
        // 当不需要转义时
        while (p) {
            if (p == end || *p == 0) {
                *next = s;
                *nextlen = (int)(p - s);
                return NULL; // 有值且完成搜索
            }

            is_sep = 0;
            for (const char *sep = seps; *sep; sep++) {
                if (*p == *sep) {
                    is_sep = 1;
                    break;
                }
            }

            if (is_sep) {
                *next = s;
                *nextlen = (int)(p++ - s);
                return p; // 有值期待下一个搜索
            }
            p++;
        }
    }

    // 无值且完成搜索
    return NULL;
}

/**
 * @brief 分割字符串为多个子串（支持多分隔符和转义处理）
 *
 * 此函数将输入字符串分割为多个子串，支持多个分隔符和转义处理。
 * 使用 cstr_split_chrs_next 实现，可获取每个子串的转义字符计数。
 *
 * @param start 字符串起始位置
 * @param end 字符串结束位置（不包含），若为NULL则处理到字符串结尾('\0')
 * @param seps 分隔字符集合（C字符串），如"$#&"表示$、#、&都是分隔符
 * @param[out] subs 输出子串指针数组
 * @param[out] sublens 输出子串长度数组
 * @param[out] escapes 输出子串转义计数数组。若为NULL则忽略转义
 * @param maxsubs 数组 subs, sublens, escapes 的最小容量（即最多能存储的子串数量），必须为非负数
 *
 * @return int
 *   - 如果 maxsubs 为 0，返回子串总数（不存储任何子串）
 *   - 如果 maxsubs > 0，返回实际存储的子串数量（最多为 maxsubs）
 *
 * @note 当实际子串数量大于 maxsubs 时，超出部分不会被存储
 * @note subs, sublens 和 escapes 数组长度必须至少为 maxsubs
 * @note 函数不会修改原始字符串内容
 *
 * @details 转义处理规则：
 *   1. 仅当 escapes 不为 NULL，才处理转义，否则忽略
 *   2. 每个子串的转义计数单独统计
 *
 * @see cstr_split_chrs_next
 */
int cstr_split_chrs_num(const char *start, const char *end, const char* seps,
    const char *subs[], int sublens[], int escapes[], int maxsubs)
{
    int i = 0;

    if (escapes) {
        const char *next;
        int nextlen;
        int escape;
        const char *str = start;
        do {
            str = cstr_split_chrs_next(str, end, seps, &next, &nextlen, &escape);
            if (next) {
                if (maxsubs > 0) {
                    if (i < maxsubs) {
                        // 存储子串信息
                        subs[i] = next;
                        sublens[i] = nextlen;
                        escapes[i] = escape;
                    } else {
                        // 存储空间已满，立即返回
                        return i;  // 返回当前已存储的子串数量
                    }
                }
                i++; // 增加子串计数
            }
        } while(str);
    } else {
        const char *next;
        int nextlen;
        const char *str = start;
        do {
            str = cstr_split_chrs_next(str, end, seps, &next, &nextlen, NULL);
            if (next) {
                if (maxsubs > 0) {
                    if (i < maxsubs) {
                        // 存储子串信息
                        subs[i] = next;
                        sublens[i] = nextlen;
                    } else {
                        // 存储空间已满，立即返回
                        return i;  // 返回当前已存储的子串数量
                    }
                }
                i++; // 增加子串计数
            }
        } while(str);
    }

    // maxsubs>0: 返回实际保存的子串数量
    // 否则返回全部子串数量，并且不保存的任何子串
    return i;
}

/**
 * @brief 去除字符串中的转义序列
 *
 * 此函数将处理字符串中的转义序列（特别是反斜杠转义）：
 * 1. "\\\\" → "\\"（两个反斜杠变为一个）
 * 2. "\\&" → "&"（转义的字符变为普通字符）
 *
 * @param str 输入字符串
 * @param len 输入字符串长度
 * @param chr 需要反转义的特殊字符（如 '&'）
 * @param copybuf 输出的字符串缓冲区(输出长度不会超过输入长度，因此调用者保证缓冲区长度为len即可)
 * @return int 处理后的 copybuf 字符串长度(不保证 copybuf 结尾为 '\0')
 *
 * @note 函数不会修改输入字符串
 */
int cstr_unescape_chr(const char *str, int len, char chr, char *copybuf)
{
    int r = 0;      // 读指针位置
    int w = 0;      // 写指针位置
    int escape = 0; // 转义状态标志

    // 遍历输入字符串
    while (r < len) {
        if (!escape && str[r] == '\\') {
            // 遇到转义字符，设置转义状态
            escape = 1;
            r++;
            continue;
        }

        if (escape) {
            // 处理转义序列
            escape = 0;

            if (str[r] == '\\' || str[r] == chr) {
                // 处理特定转义序列：\\ 和 \&
                copybuf[w++] = str[r++];
            } else {
                // 非特殊转义序列，保留反斜杠和字符
                copybuf[w++] = '\\';
                copybuf[w++] = str[r++];
            }
        } else {
            // 普通字符直接复制
            copybuf[w++] = str[r++];
        }
    }

    // 处理末尾的转义字符（如以单个 \ 结束）
    if (escape) {
        copybuf[w++] = '\\';
    }

    return w; // 返回处理后的字符串长度
}

/**
 * @brief 在字符串中查找下一个由字符串分隔的子串（不支持转义处理）
 *
 * 此函数在给定字符串范围内查找下一个由指定分隔字符串分隔的子串。
 * 不支持转义处理，分隔字符串被视为普通字符序列。
 *
 * @param start 当前搜索的起始位置（包含）
 * @param end 字符串结束位置（不包含），若为NULL则搜索到字符串结尾('\0')
 * @param sepstr 分隔字符串（如"$$"）
 * @param sepslen 分隔字符串的长度
 * @param[out] next 输出当前子串的起始位置
 * @param[out] nextlen 输出当前子串的长度
 *
 * @return const char*
 *   - 返回剩余字符串的起始位置（下一个子串开始的位置）
 *   - 若已到达字符串末尾，返回NULL
 *
 * @note 调用者必须确保start参数指向有效内存，end指向start字符串末尾('\0')或为NULL
 * @note 函数不会修改原始字符串内容，不支持转义处理，分隔字符串被视为普通字符序列
 * @note 当返回NULL时，表示没有更多子串，但此时next可能包含最后一个子串
 * @note 分隔字符串必须有效，（sepslen == 0）时行为未定义
 *
 * @see cstr_split_chr_next
 */
const char * cstr_split_str_next(const char *start, const char *end, const char* sepstr, int sepslen,
    const char **next, int *nextlen)
{
    const char* endsep = sepstr + sepslen;

    const char *s = start;
    const char *p = s;

    int found_sepstr;
    *next = NULL;

    while (p) {
        if (p == end || *p == 0) {
            *next = s;
            *nextlen = (int)(p - s);
            return NULL; // 有值且完成搜索
        }

        // p 查找 sepstr
        found_sepstr = 1;

        const char *a = p;
        const char *ep = sepstr;
        while (a != end && ep != endsep) {
            if (*a++ != *ep++) {
                found_sepstr = 0;
                break;
            }
        }

        if (found_sepstr && ep == endsep) {
            *next = s;
            *nextlen = (int)(p - s);
            p += sepslen;
            return p; // 有值期待下一个搜索
        }

        p++;
    }

    // 无值且完成搜索
    return NULL;
}

/**
 * @brief 计算字符串中由指定分隔符分隔的子串数量并存储子串信息
 *
 * 此函数通过重复调用cstr_split_str_next函数，计算在指定字符串范围内
 * 由分隔字符串分隔的子串总数，并可将子串的起始位置和长度存储到数组中。
 *
 * @param start 字符串搜索的起始位置（包含）
 * @param end 字符串结束位置（不包含），若为NULL则搜索到字符串结尾('\0')
 * @param sepstr 分隔字符串（如"$$"）
 * @param sepslen 分隔字符串的长度
 * @param[out] subs 存储子串起始位置的数组，若为NULL则不存储
 * @param[out] sublens 存储子串长度的数组，若为NULL则不存储
 * @param maxsubs 最大可存储的子串数量，若为0则仅计数不存储。不可以为负数
 *
 * @return int
 *   - 返回字符串中包含的子串总数
 *   - 当maxsubs>0时，返回实际存储的子串数量（不超过maxsubs）
 *
 * @note 调用者需确保subs和sublens数组的大小不小于maxsubs
 * @note 当maxsubs为0时，仅计算子串总数，不修改subs和sublens
 * @note 分隔字符串必须有效，（sepslen == 0）时行为未定义
 *
 * @see cstr_split_str_next
 */
int cstr_split_str_num(const char *start, const char *end, const char* sepstr, int sepslen,
    const char *subs[], int sublens[], int maxsubs)
{
    int i = 0;

    const char *next;
    int nextlen;
    const char *str = start;
    do {
        str = cstr_split_str_next(str, end, sepstr, sepslen, &next, &nextlen);
        if (next) {
            if (maxsubs > 0) {
                if (i < maxsubs) {
                    // 存储子串信息
                    subs[i] = next;
                    sublens[i] = nextlen;
                } else {
                    // 存储空间已满，立即返回
                    return i;  // 返回当前已存储的子串数量
                }
            }
            i++; // 增加子串计数
        }
    } while(str);

    // maxsubs>0: 返回实际保存的子串数量
    // 否则返回全部子串数量，并且不保存的任何子串
    return i;
}

/**
 * @brief 比较两个字符串是否不相等（区分大小写）
 *
 * 此函数用于比较两个以'\0'结尾的字符串是否不相等，是字符串不等性的判断函数。
 * 当两个字符串完全相同时返回false，否则返回true。
 *
 * @param s1 第一个待比较的字符串
 * @param s2 第二个待比较的字符串
 *
 * @return int
 *   - 返回 0：两个字符串完全相同
 *   - 返回 1：两个字符串不相同
 *
 * @note 当两个指针指向同一内存地址时，判定为相等
 * @note 支持NULL指针比较，NULL与任何非NULL字符串均判定为不相等
 * @note 比较过程区分大小写（如'A'与'a'被视为不同）
 *
 * @see cstr_neq_len
 */
int cstr_neq(const char *s1, const char *s2)
{
    if (s1 == s2) {
        return 0;
    }
    if (s1 && s2) {
        const char *a = s1;
        const char *b = s2;
        while (*a && *b) {
            // a != A
            if (*a++ != *b++) {
                // s1 != s2
                return 1;
            }
        }
        if (!*a && !*b) {
            // s1 == s2
            return 0;
        }
    }
    // s1 != s2
    return 1;
}

/**
 * @brief 比较指定长度的两个字符串片段是否不相等（区分大小写）
 *
 * 此函数用于比较两个字符串的指定长度片段是否不相等，是指定长度的字符串
 * 不等性判断函数。当两个片段完全相同时返回false，否则返回true。
 *
 * @param s1 第一个待比较的字符串
 * @param len1 第一个字符串参与比较的长度
 * @param s2 第二个待比较的字符串
 * @param len2 第二个字符串参与比较的长度
 *
 * @return int
 *   - 返回 0：两个字符串片段完全相同
 *   - 返回 1：两个字符串片段不相同
 *
 * @note 首先比较长度，长度不同直接判定为不相等
 * @note 当两个指针指向同一内存地址时，判定为相等
 * @note 支持NULL指针比较，NULL与任何非NULL字符串均判定为不相等
 * @note 比较过程区分大小写（如'A'与'a'被视为不同）
 *
 * @see cstr_neq
 */
int cstr_neq_len(const char *s1, size_t l1, const char *s2, size_t l2)
{
    if (s1 == s2) {
        // s1 == s2
        return 0; // false
    }
    if (!s1) {
        // s1 (null) != s2 (non-null)
        return 1; // true
    }
    if (!s2) {
        // s1 (non-null) != s2 (null)
        return 1; // true
    }

    // s1, s2: both non-null

    if (cstr_invalid_size(l1)) {
        l1 = strlen(s1);
    }
    if (cstr_invalid_size(l2)) {
        l2 = strlen(s2);
    }

    if (l1 != l2) {
        // s1 != s2
        return 1; // true
    }

    // l1 == l2
    if (!l1) {
        // s1 == s2: both empty
        return 0; // false
    }

    const char *end = s1 + l1;
    while (s1 < end) {
        if (*s1++ != *s2++) {
            // s1 != s2
            return 1;
        }
    }

    // s1 == s2
    return 0; // false
}

/**
 * @brief 安全比较两个字符串。字符串长度长的大于短的。相同的情况下规则与 strncmp 兼容。
 *
 * 按指定长度比较两个字符串的大小关系，支持忽略大小写，同时处理 NULL 指针、空字符串等边界场景，
 *
 * @param s1 第一个待比较的字符串（可传入 NULL）
 * @param l1 第一个字符串的比较长度；若传入 (size_t)(-1)，则自动计算 s1 的实际长度（依赖 strlen）
 * @param s2 第二个待比较的字符串（可传入 NULL）
 * @param l2 第二个字符串的比较长度；若传入 (size_t)(-1)，则自动计算 s2 的实际长度（依赖 strlen）
 * @param caseignore 是否忽略大小写（非 0 表示忽略，0 表示区分大小写）
 *
 * @return int
 *   - 返回 1：s1 大于 s2
 *   - 返回 0：s1 等于 s2
 *   - 返回 -1：s1 小于 s2
 *
 * @note 1. NULL 字符串（s1/s2 为 NULL）小于任何非 NULL 或空字符串（""）
 * @note 2. 长度不同时，较短的字符串视为更小（如 "abc" < "abcd"）
 * @note 3. 两个 NULL 字符串判定为相等（返回 0）
 * @note 4. 当 l1/l2 为 (size_t)(-1) 时，需确保非 NULL 的 s1/s2 是以 '\0' 结尾的合法字符串（否则 strlen 会越界）
 */
int cstr_compare(const char *s1, size_t l1, const char *s2, size_t l2, int caseignore)
{
    if (s1 == s2) {
        // same pointer
        return 0;
    }
    if (!s1) {
        // s2 is non-NULL: s1 < s2
        return (-1);
    }
    if (!s2) {
        // s1 is non-NULL: s1 > s2
        return 1;
    }

    if (cstr_invalid_size(l1)) {
        l1 = strlen(s1);
    }
    if (cstr_invalid_size(l2)) {
        l2 = strlen(s2);
    }

    if (l1 > l2) {
        // s1 > s2
        return 1;
    }
    if (l1 < l2) {
        // s1 < s2
        return -1;
    }

    // l1 == l2
    if (!l1) {
        // s1, s2 are both empty
        return 0;
    }

    // here: (l1==l2) > 0

    const char *end = s1 + l1;

    if (! caseignore) {
        // caseignore=0: a != A
        while (s1 < end) {
            int p = *s1++;
            int q = *s2++;
            if (p > q) {
                return 1;
            } else if (p < q) {
                return -1;
            }
        }
        // s1 == s2
        return 0;
    }

    // caseignore!=0: a == A
    while (s1 < end) {
        int p = *s1++;
        int q = *s2++;

        if (p == q) {
            continue;
        }

        p = tolower((unsigned char) p);
        q = tolower((unsigned char) q);

        if (p > q) {
            return 1;
        } else if (p < q) {
            return -1;
        }
    }
    // s1 == s2
    return 0;
}

/**
 * @brief 判断字符串是否以指定前缀开头（区分大小写）
 *
 * 验证目标字符串的起始部分是否与指定前缀完全一致，支持手动指定长度或自动计算长度（通过无效长度标记触发）。
 * 匹配规则：前缀长度需小于等于目标字符串长度，且对应位置字符完全相同（区分大小写）。
 *
 * @param str 目标字符串（待判断是否包含前缀的字符串）
 * @param len 目标字符串的比较长度；若传入无效长度(-1)，计算实际长度
 * @param start 前缀字符串（用于匹配的起始片段）
 * @param startlen 前缀字符串的长度；若传入无效长度(-1)，计算实际长度
 *
 * @return int
 *   - 返回 1：目标字符串以指定前缀开头（匹配成功）
 *   - 返回 0：目标字符串不以指定前缀开头（匹配失败，含空指针、长度不满足、字符不匹配等场景）
 *
 * @note 忽略参数有效性检查，调用者需确保：
 *       1. 非 NULL 的 str/start 是合法 C 字符串（以 '\0' 结尾），否则自动计算长度时 `strlen` 行为未定义
 *
 * @note 当 str 与 start 指向同一内存地址时，直接判定为匹配（返回 1）
 * @note 比较过程区分大小写（如 'A' 与 'a' 视为不同字符）
 */
int cstr_startswith(const char *str, size_t len, const char *start, size_t startlen)
{
    if (str == start) {
        return 1;
    }
    if (!str || !start) {
        return 0;
    }
    if (cstr_invalid_size(len)) {
        len = strlen(str);
    }
    if (cstr_invalid_size(startlen)) {
        startlen = strlen(start);
    }
    if (startlen > len) {
        return 0;
    }

    // len >= startlen
    const char * end = start + startlen;
    const char *s = str;
    const char *p = start;
    while (p < end) {
        if (*p++ != *s++) {
            return 0;
        }
    }
    return 1;
}

/**
 * @brief 判断字符串是否以指定后缀结尾（区分大小写）
 *
 * 验证目标字符串的末尾部分是否与指定后缀完全一致，支持手动指定长度或自动计算长度（通过无效长度标记触发）。
 * 匹配规则：后缀长度需小于等于目标字符串长度，且后缀与目标字符串末尾对应长度的字符完全相同（区分大小写）。
 *
 * @param str 目标字符串（待判断是否包含后缀的字符串）
 * @param len 目标字符串的有效长度；若传入无效长度(-1) 则自动调用 `strlen(str)` 计算实际长度
 * @param end 后缀字符串（用于匹配的末尾片段，如示例中的 "aBBBB"）
 * @param endlen 后缀字符串的长度；若传入无效长度(-1) 则自动调用 `strlen(str)` 计算实际长度
 *
 * @return int
 *   - 返回 1：目标字符串以指定后缀结尾（匹配成功，如示例中 str="aaaaBBBB"、end="aBBBB" 时返回 1）
 *   - 返回 0：目标字符串不以指定后缀结尾（匹配失败，含空指针、后缀长度超限、字符不匹配等场景）
 *
 * @note 忽略参数有效性检查，调用者需确保：
 *       1. 非 NULL 的 str/end 是合法 C 字符串（以 '\0' 结尾），否则自动计算长度时 `strlen` 行为未定义
 *
 * @note 当 str 与 end 指向同一内存地址时，直接判定为匹配（返回 1）
 * @note 比较过程区分大小写（如 'B' 与 'b' 视为不同字符）
 * @note 若后缀长度为 0（空字符串），则默认匹配成功（返回 1，空字符串是任何字符串的后缀）
 */
int cstr_endswith(const char *str, size_t len, const char *end, size_t endlen)
{
    if (str == end) {
        return 1;
    }
    if (!str || !end) {
        return 0;
    }
    if (cstr_invalid_size(len)) {
        len = strlen(str);
    }
    if (cstr_invalid_size(endlen)) {
        endlen = strlen(end);
    }
    if (endlen > len) {
        return 0;
    }

    // len >= endlen
    const char *s = str + len - endlen;
    const char *p = end;
    const char *endp = end + endlen;
    while (p < endp) {
        if (*p++ != *s++) {
            return 0;
        }
    }
    return 1;
}

/**
 * @brief 在目标字符串中查找第一个子串（区分大小写，支持自动计算长度）
 *
 * 在目标字符串 `str` 的前 `len` 个字符中，查找第一个与子串 `child` 完全匹配的片段，
 * 支持手动指定长度或通过 `cstr_invalid_size` 标记自动计算长度（依赖 `strlen`）。
 *
 * @param str 目标字符串（待查找子串的母串，非 NULL）
 * @param len 目标字符串的有效长度；若为无效长度（符合 `cstr_invalid_size` 规则），自动调用 `strlen(str)` 计算
 * @param child 待查找的子串（非 NULL）
 * @param childlen 子串的长度；若为无效长度（符合 `cstr_invalid_size` 规则），自动调用 `strlen(child)` 计算
 *
 * @return const char*
 *   - 成功：返回子串在目标字符串中第一次出现的起始指针（指向 `str` 中匹配片段的首字符）
 *   - 失败：返回 NULL（子串未找到、子串长于母串或参数无效）
 *
 * @note 若 `str` 与 `child` 指向同一内存地址，直接返回 `str`（视为匹配）
 * @note 比较过程区分大小写（如 'A' 与 'a' 视为不同字符）
 * @note 忽略参数有效性检查，调用者需确保非 NULL 指针指向合法 C 字符串
 */
const char* cstr_findchild(const char * str, size_t len, const char * child, size_t childlen)
{
    if (!str || !child) {
        return NULL;
    }
    if (cstr_invalid_size(len)) {
        len = strlen(str);
    }
    if (cstr_invalid_size(childlen)) {
        childlen = strlen(child);
    }
    // len >= childlen
    if (!childlen) {
        // 空串是任何字符串的子串
        return str;
    }
    if (len < childlen) {
        return NULL;
    }
    if (str == child) {
        return str;
    }

    assert(len >= childlen && childlen > 0);

    const char * start = str;
    const char * end = str + len - childlen; // 有效搜索终点

    for (; start <= end; ++start) {
        if (*start == *child && (childlen == 1 || ! memcmp(start + 1, child + 1, childlen - 1))) {
            return start;
        }
    }

    // not found
    return NULL;
}

/**
 * @brief 在目标字符串中查找数组内第一个存在的子串（支持大小写忽略）
 *
 * 遍历字符串数组 `array`，检查每个元素是否为目标字符串 `str` 的子串，返回第一个匹配元素的索引，
 * 支持通过 `caseignore` 控制是否忽略大小写，自动计算子串长度。
 *
 * @param str 目标字符串（待查找子串的母串，非 NULL）
 * @param len 目标字符串的有效长度；若为无效长度（符合 `cstr_invalid_size` 规则），自动调用 `strlen(str)` 计算
 * @param array 子串数组（每个元素为待查找的子串，非 NULL，数组以有效元素填充，长度由 `arraylen` 控制）
 * @param arraylen 子串数组的元素个数（需 >= 0）
 * @param caseignore 是否忽略大小写（非 0 表示忽略，0 表示区分）
 *
 * @return int
 *   - 成功：返回数组中第一个为 `str` 子串的元素索引（>= 0）
 *   - 失败：返回 -1（数组中无任何元素是 `str` 的子串）
 *
 * @note 忽略参数有效性检查，调用者需确保数组元素指向合法 C 字符串
 */
int cstr_findfirst_array(const char *str, size_t len, const char *array[], int arraylen, int caseignore)
{
    if (cstr_invalid_size(len)) {
        len = strlen(str);
    }
    for (int i = 0; i < arraylen; i++) {
        if (! cstr_compare(str, len, array[i], CSTR_ERR_SIZE, caseignore)) {
            return i;
        }
    }
    // not found
    return -1;
}

/**
 * @brief 检查字符串是否全部由数字字符组成
 *
 * @param str 待检查的字符串指针
 * @param len 字符串长度（使用-1表示以NULL结尾的字符串）
 *
 * @return int 返回1表示全部为数字字符，0表示包含非数字字符或空字符串
 */
int cstr_isdigit(const char *str, size_t len)
{
    if (!str) {
        return 0;
    }
    if (cstr_invalid_size(len)) {
        len = strlen(str);
    }
    if (len == 0) {
        return 0;  // 空字符串处理
    }
    for (size_t i = 0; i < len; i++) {
        // 正确转换避免符号扩展问题
        if (!isdigit((unsigned char)str[i])) {
            return 0;
        }
    }
    return 1;
}

/**
 * @brief 从文件流中读取一行文本
 *
 * @param fp 输入文件流指针（必须已打开）
 * @param line 存储读取内容的缓冲区
 * @param maxlen 缓冲区最大容量（包括终止符）
 * @param ignore_whitespace 是否忽略空白字符标志（非0忽略，0保留）
 *
 * @return int 成功时返回读取字符数（不含终止符），
 *             文件结尾且未读到数据时返回-1，
 *             错误时返回负值（需用feof/ferror判断）
 *
 * @note 特性：
 * - 自动处理UTF-8 BOM头（仅在文件开头）
 * - 跳过回车符(\r)，以换行符(\n)作为行结束标志
 * - 支持可选空白字符过滤
 * - 确保缓冲区以null结尾
 * - 不处理行续接（反斜杠处理需确认设计意图）
 */
int cstr_readline(FILE *fp, char line[], size_t maxlen, int ignore_whitespace)
{
    int ch, len = 0;
    int bytes_read = 0;

    if (ftell(fp) == 0) {
        int bom[3] = {0};
        for (int i = 0; i < 3; i++) {
            bom[i] = fgetc(fp);
            if (bom[i] == EOF) {
                break;
            }
            bytes_read++;
        }

        if (bom[0] == 0xEF && bom[1] == 0xBB && bom[2] == 0xBF) {
            // 已跳过BOM，不需要：fseek(fp, 3, SEEK_SET);
        } else {
            // 回退非BOM字节：fseek(fp, 0, SEEK_SET);
            for (int i = bytes_read - 1; i >= 0; i--) {
                ungetc(bom[i], fp);
            }
        }
    }

    while ((ch = fgetc(fp)) != EOF) {
        if ((size_t) len < maxlen - 1) {
            if (ch != '\r' && ch != '\n' && ch != '\\') {
                if (! ignore_whitespace || ! isspace((unsigned char)ch)) {
                    line[len++] = ch;
                }
            }
        }

        if (ch == '\n') {
            break;
        }
    }

    if (ch == EOF && len == 0) {
        // end of file
        return -1;
    }

    line[len] = '\0';
    return len;
}

/**
 * @brief 将日期时间结构格式化为字符串
 *
 * @param dt 日期时间结构体指针
 * @param outfmt 输出缓冲区（长度至少为CSTR_DTFMT_SIZE_MAX）
 * @return const char* 格式化后的字符串指针（同outfmt）
 *
 * @note 格式化规则：
 * - 仅输出有效字段（值为-1表示无效）
 * - 日期格式：YYYY-MM-DD
 * - 时间格式：HH:MM:SS
 * - 毫秒格式：.SSS
 * - 时区格式：+HH:MM 或 WHH:MM（负时区）
 * - 字段间自动添加空格分隔
 * - 输出示例：
 *   "2023-01-15 14:30:45.500+08:00"
 *   "14:30:45-05:00"（仅时间+时区）
 *   "2023-01-15"（仅日期）
 */
const char * cstr_datetime_print(const cstr_datetime_t *dt, char outfmt[CSTR_DATE_BSIZE])
{
    size_t offset = 0;
    *outfmt = '\0'; // 确保空终止

    // 日期部分 (YYYY-MM-DD)
    if (dt->year != -1 && dt->month != -1 && dt->day != -1) {
        offset += vsnprintf_chkd(outfmt + offset,
                                  CSTR_DATE_BSIZE - offset,
                                  "%04d-%02d-%02d",
                                  dt->year, dt->month, dt->day);
    }

    // 时间部分 (HH:MM:SS)
    int has_time = 0;
    if (dt->hour != -1 && dt->minute != -1 && dt->second != -1) {
        if (offset > 0) {
            // 日期与时间间加空格
            outfmt[offset++] = ' ';
        }
        offset += vsnprintf_chkd(outfmt + offset,
                                   CSTR_DATE_BSIZE - offset,
                                   "%02d:%02d:%02d",
                                   dt->hour, dt->minute, dt->second);
        has_time = 1;
    }

    // 毫秒部分 (.SSS)
    if (has_time && dt->millisecond != -1) {
        offset += vsnprintf_chkd(outfmt + offset,
                                   CSTR_DATE_BSIZE - offset,
                                   ".%03d",
                                   dt->millisecond);
    }

    // 时区部分 (±HH:MM)
    if (dt->timezone != -1) {
        // 添加分隔符（如果前面有内容）
        if (offset > 0) {
            outfmt[offset++] = (dt->timezone >= 0) ? '+' : '-';
        }

        int tz_abs = abs(dt->timezone);
        offset += vsnprintf_chkd(outfmt + offset,
                                   CSTR_DATE_BSIZE - offset,
                                   "%02d:%02d",
                                   tz_abs / 100,
                                   tz_abs % 100);
    }

    return outfmt;
}

/**
 * @brief 验证日期时间各字段的有效性
 *
 * @param year  年份 (1900-9999)
 * @param mon   月份 (1-12)
 * @param day   日期 (1-31，实际根据月份验证)
 * @param hour  小时 (0-24)
 * @param min   分钟 (0-59)
 * @param sec   秒数 (0-60，60用于闰秒)
 *
 * @return int 1表示有效，0表示无效
 *
 * @note 特殊规则：
 * - 闰秒允许秒数为60（根据国际地球自转服务引入）
 * - 小时允许24:00表示一天结束（ISO 8601标准）
 * - 二月天数自动处理闰年规则
 * - 各字段有独立的有效性范围检查
 */
int time_is_valid(int year, int mon, int day, int hour, int min, int sec)
{
    /* 基础范围检查 */
    if (year < 1900 || year > 9999) return 0;
    if (mon < 1 || mon > 12) return 0;
    if (day < 1 || day > 31) return 0;
    if (hour < 0 || hour > 24) return 0;  // 允许24但禁止大于24

    /* 处理24:00:00特殊情况 */
    if (hour == 24) {
        // 24小时表示法要求分秒为0
        if (min != 0 || sec != 0) {
            return 0;
        }
        // 24:00:00是有效时间，直接验证日期部分
    } else {
        // 常规时间检查
        if (min < 0 || min >= 60) return 0;
        if (sec < 0 || sec >= 61) return 0;  // 包含闰秒60
    }

    /* 闰秒验证 (sec=60) */
    if (sec == 60) {
        // 闰秒必须发生在有效分钟内
        if (min < 0 || min >= 60) return 0;
    }

    /* 月份天数验证 - 现在只依赖日期部分 */
    if (mon == 1 || mon == 3 || mon == 5 || mon == 7 || mon == 8 || mon == 10 || mon == 12) {
        return 1;  // 31天月份有效
    } else if (mon == 4 || mon == 6 || mon == 9 || mon == 11) {
        return (day <= 30) ? 1 : 0;  // 30天月份
    } else {
        // 二月特殊处理
        if (day > 29) return 0;
        if (day < 29) return 1;

        /* 闰年判断 */
        return TM_YEAR_IS_LEAP(year);
    }
}

/**
 * @brief 解析时区字符串为整数表示
 *
 * @param tz 时区字符串指针（格式："+08:00"、"-05:30"、"E0800"、"W0830"等）
 *
 * @return int
 *   - 成功：返回时区偏移值（单位：百分之一小时）
 *       示例：+08:00 -> 800, -05:30 -> -530
 *   - 失败：返回-1
 *
 * @note 支持的格式：
 *   - 带分隔符："[+-][HH]:[MM]" 或 "[EW][HH]:[MM]"（分隔符可以是':'或'.'）
 *   - 无分隔符："[EW][HH][MM]"
 *   - 小时范围：00-23
 *   - 分钟范围：00-59
 */
int cstr_parse_timezone(char *tz)
{
    if (!tz || !*tz) return -1;

    int sign = 0;
    /* 解析符号部分 */
    if (*tz == '+' || *tz == 'E') {
        sign = 1;
    } else if (*tz == '-' || *tz == 'W') {
        sign = -1;
    } else {
        return -1;
    }

    int h = 0, m = 0;
    char *p = tz + 1;

    /* 格式1: 带分隔符（[+-EW]HH:MM） */
    if (isdigit((unsigned char)p[0]) &&
        isdigit((unsigned char)p[1]) &&
        (p[2] == ':' || p[2] == '.') &&
        isdigit((unsigned char)p[3]) &&
        isdigit((unsigned char)p[4]) &&
        p[5] == '\0')
    {
        h = (p[0] - '0') * 10 + (p[1] - '0');
        m = (p[3] - '0') * 10 + (p[4] - '0');
    }
    /* 格式2: 无分隔符（[EW]HHMM） */
    else if (isdigit((unsigned char)p[0]) &&
             isdigit((unsigned char)p[1]) &&
             isdigit((unsigned char)p[2]) &&
             isdigit((unsigned char)p[3]) &&
             p[4] == '\0')
    {
        h = (p[0] - '0') * 10 + (p[1] - '0');
        m = (p[2] - '0') * 10 + (p[3] - '0');
    }
    else {
        return -1; // 无效格式
    }

    /* 验证时间范围 */
    if (h < 0 || h > 23 || m < 0 || m > 59) {
        return -1;
    }

    return (h * 100 + m) * sign;
}

/**
 * @brief 解析时间戳字符串为时间结构和毫秒时间戳
 *
 * @param timestr 时间戳字符串（支持多种格式）
 * @param outdt 输出时间结构（可为NULL）
 * @return ub8 成功时返回UTC毫秒时间戳，失败返回(ub8)-1
 *
 * @note 支持格式：
 *   - 完整格式：'2019-12-22 12:36:59.065+08:00'
 *   - 无毫秒：'2019-12-22 12:36:59-08:00'
 *   - 无时间：'2019-12-22+08:00'
 *   - 带引号：'2019-12-22 12:36:59'
 *
 * @note 时区表示：
 *   - UTC+08:00 可表示为 +08:00, E0800
 *   - UTC-11:00 可表示为 -11:00, W1100
 */
ub8 cstr_parse_timestamp(char *timestr, cstr_datetime_t *outdt)
{
    int len = 0;
    int YMD = 0, HMS = 0, MMM = 0;

    /**
     * UTC+08:00 = +0800 or E0800
     * UTC-11:00 =        W0800
     *
     * '2019-12-22 12:36:59.065+08:00' or '2019-12-22 12:36:59.065E08:00'
     * '2019-12-22 12:36:59.065'
     * '2019-12-22 12:36:59W08:00' or '2019-12-22 12:36:59-08:00'
     * '2019-12-22 12:36:59'
     * '2019-12-22E08:00' or '2019-12-22+08:00'
     * '2019-12-22'
     */
    char Year[5] = {'0', '0', '0', '0', '\0'};
    char Mon[3] = {'0', '0', '\0'};
    char Day[3] = {'0', '0', '\0'};

    char hour[3] = {'0', '0', '\0'};
    char min[3] = {'0', '0', '\0'};
    char sec[3] = {'0', '0', '\0'};

    char msec[4] = {'0', '0', '0', '\0'};

    int timezone = -1;

    char *str, *a, *b, *hms, *tz;

    tz = strchr(timestr, '+');
    if (!tz) {
        tz = strchr(timestr, 'E');
        if (!tz) {
            tz = strchr(timestr, 'W');
            if (!tz) {
                // -08:00 or -08.00
                tz = strrchr(timestr, '-');
                if (tz) {
                    if (tz[1] && tz[2] && (tz[3] == ':' || tz[3] == '.')) {
                        // has timezone
                        // tz;
                    } else {
                        // no timezone
                        tz = 0;
                    }
                }
            }
        }
    }

    if (tz) {
        timezone = cstr_parse_timezone(tz);
        if (timezone == -1) {
            // error timezone
            return (-1);
        }
        *tz = 0;
    }

    str = cstr_LRtrim_whitespace(timestr);
    a = strchr(str, 39);
    b = strrchr(str, 39);

    if (a && b) {
        *a++ = 0;
        *b-- = 0;
        str = a;
        len = (int)(b - a) + 1;
    } else if (a || b) {
        // error char
        return (-1);
    } else {
        len = cstr_length(str, 30);
    }

    if (len == 10) {
        /* 2019-12-22 */
        YMD = 1;

        a = strchr(str, '-');
        b = strrchr(str, '-');

        if (a && b && a - str == 4 && b-a == 3) {
            *a++ = 0;
            *b++ = 0;

            vsnprintf_chkd(Year, sizeof(Year), "%.*s", 4, str);
            vsnprintf_chkd(Mon, sizeof(Mon), "%.*s", 2, a);
            vsnprintf_chkd(Day, sizeof(Day), "%.*s", 2, b);
        } else {
            // error date format
            return (-1);
        }
    } else if (len == 19) {
        /* 2019-12-22 12:36:59 */
        YMD = 1;
        HMS = 1;

        a = strchr(str, 32);
        if (a && a - str == 10) {
            *a++ = 0;

            hms = a;

            a = strchr(str, '-');
            b = strrchr(str, '-');

            if (a && b && a - str == 4 && b-a == 3) {
                *a++ = 0;
                *b++ = 0;

                vsnprintf_chkd(Year, sizeof(Year), "%.*s", 4, str);
                vsnprintf_chkd(Mon, sizeof(Mon), "%.*s", 2, a);
                vsnprintf_chkd(Day, sizeof(Day), "%.*s", 2, b);
            } else {
                // error date format
                return (-1);
            }

            a = strchr(hms, ':');
            b = strrchr(hms, ':');

            if (a && b && a - hms == 2 && b-a == 3) {
                *a++ = 0;
                *b++ = 0;

                vsnprintf_chkd(hour, sizeof(hour), "%.*s", 2, hms);
                vsnprintf_chkd(min, sizeof(min), "%.*s", 2, a);
                vsnprintf_chkd(sec, sizeof(sec), "%.*s", 2, b);
            } else {
                // error date format
                return (-1);
            }
        } else {
            // error datetime format
            return (-1);
        }
    } else if (len == 23) {
        /* 2019-12-22 12:36:59.065 */
        YMD = 1;
        HMS = 1;
        MMM = 1;

        a = strchr(str, 32);
        if (a && a - str == 10) {
            *a++ = 0;

            hms = a;

            a = strchr(str, '-');
            b = strrchr(str, '-');

            if (a && b && a - str == 4 && b-a == 3) {
                *a++ = 0;
                *b++ = 0;

                vsnprintf_chkd(Year, sizeof(Year), "%.*s", 4, str);
                vsnprintf_chkd(Mon, sizeof(Mon), "%.*s", 2, a);
                vsnprintf_chkd(Day, sizeof(Day), "%.*s", 2, b);
            } else {
                // error date format
                return (-1);
            }

            a = strchr(hms, ':');
            b = strrchr(hms, ':');

            if (a && b && a - hms == 2 && b-a == 3) {
                char *dot = strchr(b, '.');
                if (!dot || dot - b != 3) {
                    // error stamp format
                    return (-1);
                }

                *a++ = 0;
                *b++ = 0;
                *dot++ = 0;

                vsnprintf_chkd(hour, sizeof(hour), "%.*s", 2, hms);
                vsnprintf_chkd(min, sizeof(min), "%.*s", 2, a);
                vsnprintf_chkd(sec, sizeof(sec), "%.*s", 2, b);

                if (*dot) {
                    msec[0] = *dot++;

                    if (*dot) {
                        msec[1] = *dot++;

                        if (*dot) {
                            msec[2] = *dot++;
                        }
                    }
                }
            } else {
                // error date format
                return (-1);
            }
        } else {
            // error datetime format
            return (-1);
        }
    } else {
        // error format
        return (-1);
    }

    if (! YMD) {
        // no year
        return (-1);
    }

    if (cstr_isdigit(Year, 4) &&
        cstr_isdigit(Mon, 2) &&
        cstr_isdigit(Day, 2) &&
        cstr_isdigit(hour, 2) &&
        cstr_isdigit(min, 2) &&
        cstr_isdigit(sec, 2) &&
        cstr_isdigit(msec, 3)) {
        ub8 tsec;
        struct tm t = {0};

        t.tm_year = atoi(Year);
        t.tm_mon = atoi(Mon);
        t.tm_mday = atoi(Day);

        t.tm_hour = atoi(hour);
        t.tm_min = atoi(min);
        t.tm_sec = atoi(sec);

        if (! time_is_valid(t.tm_year, t.tm_mon, t.tm_mday, t.tm_hour, t.tm_min, t.tm_sec)) {
            // invalid time
            return (-1);
        }

        t.tm_year -= 1900;
        t.tm_mon  -= 1;

        // since 1970-01-01 UTChh:00:00 (china: hh=8)
        tsec = (ub8) mktime(&t);
        if (tsec == (ub8)(-1)) {
            return (-1);
        }

        if (outdt) {
            outdt->year = atoi(Year);
            outdt->month = atoi(Mon);
            outdt->day = atoi(Day);

            outdt->hour = atoi(hour);
            outdt->minute = atoi(min);
            outdt->second = atoi(sec);
            outdt->millisecond = atoi(msec);

            outdt->timezone = timezone;
        }

        if (! HMS) {
            outdt->hour = -1;
            outdt->minute = 0;
            outdt->second = 0;
        }
        if (! MMM) {
            outdt->millisecond = -1;
        }

        tsec *= 1000;
        return (ub8)(tsec + atoi(msec));
    }

    // error no digit
    return (-1);
}

/**
 * @brief 将毫秒级时间戳字符串转换为格式化的日期时间字符串
 *
 * 接收以字符串形式存储的毫秒级时间戳（如 "1623456789123"），解析为数值后转换为本地时区的日期时间，
 * 格式化为 "YYYY-MM-DD HH:MM:SS" 或 "YYYY-MM-DD HH:MM:SS.fff"（含毫秒，毫秒非零时），结果存入输出缓冲区。
 *
 * @param stampms 输入的毫秒级时间戳字符串（需为十进制数字，非 NULL）
 * @param mslen 时间戳字符串的长度；若为 -1，自动调用 `cstr_length` 计算（最大限制 20 字节，避免超长）
 * @param timestr 输出的日期时间字符串缓冲区（需预先分配至少 24 字节空间，用于存储最长格式 "YYYY-MM-DD HH:MM:SS.fff"）
 *
 * @return const char*
 *   - 成功：返回 `timestr`（指向格式化后的日期时间字符串）
 *   - 失败：返回 NULL（时间戳解析失败、本地时间转换失败或日期时间无效）
 *
 * @note 时间戳解析规则：
 *       1. 输入 `stampms` 需为纯十进制数字字符串（如 "1623456789123" 表示 1623456789 秒 + 123 毫秒）
 *       2. 解析后存储为 64 位无符号整数（`ub8`），支持最大时间戳约为 1.8e19 毫秒（覆盖未来极长时间）
 * @note 跨平台时间转换：
 *       - Windows 平台使用 `localtime_s`（线程安全）
 *       - 其他平台使用 `localtime_r`（线程安全，避免 `localtime` 的线程不安全问题）
 * @note 依赖函数：
 *       1. `cstr_length`：计算时间戳字符串长度
 *       2. `cstr_to_ub8`：将字符串转换为 64 位无符号整数（`ub8`）
 *       3. `time_is_valid`：校验转换后的日期时间是否合法（如月份 1-12、日期 1-31 等）
 *       4. `vsnprintf_chkd`：安全格式化字符串（需确保其功能与 `snprintf` 兼容，且有缓冲区越界检查）
 * @note 忽略参数有效性检查（如 `stampms`/`timestr` 空指针、`timestr` 空间不足），依赖调用者保证参数合法
 */
const char * cstr_timestamp_to_datetime(char *stampms, size_t mslen, char timestr[24])
{
    ub8 stamp = 0;
    time_t tsec;
    int msec;
    struct tm t;

    if (cstr_invalid_size(mslen)) {
        mslen = cstr_length(stampms, 20);
    }

    if (cstr_to_ub8(10, stampms, mslen, &stamp, timestr, 24) > 0) {
        // error stamp
        return NULL;
    }

    tsec = (time_t)(stamp / 1000);
    msec = (int)(stamp % 1000);

#if defined(PLATFORM_WINDOWS)
    if (!localtime_s(&t, (const time_t*) &tsec)) {
        // error localtime
        return NULL;
    }
#else
    if (!localtime_r((const time_t*)&tsec, &t)) {
        // error localtime
        return NULL;
    }
#endif

    t.tm_year += 1900;
    t.tm_mon  += 1;

    if (! time_is_valid(t.tm_year, t.tm_mon, t.tm_mday, t.tm_hour, t.tm_min, t.tm_sec)) {
        // invalid time
        return NULL;
    }

    if (msec) {
        /* 2012-12-22 17:45:59.875 */
        vsnprintf_chkd(timestr, 24, "%04d-%02d-%02d %02d:%02d:%02d.%03d", t.tm_year, t.tm_mon, t.tm_mday, t.tm_hour, t.tm_min, t.tm_sec, msec);
    } else {
        vsnprintf_chkd(timestr, 20, "%04d-%02d-%02d %02d:%02d:%02d", t.tm_year, t.tm_mon, t.tm_mday, t.tm_hour, t.tm_min, t.tm_sec);
    }

    return timestr;
}

/**
 * @brief BKDR字符串哈希函数
 * @param str 输入字符串（如果为NULL则返回0）
 * @param seed 哈希种子（推荐使用质数：31, 131, 1313, 13131, 131313等）
 * @param table_size 哈希表大小（必须为0或2的幂次方：256, 1024, 2048等）
 * @return 哈希值：
 *         - 如果table_size=0，返回完整的32位哈希值（0x7FFFFFFF范围内）
 *         - 如果table_size>0，返回在[0, table_size-1]范围内的哈希索引
 *
 * @note 哈希算法：BKDRHash (Brian Kernighan和Dennis Ritchie)
 * @note 当table_size>0时，必须保证table_size是2的幂次方，否则结果不正确
 * @note 种子选择质数可以减少哈希冲突
 *
 * @example
 * // 基本哈希值
 * unsigned int hash = cstr_bkdr_hash("hello", 131, 0);
 *
 * // 哈希表索引（table_size必须是2的幂）
 * unsigned int index = cstr_bkdr_hash("key", 131, 1024); // 返回0-1023
 *
 * @see 参考经典的BKDR哈希算法实现
 */
unsigned int cstr_bkdr_hash(const char *str, unsigned int seed, unsigned int table_size)
{
    /*
     * seed = 131, 1313, 13131 131313 etc..
     * table_size = 0, 256, 1024, 2048, ...
    */
    if (str == NULL) {
        return 0;
    }
    unsigned int hash = 0;
    unsigned char *ustr = (unsigned char *)str;
    while (*ustr) {
        hash = hash * seed + (*ustr++);
    }

    hash = (hash & 0x7FFFFFFF);
    return table_size ? (hash & (table_size - 1)) : hash;
}

/**********************************************************************
 * cstrbuf Api
 *********************************************************************/

/**
 * @brief 安全获取字符串缓冲区中指定索引的字符指针（边界检查）
 *
 * 检查索引是否在有效范围内，若有效则返回对应位置的字符指针，否则返回 NULL。
 *
 * @param csb 字符串缓冲区（cstrbuf 类型，非 NULL 且有效）
 * @param at 目标字符的索引（0 基，需 >= 0 且 < 缓冲区长度）
 *
 * @return char*
 *   - 成功：返回索引 at 处的字符指针（指向 csb->str[at]）
 *   - 失败：返回 NULL（索引越界或缓冲区无效）
 *
 * @note 依赖 `cstrbufGetLen` 函数获取缓冲区当前长度
 * @note 忽略参数有效性检查，调用者需确保 csb 为合法缓冲区
 */
char * cstrbufCharAtSafe(cstrbuf csb, int at)
{
    int len = cstrbufGetLen(csb);
    if (at >= 0 && at < len) {
        return cstrbufCharAt(csb, at);
    }
    // invalid cstrbuf or index
    return NULL;
}

/**
 * @brief 创建新的字符串缓冲区并初始化
 *
 * 根据指定的最大容量、初始字符串及长度，创建并初始化一个 cstrbuf 缓冲区，
 * 自动处理容量对齐和内存分配，确保字符串以 '\0' 结尾。
 *
 * @param maxsz 期望的最大容量（字节）；0 表示自动计算，特殊值 `cstrbuf_error_size` 表示按内容扩容
 * @param str 初始字符串（可为 NULL，此时创建空缓冲区）
 * @param len 初始字符串的长度；特殊值 `cstrbuf_error_size` 表示自动调用 `cstr_length` 计算长度
 *
 * @return cstrbuf
 *   - 成功：返回新创建的字符串缓冲区（已初始化，str 内容已复制）
 *   - 失败：内存分配失败时返回 NULL（未显式处理，依赖 `mem_alloc` 的行为）
 *
 * @note 容量处理逻辑：
 *       - 若 maxsz 为 0：容量设为 len + 1
 *       - 若 maxsz 无效或 <= len：容量设为 `cstrbuf_alignsize(len + 1)`（对齐后的值）
 *       - 否则：容量设为 `cstrbuf_alignsize(maxsz)`（对齐后的值）
 * @note 初始字符串为 NULL 时，缓冲区初始化为空（len=0，str[0]='\0'）
 */
cstrbuf cstrbufNew(ub4 maxsz, const char *str, ub4 len)
{
    cstrbuf_t *csb;

    if (len == cstrbuf_error_size) {
        len = (ub4) cstr_length(str, cstr_length_max);
    }

    if (! maxsz) {
        maxsz = len + 1;
    } else if (maxsz == cstrbuf_error_size) {
        maxsz = cstrbuf_alignsize(len + 1);
    } else if (maxsz <= len) {
        maxsz = cstrbuf_alignsize(len + 1);
    } else {
        // maxsz > len
        maxsz = cstrbuf_alignsize(maxsz);
    }

    csb = (cstrbuf_t *) mem_alloc(sizeof(*csb) + maxsz);

    csb->__maxszlen = 0;
    *csb->str = 0;

    if (str) {
        memcpy(csb->str, str, len);
        memset(csb->str + len, 0, maxsz - len);
        csb->len = len;
    } else {
        memset(csb->str, 0, maxsz);
        csb->len = 0;
    }

    csb->maxsz = maxsz;
    return csb;
}

/**
 * @brief 创建指定最大长度的字符串缓冲区并初始化
 *
 * 简化版创建函数，直接按指定最大长度分配内存，复制初始字符串的前 maxlen 个字符并确保终止符。
 *
 * @param str 初始字符串（可为 NULL，此时创建空缓冲区）
 * @param maxlen 字符串的最大有效长度（不含终止符 '\0'），实际分配容量为 maxlen + 1（含终止符）
 *               如果为 -1，则自动计算字符串长度
 * @return cstrbuf
 *   - 成功：返回新创建的缓冲区（str 内容已复制，长度为实际有效字符数）
 *   - 失败：内存分配失败时返回 NULL（依赖 `mem_alloc` 的行为）
 *
 * @note 初始字符串长度超过 maxlen 时，仅复制前 maxlen 个字符（通过 `cstr_length` 控制）
 * @note 始终确保缓冲区末尾有 '\0' 终止符（str[len] = '\0'）
 */
cstrbuf cstrbufNew2(const char* str, ub4 maxlen)
{
    ub4 slen = 0;
    if (maxlen == (ub4)(-1)) {
        maxlen = (ub4) strlen(str);
        slen = maxlen;
    }

    cstrbuf_t* csb = (cstrbuf_t*)mem_alloc(sizeof(*csb) + maxlen + 1);
    csb->len = slen? slen : (ub4) cstr_length(str, maxlen);
    if (csb->len) {
        memcpy(csb->str, str, csb->len);
    }
    csb->maxsz = maxlen + 1;
    csb->str[csb->len] = '\0';
    return csb;
}

/**
 * @brief 释放字符串缓冲区并置空指针
 *
 * 安全释放 cstrbuf 缓冲区的内存，并将输入指针置空（避免悬垂指针）。
 *
 * @param csb 指向字符串缓冲区指针的指针（若为 NULL 则不操作）
 *
 * @note 若 csb 非 NULL 但指向的缓冲区为 NULL（*csb = NULL），则不执行释放操作
 * @note 依赖 `mem_free` 函数释放内存，需确保缓冲区由 `mem_alloc` 或 `mem_realloc` 分配
 */
void cstrbufFree(cstrbuf *csb)
{
    if (csb) {
        cstrbuf s = *csb;
        if (s) {
            *csb = 0;
            mem_free(s);
        }
    }
}

/**
 * @brief 将字符串缓冲区内容复制到目标缓冲区
 *
 * 从源缓冲区复制字符串内容到目标缓冲区的指定偏移位置，返回更新后的偏移。
 *
 * @param src 源字符串缓冲区（可为 NULL，此时不复制）
 * @param dstbuf 目标缓冲区（需预先分配足够内存）
 * @param offcb 目标缓冲区的起始偏移位置（复制从该位置开始）
 *
 * @return ub4
 *   - 成功：返回复制后目标缓冲区的新偏移（offcb + src->len）
 *   - 无操作：src 为 NULL 或 src->len 为 0 时，返回原始 offcb
 *
 * @note 注释要求“dstbuf 必须有足够空间”，函数不做空间检查，依赖调用者保证
 * @note 仅复制有效字符（src->str 的前 src->len 字节），不包含终止符 '\0'
 */
ub4 cstrbufCopyTo(const cstrbuf src, void *dstbuf, ub4 offcb)
{
    if (src && src->len) {
        memcpy((char*)dstbuf + offcb, src->str, src->len);
        return (ub4)(offcb + src->len);
    }
    return (ub4)offcb;
}

/**
 * @brief 将格式化的字符串复制到目标
 *
 * 将格式化的字符串复制到目标，返回更新后的目标。
 *
 * @param dst 目标（可为 NULL）
 * @param fmt 格式化字符串（同 printf 格式）
 *
 * @return 新目标
 *   - 成功：非 NULL，返回复制后目标（如果旧目标没有重用，则释放，否则返回原目标）
 *   - 失败：NULL，内存不足或无法格式化 (原目标不会更改)
 *
 * @note dst 如果有足够空间，则复用 dst，否则释放后重建
 */
cstrbuf cstrbufCopyFrom(cstrbuf dst, const char *fmt, ...)
{
    int len;
    cstrbuf dst_saved = dst;

    va_list args;

    // 首先计算格式化字符串的长度
    va_start(args, fmt);
    len = vsnprintf(NULL, 0, fmt, args);
    va_end(args);

    if (len < 0) {
        // 失败返回 NULL
        // 注意：这里不释放原始dst
        return NULL;
    }

    if (! dst) {
        // 创建新缓冲区
        dst = cstrbufNew2(NULL, len);
        if (! dst) {
            return NULL;  // should never run to this!
        }
    } else if (dst->maxsz < (ub4)(len + 1)) {
        // 现有缓冲区空间不足，需要重新分配
        cstrbuf new_dst = (cstrbuf) cstrbufNew2(NULL, len);
        if (!new_dst) {
            return NULL;  // should never run to this!
        }
        dst = new_dst;
    }

    // 现在将格式化字符串复制到缓冲区
    va_start(args, fmt);
    len = vsnprintf(dst->str, dst->maxsz, fmt, args);
    va_end(args);

    if (len < 0) {
        // 如果这是新分配的缓冲区，需要释放它
        if (dst != dst_saved) {
            cstrbufFree(&dst);
        }
        return NULL;
    }

    dst->len = len;
    dst->str[dst->len] = 0;

    if (dst != dst_saved) {
        // 如果这是新分配的缓冲区，需要释放原缓冲区
        cstrbufFree(&dst_saved);
    }

    // 成功返回
    return dst;
}

/**
 * @brief 向字符串缓冲区追加格式化字符串（支持自动扩容）
 *
 * 若缓冲区为 NULL 则创建新缓冲区；否则追加格式化字符串，空间不足时自动扩容，确保字符串有效终止。
 *
 * @param dst 目标字符串缓冲区（可为 NULL，此时创建新缓冲区）
 * @param fmt 格式化字符串（同 printf 格式）
 * @param ... 可变参数列表（与 fmt 匹配的参数）
 *
 * @return cstrbuf
 *   - 成功：返回更新后的缓冲区（新创建或扩容后的原缓冲区）
 *   - 失败：格式化失败或内存分配失败时返回 NULL（并释放已分配内存）
 *
 * @note 扩容逻辑：当现有空间不足时，通过 `cstrbuf_alignsize` 计算新容量，调用 `mem_realloc` 扩容
 * @note 依赖 `vsnprintf` 获取字符串长度和格式化内容，错误时打印日志
 * @note 始终确保缓冲区末尾有 '\0' 终止符
 */
cstrbuf cstrbufCat(cstrbuf dst, const char *fmt, ...)
{
    int vlen, len;

    if (! dst) {
        do {
            va_list args;
            va_start(args, fmt);
            vlen = vsnprintf(0, 0, fmt, args);
            va_end(args);
        } while(0);

        if (vlen < 0) {
            return 0;
        }

        dst = cstrbufNew(vlen + 1, 0, 0);

        do {
            va_list args;
            va_start(args, fmt);
            len = vsnprintf(dst->str, dst->maxsz, fmt, args);
            va_end(args);
        } while(0);

        if (len == vlen) {
            dst->len = len;
            dst->str[dst->len] = 0;
            return dst;
        }
        cstrbufFree(&dst);
        return 0;
    } else {
        do {
            va_list args;
            va_start(args, fmt);
            vlen = vsnprintf(&dst->str[dst->len], dst->maxsz - dst->len, fmt, args);
            va_end(args);
        } while(0);

        if (vlen < 0) {
            dst->str[dst->len] = 0;
            return dst;
        }

        if (dst->len + vlen < dst->maxsz) {
            dst->len += vlen;
            dst->str[dst->len] = 0;
            return dst;
        } else {
            ub4 maxsz = cstrbuf_alignsize(dst->len + vlen + 1);
            cstrbuf_t *newdst = (cstrbuf_t *) mem_realloc(dst, sizeof(*newdst) + maxsz);
            if (! newdst) {
                _exit(EXIT_FAILURE);
            }
            newdst->maxsz = maxsz;

            do {
                va_list args;
                va_start(args, fmt);
                len = vsnprintf(&newdst->str[newdst->len], newdst->maxsz - newdst->len, fmt, args);
                va_end(args);
            } while(0);

            if (len == vlen) {
                newdst->len += len;
            }

            newdst->str[newdst->len] = 0;
            return newdst;
        }
    }
}

/**
 * @brief 截断字符串缓冲区（支持正负索引）
 *
 * 根据偏移量截断缓冲区内容，调整长度并确保终止符有效。
 *
 * @param s 目标字符串缓冲区（非 NULL 且有效）
 * @param offset 截断偏移量：
 *               - 正值：截断到 offset 位置（保留前 offset 个字符，若 offset >= 当前长度则不操作）
 *               - 负值：从末尾截断 |offset| 个字符（若结果 < 0 则截断为空）
 *
 * @return cstrbuf 返回截断后的缓冲区（与输入 s 相同，无内存分配）
 *
 * @note 截断后自动设置终止符（s->str[s->len] = '\0'）
 * @note 不修改缓冲区容量（maxsz 不变），仅调整长度（len）
 */
cstrbuf cstrbufTrunc(cstrbuf s, int offset)
{
    if (offset >= 0) {
        if ((int) s->len > offset) {
            s->len = offset;
        }
    } else {
        if ((int)s->len + offset >= 0) {
            s->len += offset;
        } else {
            s->len = 0;
        }
    }
    s->str[s->len] = '\0';
    return s;
}

/**
 * @brief 拼接多个字符串缓冲区（以 NULL 结尾）
 *
 * 从可变参数列表中拼接多个 cstrbuf 缓冲区内容，返回新的缓冲区（包含所有内容的拼接结果）。
 *
 * @param start 第一个待拼接的字符串缓冲区（可为 NULL，此时返回空缓冲区）
 * @param ... 后续待拼接的字符串缓冲区，必须以 NULL 结束
 *
 * @return cstrbuf
 *   - 成功：返回新创建的缓冲区（包含所有输入缓冲区的拼接内容）
 *   - 失败：内存分配失败时返回 NULL（依赖 `cstrbufCat` 的错误处理）
 *
 * @note 内部通过 `cstrbufCat` 实现拼接，自动处理内存分配和扩容
 * @note 若所有输入缓冲区均为空，则返回空缓冲区（len=0）
 */
cstrbuf cstrbufConcat(const cstrbuf start, ...)
{
    va_list argp;
    cstrbuf src = start;
    va_start(argp, start);
    cstrbuf result = 0;

    do {
        result = cstrbufCat(result, "%.*s", cstrbufGetLen(src), cstrbufGetStr(src));
        src = va_arg(argp, cstrbuf);
    } while(src);

    va_end(argp);
    return result;
}

/**
 * @brief 复制源字符串到目标缓冲区（复用或创建新缓冲区）
 *
 * 若目标缓冲区为 NULL 则创建新缓冲区；否则复用目标缓冲区（空间足够时直接复制，不足时重新分配）。
 *
 * @param dst 目标缓冲区（可为 NULL，此时创建新缓冲区）
 * @param source 源字符串（非 NULL，需以 '\0' 结尾）
 * @param sourcelen 源字符串长度；特殊值 `cstrbuf_error_size_len` 表示自动计算长度
 *
 * @return cstrbuf
 *   - 成功：返回更新后的目标缓冲区（复用或新创建）
 *   - 失败：内存分配失败时返回 NULL（依赖 `cstrbufNew` 的行为）
 *
 * @note 源字符串长度为 0 时，目标缓冲区被清空（len=0，str[0]='\0'）
 * @note 若目标缓冲区空间不足，会释放原缓冲区并创建新缓冲区（原指针失效）
 */
cstrbuf cstrbufDup(cstrbuf dst, const char *source, ub4 sourcelen)
{
    if (! dst) {
        return cstrbufNew(0, source, sourcelen);
    }

    if (sourcelen == cstrbuf_error_size) {
        sourcelen = (ub4) cstr_length(source, -1);
    }

    if (! sourcelen) {
        dst->len = 0;
        dst->str[dst->len] = 0;
        return dst;
    }

    if (dst->maxsz > sourcelen) {
        memcpy(dst->str, source, sourcelen);

        dst->len = sourcelen;
        dst->str[dst->len] = 0;
        return dst;
    }

    mem_free(dst);
    return cstrbufNew(0, source, sourcelen);
}

/**
 * @brief 替换字符串中的指定片段（返回新缓冲区）
 *
 * 在源字符串中，将从 startindex 开始的 length 长度片段替换为 substr，返回包含结果的新缓冲区。
 *
 * @param source 源字符串（非 NULL，需以 '\0' 结尾）
 * @param startindex 替换起始索引（0 基，需在源字符串长度范围内）
 * @param length 待替换的长度（需 >= 0，且 startindex + length <= 源字符串长度）
 * @param substr 替换字符串（非 NULL）
 * @param sublen 替换字符串的长度（需 >= 0）
 *
 * @return cstrbuf 返回新创建的缓冲区（包含替换后的结果）
 *
 * @note 内部通过以下步骤实现：
 *       1. 创建存储源字符串后半部分（替换位置之后）的缓冲区 endstr
 *       2. 创建存储源字符串前半部分（替换位置之前）的缓冲区 result
 *       3. 复制 substr 到 result 的替换位置，再复制 endstr 到其后
 *       4. 释放 endstr 并返回 result
 * @note 新缓冲区长度为：源长度 - length + sublen
 */
cstrbuf cstrbufSub(const char *source, int startindex, int length, const char *substr, int sublen)
{
    int sourlen = cstr_length(source, -1);

    cstrbuf endstr = cstrbufNew(0, source + startindex + length, sourlen - startindex - length);
    cstrbuf result = cstrbufNew(sourlen - length + sublen + 1, source, startindex);

    memcpy(result->str + startindex, substr, sublen);
    memcpy(result->str + startindex + sublen, endstr->str, endstr->len);

    cstrbufFree(&endstr);

    result->len = sourlen - length + sublen;
    result->str[result->len] = 0;

    return result;
}

/**
 * @brief 向字符串缓冲区末尾追加单个字符（自动扩容）
 *
 * 在缓冲区末尾添加一个字符，空间不足时自动扩容（通过 `cstrbufCat` 实现）。
 *
 * @param dst 目标缓冲区（可为 NULL，此时创建新缓冲区）
 * @param ch 待追加的字符
 *
 * @return cstrbuf
 *   - 成功：返回更新后的缓冲区（原缓冲区或扩容后的新缓冲区）
 *   - 失败：内存分配失败时返回 NULL（依赖 `cstrbufCat` 的错误处理）
 *
 * @note 空间检查：若当前长度 + 1 < 最大容量，直接追加；否则调用 `cstrbufCat` 扩容
 * @note 缓冲区为 NULL 时，通过 `cstrbufCat` 创建仅包含 ch 的新缓冲区
 */
cstrbuf cstrbufPushBack(cstrbuf dst, char ch)
{
    if (dst) {
        if (dst->len + 1 < dst->maxsz) {
            dst->str[dst->len++] = ch;
        } else {
            dst = cstrbufCat(dst, "%c", ch);
        }
    } else {
        dst = cstrbufCat(NULL, "%c", ch);
    }
    return dst;
}
