/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file emerglog.h
 * @brief 紧急日志系统头文件。写入系统日志。
 *
 * 提供跨平台的紧急日志记录功能，支持系统错误信息格式化，设计用于关键错误处理和系统日志记录。
 * 支持 Windows、Linux 和其他 POSIX 兼容系统。
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 anomura.cc All Rights Reserved.
 * @version 0.0.46
 *
 * @since 2017-05-02 12:02:50
 * @date 2025-12-06 22:02:59
 *
 * @note 通用系统活动日志:
 *   - Debian/Ubuntu:
 *     /var/log/syslog
 *   - RHEL/CentOS:
 *     /var/log/messages
 *   - Windows
 *     按Win+R，输入`eventvwr.msc`并回车。
 *     Windows日志 -> 应用程序：应用程序相关的事件
 */
#ifndef EMERGLOG_H__
#define EMERGLOG_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "platforms.h"

#if defined(PLATFORM_WINDOWS) || defined(PLATFORM_CYGWIN)
    #if defined(PLATFORM_CYGWIN)
        #include <syslog.h>
    #else
        #include "win32/syslog.h"
    #endif

    // 格式化 Windows 系统错误信息
    const char* FormatWindowsError(DWORD dwError, char errbuf[], size_t bufsize);

    #define format_syserror(_errCode, _errMsgBuf, _bufSize)  \
        FormatWindowsError((DWORD)(_errCode), _errMsgBuf, (size_t)(_bufSize))

    // 在崩溃场景下，直接退出而不进行资源清理。Windows平台使用ExitProcess并转换错误码 */
    #define emerglog_exit(code)  ExitProcess((UINT)(code == ENOMEM ? ERROR_NOT_ENOUGH_MEMORY : code))
#else
    #include <syslog.h>

    // @brief 格式化 POSIX 系统错误信息
    const char* FormatPosixError(int posix_errno, char errbuf[], size_t bufsize);

    #define format_syserror(_errCode, _errMsgBuf, _bufSize)  \
        FormatPosixError((int)(_errCode), _errMsgBuf, (size_t)(_bufSize))

    // 在崩溃场景下，直接退出而不进行资源清理：使用_exit而不是exit，避免执行atexit处理程序
    #define emerglog_exit(code)  _exit(code)    /* Unix-like平台使用_exit */

    #define set_syslog_conf_dir(path)   ((void)0)
#endif

// 紧急日志信息最长 256 个字符(包括 null-end)
#ifndef EMERGLOG_BUFSIZE
    #define EMERGLOG_BUFSIZE    256
#endif

// 默认 syslog 选项: 包含进程ID, 不延迟打开, 不等待子进程
#ifndef EMERGLOG_OPTIONS
    #define EMERGLOG_OPTIONS   (LOG_PID | LOG_NDELAY | LOG_NOWAIT)
#endif

/**
 * @brief 只记录关键信息到系统日志(不退出当前进程)
 * 记录位置：
 *  Ubuntu: /var/log/syslog
 *  RHEL/CentOS: /var/log/messages
 * 通常用于检查初始化参数必须有效
 *
 * Usage:
 *   emerglog[EMERGLOG_BUFSIZE];  // 必须提前定义
 *   int emergloglen;
 *   ..
 *   emerglog_format(error, "Invalid value=%d", badval);
 *   emerg_syslog_message(0, 0, ident, emerglog, emergloglen);
 */
#define emerglog_format(severity, format, ...) \
        emergloglen = emerg_format_error(emerglog, sizeof(emerglog), 0, 0, #severity, __FILE__, __LINE__, __func__, 0, 0, format, ##__VA_ARGS__)

/**
 * @brief 检查条件，失败则记录错误日志并退出程序
 *
 * 如果条件为假，记录错误信息并退出程序。当 format 为 NULL 时，会自动打印条件表达式字符串。
 *
 * @param expression 要检查的条件表达式
 * @param ident 日志标识符
 * @param syserrno 系统错误代码(-1：自动取得系统错误代码)
 * @param syserrnoname 系统错误号字符串(可以为 NULL)
 * @param format 错误消息格式字符串（可为NULL）
 * @param ... 错误消息的参数
 */
#define emerglog_check_exit(expression, ident, syserrno, syserrnoname, format, ...) do { \
    if (!(expression)) { \
        if (format) { \
            emerg_syslog_error(ident, __FILE__, __LINE__, __func__, (syserrno), (syserrnoname), format, ##__VA_ARGS__); \
        } else { \
            emerg_syslog_error(ident, __FILE__, __LINE__, __func__, (syserrno), (syserrnoname), "Check failed: %s", "`"#expression"`"); \
        } \
        emerglog_exit(EXIT_FAILURE); \
    } \
} while(0)


#define emerglog_error_exit(ident, format, ...)  \
    emerglog_check_exit(NULL, ident, -1, NULL, format, ##__VA_ARGS__)

/**
 * @brief 检查内存分配是否成功的宏，失败时记录错误并退出
 *
 * 此宏用于检查内存分配操作是否成功。如果指针为NULL，则记录内存不足错误并退出程序。
 * 跨平台实现，根据平台选择适当的退出函数和退出码。
 *
 * @param memptr 要检查的内存指针
 * @param ident 日志标识符
 * @param ... 自定义错误消息格式和参数（可选）
 *
 * @note 在Unix-like系统上使用_exit()和ENOMEM退出码
 * @note 在Windows系统上使用ExitProcess()和ERROR_NOT_ENOUGH_MEMORY退出码
 *
 * @example
 * // 基本用法
 * char *buffer = malloc(100);
 * emerglog_check_memory(buffer, "myapp", 0);
 *
 * // 带格式化参数
 * int size = 100;
 * char *buffer2 = malloc(size);
 * emerglog_check_memory(buffer2, "myapp", "分配大小为%d的缓冲区失败", size);
 */
#define emerglog_check_memory(memptr, ident, format, ...)  \
    emerglog_check_exit(memptr != NULL, ident, ENOMEM, "ENOMEM", format, ##__VA_ARGS__)

/**
 * @brief 检查指针是否为非空的宏，失败时记录错误并退出
 *
 * 此宏用于检查指针是否为非空。如果指针为NULL，则记录错误信息并退出程序。
 * 跨平台实现，根据平台选择适当的退出函数和退出码。
 *
 * @param pointer 要检查的指针
 * @param ident 日志标识符
 * @param format 错误消息格式字符串（支持printf样式格式化）
 * @param ... 错误消息的参数（可选）
 *
 * @note 在Unix-like系统上使用_exit()和EFAULT退出码
 * @note 在Windows系统上使用ExitProcess()和ERROR_INVALID_ADDRESS退出码
 * @note 使用GCC/Clang的##__VA_ARGS__扩展处理可变参数
 *
 * @example
 *   // 基本用法
 *   Config* config = get_config();
 *   emerglog_check_nullptr(config, "myapp", "配置指针为空");
 *
 *   // 带格式化参数
 *   User* user = get_user_by_id(user_id);
 *   emerglog_check_nullptr(user, "myapp", "找不到用户ID为%d的用户", user_id);
 */
#define emerglog_check_nullptr(pointer, ident, format, ...) \
    emerglog_check_exit((pointer) != NULL, ident, EFAULT, "EFAULT", format, ##__VA_ARGS__)

/**
 * @brief 通用条件检查宏，失败时记录错误并退出
 *
 * 此宏用于检查任意条件表达式。如果条件为假(false)，则记录错误信息并退出程序。
 * 跨平台实现，根据平台选择适当的退出函数和退出码。
 *
 * @param condition 要检查的条件表达式
 * @param ident 日志标识符
 * @param format 错误消息格式字符串（支持printf样式格式化）
 * @param ... 错误消息的参数（可选）
 *
 * @note 在Unix-like系统上使用_exit()和指定的退出码
 * @note 在Windows系统上使用ExitProcess()和相应的错误码
 *
 * @example
 *   // 检查数值范围
 *   int value = get_value();
 *   emerglog_check_condition(value >= 0 && value <= 100, "myapp", "数值%d超出范围[0,100]", value);
 *
 *   // 检查状态标志
 *   emerglog_check_condition(flags & VALID_FLAG, "myapp", 0);
 *
 *   // 检查业务逻辑条件
 *   emerglog_check_condition(is_user_authenticated(user), "myapp", "用户未认证");
 */
#define emerglog_check_condition(condition, ident, format, ...) \
    emerglog_check_exit(condition, ident, EINVAL, "EINVAL", format, ##__VA_ARGS__)

/**
 * @brief 检查系统调用是否成功的宏，失败时记录错误并退出
 *
 * 此宏用于检查系统调用返回值。如果返回值为 -1（表示失败），则记录系统错误信息并退出程序。
 * 自动使用 errno 作为错误代码，并获取相应的错误描述。
 *
 * @param retval 系统调用返回值(-1 表示失败)
 * @param ident 日志标识符
 * @param format 错误消息格式字符串（支持printf样式格式化）
 * @param ... 错误消息的参数（可选）
 *
 * @note 在Unix-like系统上使用_exit()和errno退出码
 * @note 在Windows系统上使用ExitProcess()和相应的错误码
 * @note 系统调用通常返回 -1 表示失败，并设置 errno
 *
 * @example
 *   // 检查文件打开
 *   int fd = open("file.txt", O_RDONLY);
 *   emerglog_check_syscall(fd, "myapp", "无法打开文件: %s", "file.txt");
 *
 *   // 检查读取操作
 *   ssize_t bytes = read(fd, buffer, sizeof(buffer));
 *   emerglog_check_syscall(bytes, "myapp", "读取文件失败");
 *
 *   // 检查写入操作
 *   ssize_t written = write(fd, data, data_size);
 *   emerglog_check_syscall(written, "myapp", "写入文件失败");
 */
#define emerglog_check_syscall(retval, ident, format, ...) \
    emerglog_check_exit((retval) != -1, ident, errno, NULL, format, ##__VA_ARGS__)

/**
 * @brief 格式化错误日志消息
 *
 * 该函数生成结构化的错误日志消息，包含时间戳、模块标识、严重级别、
 * 源代码位置、系统错误信息和自定义错误消息。
 */
int emerg_format_error(char errorbuf[], size_t bufsize, // bufsize >= 256
    const char* datetime,
    const char* ident,
    const char* severity,
    const char* filename,
    int lineno,
    const char* funcname,
    const char* syserrno,
    const char* syserrstr,
    const char* format, ...);

/**
 * @brief 格式化错误日志消息（使用 va_list 参数）
 *
 * 该函数是 emerg_format_error 的内部实现，接受 va_list 参数而不是可变参数。
 */
int emerg_format_error_args(char errorbuf[], size_t bufsize, // bufsize >= 256
    const char* datetime,
    const char* ident,
    const char* severity,
    const char* filename,
    int lineno,
    const char* funcname,
    const char* syserrno,
    const char* syserrstr,
    const char* format, va_list args);

/**
 * @brief 将系统错误记录到系统日志（syslog）
 *
 * 该函数格式化系统错误信息并通过系统日志(syslog)机制记录错误。
 * 它会自动处理系统错误代码的格式化，并生成结构化的错误日志消息。
 */
void emerg_syslog_error(const char* ident,
    const char* filename,
    int lineno,
    const char* funcname,
    int syserrno,
    const char *syserrnoname,
    const char* format, ...);

/**
 * @brief 将系统错误记录到系统日志（syslog）
 *
 * 该函数是 emerg_syslog_error 的内部实现，接受 va_list 参数而不是可变参数。
 */
void emerg_syslog_error_args(const char* ident,
    const char* filename,
    int lineno,
    const char* funcname,
    int syserrno,
    const char* syserrnoname,
    const char* format, va_list args);

/**
 * @brief 将重要信息记录到系统日志（syslog）
 *
 * 该函数仅用于记录重要信息，不能作为平凡的日志 API 调用。
 */
void emerg_syslog_message(int option, int priority, const char* ident, const char* message, int messagelen);


/**
 * @brief 格式化系统错误信息，可以添加自定义前缀内容
 * @note
 *    errstrbuf - 消息缓冲区参数必须是 char errstrbuf[256]
 *    errno_name - 可以为空
 * 该函数仅用于错误消息格式化，没有写任何日志
 */
#define format_errno_message(errno_name, errstrbuf, prefix)   do { \
        int errnoCopy = errno; \
        char *errBuf = (errstrbuf); \
        size_t errBufSize = sizeof(errstrbuf); \
        DEBUG_ASSERT(errBufSize >= EMERGLOG_BUFSIZE); \
        if (prefix) { \
            int prefixlen = snprintf(errBuf, errBufSize, "(%s:%d@%s) %s:%d <%s> - ", \
                    __FILE__, __LINE__, __func__, (errno_name? errno_name : "ERROR"), errnoCopy, prefix); \
            if (prefixlen >= errBufSize || prefixlen > 128) { \
                prefixlen = 0; \
            } \
            format_syserror(errnoCopy, errBuf + prefixlen, errBufSize - prefixlen); \
        } else { \
            int prefixlen = snprintf(errBuf, errBufSize, "(%s:%d@%s) %s:%d - ", \
                    __FILE__, __LINE__, __func__, (errno_name? errno_name : "ERROR"), errnoCopy); \
            if (prefixlen >= errBufSize || prefixlen > 128) { \
                prefixlen = 0; \
            } \
            format_syserror(errnoCopy, errBuf + prefixlen, errBufSize - prefixlen); \
        } \
        errstrbuf[errBufSize - 1] = '\0'; \
        errno = errnoCopy; \
    } while(0)

#ifdef __cplusplus
}
#endif

#endif /* EMERGLOG_H__ */
