/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file emerglog.c
 * @brief 紧急日志系统。写入系统日志。
 *
 * 提供跨平台的紧急日志记录功能，支持系统错误信息格式化，设计用于关键错误处理和系统日志记录。
 * 支持 Windows、Linux 和其他 POSIX 兼容系统。
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 anomura.cc All Rights Reserved.
 * @version 0.0.44
 *
 * @since 2017-05-02 12:02:50
 * @date 2025-12-06 22:02:59
 *
 * @note 通用系统活动日志:
 *   - Debian/Ubuntu:
 *     /var/log/syslog
 *   - RHEL/CentOS:
 *     /var/log/messages
 *   - Windows
 *     按Win+R，输入`eventvwr.msc`并回车。
 *     Windows日志 -> 应用程序：应用程序相关的事件
 */
#include "emerglog.h"
#include "pathlib.h"
#include <sched.h>
#include <pthread.h>

// 默认的 ident
static char emerglog_ident[] = "emerglog";

// 全局互斥锁用于保护syslog操作
static pthread_mutex_t syslog_mutex = PTHREAD_MUTEX_INITIALIZER;


#if defined(PLATFORM_WINDOWS) || defined(PLATFORM_CYGWIN)
/**
 * @brief 格式化 Windows 系统错误信息
 *
 * 此函数将 Windows 系统错误代码转换为可读的错误消息字符串。
 * 如果传入的错误代码为 (DWORD)-1，则自动获取当前线程的最后错误代码。
 *
 * @param dwError Windows 错误代码。如果传入 (DWORD)-1，则使用 GetLastError() 获取当前错误代码
 * @param errbuf 存储错误信息的输出缓冲区。必须至少为 128 字节
 * @param bufsize errbuf 缓冲区的字节大小。必须至少为 128
 * @return const char* 指向格式化后的错误信息字符串的指针（即 errbuf）
 *
 * @note 如果 FormatMessageA 调用失败，函数将返回包含原始错误代码 dwError 和
 *       FormatMessageA 失败错误代码 LastError 的备用错误消息。
 *       错误代码 dwError 将同时以十进制 (%lu) 和十六进制 (0x%08lX) 格式显示，
 *       便于在微软文档和调试器中查找。
 *
 *       返回的字符串 errbuf 是 null-ended，并且移除了末尾的换回符。
 *
 * @example
 *   char errmsg[256];
 *   if (!SomeWindowsAPI()) {
 *       FormatWindowsError(GetLastError(), errmsg, sizeof(errmsg));
 *       printf("Error: %s\n", errmsg);
 *   }
 */
const char* FormatWindowsError(DWORD dwError, char errbuf[], size_t bufsize)
{
    if (bufsize < 2) {
        errbuf[0] = '\0';
        return errbuf;
    }

    DWORD dwRet;
    if (dwError == (DWORD)-1) {
        dwError = GetLastError();
    }

    const DWORD dwEngLang = MAKELANGID(LANG_ENGLISH, SUBLANG_ENGLISH_US);
    const DWORD dwDefLang = MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT);

    dwRet = FormatMessageA(FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
                NULL,
                dwError,
                dwEngLang,
                errbuf,
                (DWORD)bufsize,
                NULL);
    if (!dwRet && dwDefLang != dwEngLang) {
        dwRet = FormatMessageA(FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
            NULL,
            dwError,
            dwDefLang,
            errbuf,
            (DWORD)bufsize,
            NULL);
    }

    if (!dwRet) {
        DWORD fmtError = GetLastError();
        snprintf(errbuf, bufsize,
            "FormatMessageA failed for dwError=%" PRIu32 " (0x%08" PRIx32 ") with LastError=%" PRIu32,
            (uint32_t) dwError,
            (uint32_t) dwError,
            (uint32_t) fmtError
        );
        errbuf[bufsize - 1] = '\0';
    }
    else if (dwRet > 0) {
        // 成功获取错误消息，移除末尾的回车和换行符
        if (dwRet >= bufsize) {
            dwRet = (DWORD)(bufsize - 1);
        }
        char *p = errbuf + dwRet;
        *p-- = '\0';
        while (p >= errbuf && (*p == '\r' || *p == '\n' || *p == ' ')) {
            *p-- = '\0';
        }
    }
    else {
        // should never run to this.
        errbuf[0] = '\0';
    }
    return errbuf;
}
#else
/**
 * @brief 格式化 POSIX 系统错误信息
 *
 * 此函数将 POSIX 错误代码转换为可读的错误消息字符串。
 * 如果传入的错误代码为 -1，则自动获取当前线程的 errno 值。
 * 返回的字符串确保以 null 结尾。
 *
 * @param errnum POSIX 错误代码。如果传入 -1，则使用 errno 获取当前错误代码
 * @param errbuf 存储错误信息的输出缓冲区
 * @param bufsize errbuf 缓冲区的字节大小
 * @return const char* 指向格式化后的错误信息字符串的指针（即 errbuf）
 *
 * @note 此函数处理不同平台上 strerror_r 函数的两种不同实现：
 *       1. GNU 版本：返回 char*，可能指向静态字符串或提供的缓冲区
 *       2. POSIX 标准版本：返回 int，表示成功(0)或错误码
 *       如果两种方法都失败，函数将返回包含原始错误代码和失败信息的备用错误消息
 *
 * @warning 缓冲区大小应至少为 64 字节以确保有足够空间存储错误消息
 *
 * @example
 *   char errmsg[256];
 *   if (open("file", O_RDONLY) == -1) {
 *       FormatPosixError(errno, errmsg, sizeof(errmsg));
 *       printf("Error: %s\n", errmsg);
 *   }
 */
const char* FormatPosixError(int errnum, char* errbuf, size_t bufsize)
{
    if (bufsize < 2) {
        errbuf[0] = '\0';
        return errbuf;
    }
    if (errnum == -1) {
        errnum = errno;  // get_last_errno
    }
#ifdef _GNU_SOURCE
    // 尝试使用 GNU 版本的 strerror_r（返回 char *）
    char* result = strerror_r(errnum, errbuf, bufsize);
    if (result != errbuf) {
        // 如果返回的是静态字符串，复制到我们的缓冲区
        int len = snprintf(errbuf, bufsize, "%s", result);
        if (len < 0) {
            // should never run to this
            errbuf[0] = '\0';
        }
    }
#else
    // 使用 POSIX 标准版本的 strerror_r（返回 int）
    int ret = strerror_r(errnum, errbuf, bufsize);
    if (ret) {
        // 如果 strerror_r 失败，使用备用方法
        snprintf(errbuf, bufsize, "strerror_r failed for errnum=%d with return=%d", errnum, ret);
    }
#endif

    // 确保字符串以 null 结尾
    errbuf[bufsize - 1] = '\0';
    return errbuf;
}
#endif

/**
 * @brief 格式化错误日志消息
 *
 * 该函数生成结构化的错误日志消息，包含时间戳、模块标识、严重级别、
 * 源代码位置、系统错误信息和自定义错误消息。
 *
 * @param[out] errorbuf 输出缓冲区，用于存储格式化后的错误消息
 * @param[in] bufsize 输出缓冲区的大小（字节数），建议至少256字节
 * @param[in] datetime 时间戳字符串，格式应为"YYYY-MM-DD HH:MM:SS"
 * @param[in] ident 模块或组件标识符
 * @param[in] severity 严重级别（如ERROR, WARN, INFO等）
 * @param[in] filename 源代码文件名
 * @param[in] lineno 源代码行号
 * @param[in] funcname 函数名
 * @param[in] syserrno 系统错误代码（如EPERM, ENOENT等）
 * @param[in] syserrstr 系统错误描述
 * @param[in] format 自定义错误消息的格式字符串（类似printf）
 * @param[in] ... 自定义错误消息的参数
 *
 * @return int 成功写入的字符数（不包括终止null字符）
 * @retval -1 表示发生错误
 * @retval >=0 表示成功写入的字符数
 *
 * @note 输出格式示例：
 *       2023-10-05 14:30:25 [libmysqltcl] ERROR(.../src/test.c:115@funcname)<EPERM - Operation not permitted> 参数无效
 *
 * @warning 缓冲区大小应至少为256字节以确保有足够空间存储完整错误消息
 *
 * @see emerg_format_error_args()
 *
 * @example
 *   char error_msg[256];
 *   int len = emerg_format_error(
 *       error_msg, sizeof(error_msg),
 *       "2023-10-05 14:30:25",
 *       "libmysqltcl",
 *       "ERROR",
 *       __FILE__,
 *       __LINE__,
 *       __func__,
 *       "EPERM",
 *       "Operation not permitted",
 *       "参数无效"
 *   );
 *   if (len > 0) {
 *       printf("Error: %s\n", error_msg);
 *   }
 */
int emerg_format_error(char errorbuf[], size_t bufsize, // bufsize >= 256
    const char* datetime,
    const char* ident,
    const char* severity,
    const char* filename,
    int lineno,
    const char* funcname,
    const char* syserrno,
    const char* syserrstr,
    const char* format, ...)
{
    va_list args;
    va_start(args, format);
    int ret = emerg_format_error_args(errorbuf, bufsize, datetime, ident, severity, filename, lineno, funcname, syserrno, syserrstr, format, args);
    va_end(args);
    return ret;
}

/**
 * @brief 格式化错误日志消息
 *
 * 该函数生成结构化的错误日志消息，包含时间戳、模块标识、严重级别、
 * 源代码位置、系统错误信息和自定义错误消息。
 *
 * @warning 缓冲区大小应至少为256字节以确保有足够空间存储完整错误消息
 *
 * @see emerg_format_error()
 */
int emerg_format_error_args(char errorbuf[], size_t bufsize, // bufsize >= 256
    const char* datetime,
    const char* ident,
    const char* severity,
    const char* filename,
    int lineno,
    const char* funcname,
    const char* syserrno,
    const char* syserrstr,
    const char* format, va_list args)
{
#define GetStrLenSafe(str, maxlen)  ((int)(str? strnlen(str, maxlen) : 0))

#define CheckSetOffset(len)  do { \
        if (len < 1) { \
            return 0; \
        } else { \
            offcb += len; \
            if (offcb > bufsize - 4) { \
                if (offcb >= bufsize) { \
                    offcb = bufsize - 1; \
                    errorbuf[offcb] = 0; \
                    return (int)offcb; \
                } else { \
                    return (int)offcb; \
                } \
            } \
        } \
    } while(0)

    const static char seps[] = "/\\";
    *errorbuf = 0;

    int datetimelen = GetStrLenSafe(datetime, 24);
    int identlen = GetStrLenSafe(ident, 20);
    int severitylen = GetStrLenSafe(severity, 8);

    int prefixlen = 48;
    int prefixlevel = 1;
    const char* punc = 0;
    const char* prefixfile = path_prefix_level(filename, seps, &prefixlen, &prefixlevel, &punc);
    int punclen = GetStrLenSafe(punc, 3);

    int linenolen = lineno > 0 ? snprintf(errorbuf, bufsize, "%d", lineno) : 0;
    int funcnamelen = GetStrLenSafe(funcname, 24);

    int syserrnolen = GetStrLenSafe(syserrno, 16);
    int syserrstrlen = GetStrLenSafe(syserrstr, 80);

    int blen = 0;
    size_t offcb = 0;

    if (datetimelen) {
        blen = snprintf(errorbuf + offcb, bufsize - offcb, "%.*s ", datetimelen, datetime);
        CheckSetOffset(blen);
    }

    if (identlen) {
        blen = snprintf(errorbuf + offcb, bufsize - offcb, "[%.*s]", identlen, ident);
        CheckSetOffset(blen);
    }

    if (severitylen) {
        blen = snprintf(errorbuf + offcb, bufsize - offcb, "%.*s ", severitylen, severity);
        CheckSetOffset(blen);
    }

    if (prefixfile && prefixlen) {
        if (linenolen) {
            blen = snprintf(errorbuf + offcb, bufsize - offcb, "(%.*s%.*s:%d %.*s)",
                punclen, punc, prefixlen, prefixfile, lineno, funcnamelen, funcname);
            CheckSetOffset(blen);
        }
        else {
            blen = snprintf(errorbuf + offcb, bufsize - offcb, "(%.*s%.*s %.*s)",
                punclen, punc, prefixlen, prefixfile, funcnamelen, funcname);
            CheckSetOffset(blen);
        }
    }

    if (syserrnolen) {
        blen = snprintf(errorbuf + offcb, bufsize - offcb, "<%.*s:%.*s> ", syserrnolen, syserrno, syserrstrlen, syserrstr);
        CheckSetOffset(blen);

    }

    if (format) {
        blen = vsnprintf(errorbuf + offcb, bufsize - offcb, format, args);
        if (blen < 0) {
            // 格式化错误，不再追加自定义消息，但保留已有内容
            blen = 0;
        }
        else {
            offcb += blen;
        }
    }

    if (offcb >= bufsize) {
        offcb = bufsize - 1;
    }

    // 移除行尾空格
    blen = (int)offcb - 1; // blen as index
    while (blen > 0 && errorbuf[blen] == ' ') {
        blen--;
    }
    offcb = blen + 1;
    errorbuf[offcb] = 0;
    return (int)offcb;
#undef GetStrLenSafe
#undef CheckSetOffset
}

/**
 * @brief 将系统错误记录到系统日志（syslog）
 *
 * 该函数格式化系统错误信息并通过系统日志(syslog)机制记录错误。
 * 它会自动处理系统错误代码的格式化，并生成结构化的错误日志消息。
 *
 * @see emerg_syslog_error_args
 */
void emerg_syslog_error(const char* ident,
    const char* filename,
    int lineno,
    const char* funcname,
    int syserrno,
    const char* syserrnoname,
    const char* format, ...)
{
    va_list args;
    va_start(args, format);
    emerg_syslog_error_args(ident, filename, lineno, funcname, syserrno, syserrnoname, format, args);
    va_end(args);
}

/**
 * @brief 将系统错误记录到系统日志（syslog）
 *
 * 该函数格式化系统错误信息并通过系统日志(syslog)机制记录错误。
 * 它会自动处理系统错误代码的格式化，并生成结构化的错误日志消息。
 *
 * @param[in] ident 日志标识符，如果为NULL则使用默认标识符(emerglog_ident)
 * @param[in] filename 源代码文件名
 * @param[in] lineno 源代码行号
 * @param[in] funcname 函数名
 * @param[in] syserrno 系统错误代码。如果为0，则不处理系统错误信息。如果为-1，则自动获取系统最后的错误码
 * @param[in] syserrnoname 系统错误号字符串表示（如"EPERM"），可以为 NULL
 * @param[in] format 自定义错误消息的格式字符串
 * @param[in] args 自定义错误消息的参数
 *
 * @note 此函数会自动打开和关闭syslog连接
 * @note 错误级别固定为LOG_EMERG（最高紧急级别）
 * @note 如果syserrno为0，则不会包含系统错误描述
 * @note 时间戳由syslog自动添加
 * @see emerg_syslog_error
 *
 * @example
 *   // 记录权限错误
 *   emerg_syslog_error("myapp", __FILE__, __LINE__, __func__,
 *                      errno, "EACCES", "Failed to open file: %s", filename);
 *
 *   // 记录无系统错误的应用程序错误
 *   emerg_syslog_error("myapp", __FILE__, __LINE__, __func__,
 *                      0, NULL, "Invalid configuration detected");
 */
void emerg_syslog_error_args(const char* ident,
    const char* filename,
    int lineno,
    const char* funcname,
    int syserrno,
    const char* syserrnoname,
    const char* format, va_list args)
{
    int syserrno_chkd = syserrno == -1? errno : syserrno;
    int blen = 0;

    char emergbuf[EMERGLOG_BUFSIZE];   // 错误消息缓冲区
    char syserrbuf[128];               // 系统错误描述缓冲区

    // 确保错误代码名称被设置
    const char* syserrnostr = syserrnoname;
    if (! syserrnoname) {
        // 未提供系统错误代码名称
        blen = snprintf(syserrbuf, sizeof(syserrbuf), "errno(%d)", syserrno_chkd);
        if (blen <= 0) {
            blen = 0;
        }
        syserrbuf[blen++] = 0;
        syserrnostr = syserrbuf;
    }

    // 格式化系统错误信息（如果提供了系统错误代码）
    const char* syserrstr = NULL;
    if (syserrno) {
        syserrstr = format_syserror(syserrno_chkd, syserrbuf + blen, sizeof(syserrbuf) - blen);
    }

    // 格式化错误消息（处理可变参数）
    blen = emerg_format_error_args(emergbuf, sizeof(emergbuf),
            NULL,    // syslog 自动记录时间，因此不需要传递时间戳
            ident,
            "EMERG", // 固定严重级别为 EMERG
            filename,
            lineno,
            funcname,
            syserrnostr,   // 系统错误号字符串: ENOMEM
            syserrstr,     // 系统错误描述: Out of Memory
            format, args); // 自定义消息和参数

    // 如果成功格式化错误消息，则记录到系统日志
    emerg_syslog_message(EMERGLOG_OPTIONS, LOG_USER | LOG_EMERG, ident, emergbuf, blen);
}

/**
 * @brief 记录紧急系统日志消息
 *
 * 此函数用于向系统日志中记录一条紧急消息。它会打开系统日志连接，
 * 发送指定优先级的消息，然后立即关闭连接。
 *
 * @param option 系统日志选项标志（如 LOG_PID, LOG_CONS 等）。
 *               如果为0，则使用默认选项 EMERGLOG_OPTIONS。
 * @param priority 消息优先级，由设施和级别通过逻辑或组合而成。
 *                 如果为0，则使用默认优先级 LOG_USER | LOG_EMERG。
 * @param ident 用于标识日志来源的字符串。如果为NULL，则使用全局标识符 emerglog_ident。
 * @param message 要记录的消息内容。
 * @param messagelen 消息内容的长度（字节数）。
 *
 * @note 此函数设计为在紧急情况下使用，每次调用都会打开和关闭系统日志连接，
 *       确保消息能够立即被记录。但这可能会影响性能，因此不适用于高频日志记录。
 *
 * @warning 使用此函数时需要确保 emerglog_ident 已正确初始化（如果传入的 ident 为 NULL）。
 */
void emerg_syslog_message(int option, int priority, const char* ident, const char* message, int messagelen)
{
    if (messagelen == -1) {
        messagelen = cstr_length(message, 255);
    }

    if (messagelen > 0) {
        // 获取互斥锁
        pthread_mutex_lock(&syslog_mutex);

        // 确保即使出现错误也能释放互斥锁
        do {
            // 打开系统日志连接
            openlog((ident ? ident : emerglog_ident), (option ? option : EMERGLOG_OPTIONS), 0);

            // 记录消息
            syslog((priority ? priority : LOG_USER | LOG_EMERG), "%.*s", messagelen, message);

            // 关闭系统日志连接
            closelog();
        } while (0);

        // 释放互斥锁
        pthread_mutex_unlock(&syslog_mutex);
    }
}

