/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file memalign.c
 *   A pair of cross - platform C functions to allocate and free aligned memory
 * @author Liang Zhang <350137278@qq.com>
 * @copyright © 2024-2025 anomura.cc All Rights Reserved.
 * @version 0.0.17
 * @since 2025-03-22 12:54:00
 * @date 2025-12-06 22:02:59
 * @note
 *   https://github.com/NickStrupat/AlignedMalloc.git
 *
 * AlignedMalloc
 *   A pair of cross - platform C functions to allocate and free aligned memory
 *
 * void* aligned_malloc(size_t size, size_t alignment);
 * void aligned_free(void* pointer);
 *
 * Usage
 *   Use the two functions in place of `malloc` and `free` when you need
 *   aligned memory.
 * Supported platforms
 *
 * Mac OS X and Linux are supported by calling `posix_memalign`,
 * Windows by calling `_aligned_malloc` (`_aligned_malloc_dbg` while compiling
 *   with `_DEBUG`).
 * Outside of those platforms, determined with the `__APPLE__`, `__linux__`,
 *  and `_WIN32`
 * macro definitions respectively, the function will use a custom implementation.
 *
 * This custom implementation uses `malloc` under the hood, but returns a
 *  pointer to an aligned memory address within a larger memory block.
 * It stores the pointer returned by malloc in the extra space before the
 *  aligned memory for `aligned_free` to access later.
 * This is necessary to ensure the memory can be freed correctly.
 */
#include "memalign.h"
#include "platforms.h"


// 检查 alignment 是否合法
#define MEM_ALIGN_ASSERT(alignment) \
	DEBUG_ASSERT(((((alignment) != 0) && \
		((alignment) % sizeof(void*) == 0) && \
		((alignment) & ((alignment) - 1)) == 0)) && "memalign_assert failed: " #alignment)


bool memalign_is_aligned(const void* pointer, size_t alignment)
{
	if (!pointer) {
		return false; // 无效输入
	}

	if (!alignment) {
		alignment = memalign_alignment(0);
	}

	if (alignment % sizeof(void*) == 0 && (alignment & (alignment - 1)) == 0) {
		uintptr_t address = (uintptr_t)pointer;
		uintptr_t mask = alignment - 1;
		return (address & mask) == 0;
	}

	return false; // 无效输入
}

#if defined(PLATFORM_MACOS) || defined(PLATFORM_LINUX)

	#include <stdlib.h>

	void* memalign_alloc(size_t size, size_t alignment)
	{
		MEM_ALIGN_ASSERT(alignment);
		void* pointer;
		int err = posix_memalign(&pointer, alignment, size);
		return err == 0? pointer : NULL;
	}

	void memalign_free(void* pointer)
	{
		free(pointer);
	}

	void memalign_free_safe(void** pPointer)
	{
		if (pPointer) {
			void* pointer = *pPointer;
			if (pointer) {
				*pPointer = 0;
				free(pointer);
			}
		}
	}

	#if defined(PLATFORM_MACOS)
		#include <sys/sysctl.h>

		size_t memalign_alignment(size_t defaultOnFail)
		{
			int mib[2];
			size_t cacheLineSize = 0;
			size_t size = sizeof(cacheLineSize);

			mib[0] = CTL_HW;
			mib[1] = HW_CACHELINE;

			// 通过 MIB 查询
			int ret = sysctl(mib, 2, &cacheLineSize, &size, NULL, 0);
			if (ret == 0) {
				return cacheLineSize;
			}
			else {
				return defaultOnFail ? defaultOnFail : MEM_ALIGN_SIZE_64;
			}
		}

	#else // PLATFORM_LINUX

		size_t memalign_alignment(size_t defaultOnFail)
		{
			unsigned lineSize = 0;
			FILE* fp = fopen("/sys/devices/system/cpu/cpu0/cache/index0/coherency_line_size", "r");
			if (fp) {
				if (fscanf(fp, "%u", &lineSize) != 1) {
					lineSize = 0;
				}
				fclose(fp);
			}
			return (size_t)(lineSize ? lineSize : (defaultOnFail ? defaultOnFail : MEM_ALIGN_SIZE_64));
		}

	#endif

#elif defined(PLATFORM_WINDOWS)
	#include <Windows.h>
	#include <crtdbg.h>
	#include <malloc.h>

	void* memalign_alloc(size_t size, size_t alignment)
	{
		MEM_ALIGN_ASSERT(alignment);
	#ifdef _DEBUG
		// This is reduced to a call to `_aligned_malloc` when _DEBUG is not defined
		return _aligned_malloc_dbg(size, alignment, __FILE__, __LINE__);
	#else
		return _aligned_malloc(size, alignment);
	#endif
	}

	void memalign_free(void* pointer)
	{
	#ifdef _DEBUG
		// This is reduced to a call to `_aligned_free` when _DEBUG is not defined
		_aligned_free_dbg(pointer);
	#else
		_aligned_free(pointer);
	#endif
	}

	void memalign_free_safe(void** pPointer)
	{
		if (pPointer) {
			void* pointer = *pPointer;
			if (pointer) {
				*pPointer = 0;
				memalign_free(pointer);
			}
		}
	}

	size_t memalign_alignment(size_t defaultOnFail)
	{
		DWORD bufferSize = 0;
		if (!GetLogicalProcessorInformation(0, &bufferSize) && GetLastError() != ERROR_INSUFFICIENT_BUFFER) {
			return defaultOnFail? defaultOnFail : MEM_ALIGN_SIZE_64;
		}

		SYSTEM_LOGICAL_PROCESSOR_INFORMATION* buffer = (SYSTEM_LOGICAL_PROCESSOR_INFORMATION*) memalign_alloc(bufferSize, MEM_ALIGN_SIZE_64);
		if (!GetLogicalProcessorInformation(buffer, &bufferSize)) {
			memalign_free_safe((void**) &buffer);
			return defaultOnFail ? defaultOnFail : MEM_ALIGN_SIZE_64;
		}

		DWORD cacheLineSize = 0;
		for (DWORD i = 0; i < bufferSize / sizeof(SYSTEM_LOGICAL_PROCESSOR_INFORMATION); i++) {
			if (buffer[i].Relationship == RelationCache && buffer[i].Cache.Level == 1) {
				cacheLineSize = buffer[i].Cache.LineSize;
				break;
			}
		}

		memalign_free_safe((void**)&buffer);
		return (size_t) cacheLineSize ? cacheLineSize : (defaultOnFail ? defaultOnFail : MEM_ALIGN_SIZE_64);
	}

#else // unknown platform
	// https://sites.google.com/site/ruslancray/lab/bookshelf/interview/ci/low-level/write-an-aligned-malloc-free-function
	#include <stdlib.h>

	size_t memalign_alignment(size_t defaultOnFail)
	{
		return defaultOnFail? defaultOnFail : MEM_ALIGN_SIZE_64;
	}

	void* memalign_alloc(size_t size, size_t alignment)
	{
		MEM_ALIGN_ASSERT(alignment);
		void* p1;
		void** p2;
		const size_t offset = alignment; // 关键修正点
		if ((p1 = malloc(size + offset)) == NULL) {
			return NULL;
		}
		p2 = (void**)(((uintptr_t)p1 + offset) & ~(alignment - 1));

		// 安全屏障：确保 p2 前方有足够空间
		if ((uintptr_t)p2 - (uintptr_t)p1 < sizeof(void*)) {
			p2 = (void**)((uintptr_t)p2 + alignment);
		}
		p2[-1] = p1; // 安全写入
		return p2;
	}

	void memalign_free(void* pointer)
	{
		free(((void**)pointer)[-1]);
	}

	void memalign_free_safe(void** pPointer)
	{
		if (pPointer) {
			void* pointer = *pPointer;
			if (pointer) {
				*pPointer = 0;
				memalign_free(pointer);
			}
		}
	}

#endif
