/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file mscrtdbg.h
 * @brief MSVC CRT 调试支持头文件
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 anomura.cc All Rights Reserved.
 * @version 0.0.43
 *
 * @since 2019-09-30 12:37:44
 * @date 2025-12-11 00:13:23
 *
 * @note
 *   此头文件应第一个包含，确保在包含其他头文件前启用内存调试
 */
#ifndef MSCRTDBG_H_
#define MSCRTDBG_H_

// 只在调试模式下启用CRT调试
#ifndef NDEBUG
    #if defined(_WIN32) && defined(_MSC_VER)
        // 调试模式 - MSVC
        #ifndef _CRT_SECURE_NO_WARNINGS
            #define _CRT_SECURE_NO_WARNINGS
        #endif

        #pragma warning(disable:4996)

        // 启用CRT内存调试（必须在包含crtdbg.h之前定义）
        #ifndef _CRTDBG_MAP_ALLOC
            #define _CRTDBG_MAP_ALLOC
        #endif

        #include <crtdbg.h>
        #include <stdlib.h>
        #include <stdio.h>
        #include <string.h>
        #include <malloc.h>

        // 自定义报告钩子示例
        static int crtdbg_report_hook(int report_type, char* message, int* return_value)
        {
            // 可以在这里处理报告消息
            printf("CRT Report (Type: %d): %s\n", report_type, message);
            // 返回0表示继续使用CRT的默认处理
            return 0;
        }

        // 初始化CRT调试功能
        // 启用内存泄漏检测和堆检查，设置报告输出到调试器。
        // 在MSVC调试模式下有效，其他情况下为空操作。
        static void __cdecl mscrtdbg_init(void)
        {
            // 启用内存泄漏检测和堆检查
            _CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF | _CRTDBG_CHECK_ALWAYS_DF);
            // 设置报告输出到调试器
            _CrtSetReportMode(_CRT_WARN, _CRTDBG_MODE_DEBUG);
            _CrtSetReportMode(_CRT_ERROR, _CRTDBG_MODE_DEBUG);
            _CrtSetReportMode(_CRT_ASSERT, _CRTDBG_MODE_DEBUG);
        }

        // 在特定内存分配处设置断点
        // alloc_num 分配编号（从泄漏报告中获取）
        #define mscrtdbg_break(alloc_num) _CrtSetBreakAlloc(alloc_num)

        // 立即输出内存泄漏报告
        #define mscrtdbg_dump() _CrtDumpMemoryLeaks()

        // 设置自定义报告钩子函数
        #define mscrtdbg_sethook(hook) _CrtSetReportHook(hook)

        // 检查内存状态（验证堆完整性）: 如果堆正常返回TRUE，否则返回FALSE
        #define mscrtdbg_check() _CrtCheckMemory()

        #ifndef MSCRTDBG_MEM_STATE
            #define MSCRTDBG_MEM_STATE
        #endif

        // 记录当前内存状态快照
        // _CrtMemState state
        #define mscrtdbg_snapshot(state) _CrtMemCheckpoint(&(state))

        // 比较两个内存状态快照
        #define mscrtdbg_compare(diff, state1, state2) _CrtMemDifference(&(diff), &(state1), &(state2))

        // 输出差异报告
        #define mscrtdbg_dumpstate(state)  _CrtMemDumpStatistics(&(state))

        // 声明状态变量
        #define mscrtdbg_declstate(state_name)  _CrtMemState state_name
    #else
        // 调试模式 - 非MSVC（如GCC、Clang）
        #include <stdlib.h>
        #include <stdio.h>
        #include <string.h>

        #if defined(_WIN32)
            #include <malloc.h>
        #endif

        // 空实现
        #define mscrtdbg_init() ((void)0)
        #define mscrtdbg_break(alloc_num) ((void)(alloc_num))
        #define mscrtdbg_dump() ((void)0)
        #define mscrtdbg_sethook(hook) ((void)(hook))
        #define mscrtdbg_check() (1)
    #endif
#else
    // 发布模式（定义了NDEBUG）
    #if defined(_WIN32) && defined(_MSC_VER)
        #pragma warning(disable:4996)
    #endif

    #include <stdlib.h>
    #include <stdio.h>
    #include <string.h>

    #if defined(_WIN32)
        #include <malloc.h>
    #endif

    // 空实现
    #define mscrtdbg_init() ((void)0)
    #define mscrtdbg_break(alloc_num) ((void)(alloc_num))
    #define mscrtdbg_dump() ((void)0)
    #define mscrtdbg_sethook(hook) ((void)(hook))
    #define mscrtdbg_check() (1)
#endif

// 为方便使用提供的宏
// MSCRTDBG_INIT() 放在 main() 函数的第1行
#define MSCRTDBG_INIT() mscrtdbg_init()
#define MSCRTDBG_SETHOOK(hook) mscrtdbg_sethook(hook)
#define MSCRTDBG_BREAK(alloc_num) mscrtdbg_break(alloc_num)
#define MSCRTDBG_DUMP() mscrtdbg_dump()
#define MSCRTDBG_CHECK() mscrtdbg_check()

#ifdef MSCRTDBG_MEM_STATE
    #define MSCRTDBG_SNAPSHOT(state) mscrtdbg_snapshot(state)
    #define MSCRTDBG_COMPARE(diff, state1, state2) mscrtdbg_compare(diff, state1, state2)
    #define MSCRTDBG_DUMPSTATE(state) mscrtdbg_dumpstate(state)
    #define MSCRTDBG_DECLSTATE(state) mscrtdbg_declstate(state)
#endif

#endif /* MSCRTDBG_H_ */
