/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file pathlib.h
 * @brief 跨平台文件路径操作API，适用于 macOS, Linux, Windows, Cygwin, MinGW 等环境
 *   提供统一的文件路径操作、文件系统访问和文件I/O接口，封装平台差异，简化跨平台开发。
 *   核心功能包括路径解析、文件/目录操作、文件信息和文件读写等。
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 anomura.cc All Rights Reserved.
 * @version 0.0.63
 *
 * @since 2019-09-30 12:37:44
 * @date 2025-12-06 22:02:59
 *
 * @note
 *   Windows 平台依赖 `<windows.h>` 等系统头文件，需确保链接 Windows SDK；
 *   类 Unix 平台依赖 POSIX 标准头文件，需确保编译器支持 POSIX 接口
 */
#ifndef PATHLIB_H_
#define PATHLIB_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "unitypes.h"
#include "memapi.h"
#include "cstrbuf.h"

/* 平台特定头文件与常量定义：封装跨平台差异，提供统一抽象 */
#if defined(PLATFORM_WINDOWS)
    #include <direct.h>     // Windows 目录操作（_mkdir 等）
    #include <io.h>         // Windows I/O 辅助函数

    /**
     * @brief Windows 平台路径分隔符（字符形式）
     * @note 如 "C:\\Users\\file.txt" 中的 '\\'，使用时需注意字符串转义（代码中写为 '\\'）
     */
    #define PATH_SEP_CHR '\\'

    /**
     * @brief Windows 平台路径分隔符（字符串形式）
     * @note 如拼接路径时使用："data" PATH_SEP_STR "config.txt" → "data\\config.txt"
     */
    #define PATH_SEP_STR "\\"

    /**
     * @brief Windows 平台最大路径长度（含终止符）
     * @note 对应 Windows API 中的 MAX_PATH，值为 260 字节，不支持超长路径（需手动添加 "\\?\\" 前缀扩展）
     */
    #define PATH_SIZE_MAX MAX_PATH

    /**
     * @brief 跨平台文件句柄类型（Windows 平台）
     * @note 对应 Windows 的 HANDLE 类型，用于标识打开的文件
     */
    typedef HANDLE filehandle_t;

    /**
     * @brief 无效的文件句柄（Windows 平台）
     * @note 对应 Windows 的 INVALID_HANDLE_VALUE，用于判断文件创建/打开是否失败
     */
    # define filehandle_invalid  INVALID_HANDLE_VALUE

    /**
     * @brief 文件定位起始位置（从文件开头）
     * @note 映射 Windows 的 FILE_BEGIN，用于 file_seek 等函数
     */

    # define fseek_pos_set       ((int)FILE_BEGIN)

    /**
     * @brief 文件定位起始位置（从当前位置）
     * @note 映射 Windows 的 FILE_CURRENT，用于 file_seek 等函数
     */
    # define fseek_pos_cur       ((int)FILE_CURRENT)

     /**
     * @brief 文件定位起始位置（从文件末尾）
     * @note 映射 Windows 的 FILE_END，用于 file_seek 等函数
     */
    # define fseek_pos_end       ((int)FILE_END)
#else
    #include <unistd.h>     // POSIX 系统调用（getcwd、unistd 等）
    #include <dirent.h>     // POSIX 目录操作（opendir、readdir 等）
    #include <sys/stat.h>   // POSIX 文件状态（stat 等）
    #include <sys/types.h>  // POSIX 类型定义（mode_t 等）
    #include <fcntl.h>      // POSIX 文件控制（open、fcntl 等）
    #include <limits.h>     // POSIX 系统限制（PATH_MAX 等）

    /**
     * @brief 类 Unix 平台路径分隔符（字符形式）
     * @note 如 "/home/user/file.txt" 中的 '/'，无需转义，直接使用
     */
    #define PATH_SEP_CHR '/'

    /**
     * @brief 类 Unix 平台路径分隔符（字符串形式）
     * @note 如拼接路径时使用："data" PATH_SEP_STR "config.txt" → "data/config.txt"
     */
    #define PATH_SEP_STR "/"

    /**
     * @brief 类 Unix 平台最大路径长度（含终止符）
     * @note 对应 POSIX 的 PATH_MAX，通常为 4096 字节，具体值可通过 `getconf PATH_MAX` 查看
     */
    #define PATH_SIZE_MAX  PATH_MAX

    /**
     * @brief 跨平台文件句柄类型（类 Unix 平台）
     * @note 对应 POSIX 的文件描述符（int 类型），用于标识打开的文件
     */
    typedef int filehandle_t;

    /**
     * @brief 无效的文件句柄（类 Unix 平台）
     * @note 对应 POSIX 的 -1，用于判断文件创建/打开是否失败
     */
    # define filehandle_invalid ((filehandle_t)(-1))

    /**
     * @brief 文件定位起始位置（从文件开头）
     * @note 映射 POSIX 的 SEEK_SET，用于 file_seek 等函数
     */
    # define fseek_pos_set      ((int)SEEK_SET)

    /**
     * @brief 文件定位起始位置（从当前位置）
     * @note 映射 POSIX 的 SEEK_CUR，用于 file_seek 等函数
     */
    # define fseek_pos_cur      ((int)SEEK_CUR)

    /**
     * @brief 文件定位起始位置（从文件末尾）
     * @note 映射 POSIX 的 SEEK_END，用于 file_seek 等函数
     */
    # define fseek_pos_end      ((int)SEEK_END)
#endif

/**
 * @brief 创建新文件（文件已存在则失败）
 */
filehandle_t file_create(const char *pathfile, int flags, int mode);

/**
 * @brief 打开已存在的文件用于只读访问（跨平台）
 */
filehandle_t file_open_read(const char *pathfile);

/**
 * @brief 创建新的空文件用于只写访问（文件已存在则失败，跨平台）
 */
filehandle_t file_write_new(const char *pathfile);

/**
 * @brief 关闭文件句柄并置为无效（避免悬空指针，跨平台）
 */
int file_close(filehandle_t *phf);

/**
 * @brief 调整文件读写指针位置（支持 64 位偏移，跨平台）
 */
sb8 file_seek(filehandle_t hf, sb8 distance, int fseekpos);

/**
 * @brief 获取文件大小（通过指针定位实现，跨平台）
 */
sb8 file_size(filehandle_t hf);

/**
 * @brief 从文件中读取指定字节数（支持部分读取，跨平台）
 */
int file_readbytes(filehandle_t hf, char *bytesbuf, ub4 sizebuf);

/**
 * @brief 向文件中写入指定字节数（支持部分写入，跨平台）
 * @see https://linux.die.net/man/2/write
 */
int file_writebytes(filehandle_t hf, const char *bytesbuf, ub4 bytestowrite);

/**
 * @brief 跨平台删除文件
 */
int file_remove(const char *pathfile);

/**
 * @brief 跨平台移动/重命名文件（或目录）
 */
int file_move(const char *pathfileOld, const char *pathfileNew);

/**
 * @brief 检查指定路径的文件或目录是否存在
 */
bool file_exists(const char *pathfile);

/**
 * @brief 检查指定路径是否是目录
 */
bool path_is_dir(const char *path);

/**
 * @brief 读取环境变量并在其值前拼接前缀，结果存入指定缓冲区（安全拼接，避免溢出）
 */
int getenv_with_prefix(const char *varName, const char *prefix, char *valBuf, size_t valBufSize);

/**
 * @brief 获取当前进程可执行文件的完整路径（跨平台）
 */
cstrbuf get_proc_pathfile(bool unixpath);

/**
 * @brief 获取当前进程可执行文件所在目录的绝对路径（跨平台）
 */
cstrbuf get_proc_abspath(bool unixpath);

/**
 * @brief 获取当前进程的工作目录（CWD，Current Working Directory）
 */
cstrbuf get_proc_cwd(bool unixpath);

/**
 * @brief 按优先级查找配置文件的路径（跨平台，支持多场景查找）
 */
cstrbuf find_config_file(const char *cfgpath, const char *cfgname, const char *envvarname, const char *etcconfpath);

/**
 * @brief 通过路径的前两个字符判断是否为绝对路径（跨平台）
 */
int path_is_abspath(char first, char second);

/**
 * @brief 从路径字符串中提取指定层级的目录和文件名部分
 */
const char* path_prefix_level(const char* fullpath, const char sepchars[], int* prefixlen, int* prefixlevel, const char** punctrated);

/**
 * @brief 将Windows格式路径转换为Unix风格路径
 */
const char* path_win_to_unix(char* pathbuf, size_t bufsize);

/**
 * @brief 将Unix风格路径转换为Windows格式路径
 */
const char* path_unix_to_win(char* pathbuf, size_t bufsize);

#if defined(__cplusplus)
}
#endif

#endif /* PATHLIB_H_ */
