/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file pathlib.c
 * @brief 跨平台文件路径操作API，适用于 macOS, Linux, Windows, Cygwin, MinGW 等环境
 *   提供统一的文件路径操作、文件系统访问和文件I/O接口，封装平台差异，简化跨平台开发。
 *   核心功能包括路径解析、文件/目录操作、文件信息和文件读写等。
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 anomura.cc All Rights Reserved.
 * @version 0.0.63
 *
 * @since 2019-09-30 12:37:44
 * @date 2025-12-06 22:02:59
 *
 * @note
 *   Windows 平台依赖 `<windows.h>` 等系统头文件，需确保链接 Windows SDK；
 *   类 Unix 平台依赖 POSIX 标准头文件，需确保编译器支持 POSIX 接口
 */
#include "pathlib.h"


/**
 * @brief 创建新文件（文件已存在则失败）
 * @param pathfile 目标文件的完整路径（如 "data/log.txt"，需符合当前平台路径格式）
 * @param flags 文件访问权限标志（需传入平台兼容值）：
 *              - Windows 平台：传入 Windows API 兼容的 `dwDesiredAccess` 值（如 `GENERIC_WRITE` `GENERIC_READ`）；
 *              - 类 Unix 平台：传入 POSIX `open` 兼容的标志（如 `O_WRONLY` `O_RDWR`）。
 * @param mode 文件创建模式/属性（需传入平台兼容值）：
 *             - Windows 平台：传入 Windows API 兼容的 `dwFlagsAndAttributes` 值（如 `FILE_ATTRIBUTE_NORMAL`）；
 *             - 类 Unix 平台：传入 POSIX 文件权限（如 `0644` 表示所有者读写、其他只读）。
 * @return filehandle_t
 *   - 成功：返回有效的文件句柄（可用于后续读写操作）；
 *   - 失败：返回 `filehandle_invalid`（需通过平台原生方式获取错误原因，如 Windows `GetLastError()`、类 Unix `errno`）。
 * @note 1. 核心行为：仅创建“不存在的新文件”，若文件已存在则直接失败（Windows 用 `CREATE_NEW`，类 Unix 用 `O_EXCL`）；
 * @note 2. 错误处理：调用者需通过 `filehandle_invalid` 判断失败，再调用平台原生接口获取错误详情；
 * @note 3. Windows 平台仅支持 ANSI 路径（`CreateFileA`），若需宽字符路径，需扩展为 `CreateFileW`。
 */
filehandle_t file_create(const char *pathfile, int flags, int mode)
{
#if defined(PLATFORM_WINDOWS)
    /*
     * CreateFileA 参数说明：
     * - lpFileName: 目标文件路径（ANSI）；
     * - dwDesiredAccess: 文件访问权限（由 flags 传入，如 GENERIC_WRITE）；
     * - dwShareMode: 共享模式（仅允许读共享，避免其他进程写冲突）；
     * - lpSecurityAttributes: 安全属性（默认 NULL，使用默认安全描述符）；
     * - dwCreationDisposition: 创建方式（CREATE_NEW：仅创建新文件，已存在则失败）；
     * - dwFlagsAndAttributes: 文件属性（由 mode 传入，如 FILE_ATTRIBUTE_NORMAL）；
     * - hTemplateFile: 模板文件（NULL，无模板）。
     */
    filehandle_t hf = CreateFileA(
        pathfile,
        (DWORD)(flags),          // 访问权限（强制转为 DWORD，需调用者传入合法值）
        FILE_SHARE_READ,         // 共享读，禁止共享写
        NULL,                    // 默认安全属性
        CREATE_NEW,              // 仅创建新文件，已存在则失败
        (DWORD)(mode),           // 文件属性（强制转为 DWORD，需调用者传入合法值）
        NULL                     // 无模板文件
    );
    return hf;
#else // Linux, macOS, Cygwin 等类 Unix 平台
    /*
     * open 参数说明：
     * - pathname: 目标文件路径；
     * - flags: 打开标志（叠加 O_CREAT（创建文件）、O_EXCL（仅新文件），需调用者传入读写标志如 O_WRONLY）；
     * - mode: 文件权限（仅 O_CREAT 时有效，如 0644，强制转为 mode_t）。
     */
    int fd = open(
        pathfile,
        flags | O_CREAT | O_EXCL,  // 叠加“创建”和“仅新文件”标志
        (mode_t)(mode)             // 文件权限（强制转为 mode_t，需调用者传入合法值）
    );
    return fd;  // 返回文件描述符（int 类型，对应 filehandle_t）
#endif
}

/**
 * @brief 打开已存在的文件用于只读访问（跨平台）
 * @param pathfile 待打开的文件路径（需为已存在的文件，非目录）
 * @return filehandle_t
 *   - 成功：返回有效的只读文件句柄（可用于后续 `file_readbytes`/`file_seek` 等操作）；
 *   - 失败：返回 `filehandle_invalid`（原因包括文件不存在、权限不足、路径为目录等）。
 * @note 1. 核心语义：仅打开“已存在”的文件，不存在则直接失败（Windows `OPEN_EXISTING` 标志）；
 * @note 2. 平台实现细节：
 *           - Windows：调用 `CreateFileA`，共享模式为 `FILE_SHARE_READ`（允许其他进程读），文件属性为 `FILE_ATTRIBUTE_NORMAL`；
 *           - 类 Unix（Linux/macOS/Cygwin）：调用 `open`，模式为 `O_RDONLY`（只读），原 `O_EXCL` 冗余（已建议删除），权限为“所有者/组/其他均只读”（S_IRUSR|S_IRGRP|S_IROTH）；
 * @note 3. 编译修正：Windows 分支中 `pathname` 需改为 `pathfile`（函数参数名），否则编译失败；
 * @note 4. 错误排查：失败原因需通过平台原生接口获取（Windows `GetLastError()`、类 Unix `errno`）。
 */
filehandle_t file_open_read(const char *pathfile)
{
#if defined(PLATFORM_WINDOWS)
    filehandle_t hf = CreateFileA(pathfile,
        GENERIC_READ,
        FILE_SHARE_READ,
        NULL,
        OPEN_EXISTING,
        FILE_ATTRIBUTE_NORMAL,
        NULL);
    return hf;
#else // Linux, macOS, Cygwin 等类 Unix 平台
    // 优化：删除 O_EXCL（只读模式下无意义，仅 O_CREAT 时有效）
    int fd = open(pathfile, O_RDONLY, S_IRUSR | S_IRGRP | S_IROTH);
    return fd;
#endif
}

/**
 * @brief 创建新的空文件用于只写访问（文件已存在则失败，跨平台）
 * @param pathfile 待创建的文件路径（若路径已存在文件，操作失败）
 * @return filehandle_t
 *   - 成功：返回有效的只写文件句柄（可用于后续 `file_writebytes`/`file_seek` 等操作）；
 *   - 失败：返回 `filehandle_invalid`（原因包括文件已存在、权限不足、路径非法等）。
 * @note 1. 核心语义：仅创建“不存在的新文件”，已存在则失败（继承 `file_create` 的 `CREATE_NEW`/`O_EXCL` 行为）；
 * @note 2. 依赖函数：完全依赖 `file_create` 实现，其失败行为（如路径非法、内存不足）会继承至此函数；
 * @note 3. 平台权限说明：
 *           - Windows：文件属性为 `FILE_ATTRIBUTE_NORMAL`（无特殊属性），访问权限为 `GENERIC_WRITE`（仅写）；
 *           - 类 Unix：文件权限为 `S_IRUSR|S_IWUSR|S_IRGRP|S_IROTH`（所有者读写，组/其他只读），打开模式为 `O_WRONLY`（仅写）；
 * @note 4. 错误排查：失败原因需通过平台原生接口获取（Windows `GetLastError()`、类 Unix `errno`）。
 */
filehandle_t file_write_new(const char *pathfile)
{
#if defined(PLATFORM_WINDOWS)
    // 调用 file_create，传入写权限和常规文件属性
    return file_create(pathfile, GENERIC_WRITE, FILE_ATTRIBUTE_NORMAL);
#else // Linux, macOS, Cygwin 等类 Unix 平台
    // 调用 file_create，传入只写模式和文件权限
    return file_create(pathfile, O_WRONLY, S_IRUSR|S_IWUSR|S_IRGRP|S_IROTH);
#endif
}

/**
 * @brief 关闭文件句柄并置为无效（避免悬空指针，跨平台）
 * @param phf 指向文件句柄的指针（需非 NULL，否则返回 -1）
 * @return int
 *   - 0：句柄关闭成功；
 *   - -1：失败（原因包括 phf 为 NULL、句柄已无效、系统调用错误）。
 * @note 1. 核心安全设计：关闭后自动将 `*phf` 设为 `filehandle_invalid`，防止调用者复用已关闭的句柄；
 * @note 2. 调用约束：
 *           - 必须传入“指向有效句柄的指针”（若 phf 为 NULL，直接返回 -1）；
 *           - 句柄已为 `filehandle_invalid` 时，无需重复关闭，直接返回 -1；
 * @note 3. 平台实现细节：
 *           - Windows：调用 `CloseHandle`，成功返回 TRUE 时返回 0；
 *           - 类 Unix：调用 `close`，返回 0 时表示成功，返回 -1 时表示系统调用错误；
 * @note 4. 错误排查：系统调用错误需通过平台原生接口获取（Windows `GetLastError()`、类 Unix `errno`）。
 */
int file_close(filehandle_t *phf)
{
    if (phf) {
        filehandle_t hf = *phf;
#if defined(PLATFORM_WINDOWS)
        if (hf != filehandle_invalid) {
            *phf = filehandle_invalid;
            if (CloseHandle(hf)) {
                return 0;
            }
        }
#else // Linux, macOS, Cygwin 等类 Unix 平台
        if (hf != filehandle_invalid) {
            *phf = filehandle_invalid;
            return close(hf);
        }
#endif
    }
    return (-1);
}

/**
 * @brief 调整文件读写指针位置（支持 64 位偏移，跨平台）
 * @param hf 有效的文件句柄（需通过 `file_open_read`/`file_write_new` 等函数获取）；
 * @param distance 偏移量（signed 64-bit，正数向前移，负数向后移，需确保不越界）；
 * @param fseekpos 偏移基准位置（必须传入预定义宏）：
 *                 - `fseek_pos_set`：以文件开头为基准；
 *                 - `fseek_pos_cur`：以当前指针位置为基准；
 *                 - `fseek_pos_end`：以文件末尾为基准；
 * @return sb8
 *   - 成功：返回调整后指针相对于“文件开头”的偏移量（sb8 为 signed 64-bit integer）；
 *   - 失败：返回 `-1`（原因包括句柄无效、偏移越界、系统调用错误）。
 * @note 1. 大文件支持：Windows 用 `SetFilePointerEx`，类 Unix 用 `lseek64`（Cygwin 用 `lseek`），均支持 >4GB 文件；
 * @note 2. 偏移越界：若 `distance` 导致指针超出文件范围（如从开头向前移），返回 `-1`；
 * @note 3. 错误排查：系统调用错误需通过平台原生接口获取（Windows `GetLastError()`、类 Unix `errno`）。
 */
sb8 file_seek(filehandle_t hf, sb8 distance, int fseekpos)
{
#if defined(PLATFORM_WINDOWS)
    LARGE_INTEGER li, l2;
    li.QuadPart = distance;
    if (SetFilePointerEx(hf, li, &l2, fseekpos)) {
        // 返回相对于文件开头的偏移量
        return (sb8)l2.QuadPart;
    }
    /* error */
    return (sb8)(-1);
#elif defined(PLATFORM_CYGWIN)
    /* Cygwin：用 lseek 支持大文件 */
    return (sb8) lseek(hf, (off_t)distance, fseekpos);
#else // Linux, macOS, Cygwin 等类 Unix 平台
    /* 其他类 Unix 平台：用 lseek64 支持大文件 */
    return (sb8) lseek64(hf, (off64_t)distance, fseekpos);
#endif
}

/**
 * @brief 获取文件大小（通过指针定位实现，跨平台）
 * @param hf 有效的文件句柄（需支持 `file_seek` 操作，如常规文件）
 * @return sb8
 *   - 成功：返回文件大小（字节数，sb8 为 signed 64-bit integer，等于文件末尾相对于开头的偏移量）；
 *   - 失败：返回 `-1`（原因包括句柄无效、`file_seek` 失败、恢复原位置失败）。
 * @note 1. 核心逻辑（三步操作，任一失败则整体失败）：
 *           1. 调用 `file_seek(hf, 0, fseek_pos_cur)` 记录当前指针位置（offset0）；
 *           2. 调用 `file_seek(hf, 0, fseek_pos_end)` 跳至文件末尾，获取偏移量（offset2，即文件大小）；
 *           3. 调用 `file_seek(hf, offset0, fseek_pos_set)` 恢复原指针位置；
 * @note 2. 不支持场景：管道、设备文件等无法通过 `file_seek` 定位的文件，返回 `-1`；
 * @note 3. 依赖函数：完全依赖 `file_seek` 实现，其错误原因（如偏移越界）可通过平台原生接口排查；
 * @note 4. 示例：若文件大小为 1024 字节，返回 1024；空文件返回 0。
 */
sb8 file_size(filehandle_t hf)
{
#if defined(PLATFORM_WINDOWS)
    // 记录当前指针位置（相对于文件开头）
    sb8 offset0 = file_seek(hf, 0, fseek_pos_cur);
    if (offset0 != -1) {
        // 跳至文件末尾，获取偏移量（即文件大小）
        sb8 offset2 = file_seek(hf, 0, fseek_pos_end);
        if (offset2 != -1) {
            // 恢复原指针位置，成功则返回文件大小
            if (file_seek(hf, offset0, fseek_pos_set) != -1) {
                return offset2;
            }
        }
    }
    /* error: -1 */
    return (sb8)(-1);
#else // Linux, macOS, Cygwin 等类 Unix 平台
    sb8 offset0 = file_seek(hf, 0, fseek_pos_cur);
    if (offset0 != -1) {
        // 跳至文件末尾获取大小
        sb8 offset2 = file_seek(hf, 0, fseek_pos_end);
        if (offset2 != -1) {
            // 恢复原位置
            if (file_seek(hf, offset0, fseek_pos_set) != -1) {
                return offset2;
            }
        }
    }
    // error: -1
    return -1;
#endif
}

/**
 * @brief 从文件中读取指定字节数（支持部分读取，跨平台）
 * @param hf 有效的只读/读写文件句柄（需通过 `file_open_read` 等函数获取）；
 * @param bytesbuf 存储读取数据的缓冲区（需非 NULL 且可写，大小 ≥ sizebuf）；
 * @param sizebuf 期望读取的字节数（ub4 为 unsigned 32-bit integer，若为 0，返回 0）；
 * @return int
 *   - ≥0：成功，返回实际读取的字节数（可能小于 sizebuf，如已到文件末尾）；
 *   - -1：失败（原因包括句柄无效、bytesbuf 为 NULL、系统调用错误）。
 * @note 1. 部分读取处理：若系统调用一次未读完（如内核缓冲区不足），会循环读取，直到读完 sizebuf 或到文件末尾；
 * @note 2. 调用约束：
 *           - 必须确保 `bytesbuf` 非 NULL 且大小 ≥ sizebuf，否则可能触发空指针解引用或缓冲区溢出；
 *           - `sizebuf == 0` 时，直接返回 0（无数据读取）；
 * @note 3. 平台实现细节：
 *           - Windows：调用 `ReadFile`，`cbread` 为单次读取字节数，失败时 `!ret`；
 *           - 类 Unix：调用 `read`，返回 `-1` 表示错误，返回 `0` 表示到文件末尾；
 * @note 4. 错误排查：系统调用错误需通过平台原生接口获取（Windows `GetLastError()`、类 Unix `errno`）。
 */
int file_readbytes(filehandle_t hf, char *bytesbuf, ub4 sizebuf)
{
#if defined(PLATFORM_WINDOWS)
    BOOL ret;
    DWORD cbread, cboffset = 0;

    while (cboffset != (DWORD)sizebuf) {
        ret = ReadFile(hf, (void *)(bytesbuf + cboffset), (DWORD)(sizebuf - cboffset), &cbread, NULL);
        if (!ret) {
            /* read on error: uses GetLastError() for more */
            return (-1);
        }
        if (cbread == 0) {
            /* reach to end of file */
            break;
        }
        cboffset += cbread;
    }
    /* success: actual read bytes */
    return (int)cboffset;
#else // Linux, macOS, Cygwin 等类 Unix 平台
    size_t cbread, cboffset = 0;
    while (cboffset != (size_t)sizebuf) {
        cbread = read(hf, (void *)(bytesbuf + cboffset), (size_t)(sizebuf - cboffset));
        if (cbread == -1) {
            /* read on error: uses strerror(errno) for more */
            return (-1);
        }
        if (cbread == 0) {
            /* reach to end of file */
            break;
        }
        cboffset += cbread;
    }
    /* success: actual read bytes */
    return (int)cboffset;
#endif
}

/**
 * @brief 向文件中写入指定字节数（支持部分写入，跨平台）
 * @param hf 有效的只写/读写文件句柄（需通过 `file_write_new` 等函数获取）；
 * @param bytesbuf 存储待写入数据的缓冲区（需非 NULL 且可读，大小 ≥ bytestowrite）；
 * @param bytestowrite 期望写入的字节数（ub4 为 unsigned 32-bit integer，若为 0，返回 0）；
 * @return int
 *   - 0：成功，所有字节均已写入；
 *   - -1：失败（原因包括句柄无效、bytesbuf 为 NULL、系统调用错误、磁盘空间不足）。
 * @note 1. 部分写入处理：若系统调用一次未写完（如内核缓冲区不足），会循环写入，直到写完 bytestowrite；
 * @note 2. 调用约束：
 *           - 必须确保 `bytesbuf` 非 NULL 且大小 ≥ bytestowrite，否则可能触发空指针解引用或读取越界；
 *           - `bytestowrite == 0` 时，直接返回 0（无数据写入）；
 * @note 3. 平台实现细节：
 *           - Windows：调用 `WriteFile`，`cbwritten` 为单次写入字节数，失败时 `!ret`；
 *           - 类 Unix：调用 `write`，返回 `-1` 表示错误，返回 `0` 时忽略（继续写入）；
 * @note 4. 特殊失败场景：磁盘空间不足时，写入会提前失败，返回 `-1`，需通过平台接口排查（如 Windows `ERROR_DISK_FULL`）。
 * @see https://linux.die.net/man/2/write
 */
int file_writebytes(filehandle_t hf, const char *bytesbuf, ub4 bytestowrite)
{
#if defined(PLATFORM_WINDOWS)
    BOOL ret;
    DWORD cbwritten, cboffset = 0;
    while (cboffset != (DWORD)bytestowrite) {
        ret = WriteFile(hf, (const void *)(bytesbuf + cboffset), (DWORD)(bytestowrite - cboffset), &cbwritten, NULL);
        if (!ret) {
            /* write on error */
            return (-1);
        }
        cboffset += cbwritten;
    }
    /* success */
    return 0;
#else // Linux, macOS, Cygwin 等类 Unix 平台
    ssize_t cbret;
    off_t woffset = 0;
    while (woffset != (off_t)bytestowrite) {
        cbret = write(hf, (const void *)(bytesbuf + woffset), bytestowrite - woffset);
        if (cbret == -1) {
            /* error */
            return (-1);
        }
        if (cbret > 0) {
            woffset += cbret;
        }
    }
    /* success */
    return 0;
#endif
}

/**
 * @brief 跨平台删除文件
 * @param pathfile 待删除的文件路径（需符合当前平台格式，不能是目录）
 * @return int
 *   - 0：删除成功；
 *   - -1：删除失败（原因包括文件不存在、权限不足、路径指向目录等）。
 * @note 1. 仅用于删除文件，删除目录需使用专门的目录删除函数（如 `pathdir_remove`）；
 * @note 2. 失败原因可通过平台原生接口获取：
 *           - Windows：调用 `GetLastError()` 获取错误码；
 *           - 类 Unix：检查全局变量 `errno`（如 `ENOENT` 表示文件不存在）。
 */
int file_remove(const char *pathfile)
{
#if defined(PLATFORM_WINDOWS)
    if (DeleteFileA(pathfile)) {
        return 0;
    }
    return (-1);
#else // Linux, macOS, Cygwin 等类 Unix 平台
    return remove(pathfile);
#endif
}

/**
 * @brief 跨平台移动/重命名文件（或目录）
 * @param pathfileOld 源路径（文件或目录的当前路径）
 * @param pathfileNew 目标路径（移动/重命名后的路径）
 * @return int
 *   - 0：移动/重命名成功；
 *   - -1：操作失败（原因包括源路径不存在、目标路径已存在、权限不足等）。
 * @note 1. 支持文件和目录的移动/重命名（跨目录移动需目标分区支持）；
 * @note 2. Windows 平台下，若目标文件已存在，`MoveFileA` 会失败（返回 -1）；
 * @note 3. 类 Unix 平台下，若目标文件已存在且为普通文件，会被覆盖（POSIX 规范）；
 * @note 4. 失败原因可通过平台原生接口获取：
 *           - Windows：调用 `GetLastError()` 获取错误码；
 *           - 类 Unix：检查全局变量 `errno`（如 `EXDEV` 表示跨分区移动不支持）。
 */
int file_move(const char *pathfileOld, const char *pathfileNew)
{
#if defined(PLATFORM_WINDOWS)
    BOOL bRet = MoveFileA(pathfileOld, pathfileNew);
    return bRet? 0 : -1;
#else // Linux, macOS, Cygwin 等类 Unix 平台
    return rename(pathfileOld, pathfileNew);
#endif
}

/**
 * @brief 检查指定路径的文件或目录是否存在（跨平台实现）
 * @param pathfile 待检查的路径（文件或目录的完整路径，可为 NULL）
 * @return bool
 *   - true：路径存在（可能是文件或目录）；
 *   - false：路径不存在，或输入为 NULL，或检查失败。
 * @note 1. 不区分“文件”和“目录”，只要路径存在即返回 true；
 * @note 2. 若需严格判断“是否为文件”或“是否为目录”，需使用专门的类型判断函数（如 `is_regular_file`）；
 * @note 3. 失败场景包括：权限不足（无法访问路径）、路径格式错误等，均返回 false；
 * @note 4. 平台实现细节：
 *           - Windows：通过 `FindFirstFileA` 实现，支持通配符路径（但不建议使用）；
 *           - 类 Unix：通过 `access(F_OK)` 实现，仅检查路径存在性，不依赖文件类型。
 */
bool file_exists(const char *pathfile)
{
#if defined(PLATFORM_WINDOWS)
    if (pathfile) {
        WIN32_FIND_DATAA FindFileData;
        HANDLE handle = FindFirstFileA(pathfile, &FindFileData);
        if (handle != INVALID_HANDLE_VALUE) {
            FindClose(handle);
            return true;
        }
    }
    return false;
#else // Linux, macOS, Cygwin 等类 Unix 平台
    if (pathfile && access(pathfile, F_OK) != -1) {
        return true;
    }
    return false;
#endif
}

/**
 * @brief 检查指定路径是否是目录
 */
bool path_is_dir(const char *path)
{
#if defined(PLATFORM_WINDOWS)
    DWORD attributes = GetFileAttributesA(path);
    if (attributes == INVALID_FILE_ATTRIBUTES) {
        return false;  // 路径不存在或无法访问
    }
    return (attributes & FILE_ATTRIBUTE_DIRECTORY) != 0;
#else // Linux, macOS, Cygwin 等类 Unix 平台
    struct stat path_stat;
    if (stat(path, &path_stat) != 0) {
        return false;  // 路径不存在或无法访问
    }
    return S_ISDIR(path_stat.st_mode);
#endif
}

/**
 * @brief 读取环境变量并在其值前拼接前缀，结果存入指定缓冲区（安全拼接，避免溢出）
 * @param varName 待读取的环境变量名（如 "APP_PATH"，非 NULL）；
 * @param prefix 需拼接在环境变量值前的前缀字符串（如 "/opt/"，非 NULL，可空字符串）；
 * @param valBuf 存储拼接结果的输出缓冲区（可为 NULL，此时仅判断环境变量是否存在及长度是否足够）；
 * @param valBufSize 输出缓冲区的大小（字节数，需 ≥1 以容纳终止符；若 valBuf 为 NULL，此参数无效）；
 * @return int
 *   - 返回 ≥0：成功（返回值为拼接后字符串的有效长度，不含终止符 `\0`）；
 *     - 特殊情况：若环境变量 `varName` 不存在，返回 0（无数据写入缓冲区）；
 *   - 返回 -1：失败（原因包括：valBuf 非 NULL 但 valBufSize < 1、缓冲区不足、valBuf 为 NULL 且环境变量存在）；
 *   - 返回 -2：参数非法（varName/prefix 为 NULL，或 valBuf 非 NULL 但 valBufSize 为 0）。
 * @note 1. 核心逻辑：环境变量存在时，拼接 "prefix + env_value" 存入 valBuf，自动添加终止符 `\0`；环境变量不存在时，缓冲区无写入（保持初始状态）。
 * @note 2. 长度计算规则：
 *           - prefix 长度：取其实际有效长度（不含终止符），若 prefix 为空字符串则长度为 0；
 *           - env_value 长度：取环境变量值的实际有效长度（不含终止符）；
 *           - 拼接后总长度 = prefix 长度 + env_value 长度，需满足 "总长度 + 1 ≤ valBufSize"（+1 为终止符），否则返回 -1。
 * @note 3. 安全保障：
 *           - 检查 varName/prefix 非 NULL，避免空指针访问；
 *           - 检查 valBuf 非 NULL 时 valBufSize ≥1，避免无效缓冲区；
 *           - 依赖 `vsnprintf_chkd` 确保拼接不溢出（需 `vsnprintf_chkd` 实现“不超过缓冲区大小且自动加终止符”）。
 * @note 4. 示例：
 *           - 若环境变量 "APP_PATH" 为 "bin"，prefix 为 "/opt/"，valBufSize=10：拼接结果为 "/opt/bin"，返回 7（有效长度）；
 *           - 若环境变量 "APP_PATH" 不存在：返回 0，valBuf 无修改。
 */
int getenv_with_prefix(const char *varName, const char *prefix, char *valBuf, size_t valBufSize)
{
    const char *env = getenv(varName);
    if (env) {
        int prelen = cstr_length(prefix, valBufSize);
        int envlen = cstr_length(env, valBufSize);
        if (prelen + envlen < (int)valBufSize) {
            return vsnprintf_chkd(valBuf, valBufSize, "%.*s%.*s", prelen, prefix, envlen, env);
        } else {
            /* buffer is not enough */
            return -1;
        }
    }
    /* env not found */
    return 0;
}

/**
 * @brief 获取当前进程可执行文件的完整路径（跨平台）
 * @unixpath 是否转为 unix 风格的路径：/c/var/log/app.exe
 * @return cstrbuf
 *   - 成功：返回包含可执行文件完整路径的 `cstrbuf`（如 Windows "C:\app\exe.exe"、Linux "/usr/bin/app"）；
 *   - 失败：直接调用 `abort()` 终止程序（无返回值）。
 * @note 1. 返回的 `cstrbuf` 需由调用者通过 `cstrbufFree(&buf)` 手动释放，避免内存泄漏；
 * @note 2. 失败场景（触发终止）：路径长度超过 `PATH_SIZE_MAX`（Windows 260 字节、类 Unix 4096 字节）、系统调用失败；
 * @note 3. 平台实现细节：
 *           - Windows：调用 `GetModuleFileNameA(0, ...)`，0 表示获取当前进程的可执行文件路径；
 *           - 类 Unix（Linux/macOS/Cygwin）：调用 `readlink("/proc/self/exe", ...)`，读取进程符号链接获取路径。
 */
cstrbuf get_proc_pathfile(bool unixpath)
{
    int r;
    char pathbuf[PATH_SIZE_MAX] = {0};

#if defined(PLATFORM_WINDOWS)
    r = (int) GetModuleFileNameA(0, pathbuf, (DWORD) PATH_SIZE_MAX);
    if (r < 1 || r >= PATH_SIZE_MAX) {
        fprintf(stderr, "(pathlib.h:%d) fatal error: GetModuleFileNameA\n", __LINE__);
        fflush(stderr);
        abort();
    }
#else // Linux, macOS, Cygwin 等类 Unix 平台
    r = readlink("/proc/self/exe", pathbuf, PATH_SIZE_MAX);
    if (r < 1 || r >= PATH_SIZE_MAX) {
        fprintf(stderr, "(pathlib.h:%d) fatal error: readlink\n", __LINE__);
        fflush(stderr);
        abort();
    }
#endif
    pathbuf[r] = '\0';

    if (unixpath) {
        path_win_to_unix(pathbuf, sizeof(pathbuf));
    }

    return cstrbufNew(0, pathbuf, r);
}

/**
 * @brief 获取当前进程可执行文件所在目录的绝对路径（跨平台）
 * @return cstrbuf
 *   - 成功：返回包含目录绝对路径的 `cstrbuf`（如 Windows "C:\app"、Linux "/usr/bin"）；
 *   - 失败：依赖 `get_proc_pathfile`，失败时直接终止程序（无返回值）。
 * @note 1. 返回的 `cstrbuf` 需由调用者通过 `cstrbufFree(&buf)` 手动释放；
 * @note 2. 路径截断规则：
 *           - 若路径中同时存在 `\`（Windows）和 `/`（类 Unix），取位置更靠后的分隔符截断；
 *           - 若路径无分隔符（如可执行文件在根目录），返回空字符串（需调用者处理）；
 * @note 3. 依赖 `get_proc_pathfile` 函数，其失败行为（终止程序）会继承至此函数；
 * @note 4. 示例：若 `get_proc_pathfile` 返回 "C:\app\test.exe"，此函数返回 "C:\app"。
 */
cstrbuf get_proc_abspath(bool unixpath)
{
    cstrbuf pathfile = get_proc_pathfile(unixpath);

    char *p = strrchr(pathfile->str, '\\');
    char *q = strrchr(pathfile->str, '/');
    if (p && q) {
        (p > q)? (*p = 0) : (*q = 0);
    } else if (p) {
        *p = 0;
    } else if (q) {
        *q = 0;
    }

    pathfile->len = (ub4)strnlen(pathfile->str, pathfile->len);
    return pathfile;
}

/**
 * @brief 获取当前进程的工作目录（CWD，Current Working Directory）
 * @unixpath 是否转为 unix 风格的路径：/c/var/log
 * @return cstrbuf
 *   - 成功：返回包含当前工作目录路径的 `cstrbuf`（如 Windows "C:\work"、Linux "/home/user/work"）；
 *   - 失败：返回 0（原因包括路径长度超过 1024 字节、内存分配失败、系统调用错误）。
 * @note 1. 成功时，返回的 `cstrbuf` 需由调用者通过 `cstrbufFree(&buf)` 手动释放；
 * @note 2. 路径长度限制：内部缓冲区大小为 1024 字节，超过此长度会返回 0（需扩展缓冲区需修改源码）；
 * @note 3. 平台实现细节：
 *           - Windows：依赖 `<direct.h>` 的 `_getcwd` 函数，需确保头文件已包含；
 *           - 类 Unix（Linux/macOS/Cygwin）：依赖 `<unistd.h>` 的 `getcwd` 函数；
 * @note 4. 示例：若进程在 "/home/user/project" 中运行，返回此路径字符串。
 */
cstrbuf get_proc_cwd(bool unixpath)
{
    cstrbuf newcsb = NULL;
    char* cwd = 0;
    char cwdbuf[PATH_SIZE_MAX];

#if defined(_INC_DIRECT)
    // direct.h on windows
    cwd = _getcwd(cwdbuf, sizeof(cwdbuf));
#else
    // <unistd.h> on Linux/macOS
    cwd = getcwd(cwdbuf, sizeof(cwdbuf));
#endif
    if (cwd) {
        if (unixpath) {
            const char* psz = path_win_to_unix(cwdbuf, sizeof(cwdbuf));
            newcsb = cstrbufNew(0, psz, cstrbuf_error_size);
        }
        else {
            newcsb = cstrbufNew(0, cwd, cstrbuf_error_size);
        }
    }

    // if null: path is too long or out of memory
    return newcsb;
}

/**
 * @brief 按优先级查找配置文件的路径（跨平台，支持多场景查找）
 * @param cfgpath 优先查找的配置文件路径（可为 NULL，若为目录则自动拼接文件名）；
 * @param cfgname 配置文件名（必填，如 "clogger.cfg"）；
 * @param envvarname 存储配置路径的环境变量名（可为 NULL，如 "CLOGGER_CFG_DIR"）；
 * @param etcconfpath 系统级配置目录（可为 NULL，如 "/etc/app"）；
 * @return cstrbuf
 *   - 成功：返回拼接后的配置文件路径（`cstrbuf` 类型，可能不存在，需调用者验证）；
 *   - 失败：返回 0（仅当所有查找场景均失败且内存分配错误时）。
 * @note 1. 返回的 `cstrbuf` 需由调用者通过 `cstrbufFree(&buf)` 手动释放；
 * @note 2. 查找优先级（从高到低）：
 *           1. 若 `cfgpath` 非 NULL：若为完整路径则直接返回，若为目录则拼接 `cfgname`；
 *           2. 进程可执行文件所在目录（调用 `get_proc_abspath`）+ `cfgname`；
 *           3. 进程目录下的 "conf" 子目录 + `cfgname`；
 *           4. 进程目录的上级目录下 "conf" 子目录 + `cfgname`；
 *           5. 若 `envvarname` 非 NULL：读取环境变量值，拼接 `cfgname`（若为目录）；
 *           6. 若 `etcconfpath` 非 NULL：系统级目录 + `cfgname`；
 * @note 3. 路径拼接规则：自动处理目录末尾是否有路径分隔符（`PATH_SEP_CHR`），避免重复或缺失；
 * @note 4. 关键依赖：
 *           - `get_proc_abspath`：获取进程目录；
 *           - `file_exists`：判断路径是否存在；
 *           - `cstrbufCat/cstrbufConcat`：路径拼接；
 * @note 5. 重要提示：返回的路径仅为“可能的配置路径”，其是否存在需调用者通过 `file_exists` 二次验证。
 */
cstrbuf find_config_file(const char *cfgpath, const char *cfgname, const char *envvarname, const char *etcconfpath)
{
    cstrbuf config = 0;
    cstrbuf dname = 0;
    cstrbuf tname = 0;
    cstrbuf pname = 0;

    tname = cstrbufCat(0, "/%s", cfgname);
    pname = cstrbufCat(0, "%c%s", PATH_SEP_CHR, cfgname);

    if (cfgpath) {
        int pathlen = cstr_length(cfgpath, -1);
        if (cstr_endswith(cfgpath, pathlen, pname->str, (int)pname->len) ||
            cstr_endswith(cfgpath, pathlen, tname->str, (int)tname->len)) {
            config = cstrbufNew(0, cfgpath, pathlen);
        } else {
            char endchr = cfgpath[pathlen - 1];
            if (endchr == PATH_SEP_CHR || endchr == '/') {
                config = cstrbufCat(0, "%.*s%.*s", pathlen, cfgpath, (int)pname->len - 1, cfgname);
            } else {
                config = cstrbufCat(0, "%.*s%c%.*s", pathlen, cfgpath, PATH_SEP_CHR, (int)pname->len - 1, cfgname);
            }
        }
        goto finish_up;
    } else {
        char *p;
        dname = get_proc_abspath(0);

        // 1: "$(appbin_dir)/clogger.cfg"
        config = cstrbufConcat(dname, pname, 0);
        if (file_exists(config->str)) {
            goto finish_up;
        }
        cstrbufFree(&config);

        // 2: "$(appbin_dir)/conf/clogger.cfg"
        config = cstrbufCat(0, "%.*s%cconf%.*s", cstrbufGetLen(dname), cstrbufGetStr(dname), PATH_SEP_CHR, cstrbufGetLen(pname), cstrbufGetStr(pname));
        if (file_exists(config->str)) {
            goto finish_up;
        }

        // 3: "$appbindir/../conf/clogger.cfg"
        cstrbufTrunc(config, dname->len);
        p = strrchr(config->str, PATH_SEP_CHR);
        if (p) {
            cstrbufTrunc(config, (ub4)(p - config->str));
            config = cstrbufCat(config, "%cconf%.*s", PATH_SEP_CHR, cstrbufGetLen(pname), cstrbufGetStr(pname));
            if (file_exists(config->str)) {
                goto finish_up;
            }
        }
        cstrbufFree(&config);

        if (envvarname) {
            // 4: $CLOGGER_CFG_DIR=/path/to
            p = getenv(envvarname);
            if (p) {
                config = cstrbufCat(0, "%s%.*s", p, cstrbufGetLen(pname), cstrbufGetStr(pname));
                if (file_exists(config->str)) {
                    goto finish_up;
                }
                cstrbufFree(&config);
            }
        }

        if (etcconfpath) {
            config = cstrbufCat(0, "%s%.*s", etcconfpath, cstrbufGetLen(pname), cstrbufGetStr(pname));
            if (file_exists(config->str)) {
                goto finish_up;
            }
            cstrbufFree(&config);
        }
    }

finish_up:
    cstrbufFree(&tname);
    cstrbufFree(&pname);
    cstrbufFree(&dname);

    /* dont need to know whether config exists or not at all */
    return config;
}

/**
 * @brief 通过路径的前两个字符判断是否为绝对路径（跨平台）
 * @param first 路径字符串的第一个字符（如 path[0]）；
 * @param second 路径字符串的第二个字符（如 path[1]，路径长度为 1 时传入 '\0'）；
 * @return int
 *   - 1：路径为绝对路径；
 *   - 0：路径为相对路径。
 * @note 1. 判断规则（满足任一即为绝对路径）：
 *           - 类 Unix 平台：first 为 '/'（如 "/home"、"/c"（MinGW））；
 *           - Windows 平台：second 为 ':'（如 "C:\temp"、"D:file.txt"）；
 * @note 2. 相对路径判断（返回 0）：
 *           - first 为 '.'（如 "./doc"、"../conf"）；
 *           - 不满足上述绝对路径规则的路径（如 "data"、"app/config"）；
 * @note 3. 示例：
 *           - 绝对路径：first='/', second='h' → 1；first='C', second=':' → 1；
 *           - 相对路径：first='.', second='/' → 0；first='d', second='a' → 0；
 * @note 4. 调用者需确保：路径字符串非空（至少传入 first 字符），避免空指针访问。
 */
int path_is_abspath(char first, char second)
{
    // relative path
    // ./
    // ../
    if (first == '.') {
        return 0;
    }

    // absolute path
    //   linux: /home/...
    //   mingw: /c/...
    //   cygwin: /cygdrive/c/...
    if (first == '/') {
        return 1;
    }

    // absolute path for windows
    //   windows: C:\temp\...
    if (second == ':') {
        return 1;
    }

    // relative path
    return 0;
}

/**
 * @brief 从路径字符串中提取指定层级的目录和文件名部分
 *
 * 此函数从完整文件路径中提取指定层级数的路径部分。可以控制提取的最大长度和目录层级，
 * 并指示是否需要添加省略号前缀。
 *
 * @param[in] fullpath 完整文件路径字符串，不可为NULL
 * @param[in] sepchars 路径分隔符字符串（如"/\\"），不可为NULL或空字符串
 * @param[in,out] prefixlen 输入时为最大允许提取长度，输出时为实际提取长度
 * @param[in,out] prefixlevel 输入时为最大目录回溯层级，输出时为实际回溯层级
 * @param[out] punctrated 输出时指示是否需要添加省略号("...")
 * @return 指向路径中提取部分的指针（位于原路径字符串内），失败返回NULL
 *
 * @note 提取规则：
 * - level=0: 纯文件名部分（如"test.c"）
 * - level=1: 文件名及直接父目录（如"...\\src\\test.c"）
 * - level=N: 向上回溯N级目录
 * - 当回溯层级超过路径实际层级时，返回完整路径
 * - 当提取的部分不是从路径开头开始时，punctrated会指示需要添加省略号
 *
 * @code
 * static const char seps[] = "/\\";
 * const char* fullpath = "C:\\WORKSPACE\\VULKAN_DEV\\test_c\\src\\test.c";
 *
 * for (int level = 0; level < 7; level++) {
 *     int prefixlevel = level;
 *     int prefixlen = 64;
 *     const char* punctrated;
 *
 *     const char* prefix = path_prefix_level(fullpath, seps, &prefixlen, &prefixlevel, &punctrated);
 *
 *     printf("(level=%2d, len=%2d) '%s%.*s'\n", prefixlevel, prefixlen, punctrated, prefixlen, prefix);
 * }
 * @endcode
 *
 * 输出示例：
 * (level= 0, len= 6) 'test.c'
 * (level= 1, len=11) '...\src\test.c'
 * (level= 2, len=18) '...\test_c\src\test.c'
 * (level= 3, len=29) '...\VULKAN_DEV\test_c\src\test.c'
 * (level= 4, len=39) '...\WORKSPACE\VULKAN_DEV\test_c\src\test.c'
 * (level= 4, len=41) 'C:\WORKSPACE\VULKAN_DEV\test_c\src\test.c'
 * (level= 4, len=41) 'C:\WORKSPACE\VULKAN_DEV\test_c\src\test.c'
 */
const char* path_prefix_level(const char* fullpath, const char sepchars[],
    int* prefixlen, int* prefixlevel, const char** punctrated)
{
    static const char has_ellipsis[] = "...";
    static const char no_ellipsis[] = "";

    if (punctrated) {
        *punctrated = no_ellipsis;
    }

    if (!fullpath || !sepchars) {
        if (prefixlen) {
            *prefixlen = 0;
        }
        if (prefixlevel) {
            *prefixlevel = 0;
        }
        return NULL;
    }

    const char* end = &fullpath[strlen(fullpath)];
    if (fullpath == end) {
        if (prefixlen) {
            *prefixlen = 0;
        }
        if (prefixlevel) {
            *prefixlevel = 0;
        }
        return fullpath; // 空路径
    }

    const char* endseps = sepchars;
    while (*endseps) {
        endseps++;
    }

    int level_chkd = prefixlevel? *prefixlevel : 0;

    const char* prefix = NULL;
    const char* p = end;
    int level = 0;
    while (p-- > fullpath) {
        int foundsep = 0;
        for (const char* sep = sepchars; sep != endseps; ++sep) {
            if (*p == *sep) {
                foundsep = 1;
                break;
            }
        }
        if (foundsep) {
            if (!prefix) {
                prefix = p;
                level = 0;
            }
            else {
                prefix = p;
                level++;
            }
        }
        if (prefix) {
            if (prefixlen && end - prefix >= *prefixlen) {
                if (prefix == fullpath) {
                    prefix = NULL;
                }
                break; // 达到最大长度
            }
            if (level >= level_chkd) {
                if (prefix == fullpath) {
                    prefix = NULL;
                }
                break; // 达到最大目录层
            }
        }
        if (p == fullpath) {
            prefix = NULL;
            break; // 到达路径起点
        }
    }

    if (!prefix) {
        prefix = fullpath;
    }
    else if (level == 0) {
        int foundsep = 0;
        for (const char* sep = sepchars; sep != endseps; ++sep) {
            if (*p == *sep) {
                foundsep = 1;
                break;
            }
        }
        if (foundsep) {
            prefix++;
        }
    }
    else if (punctrated) {
        *punctrated = has_ellipsis;
    }

    if (prefixlen) {
        *prefixlen = (int)(end - prefix);
    }
    if (prefixlevel) {
        *prefixlevel = level;
    }
    return prefix;
}

/**
 * @brief 将Windows格式路径转换为Unix风格路径
 *
 * 此函数将Windows风格的路径字符串就地转换为Unix风格路径。转换包括：
 * - 将盘符格式从 "C:" 转换为 "/c"
 * - 将反斜杠分隔符 '\' 转换为正斜杠 '/'
 *
 * @param[in,out] pathbuf 待转换的路径字符串缓冲区（必须以null结尾）
 * @param[in] bufsize 缓冲区大小（必须大于字符串长度）
 * @return 转换后的路径指针，失败返回NULL
 *
 * @note 转换规则：
 * - 盘符转换: "C:\path\to" -> "/c/path/to"
 * - 分隔符转换: '\' -> '/'
 * - 空字符串或无效输入返回原值或NULL
 *
 * @code
 * char path[256] = "C:\\WORKSPACE\\test.c";
 * const char* result = path_win_to_unix(path, sizeof(path));
 * // 结果: "/c/WORKSPACE/test.c"
 * @endcode
 */
const char* path_win_to_unix(char* pathbuf, size_t bufsize)
{
    if (!pathbuf || bufsize == -1) {
        return NULL; // 空值检验
    }
    size_t len = strnlen(pathbuf, bufsize);
    if (len == bufsize) {
        return NULL; // pathbuf 不是 null-ended
    }

    if (len == 0) {
        return pathbuf; // pathbuf 是空字符串
    }
    if (len == 1) {
        if (pathbuf[0] == '\\') {
            pathbuf[0] = '/';
        }
        return pathbuf;
    }
    // len >= 2
    char d = pathbuf[0];
    if (pathbuf[1] == ':') {
        if (d >= 'C' && d <= 'Z') {
            d += 'a' - 'A';
        }
        if (d >= 'c' && d <= 'z') {
            // d 是驱动器盘符开始
            pathbuf[0] = '/';
            pathbuf[1] = d;
        }
    }
    // 替换分隔符
    for (char* p = pathbuf; *p != '\0'; p++) {
        if (*p == '\\') {
            *p = '/';
        }
    }
    return pathbuf; // 转换成功
}

/**
 * @brief 将Unix风格路径转换为Windows格式路径
 *
 * 此函数将Unix风格的路径字符串就地转换为Windows格式路径。转换包括：
 * - 将盘符格式从 "/c" 转换为 "C:"
 * - 将正斜杠分隔符 '/' 转换为反斜杠 '\'
 *
 * @param[in,out] pathbuf 待转换的路径字符串缓冲区（必须以null结尾）
 * @param[in] bufsize 缓冲区大小（必须大于字符串长度）
 * @return 转换后的路径指针，失败返回NULL
 *
 * @note 转换规则：
 * - 盘符转换: "/c/path" -> "C:\path"
 * - 分隔符转换: '/' -> '\'
 * - 空字符串或无效输入返回原值或NULL
 *
 * @code
 * char path[256] = "/c/WORKSPACE/test.c";
 * const char* result = path_unix_to_win(path, sizeof(path));
 * // 结果: "C:\WORKSPACE\test.c"
 * @endcode
 */
const char* path_unix_to_win(char* pathbuf, size_t bufsize)
{
    if (!pathbuf || bufsize == -1) {
        return NULL; // 空值检验
    }
    size_t len = strnlen(pathbuf, bufsize);
    if (len == bufsize) {
        return NULL; // pathbuf 不是 null-ended
    }
    if (len == 0) {
        return pathbuf; // pathbuf 是空字符串
    }
    if (len > 2) { // 至少 3个字符: /c/ => C:
        char d = pathbuf[1];
        if (pathbuf[0] == '/' && pathbuf[2] == '/') {
            if (d >= 'c' && d <= 'z') {
                d += 'A' - 'a';
            }
            if (d >= 'C' && d <= 'Z') {
                pathbuf[0] = d;
                pathbuf[1] = ':';
            }
        }
    }
    // 替换分隔符
    for (char* p = pathbuf; *p != '\0'; p++) {
        if (*p == '/') {
            *p = '\\';
        }
    }
    return pathbuf; // 转换成功
}
