/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file randctx.c
 * @brief ISAAC 随机数生成器实现 (32/64位)
 *
 * 实现特性：
 *   1. 加密级伪随机数生成器 (ISAAC 算法)
 *   2. 范围受限的随机数生成
 *   3. 二进制与格雷码互转
 *   4. 快速跳跃的 LCG 生成器
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 anomura.cc All Rights Reserved.
 * @version 1.0.21
 * @since 2015-01-19 12:37:44
 * @date 2025-12-06 22:02:59
 */
#include "randctx.h"

#include <assert.h>


// ======================== 32位 ISAAC 实现 ========================

/**
 * RAND32_LCG LCG
 */
#define RAND32_LCG_A 1103515245UL
#define RAND32_LCG_C 12345UL
#define RAND32_LCG_M 0x7FFFFFFFUL  // 2^31 - 1 (31-bit)

#define isaac_golden_ratio32  0x9e3779b9

// 状态数组索引宏
#define ind32(mm,x)  (*(uint32_t *)((unsigned char *)(mm) + ((x) & ((RANDSIZ-1)<<2))))

// ISAAC 核心步骤
#define rngstep32(mix,a,b,mm,m,m2,r,x) do { \
        x = *m;  \
        a = (a^(mix)) + *(m2++); \
        *(m++) = y = ind32(mm,x) + a + b; \
        *(r++) = b = ind32(mm,y>>RANDSIZL) + x; \
    } while(0)

// 混合函数
#define mix32(a,b,c,d,e,f,g,h) do { \
        a^=b<<11; d+=a; b+=c; \
        b^=c>>2;  e+=b; c+=d; \
        c^=d<<8;  f+=c; d+=e; \
        d^=e>>16; g+=d; e+=f; \
        e^=f<<10; h+=e; f+=g; \
        f^=g>>4;  a+=f; g+=h; \
        g^=h<<8;  b+=g; h+=a; \
        h^=a>>9;  c+=h; a+=b; \
    } while(0)

/**
 * @brief ISAAC 算法核心 (32位)
 * @param ctx 随机数上下文
 */
static void isaac32(randctx32_t * ctx)
{
    register uint32_t a, b, x, y, * m, * mm, * m2, * r, * mend;
    mm = ctx->mm;
    r = ctx->seed;
    a = ctx->aa;
    b = ctx->bb + (++ctx->cc);

    for (m = mm, mend = m2 = m + (RANDSIZ / 2); m < mend; ) {
        rngstep32(a << 13, a, b, mm, m, m2, r, x);
        rngstep32(a >> 6, a, b, mm, m, m2, r, x);
        rngstep32(a << 2, a, b, mm, m, m2, r, x);
        rngstep32(a >> 16, a, b, mm, m, m2, r, x);
    }

    for (m2 = mm; m2 < mend; ) {
        rngstep32(a << 13, a, b, mm, m, m2, r, x);
        rngstep32(a >> 6, a, b, mm, m, m2, r, x);
        rngstep32(a << 2, a, b, mm, m, m2, r, x);
        rngstep32(a >> 16, a, b, mm, m, m2, r, x);
    }

    ctx->bb = b;
    ctx->aa = a;
}


void randctx_init(randctx32_t *ctx, uint32_t seed)
{
    int i;
    uint32_t a, b, c, d, e, f, g, h;
    uint32_t *m, *r;
    ctx->aa = ctx->bb = ctx->cc = 0;
    m = ctx->mm;
    r = ctx->seed;
    a = b = c = d = e = f = g = h = isaac_golden_ratio32; /* the golden ratio */

    /* init seed */
    for (i=0; i<256; ++i) {
        r[i] = seed;
    }

    for (i=0; i<4; ++i) {                                 /* scramble it */
        mix32(a,b,c,d,e,f,g,h);
    }

    /* initialize using the contents of r[] as the seed */
    for (i=0; i<RANDSIZ; i+=8) {
        a+=r[i  ]; b+=r[i+1]; c+=r[i+2]; d+=r[i+3];
        e+=r[i+4]; f+=r[i+5]; g+=r[i+6]; h+=r[i+7];
        mix32(a,b,c,d,e,f,g,h);
        m[i  ]=a; m[i+1]=b; m[i+2]=c; m[i+3]=d;
        m[i+4]=e; m[i+5]=f; m[i+6]=g; m[i+7]=h;
    }

    /* do a second pass to make all of the seed affect all of m */
    for (i=0; i<RANDSIZ; i+=8) {
        a+=m[i  ]; b+=m[i+1]; c+=m[i+2]; d+=m[i+3];
        e+=m[i+4]; f+=m[i+5]; g+=m[i+6]; h+=m[i+7];
        mix32(a,b,c,d,e,f,g,h);
        m[i  ]=a; m[i+1]=b; m[i+2]=c; m[i+3]=d;
        m[i+4]=e; m[i+5]=f; m[i+6]=g; m[i+7]=h;
    }

    isaac32(ctx);              /* fill in the first set of results */
    ctx->randcnt = RANDSIZ;  /* prepare to use the first set of results */
}


/**
 * @brief 生成32位随机数
 * @param r 上下文指针
 * @return 32位随机数
 */
uint32_t rand_gen(randctx32_t* r)
{
    if (!(r)->randcnt--) {
        isaac32(r);
        (r)->randcnt = RANDSIZ - 1;
    }
    return (r)->seed[(r)->randcnt];
}

/**
 * @brief 生成范围受限的32位随机数
 * @param r 上下文指针
 * @param rmin 最小值
 * @param rmax 最大值
 * @return [rmin, rmax] 范围内的随机数
 */
uint32_t rand_gen_int(randctx32_t* r, uint32_t rmin, uint32_t rmax)
{
    if (rmax < rmin) return rmin;  // 处理无效范围

    uint32_t range = rmax - rmin + 1;
    uint32_t limit = (0xFFFFFFFF / range) * range;
    uint32_t ret;

    // 使用拒绝采样消除取模偏差
    do {
        ret = rand_gen(r);
    } while (ret >= limit);

    return rmin + (ret % range);
}


// ======================== 64位 ISAAC 实现 ========================

#define isaac_golden_ratio64  0x9e3779b97f4a7c13ULL

#define ind64(mm,x)  (*(uint64_t *)((unsigned char *)(mm) + ((x) & ((RANDSIZ-1)<<3))))

#define rngstep64(mix,a,b,mm,m,m2,r,x) do { \
        x = *m;  \
        a = (mix) + *(m2++); \
        *(m++) = y = ind64(mm,x) + a + b; \
        *(r++) = b = ind64(mm,y>>RANDSIZL) + x; \
    } while(0)


#define mix64(a,b,c,d,e,f,g,h) do { \
        a-=e; f^=h>>9;  h+=a; \
        b-=f; g^=a<<9;  a+=b; \
        c-=g; h^=b>>23; b+=c; \
        d-=h; a^=c<<15; c+=d; \
        e-=a; b^=d>>14; d+=e; \
        f-=b; c^=e<<20; e+=f; \
        g-=c; d^=f>>17; f+=g; \
        h-=d; e^=g<<14; g+=h; \
    } while(0)

static void isaac64(randctx64_t *ctx)
{
    register uint64_t a,b,x,y,*m,*mm,*m2,*r,*mend;
    mm = ctx->mm;
    r = ctx->seed;
    a = ctx->aa;
    b = ctx->bb + (++ctx->cc);

    for (m = mm, mend = m2 = m+(RANDSIZ/2); m<mend; ) {
        rngstep64(~(a^(a<<21)), a, b, mm, m, m2, r, x);
        rngstep64(  a^(a>>5)  , a, b, mm, m, m2, r, x);
        rngstep64(  a^(a<<12) , a, b, mm, m, m2, r, x);
        rngstep64(  a^(a>>33) , a, b, mm, m, m2, r, x);
    }

    for (m2 = mm; m2<mend; ) {
        rngstep64(~(a^(a<<21)), a, b, mm, m, m2, r, x);
        rngstep64(  a^(a>>5)  , a, b, mm, m, m2, r, x);
        rngstep64(  a^(a<<12) , a, b, mm, m, m2, r, x);
        rngstep64(  a^(a>>33) , a, b, mm, m, m2, r, x);
    }
    ctx->bb = b;
    ctx->aa = a;
}

void randctx64_init(randctx64_t *ctx, uint64_t seed)
{
    int i;
    uint64_t a,b,c,d,e,f,g,h;
    uint64_t *mm, *r;
    ctx->aa = ctx->bb = ctx->cc = (uint64_t) 0;

    a=b=c=d=e=f=g=h= isaac_golden_ratio64;  /* the golden ratio */

    mm = ctx->mm;
    r = ctx->seed;

    /* init seed */
    for (i=0; i<256; ++i) {
        r[i] = seed;
    }

    for (i=0; i<4; ++i) {                   /* scramble it */
        mix64(a,b,c,d,e,f,g,h);
    }

    for (i=0; i<RANDSIZ; i+=8) {  /* fill in mm[] with messy stuff */
        if (1) {               /* use all the information in the seed */
            a+=r[i  ]; b+=r[i+1]; c+=r[i+2]; d+=r[i+3];
            e+=r[i+4]; f+=r[i+5]; g+=r[i+6]; h+=r[i+7];
        }
        mix64(a,b,c,d,e,f,g,h);
        mm[i  ]=a; mm[i+1]=b; mm[i+2]=c; mm[i+3]=d;
        mm[i+4]=e; mm[i+5]=f; mm[i+6]=g; mm[i+7]=h;
    }

    if (1) {
        /* do a second pass to make all of the seed affect all of mm */
        for (i=0; i<RANDSIZ; i+=8) {
            a+=mm[i  ]; b+=mm[i+1]; c+=mm[i+2]; d+=mm[i+3];
            e+=mm[i+4]; f+=mm[i+5]; g+=mm[i+6]; h+=mm[i+7];
            mix64(a,b,c,d,e,f,g,h);
            mm[i  ]=a; mm[i+1]=b; mm[i+2]=c; mm[i+3]=d;
            mm[i+4]=e; mm[i+5]=f; mm[i+6]=g; mm[i+7]=h;
        }
    }

    isaac64(ctx);             /* fill in the first set of results */
    ctx->randcnt = RANDSIZ;   /* prepare to use the first set of results */
}


/**
 * @brief 生成64位随机数 (优化可读性)
 */
uint64_t rand64_gen(randctx64_t* r)
{
    if (!(r)->randcnt--) {
        isaac64(r);
        (r)->randcnt = RANDSIZ - 1;
    }
    return (r)->seed[(r)->randcnt];
}


/**
 * @brief 生成范围受限的64位随机数 (修复取模偏差)
 */
uint64_t rand64_gen_int(randctx64_t* r, uint64_t rmin, uint64_t rmax)
{
    if (rmax < rmin) return rmin;

    uint64_t range = rmax - rmin + 1;
    uint64_t limit = (0xFFFFFFFFFFFFFFFFULL / range) * range;
    uint64_t ret;

    do {
        ret = rand64_gen(r);
    } while (ret >= limit);

    return rmin + (ret % range);
}


// ======================== 格雷码转换 ========================

/**
 * @brief 32位二进制转格雷码
 * @param x 二进制值
 * @return 格雷码
 */
uint32_t binary2graycode(uint32_t x) {
    return x ^ (x >> 1);
}

/**
 * @brief 32位格雷码转二进制
 * @param x 格雷码值
 * @return 二进制值
 */
uint32_t graycode2binary(uint32_t x) {
    x ^= x >> 16;
    x ^= x >> 8;
    x ^= x >> 4;
    x ^= x >> 2;
    x ^= x >> 1;
    return x;
}

/**
 * @brief 64位二进制转格雷码
 * @param x 二进制值
 * @return 格雷码
 */
uint64_t binary2graycode64(uint64_t x) {
    return x ^ (x >> 1);
}

/**
 * @brief 64位格雷码转二进制
 * @param g 格雷码值
 * @return 二进制值
 */
uint64_t graycode2binary64(uint64_t g) {
    g ^= g >> 32;
    g ^= g >> 16;
    g ^= g >> 8;
    g ^= g >> 4;
    g ^= g >> 2;
    g ^= g >> 1;
    return g;
}

// ======================== LCG 实现 ========================

/**
 * @brief 生成经过多次迭代的 LCG 随机数（安全版）
 * @param seed  初始种子（需在 [0, LCG_M-1] 范围内）
 * @param loops 迭代次数（必须 >= 0）
 * @return 迭代后的随机数（范围 [0, LCG_M-1]）
 */
uint32_t random_uint32_safe(uint32_t seed, unsigned loops)
{
    // 显式检查 loops 为 0 的情况
    if (loops == 0) {
        return seed % RAND32_LCG_M;
    }
    // 使用 64 位运算防止溢出
    for (unsigned i = 0; i < loops; i++) {
        seed = (uint32_t)(((uint64_t)RAND32_LCG_A * seed + RAND32_LCG_C) % RAND32_LCG_M);
    }
    return seed;
}

/**
 * @brief 生成经过多次迭代的 LCG 随机数（快速跳跃版）
 * @param seed  初始种子（需在 [0, LCG_M-1] 范围内）
 * @param loops 迭代次数（必须 >= 0）
 * @return 迭代后的随机数（范围 [0, LCG_M-1]）
 */
uint32_t random_uint32_fast(uint32_t seed, unsigned loops)
{
    // 显式检查 loops 为 0 的情况
    if (loops == 0) {
        return seed % RAND32_LCG_M;
    }

    // 快速幂算法计算 a^loops mod m
    uint64_t a = RAND32_LCG_A;
    uint64_t c = RAND32_LCG_C;
    uint64_t m = RAND32_LCG_M;
    uint64_t a_pow = 1;    // a^loops mod m
    uint64_t c_sum = 0;    // c * (a^(loops-1) + ... + a^0) mod m
    uint64_t curr_a = a;
    uint64_t curr_c = 1;   // 跟踪等比数列系数

    unsigned n = loops;
    while (n > 0) {
        if (n % 2 == 1) {
            a_pow = (a_pow * curr_a) % m;
            c_sum = (c_sum * curr_a + curr_c) % m;
        }
        curr_c = (curr_c * (curr_a + 1)) % m; // 等比数列和递推
        curr_a = (curr_a * curr_a) % m;
        n /= 2;
    }

    // 最终结果: (a^loops * seed + c * c_sum) mod m
    uint64_t result = (a_pow * seed + c * c_sum) % m;
    return (uint32_t)result;
}


#ifdef RANDCTX_HAS_TESTS

void test_graycode_conversion()
{
    printf("===== Testing Gray Code Conversion =====\n");

    // 测试32位格雷码
    uint32_t test_values32[] = { 0, 1, 0xFFFFFFFF, 0xAAAAAAAA, 0x55555555, 0x12345678 };
    for (int i = 0; i < sizeof(test_values32) / sizeof(uint32_t); i++) {
        uint32_t original = test_values32[i];
        uint32_t gray = binary2graycode(original);
        uint32_t reconstructed = graycode2binary(gray);

        printf("32-bit Test %d:\n", i + 1);
        printf("  Original:    0x%08X\n", original);
        printf("  Gray Code:   0x%08X\n", gray);
        printf("  Reconstructed: 0x%08X\n", reconstructed);

        assert(original == reconstructed);
        assert(gray == (original ^ (original >> 1)));
    }
    printf("32-bit Gray Code: All tests passed!\n\n");

    // 测试64位格雷码
    uint64_t test_values64[] = {
        0, 1,
        0xFFFFFFFFFFFFFFFFULL,
        0xAAAAAAAAAAAAAAAAULL,
        0x5555555555555555ULL,
        0x123456789ABCDEF0ULL
    };

    for (int i = 0; i < sizeof(test_values64) / sizeof(uint64_t); i++) {
        uint64_t original = test_values64[i];
        uint64_t gray = binary2graycode64(original);
        uint64_t reconstructed = graycode2binary64(gray);

        printf("64-bit Test %d:\n", i + 1);
        printf("  Original:    0x%016llX\n", (unsigned long long)original);
        printf("  Gray Code:   0x%016llX\n", (unsigned long long)gray);
        printf("  Reconstructed: 0x%016llX\n", (unsigned long long)reconstructed);

        assert(original == reconstructed);
        assert(gray == (original ^ (original >> 1)));
    }
    printf("64-bit Gray Code: All tests passed!\n\n");

    // 测试相邻数字的格雷码只有1位不同
    for (uint32_t i = 1; i < 100; i++) {
        uint32_t gray1 = binary2graycode(i - 1);
        uint32_t gray2 = binary2graycode(i);
        uint32_t diff = gray1 ^ gray2;

        // 验证只有一个位不同
        assert((diff & (diff - 1)) == 0);
    }
    printf("Adjacent Gray Codes: Only one bit changes. Test passed!\n");
}


void test_random_generation()
{
    printf("\n===== Testing Random Number Generation =====\n");

    // 初始化随机数上下文
    randctx32_t ctx32;
    randctx64_t ctx64;

    time_t seed = time(NULL);
    randctx_init(&ctx32, (uint32_t)seed);
    randctx64_init(&ctx64, (uint64_t)seed);

    // 测试32位基本随机数
    printf("-- Testing 32-bit Random Numbers --\n");
    for (int i = 0; i < 5; i++) {
        uint32_t r = rand_gen(&ctx32);
        printf("  Random %d: 0x%08X\n", i + 1, r);
        assert(r != 0);  // 极低概率失败
    }

    // 测试32位范围随机数
    uint32_t rmin32 = 10;
    uint32_t rmax32 = 100;
    printf("\n-- Testing 32-bit Range [%u, %u] --\n", rmin32, rmax32);
    for (int i = 0; i < 20; i++) {
        uint32_t r = rand_gen_int(&ctx32, rmin32, rmax32);
        printf("  %u ", r);
        assert(r >= rmin32 && r <= rmax32);
    }
    printf("\nAll values in range!\n");

    // 测试64位基本随机数
    printf("\n-- Testing 64-bit Random Numbers --\n");
    for (int i = 0; i < 5; i++) {
        uint64_t r = rand64_gen(&ctx64);
        printf("  Random %d: 0x%016llX\n", i + 1, (unsigned long long)r);
        assert(r != 0);  // 极低概率失败
    }

    // 测试64位范围随机数
    uint64_t rmin64 = 1000;
    uint64_t rmax64 = 2000;
    printf("\n-- Testing 64-bit Range [%llu, %llu] --\n",
        (unsigned long long)rmin64, (unsigned long long)rmax64);
    for (int i = 0; i < 20; i++) {
        uint64_t r = rand64_gen_int(&ctx64, rmin64, rmax64);
        printf("  %llu ", (unsigned long long)r);
        assert(r >= rmin64 && r <= rmax64);
    }
    printf("\nAll values in range!\n");

    // 测试分布均匀性（粗略）
    printf("\n-- Testing Uniform Distribution (32-bit) --\n");
    int buckets[10] = { 0 };
    for (int i = 0; i < 10000; i++) {
        uint32_t r = rand_gen_int(&ctx32, 0, 9);
        buckets[r]++;
    }

    printf("Distribution: ");
    for (int i = 0; i < 10; i++) {
        printf("%d: %d ", i, buckets[i]);
        assert(buckets[i] > 800 && buckets[i] < 1200); // 允许±20%偏差
    }
    printf("\nDistribution looks uniform!\n");

    // 测试LCG生成器
    printf("\n-- Testing LCG Generators --\n");
    uint32_t seed32 = 12345;
    unsigned loops = 5;

    uint32_t safe_result = random_uint32_safe(seed32, loops);
    uint32_t fast_result = random_uint32_fast(seed32, loops);

    printf("Safe LCG: %u\n", safe_result);
    printf("Fast LCG: %u\n", fast_result);
    assert(safe_result == fast_result);

    // 验证0次迭代
    assert(random_uint32_safe(seed32, 0) == seed32 % RAND32_LCG_M);
    assert(random_uint32_fast(seed32, 0) == seed32 % RAND32_LCG_M);

    printf("LCG tests passed!\n");
}

#endif
