/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file randctx.h
 * @brief 随机数生成器 API (支持 Linux 和 Windows)
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 anomura.cc All Rights Reserved.
 * @version 1.0.23
 * @since 2015-01-19 12:37:44
 * @date 2025-12-06 22:02:59
 *
 * @note 提供 32 位和 64 位随机数生成器实现，包含：
 *   - ISAAC 算法伪随机数生成器
 *   - 范围限制的随机数生成
 *   - 格雷码转换功能
 *   - 安全/快速版本的 LCG 随机数生成
 */
#ifndef RANDCTX_H__
#define RANDCTX_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#define RANDSIZL   (8)          ///< 随机状态数组大小的对数
#define RANDSIZ    (1<<RANDSIZL) ///< 随机状态数组大小 (256)

/**
 * @brief 32 位随机数生成器上下文
 */
typedef struct randctx32_t
{
    uint32_t randcnt;            ///< 随机数计数器
    uint32_t seed[RANDSIZ];      ///< 随机种子数组
    uint32_t mm[RANDSIZ];        ///< 内部状态数组
    uint32_t aa;                 ///< ISAAC 算法累加器
    uint32_t bb;                 ///< ISAAC 算法上次结果
    uint32_t cc;                 ///< ISAAC 算法计数器
} randctx32_t;

/**
 * @brief 64 位随机数生成器上下文
 */
typedef struct randctx64_t
{
    uint64_t randcnt;            ///< 随机数计数器
    uint64_t seed[RANDSIZ];      ///< 随机种子数组
    uint64_t mm[RANDSIZ];        ///< 内部状态数组
    uint64_t aa;                 ///< ISAAC 算法累加器
    uint64_t bb;                 ///< ISAAC 算法上次结果
    uint64_t cc;                 ///< ISAAC 算法计数器
} randctx64_t;


/* ======================== 32 位随机数 API ======================== */

/**
 * @brief 初始化 32 位随机数生成器上下文
 * @param r     随机数上下文指针
 * @param seed  初始化种子值
 */
void randctx_init(randctx32_t *r, uint32_t seed);

/**
 * @brief 生成 32 位随机数
 * @param r 随机数上下文指针
 * @return 32 位无符号随机整数
 */
uint32_t rand_gen(randctx32_t *r);

/**
 * @brief 生成指定范围内的 32 位随机整数
 * @param r     随机数上下文指针
 * @param rmin  范围最小值 (包含)
 * @param rmax  范围最大值 (包含)
 * @return [rmin, rmax] 范围内的随机整数
 */
uint32_t rand_gen_int(randctx32_t *r, uint32_t rmin, uint32_t rmax);

/* ======================== 64 位随机数 API ======================== */

/**
 * @brief 初始化 64 位随机数生成器上下文
 * @param r     随机数上下文指针
 * @param seed  初始化种子值
 */
void randctx64_init(randctx64_t *r, uint64_t seed);

/**
 * @brief 生成 64 位随机数
 * @param r 随机数上下文指针
 * @return 64 位无符号随机整数
 */
uint64_t rand64_gen(randctx64_t *r);

/**
 * @brief 生成指定范围内的 64 位随机整数
 * @param r     随机数上下文指针
 * @param rmin  范围最小值 (包含)
 * @param rmax  范围最大值 (包含)
 * @return [rmin, rmax] 范围内的随机整数
 */
uint64_t rand64_gen_int(randctx64_t *r, uint64_t rmin, uint64_t rmax);

/* ======================== 格雷码转换 API ======================== */

/**
 * @brief 32 位二进制转格雷码
 * @param x 二进制数值
 * @return 对应的格雷码
 */
uint32_t binary2graycode(uint32_t x);

/**
 * @brief 32 位格雷码转二进制
 * @param x 格雷码数值
 * @return 对应的二进制值
 */
uint32_t graycode2binary(uint32_t x);

/**
 * @brief 64 位二进制转格雷码
 * @param x 二进制数值
 * @return 对应的格雷码
 */
uint64_t binary2graycode64(uint64_t x);

/**
 * @brief 64 位格雷码转二进制
 * @param x 格雷码数值
 * @return 对应的二进制值
 */
uint64_t graycode2binary64(uint64_t x);

/* ======================== LCG 随机数生成器 ======================== */

/**
 * @brief 安全版 LCG 随机数生成 (多次迭代)
 * @param seed  初始种子值
 * @param loops 迭代次数 (必须 >= 0)
 * @return 迭代后的随机数
 * @note 使用模运算保证范围在 [0, LCG_M-1]
 */
uint32_t random_uint32_safe(uint32_t seed, unsigned loops);

/**
 * @brief 快速跳跃版 LCG 随机数生成
 * @param seed  初始种子值
 * @param loops 迭代次数 (必须 >= 0)
 * @return 迭代后的随机数
 * @note 使用数学优化加速多次迭代
 */
uint32_t random_uint32_fast(uint32_t seed, unsigned loops);

#if defined(__cplusplus)
}
#endif

#endif /* RANDCTX_H__ */
