/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file readconf.c
 * @brief read ini file api for Linux and Windows
 * @copyright © 2024-2030 anomura.cc All Rights Reserved.
 * @author Liang Zhang <350137278@qq.com>
 * @version 1.0.19
 * @since 2012-05-21 12:37:44
 * @date 2025-12-06 22:02:59
 */
#include "readconf.h"

#include <stdio.h>
#include <assert.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <ctype.h>
#include <math.h>

/**
 * @brief 内存分配失败检查宏
 * @param p 分配的内存指针
 * @note 分配失败时打印错误信息并终止程序
 */
#define ConfMemCheck(p) do { \
    if (!(p)) { \
        fprintf(stderr, "(readconf.h:%d) fatal error: out of memory\n", __LINE__); \
        fflush(stderr); \
        abort(); \
    } \
} while(0)


/* INI文件标记字符定义 */
typedef enum {
    READCONF_SEC_BEGIN = 91,   /* '[' 节开始 */
    READCONF_SEC_END = 93,     /* ']' 节结束 */
    READCONF_SEP_CHAR = 61,    /* '=' 键值分隔符 */
    READCONF_NOTE_CHAR = 35,   /* '#' 注释字符 */
    READCONF_SEC_SEMI = 58     /* ':' 节名分隔符 */
} READCONF_MARKER;


/* 配置文件位置上下文结构 */
typedef struct _conf_position_t
{
    FILE* _fp;                 /* 文件指针 */
    char encode[16];           /* 文件编码 */
    char secname[READCONF_SECNAME_MAX + 4];  /* 当前节名 */
    char linebuf[READCONF_LINESIZE_MAX + 4]; /* 行缓冲区 */
} conf_position_t;

/**
 * @brief 比较两个字符串（可选择是否忽略大小写）
 * @param s1 第一个字符串
 * @param l1 第一个字符串长度（-1表示自动计算）
 * @param s2 第二个字符串
 * @param l2 第二个字符串长度（-1表示自动计算）
 * @param caseignore 是否忽略大小写（0=不忽略，非0=忽略）
 * @return 比较结果（0=相等，负数=s1<s2，正数=s1>s2）
 */
static int StrCaseCompareLen(const char* s1, size_t l1, const char* s2, size_t l2, int caseignore)
{
    if (s1 == s2) {
        // same pointer
        return 0;
    }
    if (!s1) {
        // s2 is non-NULL: s1 < s2
        return (-1);
    }
    if (!s2) {
        // s1 is non-NULL: s1 > s2
        return 1;
    }
    if (l1 == (size_t)(-1)) {
        l1 = strlen(s1);
    }
    if (l2 == (size_t)(-1)) {
        l2 = strlen(s2);
    }
    if (l1 > l2) {
        // s1 > s2
        return 1;
    }
    if (l1 < l2) {
        // s1 < s2
        return -1;
    }
    // l1 == l2
    if (!l1) {
        // s1, s2 are both empty
        return 0;
    }
    // here: (l1==l2) > 0
    const char* end = s1 + l1;
    if (!caseignore) {
        // caseignore=0: a != A
        while (s1 < end) {
            int p = *s1++;
            int q = *s2++;
            if (p > q) {
                return 1;
            }
            else if (p < q) {
                return -1;
            }
        }
        // s1 == s2
        return 0;
    }
    // caseignore!=0: a == A
    while (s1 < end) {
        int p = *s1++;
        int q = *s2++;
        if (p == q) {
            continue;
        }
        p = tolower((unsigned char)p);
        q = tolower((unsigned char)q);
        if (p > q) {
            return 1;
        }
        else if (p < q) {
            return -1;
        }
    }
    // s1 == s2
    return 0;
}

/* 不区分大小写的字符串比较宏 */
#define StrNCaseComp(s1, s2)   StrCaseCompareLen(s1, ((size_t)(-1)), s2, ((size_t)(-1)), 1)

/* 区分大小写的字符串比较宏 */
#define StrCaseComp(s1, s2)   StrCaseCompareLen(s1, ((size_t)(-1)), s2, ((size_t)(-1)), 0)

/**
 * @brief 递归修剪字符串中的所有空白字符
 * @param s 要修剪的字符串
 * @return 修剪后的字符串
 */
static char * StrTrimSpace(char * s)
{
    return (*s==0)?s:(((!isspace((int)*s) )?(((StrTrimSpace(s+1)-1)==s)? s : (*(StrTrimSpace(s+1)-1)=*s, *s=32 ,StrTrimSpace(s+1))):StrTrimSpace(s+1)));
}

/**
 * @brief 从左侧修剪指定字符
 * @param s 要修剪的字符串
 * @param c 要修剪的字符
 * @return 修剪后的字符串
 */
static char * StrLeftTrimChr(char *s, char c)
{
    while(*s!=0&&*s==c){s++;}return s;
}

/**
 * @brief 从右侧修剪指定字符
 * @param s 要修剪的字符串
 * @param c 要修剪的字符
 * @return 修剪后的字符串
 */
static char * StrRightTrimChr(char *s, char c)
{
    char *p=s,*q=s;while(*p!=0){if(*p!=c){q=p;q++;}p++;}if(q!=s)*q=0;return s;
}

/**
 * @brief 从两侧修剪指定字符
 * @param s 要修剪的字符串
 * @param c 要修剪的字符
 * @return 修剪后的字符串
 */
static char * StrStripChr(char *s, char c)
{
    return StrRightTrimChr(StrLeftTrimChr(s, c), c);
}

/**
 * @brief 从右侧修剪空白字符
 * @param str 要修剪的字符串
 * @param len 字符串长度
 * @return 修剪后的新长度
 */
static int StrRightTrimSpace(char* str, int len)
{
    while (len-- > 0) {
        if (isspace((int)str[len])) {
            str[len] = 0;
        }
        else {
            break;
        }
    }
    return len + 1;
}

/**
 * @brief 将字符串分割为键值对
 * @param strbuf 输入字符串
 * @param sep 分隔符
 * @param key 输出键指针
 * @param val 输出值指针
 * @return 成功返回READCONF_TRUE，失败返回READCONF_FALSE
 */
static READCONF_BOOL StrSplitPair(char *strbuf, char sep, char **key, char **val)
{
    char *at = strchr(strbuf, sep);
    if (at) {
        *at++ = 0;
    }

    *key = strbuf;
    *key = StrStripChr(StrStripChr(*key, 32), 9);

    *val = at;
    if (at) {
        *val = StrStripChr(StrStripChr(StrStripChr(*val, 32), 9), 34); /* '\"' */
    }

    if (*key != 0) {
        return READCONF_TRUE;
    } else {
        return READCONF_FALSE;
    }
}

/**
 * @brief 字符串替换函数
 * @param original 原始字符串
 * @param orilen 原始字符串长度
 * @param pattern 要替换的模式
 * @param patlen 模式长度
 * @param replacement 替换字符串
 * @param replen 替换字符串长度
 * @param outresult 输出结果指针
 * @return 新字符串长度，0表示没有替换
 */
static int StrReplaceNew(const char* original, int orilen, const char* pattern, int patlen, const char* replacement, int replen, char** outresult)
{
    size_t patcnt = 0;

    const char* oriptr;
    const char* patloc;

    *outresult = 0;

    // find how many times the pattern occurs in the original string
    for ((oriptr = original); (patloc = strstr(oriptr, pattern)); (oriptr = patloc + patlen)) {
        patcnt++;
    }

    if (patcnt) {
        // allocate memory for the new string
        size_t len = orilen + patcnt * (replen - patlen);

        char* result = (char*) malloc(sizeof(char) * (len + 1));

        // copy the original string,
        // replacing all the instances of the pattern
        char* retptr = result;

        for ((oriptr = original); (patloc = strstr(oriptr, pattern)); (oriptr = patloc + patlen)) {
            size_t const skplen = patloc - oriptr;

            // copy the section until the occurence of the pattern
            strncpy(retptr, oriptr, skplen);
            retptr += skplen;

            // copy the replacement
            strncpy(retptr, replacement, replen);
            retptr += replen;
        }

        // copy the rest of the string.
        strcpy(retptr, oriptr);

        *outresult = result;
        return (int)len;
    }

    return 0;
}

/**
 * @brief 从文件中读取一行文本并进行处理
 *
 * 使用fgets读取一行，移除行末换行符，并进行右侧空格修剪
 * 注意：行长度限制为bufsize-1，超长行会被截断并返回错误
 *
 * @param fp 文件指针，必须已打开并可读
 * @param linebuf 输出缓冲区，必须至少有bufsize大小
 * @param bufsize 缓冲区大小，应至少为2以存储至少一个字符
 * @return int 处理后的行长度(不含终止null字符)
 *             -1: 文件结束(EOF)
 *             -2: 读取错误
 */
static int ReadFileLine(FILE* fp, char* linebuf, int bufsize)
{
#ifdef DEBUG
    assert(fp && linebuf && bufsize > 1);
#endif

    if (fgets(linebuf, bufsize, fp) == NULL) {
        if (feof(fp)) {
            return -1; // 文件结束
        }
        return -2; // 读取错误
    }

    int len = (int)strnlen(linebuf, bufsize);

    // 检查是否行过长(缓冲区已满且最后一个字符不是换行符)
    if (len >= (bufsize - 1) && linebuf[bufsize - 2] != '\n') {
        // 太长的行自取前面的数据
        len = bufsize - 1;
        linebuf[len] = 0;

        // 行过长，需要消耗掉剩余部分直到遇到换行符或文件结束
        int ch;
        while ((ch = fgetc(fp)) != EOF && ch != '\n') {
            // 消耗字符但不存储
        }
    }

    // 处理空行情况
    if (len < 1) {
        linebuf[0] = '\0';
        return 0;
    }
    // 移除行末的换行符(LF - Unix风格)
    if (linebuf[len - 1] == '\n') {
        linebuf[--len] = '\0';
    }
    // 移除行末的回车符(CR - Windows风格)
    if (len > 0 && linebuf[len - 1] == '\r') {
        linebuf[--len] = '\0';
    }
    // 使用StrRightTrimSpace函数修剪右侧空格并返回新长度
    return StrRightTrimSpace(linebuf, len);
}

/**
 * @brief 分配节列表内存
 * @param numSections 节数量
 * @return 分配的节列表
 */
static char** _SectionListAlloc(int numSections)
{
    char** secs = (char**)ConfMemAlloc(numSections + 1, sizeof(char*));
    secs[0] = (char*)(uintptr_t)numSections;
    return secs;
}

/* ======================== public api ============================= */

/**
 * @brief 分配内存
 * @param numElems 元素数量
 * @param sizeElem 元素大小
 * @return 分配的内存指针
 */
void * ConfMemAlloc(int numElems, int sizeElem)
{
    void *p = calloc((size_t) numElems, (size_t) sizeElem);
    ConfMemCheck(p);
    return p;
}

/**
 * @brief 重新分配内存
 * @param oldBuffer 旧缓冲区
 * @param oldSize 旧大小
 * @param newSize 新大小
 * @return 重新分配的内存指针
 */
void * ConfMemRealloc(void *oldBuffer, int oldSize, int newSize)
{
    void *newBuffer = 0;
    assert(newSize >= 0);
    if (newSize==0) {
        ConfMemFree(oldBuffer);
        return newBuffer;
    }

    if (oldSize==newSize) {
        return oldBuffer? oldBuffer : ConfMemAlloc(1, newSize);
    }

    newBuffer = realloc(oldBuffer, newSize);
    ConfMemCheck(newBuffer);

    if (newSize > oldSize) {
        memset((char*)newBuffer+oldSize, 0, (size_t)(newSize-oldSize));
    }
    return newBuffer;
}

/**
 * @brief 释放内存
 * @param pBuffer 要释放的内存指针
 */
void ConfMemFree(void *pBuffer)
{
    if (pBuffer) {
        free(pBuffer);
    }
}

/**
 * @brief 清除配置变量环境
 * @param env 配置变量环境
 */
void ConfVariablesClear(ConfVariables* env)
{
    for (int i = 0; i < env->count; i++) {
        ConfMemFree(env->keys[i]);
        ConfMemFree(env->values[i]);
    }

    ConfMemFree(env->values);
    ConfMemFree(env->keys);
    ConfMemFree(env->valuelens);
    ConfMemFree(env->keylens);

    memset(env, 0, sizeof(*env));
}

/**
 * @brief 创建字符串数组
 * @param numElems 元素数量
 * @return 分配的字符串数组
 */
char ** ConfStringArrayNew(int numElems)
{
    char ** strs = (char **) malloc(sizeof(char *) * (numElems));
    ConfMemCheck(strs);

    while (numElems-- > 0) {
        strs[numElems] = 0;
    }
    return strs;
}

/**
 * @brief 释放字符串数组
 * @param strs 字符串数组
 * @param numElems 元素数量
 */
void ConfStringArrayFree(char **strs, int numElems)
{
    while (numElems-- > 0) {
        ConfMemFree(strs[numElems]);
    }
    ConfMemFree(strs);
}

/**
 * @brief 复制字符串
 * @param src 源字符串
 * @param chlen 字符串长度（-1表示自动计算）
 * @return 复制的字符串
 */
char * ConfMemCopyString(const char *src, size_t chlen)
{
    if (src) {
        char *buf;
        int num = (int) (chlen == -1 ? strlen(src) : chlen);
        buf = (char*) ConfMemAlloc(num + 1, sizeof(char));
        memcpy(buf, src, num);
        return buf;
    }
    return 0;
}

/**
 * @brief 打开配置文件
 * @param conf 配置文件路径
 * @return 配置文件位置上下文
 */
CONF_position ConfOpenFile(const char *conf)
{
    CONF_position cpos;
    FILE *fp = fopen(conf, "rb");
    if (! fp) {
        return 0;
    }
    cpos = (CONF_position) ConfMemAlloc(1, sizeof(conf_position_t));

    if (fgets(cpos->linebuf, sizeof(cpos->linebuf) - 1, fp) != 0) {
        char* end = strrchr(cpos->linebuf, ')');
        if (end && !strncmp(cpos->linebuf, "#!encode(", 9)) {
            char* start = cpos->linebuf + 8;
            int blen = (int)(end - start);
            if (blen > 0 && blen < (int) sizeof(cpos->encode)) {
                snprintf(cpos->encode, sizeof(cpos->encode), "%.*s", blen-1, ++start);
            }
        }
    }
    rewind(fp);
    cpos->_fp = fp;
    return cpos;
}

/**
 * @brief 获取文件编码
 * @param cpos 配置文件位置上下文
 * @return 编码字符串
 */
const char* ConfGetEncode(CONF_position cpos)
{
    return cpos->encode;
}

/**
 * @brief 关闭配置文件
 * @param cpos 配置文件位置上下文
 */
void ConfCloseFile(CONF_position cpos)
{
    fclose(cpos->_fp);
    ConfMemFree(cpos);
}

/**
 * @brief 获取下一个键值对
 * @param cpos 配置文件位置上下文
 * @param key 输出键指针
 * @param val 输出值指针
 * @return 原始行字符串
 */
char * ConfGetNextPair(CONF_position cpos, char **key, char **val)
{
    char *start;
    int   nch;

    for (;;) {
        nch = ReadFileLine(cpos->_fp, cpos->linebuf, READCONF_LINESIZE_MAX);
        if (nch < 0) {
            return 0;
        }
        start = StrStripChr(StrStripChr(cpos->linebuf, 32), 9);
        if (*start == READCONF_NOTE_CHAR) { /* # */
            continue;
        }

        nch = (int) strlen(start);
        if (nch > 2) {
            if (nch <= READCONF_SECNAME_MAX && *start == READCONF_SEC_BEGIN && *(start+nch-1) == READCONF_SEC_END) {
                /* find a section */
                memcpy(cpos->secname, start+1, nch-1);
                cpos->secname[nch-1] = 0;
                cpos->secname[nch-2] = 0;
                continue;
            }

            if (StrSplitPair(start, READCONF_SEP_CHAR, key, val)==READCONF_TRUE) {
                return start;
            }
        }
    }
    return 0;
}

/**
 * @brief 获取第一个键值对
 * @param cpos 配置文件位置上下文
 * @param key 输出键指针
 * @param val 输出值指针
 * @return 原始行字符串
 */
char * ConfGetFirstPair(CONF_position cpos, char **key, char **val)
{
    if (! cpos) {
        return 0;
    }

    rewind(cpos->_fp);
    return ConfGetNextPair(cpos, key, val);
}

/**
 * @brief 获取当前节名
 * @param cpos 配置文件位置上下文
 * @return 节名字符串
 */
const char * ConfGetSection(CONF_position cpos)
{
    return cpos->secname;
}

/**
 * @brief 复制当前节名
 * @param cpos 配置文件位置上下文
 * @param secName 输出节名缓冲区
 * @return 操作结果
 */
READCONF_RESULT ConfCopySection(CONF_position cpos, char *secName)
{
    if (!cpos->secname[0]) {
        return READCONF_RET_ERROR;
    }
    if (!secName) {
        return (int) strlen(cpos->secname)+2;
    }
    memcpy(secName, cpos->secname, strlen(cpos->secname)+2);
    return READCONF_RET_SUCCESS;
}

/**
 * @brief 读取配置值
 * @param confFile 配置文件路径
 * @param sectionName 节名
 * @param keyName 键名
 * @param valbuf 值缓冲区
 * @param maxbufsize 缓冲区最大大小
 * @return 值长度（不含终止null字符）
 */
int ConfReadValue(const char *confFile, const char *sectionName, const char *keyName, char *valbuf, size_t maxbufsize)
{
    char *str, *key, *val, endchr;
    int valsz;

    CONF_position cpos = ConfOpenFile(confFile);

    str = ConfGetFirstPair(cpos, &key, &val);
    while (str) {
        if (! sectionName || !StrCaseComp(ConfGetSection(cpos), sectionName)) {
            if (!StrCaseComp(key, keyName)) {
                if (val) {
                    valsz = (int) strlen(val) + 1;

                    if (! valbuf) {
                        ConfCloseFile(cpos);
                        return valsz;
                    }

                    memcpy(valbuf, val, valsz);

                    /* check last char: '\' */
                    if (valbuf[valsz - 2] != '\\') {
                        /* end of val */
                        ConfCloseFile(cpos);
                        return valsz;
                    }

                    endchr = valbuf[valsz - 2];

                    while (endchr == '\\') {
                        char *start;

                        /* read next line for: '+' */
                        int nch = ReadFileLine(cpos->_fp, cpos->linebuf, READCONF_LINESIZE_MAX);
                        if (nch < 0) {
                            /* end of val */
                            ConfCloseFile(cpos);
                            return valsz;
                        }

                        start = StrStripChr(StrStripChr(cpos->linebuf, 32), 9);
                        if (*start == READCONF_NOTE_CHAR) { /* # */
                            continue;
                        }

                        if (*start != '+') {
                            /* end of val */
                            valbuf[valsz-- - 2] = '\0';
                            ConfCloseFile(cpos);
                            return valsz;
                        }

                        start = StrStripChr(StrStripChr(start+1, 32), 9);
                        nch = (int) strlen(start);
                        endchr = start[nch - 1];

                        if (valsz - 2 + nch < (int)maxbufsize) {
                            memcpy(valbuf + valsz - 2, start, nch + 1);
                        }

                        valsz = valsz - 2 + nch + 1;
                    }

                    ConfCloseFile(cpos);
                    return valsz;
                } else {
                    *valbuf = 0;
                    ConfCloseFile(cpos);
                    return 1;
                }
            }
        }

        str = ConfGetNextPair(cpos, &key, &val);
    }

    ConfCloseFile(cpos);
    return 0;
}

/**
 * @brief 读取配置值引用（不复制）
 * @param confFile 配置文件路径
 * @param sectionName 节名
 * @param keyName 键名
 * @param ppRefVal 输出值引用指针
 * @return 是否找到
 */
READCONF_BOOL ConfReadValueRef(const char *confFile, const char *sectionName, const char *keyName, char **ppRefVal)
{
    char *str;
    char *key;
    char *val;

    CONF_position cpos = ConfOpenFile(confFile);

    str = ConfGetFirstPair(cpos, &key, &val);
    while (str) {
        if (! sectionName || !StrCaseComp(ConfGetSection(cpos), sectionName)) {
            if (!StrCaseComp(key, keyName)) {
                *ppRefVal = val;
                ConfCloseFile(cpos);
                return READCONF_TRUE;
            }
        }

        str = ConfGetNextPair(cpos, &key, &val);
    }

    ConfCloseFile(cpos);
    return READCONF_FALSE;
}

/**
 * @brief 读取节的所有变量
 * @param confFile 配置文件路径
 * @param sectionName 节名
 * @param outVars 输出变量结构
 * @return 变量数量
 */
int ConfReadSectionVariables(const char* confFile, const char* sectionName, ConfVariables* outVars)
{
    char* str;
    char* key;
    char* val;

    size_t count = 0;

    memset(outVars, 0, sizeof(*outVars));

    // 第一次获得元素数目
    CONF_position cpos = ConfOpenFile(confFile);
    str = ConfGetFirstPair(cpos, &key, &val);
    while (str) {
        if (! sectionName || !StrCaseComp(ConfGetSection(cpos), sectionName)) {
            count++;
        }
        str = ConfGetNextPair(cpos, &key, &val);
    }
    ConfCloseFile(cpos);

    if (! count) {
        return 0;
    }

    // 第一次取得获得元素
    int number = 0;

    char keypattern[READCONF_KEYLEN_MAX + 4];

    char **keys = ConfStringArrayNew((int)count);
    int* keylens = ConfMemAlloc((int)count, sizeof(int));

    char** values = ConfStringArrayNew((int)count);
    int* valuelens = ConfMemAlloc((int)count, sizeof(int));

    cpos = ConfOpenFile(confFile);
    str = ConfGetFirstPair(cpos, &key, &val);
    while (str) {
        if (!sectionName || !StrCaseComp(ConfGetSection(cpos), sectionName)) {
            if (number < count) {
                int kl = (int) strnlen(key, READCONF_KEYLEN_MAX + 1);
                int vl = (int) strnlen(val, READCONF_LINESIZE_MAX);
                if (kl != READCONF_KEYLEN_MAX + 1 && vl != READCONF_LINESIZE_MAX) {
                    keys[number] = ConfMemCopyString(key, kl);
                    values[number] = ConfMemCopyString(val, vl);
                    keylens[number] = kl;
                    valuelens[number] = vl;

                    number++;
                }
            }
        }
        str = ConfGetNextPair(cpos, &key, &val);
    }
    ConfCloseFile(cpos);

    if (number != count) {
        // Unexpect: should never run to this.
        ConfStringArrayFree(keys, number);
        ConfStringArrayFree(values, number);
        ConfMemFree(keylens);
        ConfMemFree(valuelens);
        return -1;
    }

    for (int i = 0; i < number; i++) {
        int patternlen = snprintf(keypattern, sizeof(keypattern), "$(%.*s)", keylens[i], keys[i]);
        char* replacement = values[i];
        int replacelen = valuelens[i];

        for (int j = 0; j < number; j++) {
            if (i != j) {
                // replace $(KEY) in values[j] with KEY's value
                char* result = 0;
                int reslen = StrReplaceNew(values[j], valuelens[j], keypattern, patternlen, replacement, replacelen, &result);
                if (reslen > 0) {
                    ConfMemFree(values[j]);
                    values[j] = ConfMemCopyString(result, reslen);
                    valuelens[j] = reslen;
                    free(result);
                }
            }
        }
    }

    // set output
    outVars->keys = keys;
    outVars->keylens = keylens;
    outVars->values = values;
    outVars->valuelens = valuelens;
    outVars->count = (int)count;

    return (int) count;
}

/**
 * @brief 使用配置变量替换输入字符串中的变量引用
 * @param input 输入字符串
 * @param inlen 输入字符串长度
 * @param vars 配置变量
 * @param output 输出字符串指针
 * @return 输出字符串长度
 */
int ConfVariablesReplace(const char* input, int inlen, const ConfVariables* vars, char** output)
{
    char keypattern[READCONF_KEYLEN_MAX + 4];

    int replen = inlen;
    char * repstr = (char *) input;

    for (int i = 0; i < vars->count; i++) {
        int patlen = snprintf(keypattern, sizeof(keypattern), "$(%.*s)", vars->keylens[i], vars->keys[i]);

        char *outstr;
        int outlen = StrReplaceNew(repstr, replen, keypattern, patlen, vars->values[i], vars->valuelens[i], &outstr);
        if (outlen > 0) {
            if (repstr != input) {
                ConfMemFree(repstr);
            }
            repstr = outstr;
            replen = outlen;
        }
    }

    if (repstr == input) {
        *output = ConfMemCopyString(input, inlen);
        return inlen;
    }

    *output = repstr;
    return replen;
}

/**
 * @brief 读取解析后的配置值
 * @param confFile 配置文件路径
 * @param family 族名
 * @param qualifier 限定符
 * @param key 键名
 * @param valbuf 值缓冲区
 * @param maxbufsize 缓冲区最大大小
 * @return 值长度
 */
int ConfReadValueParsed(const char *confFile, const char *family, const char *qualifier, const char *key, char *valbuf, size_t maxbufsize)
{
    if (! qualifier) {
        return  ConfReadValue(confFile, family, key, valbuf, maxbufsize);
    } else {
        char section[READCONF_SECNAME_MAX + 4];
        snprintf(section, sizeof(section), "%s:%s", family, qualifier);
        return  ConfReadValue(confFile, section, key, valbuf, maxbufsize);
    }
}

/**
 * @brief 读取解析后的配置值（带长度限制）
 * @param confFile 配置文件路径
 * @param family 族名
 * @param qualifier 限定符
 * @param qualifierlen 限定符长度
 * @param key 键名
 * @param valbuf 值缓冲区
 * @param maxbufsize 缓冲区最大大小
 * @return 值长度
 */
int ConfReadValueParsed2(const char* confFile, const char* family, const char* qualifier, size_t qualifierlen, const char* key, char* valbuf, size_t maxbufsize)
{
    if (!qualifier) {
        return  ConfReadValue(confFile, family, key, valbuf, maxbufsize);
    }
    else {
        int qlen = (int) (qualifierlen == -1 ? strnlen(qualifier, READCONF_KEYLEN_MAX) : qualifierlen);
        char section[READCONF_SECNAME_MAX + READCONF_KEYLEN_MAX + 4];
        snprintf(section, sizeof(section), "%s:%.*s", family, qlen, qualifier);
        return  ConfReadValue(confFile, section, key, valbuf, maxbufsize);
    }
}

/**
 * @brief 读取配置值并自动分配内存
 * @param confFile 配置文件路径
 * @param family 族名
 * @param qualifier 限定符
 * @param key 键名
 * @param value 输出值指针
 * @return 值长度
 */
int ConfReadValueParsedAlloc(const char *confFile, const char *family, const char *qualifier, const char *key, char **value)
{
    int maxbufsize = READCONF_LINESIZE_MAX;
    char *valbuf = ConfMemAlloc(1, maxbufsize);

    int valsz = ConfReadValueParsed(confFile, family, qualifier, key, valbuf, maxbufsize);
    if (valsz > maxbufsize) {
        maxbufsize = valsz;

        ConfMemFree(valbuf);
        valbuf = ConfMemAlloc(1, maxbufsize);

        valsz = ConfReadValueParsed(confFile, family, qualifier, key, valbuf, maxbufsize);
    }

    *value = valbuf;
    return valsz;
}

/**
 * @brief 获取节列表
 * @param confFile 配置文件路径
 * @param sectionList 输出节列表
 * @return 节数量
 */
int ConfGetSectionList(const char *confFile, void **sectionList)
{
    char *key;
    char *val;
    int   numSections = 0;
    *sectionList = 0;

    CONF_position cpos = ConfOpenFile(confFile);
    if (!cpos) {
        return READCONF_RET_ERROR;
    }

    /* get count of secions */
    char  secName[READCONF_SECNAME_MAX];
    secName[0] = 0;
    while (ConfGetNextPair(cpos, &key, &val) != 0) {
        const char *sec = ConfGetSection(cpos);
        if (StrCaseComp(sec, secName)) {
            ConfCopySection(cpos, secName);
            numSections++;
        }
    }
    ConfCloseFile(cpos);

    if (numSections > 0) {
        int  secNo = 1;
        char **secs = _SectionListAlloc(numSections);

        /* again get all of secions */
        cpos = ConfOpenFile(confFile);
        if (cpos) {
            while (secNo <= numSections && ConfGetNextPair(cpos, &key, &val) != 0) {
                const char *sec = ConfGetSection(cpos);
                if (secNo==1 || StrCaseComp(sec, secs[secNo-1])) {
                    int secSize = ConfCopySection(cpos, 0);
                    secs[secNo] = (char*) ConfMemAlloc(secSize, sizeof(char));
                    ConfCopySection(cpos, secs[secNo]);
                    secNo++;
                }
            }
            ConfCloseFile(cpos);
        }
        *sectionList = (void*) secs;
    }

    return numSections;
}

/**
 * @brief 释放节列表
 * @param sections 节列表
 */
void ConfSectionListFree(void *sections)
{
    if (sections) {
        char ** secs = (char **) sections;
        int numSections = (int) (uintptr_t) secs[0];
        while(numSections>0) {
            ConfMemFree(secs[numSections--]);
        }
        ConfMemFree(secs);
    }
}

/**
 * @brief 获取节列表中指定索引的节名
 * @param sections 节列表
 * @param secIndex 节索引
 * @return 节名字符串
 */
char * ConfSectionListGetAt(void *sections, int secIndex)
{
    char ** secs = (char **) sections;
    int numSections = (int) (uintptr_t) secs[0];
    if (secIndex < 0 || secIndex >= numSections) {
        return (char *) 0;
    }
    return secs[secIndex+1];
}

/**
 * @brief 解析节名
 * @param sectionName 节名
 * @param family 输出族名指针
 * @param qualifier 输出限定符指针
 * @return 解析结果（1=只有族名，2=有族名和限定符）
 */
int ConfSectionParse(char *sectionName, char **family, char **qualifier)
{
    char *p, *q;

    if (! sectionName) {
        /* null string */
        return -1;
    }

    if (! sectionName[0]) {
        /* empty string */
        return 0;
    }

    *qualifier = 0;
    *family = sectionName;

    p = strchr(sectionName, (char)READCONF_SEC_SEMI);
    q = strrchr(sectionName, (char)READCONF_SEC_SEMI);

    if (p == q && p) {
        *p++ = 0;

        *qualifier = p;
        return 2;
    }

    return 1;
}

/**
 * @brief 解析布尔值
 * @param value 值字符串
 * @param defvalue 默认值
 * @return 解析后的布尔值
 */
int ConfParseBoolValue(const char *value, int defvalue)
{
    if (! value || *value == '\0') {
        return defvalue;
    }
    if (! StrNCaseComp("1", value) ||
        ! StrNCaseComp("yes", value) || ! StrNCaseComp("y", value) ||
        ! StrNCaseComp("on", value) || ! StrNCaseComp("open", value) ||
        ! StrNCaseComp("true", value) || ! StrNCaseComp("t", value)) {
        return 1;
    }
    if (! StrNCaseComp("0", value) ||
        ! StrNCaseComp("no", value) || ! StrNCaseComp("n", value) ||
        ! StrNCaseComp("off", value) || ! StrNCaseComp("close", value) ||
        ! StrNCaseComp("false", value) || ! StrNCaseComp("f", value)) {
        return 0;
    }
    return (-1);
}

/**
 * @brief 解析字节大小值
 * @param valuebuf 值字符串
 * @param defvalue 默认值
 * @param base 输出基数指针
 * @param exponent 输出指数指针
 * @return 解析后的字节数
 *
 * @note
 * -----------------------------------------------------------
 *  NAME       ABBR. BYTES        NAME      ABBR.  BYTES
 * -----------------------------------------------------------
 *  bit        *bit   1/8         Byte        B      1
 *  kilobyte   KB    10^3 (1000)  kibibyte  KiB    2^10 (1024)
 *  megabyte   MB    10^6         mebibyte  MiB    2^20
 *  gigabyte   GB    10^9         gibibyte  GiB    2^30
 *  terabyte   TB    10^12        tebibyte  TiB    2^40
 *  petabyte   PB    10^15        pebibyte  PiB    2^50
 *  exabyte    EB    10^18        exbibyte  EiB    2^60
 *  zettabyte  ZB    10^21        zebibyte  ZiB    2^70
 *  yottabyte  YB    10^24        yobibyte  YiB    2^80
 * -----------------------------------------------------------
 */
double ConfParseSizeBytesValue(char *valuebuf, double defvalue, int *base, int *exponent)
{
    static const struct {
        char name[4];
        int base;
        int exponent;
    } namebytes[] = {
        {"B",   10,  0},
        {"KiB",  2, 10},
        {"KB",  10,  3},
        {"K",   10,  3},
        {"MiB",  2, 20},
        {"MB",  10,  6},
        {"M",   10,  6},
        {"GiB",  2, 30},
        {"GB",  10,  9},
        {"G",   10,  9},
        {"TiB",  2, 40},
        {"TB",  10, 12},
        {"T",   10, 12},
        {"PiB",  2, 50},
        {"PB",  10, 15},
        {"P",   10, 15},
        {"EiB",  2, 60},
        {"EB",  10, 18},
        {"E",   10, 18},
        {"ZiB",  2, 70},
        {"ZB",  10, 21},
        {"Z",   10, 21},
        {"YiB",  2, 80},
        {"YB",  10, 24},
        {"Y",   10, 24}
    };

    if (base && exponent) {
        *base = 10;
        *exponent = 0;
    }

    if (valuebuf) {
        size_t num = sizeof(namebytes)/sizeof(namebytes[0]);
        char *value = StrTrimSpace(valuebuf);
        int len = (int) strnlen(value, 128);
        int end;

        for (end = len - 1; end >= 0; end--) {
            if (value[end] >= '0' && value[end] <= '9') {
                size_t i;
                double retbytes = defvalue;

                char *name = &value[end + 1];

                for (i = 0; i != num; i++) {
                    if (!memcmp(namebytes[i].name, name, len - end)) {
                        if (base && exponent) {
                            *base = namebytes[i].base;
                            *exponent = namebytes[i].exponent;
                        }

                        *name = 0;

                        retbytes = atof(value);

                        if (base && exponent) {
                            return retbytes;
                        } else {
                            return retbytes * pow(namebytes[i].base, namebytes[i].exponent);
                        }
                    }
                }
            }
        }
    }

    return defvalue;
}
