/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file refcobj.h
 * @brief C语言非侵入式引用计数对象包装器
 *
 * 提供对现有对象结构的引用计数封装，无需修改原始对象结构。
 * 通过柔性数组技术将引用计数头与对象内存连续分配，实现非侵入式设计。
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 anomura.cc All Rights Reserved.
 * @version 0.0.46
 *
 * @since 2020-12-09 21:12:10
 * @date 2025-12-06 22:02:59
 *
 * @note 使用注意事项:
 * 1. 多线程环境下，调用者需确保正确调用引用计数函数:
 *    - 对象传递给其他线程前必须先调用refcobj_inc增加引用计数
 *    - 对象不再使用时必须调用refcobj_dec减少引用计数
 * 2. 引用计数为0时对象会自动销毁，不应再访问已销毁的对象
 * 3. 读写锁用于保护对象内容访问，但不保护引用计数操作
 * 4. 对象指针必须是通过refcobj_new创建的，不能直接用于堆分配的对象
 * 5. 标志位操作非原子性，多线程环境下需额外同步
 */
#ifndef _REFC_OBJ_H_
#define _REFC_OBJ_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "memapi.h"
#include "uatomic.h"
#include "rwlock.h"

#include <stddef.h> // for offsetof

// 标志位定义
#define REFC_FLAG_IGNORE      0x0         // 忽略
#define REFC_FLAG_READONLY    0x00000001  // 对象只读
#define REFC_FLAG_SHARED      0x00000002  // 对象可共享
#define REFC_FLAG_POOLED      0x00000004  // 对象来自内存池
#define REFC_FLAG_AUTORELEASE 0x00000008  // 自动释放
#define REFC_FLAG_TRACKED     0x00000010  // 跟踪对象使用
#define REFC_FLAG_DESTROYED   0x00000020  // 对象已标记为销毁

// 锁状态定义
#define REFC_LOCKSTATE_FREE   0           // 锁空闲
#define REFC_LOCKSTATE_BUSY   1           // 正在获取锁（忙等待）
#define REFC_LOCKSTATE_READ   2           // 读锁定
#define REFC_LOCKSTATE_WRITE  3           // 写锁定

// 无侵入的对已经存在的对象结构体进程引用计数的封装
typedef struct ALIGNED_AS(8)
{
    void (*finalize)(void *);  // 用户定义的对象清理函数
    ThreadRWLock_t rwlock;     // 读写锁，用于安全访问对象
    UAtomicInt lockstate;      // 锁状态: 0-无锁, 1-读锁定, 2-写锁定
    UAtomicInt refc;           // 引用计数器: 为 0 时调用 finalize 清理对象
    uint32_t flags;            // 标志字段: 默认 REFCOUNT_FLAG_IGNORE
    uint32_t type;             // 被包装的对象类型
    void *_obj[0];             // 被包装的对象地址
} refcobj_t;


/**
 * @brief 创建新的引用计数对象
 * @param type 对象类型标识符
 * @param elemsz 对象实际大小（字节）
 * @param finalize 对象销毁时的清理函数（可为NULL）
 * @return 指向对象的指针，失败返回NULL
 */
STATIC_INLINE void * refcobj_new(uint32_t type, size_t elemsz, void (*finalize)(void *))
{
    refcobj_t *p = (refcobj_t *) mem_alloc(sizeof(*p) + memapi_align_bsize(elemsz, 8));
    p->finalize = finalize;
    p->type = type;
    p->flags = REFC_FLAG_IGNORE;
    p->lockstate = REFC_LOCKSTATE_FREE;
    p->refc = 1;
    RWLockInit(&p->rwlock);
    return p->_obj;
}

/**
 * @brief 增加对象的引用计数
 * @param ppobj 指向对象指针的指针
 * @return 对象指针（成功时）或NULL（对象已释放）
 * @note 调用者需确保对象在传递给其他线程前调用此函数
 */
STATIC_INLINE void* refcobj_inc(void **ppobj)
{
    // 计算结构体的起始地址：从 _obj 指针减去 offsetof(refcobj_t, _obj)
    refcobj_t *p = (refcobj_t *)((char *)(*ppobj) - offsetof(refcobj_t, _obj));

    // 原子增加引用计数，并获取增加前的值。如果增加后的引用计数>1，表示对象有效
    //（因为初始引用计数为1，增加后至少为2）
    // 注意：如果对象已经被释放，引用计数可能为0，然后我们增加1得到1，这种情况需要处理
    if (UAtomicIntAdd(&p->refc) > 0) {
        return p->_obj;
    }

    // 如果增加后的引用计数为1，说明在增加之前引用计数为0，对象已经被释放，因此增加操作无效，需要撤销？
    // 但是注意：对象被释放后，内存可能已经被重用，所以我们不能简单地减少引用计数。
    // 实际上，在引用计数为0时，对象已经被释放，我们不应该再增加引用计数。
    // 因此，这种情况应该避免，但如果在释放后仍尝试增加，我们这里返回NULL，并且不撤销增加操作，因为对象已经无效。

    // 注意：这里有一个竞态条件：对象刚刚被释放，我们却增加了引用计数。这通常意味着程序逻辑有错误。
    // 为了安全起见，我们返回NULL，表示增加失败。
    return NULL;
}

/**
 * @brief 减少对象的引用计数，可能触发对象销毁
 * @param ppobj 指向对象指针的指针
 * @note 引用计数为0时会自动调用清理函数并释放内存
 *       调用后会将*ppobj设为NULL避免悬空指针
 */
STATIC_INLINE void refcobj_dec(void **ppobj)
{
    // 计算结构体的起始地址：从 _obj 指针减去 offsetof(refcobj_t, _obj)
    refcobj_t *p = (refcobj_t *)((char *)(*ppobj) - offsetof(refcobj_t, _obj));

    // 如果减少后的引用计数为0 (旧值=1)，表示需要释放对象
    if (UAtomicIntSub(&p->refc) == 1) {
        *ppobj = NULL; // 避免悬空指针

        // 调用析构函数（如果存在）
        if (p->finalize) {
            p->finalize(p->_obj);
        }

        // 销毁锁
        RWLockUninit(&p->rwlock);

        // 释放内存
        mem_free(p);
    }
}

/**
 * @brief 获取对象的类型标识符
 * @param pobj 对象指针
 * @return 对象类型标识符
 */
STATIC_INLINE uint32_t refcobj_get_type(const void *pobj)
{
    const refcobj_t *p = (const refcobj_t *)((const char *)(pobj) - offsetof(refcobj_t, _obj));
    return p->type;
}

/**
 * @brief 设置对象的标志位
 * @param pobj 对象指针
 * @param flags 要设置的标志位（位掩码）
 */
STATIC_INLINE void refcobj_set_flags(void *pobj, uint32_t flags)
{
    refcobj_t *p = (refcobj_t *)((char *)pobj - offsetof(refcobj_t, _obj));
    p->flags |= flags;
}

/**
 * @brief 清除对象的标志位
 * @param pobj 对象指针
 * @param flags 要清除的标志位（位掩码）
 */
STATIC_INLINE void refcobj_clr_flags(void *pobj, uint32_t flags)
{
    refcobj_t *p = (refcobj_t *)((char *)pobj - offsetof(refcobj_t, _obj));
    p->flags &= ~flags;
}

/**
 * @brief 检查对象是否具有指定标志位
 * @param pobj 对象指针
 * @param flags 要检查的标志位（位掩码）
 * @return 1-具有所有指定标志位，0-不具有所有指定标志位
 */
STATIC_INLINE int refcobj_has_flags(const void *pobj, uint32_t flags)
{
    refcobj_t *p = (refcobj_t *)((char *)pobj - offsetof(refcobj_t, _obj));
    return (p->flags & flags) == flags ? 1 : 0;
}

/**
 * @brief 锁定对象以进行线程安全访问
 * @param pobj 对象指针
 * @param istry 是否尝试锁定（非阻塞）
 * @param readonly 是否只读锁定
 * @return 0-成功，其他-失败（锁忙或尝试锁定失败）
 */
STATIC_INLINE int refcobj_lock(void *pobj, int istry, int readonly)
{
    refcobj_t *p = (refcobj_t *)((char *)pobj - offsetof(refcobj_t, _obj));

    if (UAtomicIntCompExch(&p->lockstate, REFC_LOCKSTATE_FREE, REFC_LOCKSTATE_BUSY) == 0) {
        int ret;
        if (readonly) {
            ret = RWLockAcquire(&p->rwlock, RWLOCK_STATE_READ, istry);
            if (ret == 0) { // 成功获得只读锁
                UAtomicIntSet(&p->lockstate, REFC_LOCKSTATE_READ);
            }
        } else {
            ret = RWLockAcquire(&p->rwlock, RWLOCK_STATE_WRITE, istry);
            if (ret == 0) { // 成功获得读写锁
                UAtomicIntSet(&p->lockstate, REFC_LOCKSTATE_WRITE);
            }
        }
        if (ret) {
            // 获取失败，恢复原来的值
            UAtomicIntSet(&p->lockstate, REFC_LOCKSTATE_FREE);
        }
        return ret;
    }

    // lock is busy
    return REFC_LOCKSTATE_BUSY;
}

/**
 * @brief 解锁对象
 * @param pobj 对象指针
 * @return 0-成功，其他-失败
 */
STATIC_INLINE int refcobj_unlock(void *pobj)
{
    refcobj_t *p = (refcobj_t *)((char *)pobj - offsetof(refcobj_t, _obj));

    int ret;

    int state = UAtomicIntGet(&p->lockstate);
    if (state ==  REFC_LOCKSTATE_READ) {
        // 如果是读锁定
        ret = RWLockRelease(&p->rwlock, RWLOCK_STATE_READ);
        if (ret == 0) {
            // 释放锁成功
            UAtomicIntSet(&p->lockstate, REFC_LOCKSTATE_FREE);
        }
        return ret;
    } else if (state == REFC_LOCKSTATE_WRITE) {
        // 如果是读写锁定
        ret = RWLockRelease(&p->rwlock, RWLOCK_STATE_WRITE);
        if (ret == 0) {
            // 释放锁成功
            UAtomicIntSet(&p->lockstate, REFC_LOCKSTATE_FREE);
        }
        return ret;
    }

    // 锁状态
    return state;
}

#ifdef __cplusplus
}
#endif

#endif /* _REFC_OBJ_H_ */
