/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file ringbufst.h
 * @brief 多线程安全的静态内存 Ring Buffer
 *
 * @copyright © 2024-2030 anomura.cc All Rights Reserved.
 * @author Liang Zhang <350137278@qq.com>
 * @version 1.0.26
 * @since 2019-12-14 12:46:50
 * @date 2025-12-06 22:02:59
 *
 * @note 此 ringbufst 实现了只要一次静态内存分配，适合频繁写入和读取的情况。
 */
#ifndef _RINGBUFST_H_
#define _RINGBUFST_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>  /* size_t */
#include <stdint.h>  /* uint8_t */

#ifndef RINGBUFST_LEN_MAX
    #define RINGBUFST_LEN_MAX     131072
#endif

/* 静态环形缓冲区句柄 */
typedef struct _ring_buffer_st*       ringbufst_t;

/* 静态环形缓冲区条目句柄 */
typedef struct _ringbuffer_entry_st*  ringbufst_entry;


/**
 * The layout of memory for any one entry in ringbufst.
 */
typedef struct _ringbuffer_entry_st
{
    size_t size;
    uint8_t chunk[0];
} ringbuffer_entry_st;


/**
 * @brief 初始化静态环形缓冲区
 * @param length 缓冲区长度（条目数量）
 * @param entrysize 每个条目的最大大小（字节）
 * @return 环形缓冲区句柄，失败返回NULL
 */
ringbufst_t ringbufst_init(int length, size_t entrysize);

/**
 * @brief 释放静态环形缓冲区
 * @param rbst 环形缓冲区句柄
 */
void ringbufst_uninit(ringbufst_t rbst);

/**
 * @brief 向环形缓冲区写入数据
 * @param rbst 环形缓冲区句柄
 * @param chunksize 要写入的数据大小
 * @param write_cb 写入回调函数，用于填充数据
 * @param arg 传递给回调函数的参数
 * @return 成功返回1，缓冲区满返回0，错误返回-1
 */
int ringbufst_write(ringbufst_t rbst, size_t chunksz, void(*write_cb)(uint8_t *, size_t, void *), void *arg);

/**
 * @brief 从环形缓冲区读取数据到提供的缓冲区
 * @param rbst 环形缓冲区句柄
 * @param rdbuf 接收数据的缓冲区
 * @param rdbufsz 接收缓冲区的大小
 * @return 成功返回读取的数据大小，缓冲区空返回0，错误返回-1
 *         如果返回的大小大于rdbufsz，表示缓冲区不足，需要更大缓冲区重试
 */
size_t ringbufst_read_copy(ringbufst_t rbst, uint8_t *rdbuf, size_t rdbufsz);

/**
 * @brief 从环形缓冲区读取下一个条目（回调方式）
 * @param rbst 环形缓冲区句柄
 * @param nextentry_cb 处理条目的回调函数
 * @param arg 传递给回调函数的参数
 * @return 成功读取并处理返回1，缓冲区空返回0，错误返回-1
 */
int ringbufst_read_next(ringbufst_t rbst, int (*nextentry_cb)(const ringbufst_entry entry, void *arg), void *arg);

/**
 * @brief 从环形缓冲区批量读取多个条目
 * @param rbst 环形缓冲区句柄
 * @param nextentry_cb 处理条目的回调函数
 * @param arg 传递给回调函数的参数
 * @param batch 要读取的最大条目数量
 * @return 成功读取的条目数量，错误返回-1
 */
int ringbufst_read_next_batch(ringbufst_t rbst, int (*nextentry_cb)(const ringbufst_entry, void *), void *arg, int batch);

#ifdef __cplusplus
}
#endif

#endif /* _RINGBUFST_H_ */
