/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file ringbuf.c
 * @brief Multi-threads Safety Ring Buffer
 *
 * @copyright © 2024-2030 anomura.cc All Rights Reserved.
 * @author Liang Zhang <350137278@qq.com>
 * @version 1.0.23
 * @since 2019-12-14 12:46:50
 * @date 2025-12-06 22:02:59
 * @note
 *
 * Length(L) = 10, Read(R), Write(W), wrap factor=0,1
 * Space(S)
 *
 * +           R        W        +                             +
 * |--+--+--+--+--+--+--+--+--+--|--+--+--+--+--+--+--+--+--+--|--+--+--+--
 * 0  1  2  3  4  5  6  7  8  9  0  1  2  3  4  5  6  7  8  9  0  1  2  3
 *
 *  S = L - (fL + W - R), W - R < L
 *  D = fL + W - R
 *
 *    S > 0: writable
 *    D > 0: readable
 *
 *
 *                 RW
 *  wrap=0      |----------|----------|---
 *                    L          L
 *                     R     W
 *  wrap=1      |----------|----------|---
 *
 *                             RW
 *  wrap=0      |----------|----------|---
 *
 *               W                 R
 *  wrap=1      |----------|----------|---
 *
 *                  RW
 *  wrap=0      |----------|----------|---
 *
 *  wrap(R, W, L) => ((R/L == W/L)? 0 : 1)
 *
 *  A = W + 1 (or A = R + 1)
 *
 *  W1 = (( A/L ) %2 ) * L + A % L
 *
 */
#include "ringbuf.h"

#include "memapi.h"
#include "uatomic.h"
#include "unitypes.h"
#include "timeapi.h"

/* 等待间隔微秒 */
#define RINGBUF_INTERVAL_USEC   100

#define RINGBUF_RESTORE_STATE(Ro, Wo, L)  \
    int wrap = ((int)((Ro)/(L) == (Wo)/(L) ? 0 : 1)); \
    int R = (Ro) % (L); \
    int W = (Wo) % (L)


#define RINGBUF_NORMALIZE_OFFSET(Ao, L)   \
    ((((Ao)/(L))%2)*L + (Ao)%(L))


typedef struct _ringbuffer_t
{
    /* MT-safety Read Lock */
    UAtomicInt RLock;

    /* MT-safety Write Lock */
    UAtomicInt WLock;

    /* Write (push) index: 0, L-1 */
    UAtomicInt W;

    /* Read (pop) index: 0, L-1 */
    UAtomicInt R;

    /* Length of ring buffer */
    int L;

    /* Buffer */
    ringbuf_elt_t B[0];
} ringbuffer_t;


/* ======================== public interface ======================= */

ringbuf_elt_t ringbuf_elt_new(int datasize, uint8_t **ppdata)
{
    // datasize 必须 > 0
    size_t bsize = memapi_align_psize(datasize);
    ringbuffer_elt_t* elt = (ringbuffer_elt_t*) mem_calloc(1, sizeof(*elt) + bsize);
    elt->free_cb = mem_free;
    elt->size = bsize;
    if (ppdata) {
        *ppdata = elt->data;
    }
    return elt;
}


ringbuf_t ringbuf_init(int length)
{
    size_t rblen = memapi_align_bsize(length, 64);
    if (rblen > RINGBUF_LEN_MAX) {
        rblen = RINGBUF_LEN_MAX;
    }
    /* new and initialize read and write index by 0 */
    ringbuffer_t* rb = (ringbuffer_t*) mem_calloc(1, sizeof(*rb) + sizeof(ringbuf_elt_t) * rblen);
    rb->L = (int) rblen;
    return rb;
}


void ringbuf_uninit(ringbuf_t rb)
{
    UAtomicIntSet(&rb->RLock, 1);
    UAtomicIntSet(&rb->WLock, 1);

    int i = rb->L;
    while (i-- > 0) {
        ringbuf_elt_t elt = rb->B[i];
        if (elt) {
            rb->B[i] = NULL;
            elt->free_cb(elt);
        }
    }
    mem_free(rb);
}


int ringbuf_push(ringbuf_t rb, ringbuf_elt_t elt)
{
    if (! UAtomicIntCompExch(&rb->WLock, 0, 1)) {
        /* copy constant of length */
        int L = rb->L;

        /* original values of R, W */
        int Ro = UAtomicIntGet(&rb->R);

        /* MUST get W after R */
        int Wo = rb->W;

        RINGBUF_RESTORE_STATE(Ro, Wo, L);

        /* Sw = L - (f*L+W - R) */
        if (L + R - wrap*L - W > 0) {
            /* writable: Sw > 0 */
            rb->B[W] = elt;

            /* to next Write offset */
            ++Wo;

            /* W = [0, 2L) */
            W = RINGBUF_NORMALIZE_OFFSET(Wo, L);

            UAtomicIntSet(&rb->W, W);

            /* push success */
            UAtomicIntZero(&rb->WLock);
            return 1;
        }

        UAtomicIntZero(&rb->WLock);
    }

    /* push failed */
    return 0;
}


int ringbuf_pop(ringbuf_t rb, ringbuf_elt_t *eltp)
{
    if (! UAtomicIntCompExch(&rb->RLock, 0, 1)) {
        int L = rb->L;

        /* original values of W, R */
        int Wo = UAtomicIntGet(&rb->W);

        /* MUST get R after W */
        int Ro = rb->R;

        RINGBUF_RESTORE_STATE(Ro, Wo, L);

        /* Sr = f*L + W - R */
        if (wrap*L + W - R > 0) {
            /* readable: Sr > 0 */
            *eltp = rb->B[R];

            /* must clear elt */
            rb->B[R] = NULL;

            ++Ro;

            /* R = [0, 2L) */
            R = RINGBUF_NORMALIZE_OFFSET(Ro, L);

            UAtomicIntSet(&rb->R, R);

            /* pop success */
            UAtomicIntZero(&rb->RLock);
            return 1;
        }

        UAtomicIntZero(&rb->RLock);
    }

    /* pop failed */
    return 0;
}


int ringbuf_push_timeout(ringbuf_t rb, ringbuf_elt_t elt, int timeout_ms)
{
    if (timeout_ms == 0) {
        // 0 无限忙等待: 不推荐
        while (ringbuf_push(rb, elt) != 1);
    } else if (timeout_ms < 0) {
        // -1 无限等待
        while (ringbuf_push(rb, elt) != 1) {
            // 短暂的休眠以减少CPU占用
            sleep_usec(RINGBUF_INTERVAL_USEC);
        }
    } else {
        // 有限时间等待 timeout_ms 毫秒
        sb8 timeout_us = timeout_ms * 1000;
        while (ringbuf_push(rb, elt) != 1) {
            // 短暂的休眠以减少CPU占用
            sleep_usec(RINGBUF_INTERVAL_USEC);
            timeout_us -= RINGBUF_INTERVAL_USEC;
            if (timeout_us < 1) {
                // 超时耗尽，仍然失败
                return (-1);
            }
        }
    }
    return 1; // 成功
}


int ringbuf_pop_timeout(ringbuf_t rb, ringbuf_elt_t *eltp, int timeout_ms)
{
    if (timeout_ms == 0) {
        // 0 无限忙等待: 不推荐
        while (ringbuf_pop(rb, eltp) != 1);
    } else if (timeout_ms < 0) {
        // -1 无限等待
        while (ringbuf_pop(rb, eltp) != 1) {
            // 短暂的休眠以减少CPU占用
            sleep_usec(RINGBUF_INTERVAL_USEC);
        }
    } else {
        // 有限时间等待 timeout_ms 毫秒
        sb8 timeout_us = timeout_ms * 1000;
        while (ringbuf_pop(rb, eltp) != 1) {
            // 短暂的休眠以减少CPU占用
            sleep_usec(RINGBUF_INTERVAL_USEC);
            timeout_us -= RINGBUF_INTERVAL_USEC;
            if (timeout_us < 1) {
                // 超时耗尽，仍然失败
                return (-1);
            }
        }
    }
    return 1; // 成功
}
