/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file rtclock.h
 * @brief real time clock up to year 2484.
 * @copyright © 2024-2030 anomura.cc All Rights Reserved.
 * @author Liang Zhang <350137278@qq.com>
 * @version 0.0.38
 * @since 2020-12-14 10:44:05
 * @date 2025-12-06 22:02:59
 */
#ifndef RTCLOCK_H__
#define RTCLOCK_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "timeapi.h"

/* (ms) milliseconds of one second */
#define MILLIS_OF_SECOND   ((uint64_t)1000l)

/* (us) microseconds of one second */
#define MICROS_OF_SECOND   ((uint64_t)1000000l)

/* (ns) nanoeconds of one second */
#define NANOS_OF_SECOND    ((uint64_t)1000000000l)

/**
 * process-wide realtime clock
 */
typedef struct _rtclock_t* rtclock_t;

typedef enum
{
    RTCLOCK_FREQ_SEC = 0,     /* 1 second */
    RTCLOCK_FREQ_MSEC = 1     /* 1 millisecond */
} rtclock_frequency_t;


/**
 * real time clock public api
 */
rtclock_t rtclock_init(rtclock_frequency_t frequency);

void rtclock_uninit(rtclock_t rtc);

int rtclock_timezone(rtclock_t rtc, const char **tzfmt);

int rtclock_daylight(rtclock_t rtc);

int64_t rtclock_ticktime(rtclock_t rtc, struct timespec *ticktime);

void rtclock_localtime(int timezone, int daylight, struct tm *tmloc, struct timespec *now);

#ifdef __cplusplus
}
#endif
#endif /* RTCLOCK_H__ */
