/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file rtclock.c
 * @brief real time clock up to year 2484.
 * @copyright © 2024-2030 anomura.cc All Rights Reserved.
 * @author Liang Zhang <350137278@qq.com>
 * @version 0.0.37
 * @since 2020-12-14 10:44:05
 * @date 2025-12-06 22:02:59
 */
#include "rtclock.h"
#include "memapi.h"
#include "uatomic.h"

#if defined(PLATFORM_WINDOWS)
    #include <Windows.h>
    #include <pthread.h>
    #ifdef _MSC_VER
        #pragma comment(lib, "pthreadVC2.lib")  // link to pthread-w32 lib
    #endif
# else
    #include <pthread.h>
#endif


typedef struct _rtclock_t
{
    /* if 0 : not exit */
    UAtomicBool exit_flag;

    /* ratio in us */
    UAtomicInt ratious;

    // 设置进程 ID
    int owner_pid;

    /* 使用条件变量精确控制时钟 */
    pthread_mutex_t mutex;
    pthread_cond_t cond;
    pthread_t timerthread;

    /* fake time in nanos supports up to max year 2484 AC. */
    UAtomicInt64 ticknanos;

    int daylight;
    long timezone;
    char timezonefmt[TIMEZONE_FORMAT_SIZE];
} _rtclock_t;


static void rtclock_updatetime(rtclock_t rtc, struct timespec* nowtime)
{
    uint64_t timeus;

    getnowtimeofday(nowtime);

    /* now time in us: timeus=1606890292682864 */
    timeus = (uint64_t)(((int64_t)nowtime->tv_sec) * MICROS_OF_SECOND + nowtime->tv_nsec / 1000);

    /* aligned time in us: timeus=1606890292000000 */
    timeus = (uint64_t)((timeus / rtc->ratious) * rtc->ratious);

    /* set aligned time in ns: ticknanos=1606890292000000000 */
    UAtomicInt64Set(&rtc->ticknanos, timeus * (uint64_t)1000);
}

static void* rtclock_timerthread(void* _rtc)
{
    int err;
    uint64_t nanos;

    struct timespec nowtime, abstime;

    rtclock_t rtc = (rtclock_t)_rtc;

    int64_t ratious = (int64_t)UAtomicIntGet(&rtc->ratious);

    struct timespec timeout;
    timeout.tv_sec = ratious / MICROS_OF_SECOND;
    timeout.tv_nsec = (ratious % MICROS_OF_SECOND) * 1000;

    for (;;) {
        // 更新时钟
        rtclock_updatetime(rtc, &nowtime);

        // 计算下一次更新时间
        nanos = nowtime.tv_nsec + timeout.tv_nsec;
        abstime.tv_sec = nowtime.tv_sec + timeout.tv_sec + nanos / NANOS_OF_SECOND;
        abstime.tv_nsec = nanos % NANOS_OF_SECOND;

        // 使用条件变量等待到指定时间
        pthread_mutex_lock(&rtc->mutex);
        err = pthread_cond_timedwait(&rtc->cond, &rtc->mutex, &abstime);
        pthread_mutex_unlock(&rtc->mutex);

        if (err == ETIMEDOUT) {
            // 正常超时，继续循环
            continue;
        }
        else if (err != 0) { // 错误处理
            fprintf(stderr, "(rtclock.h:%d) pthread_cond_timedwait error:%d\n", __LINE__, err);
            fflush(stderr);
            abort();  // 异常失败，只能放弃
        }
        else { // 被信号唤醒，检查是否需要退出
            if (UAtomicIntGet(&rtc->exit_flag)) {
                break;
            }
        }
    }

    return (void*)0;
}


rtclock_t rtclock_init(rtclock_frequency_t frequency)
{
    rtclock_t rtc = mem_calloc(1, sizeof(*rtc));

    // 设置进程 pid
    rtc->owner_pid = getprocessid();

    int err;
    struct timespec nowtime;

    if (frequency) {
        /* RTCLOCK_FREQ_MSEC: 1ms = 1000 us */
        UAtomicIntSet(&rtc->ratious, (int)MILLIS_OF_SECOND);
    }
    else {
        /* RTCLOCK_FREQ_SECOND: 1s = 1000000 us */
        UAtomicIntSet(&rtc->ratious, (int)MICROS_OF_SECOND);
    }

    err = pthread_mutex_init(&rtc->mutex, 0);
    if (err) {
        fprintf(stderr, "(rtclock.h:%d) pthread_mutex_init error:%d\n", __LINE__, err);
        fflush(stderr);
        mem_free(rtc);
        return NULL;
    }

    err = pthread_cond_init(&rtc->cond, 0);
    if (err) {
        fprintf(stderr, "(rtclock.h:%d) pthread_cond_init error:%d\n", __LINE__, err);
        fflush(stderr);
        pthread_mutex_destroy(&rtc->mutex);
        mem_free(rtc);
        return NULL;
    }

    rtclock_updatetime(rtc, &nowtime);

    rtc->timezone = timezone_compute(nowtime.tv_sec, rtc->timezonefmt);
    if (rtc->timezone == -1) {
        fprintf(stderr, "(rtclock.h:%d) timezone_compute failed\n", __LINE__);
        fflush(stderr);
        goto fatal_error;
    }

    rtc->daylight = daylight_compute(nowtime.tv_sec);

    if (pthread_create(&rtc->timerthread, NULL, rtclock_timerthread, (void*)rtc) != 0) {
        fprintf(stderr, "(rtclock.h:%d) pthread_create failed\n", __LINE__);
        fflush(stderr);
        goto fatal_error;
    }

    // success
    return rtc;

fatal_error:
    pthread_cond_destroy(&rtc->cond);
    pthread_mutex_destroy(&rtc->mutex);
    mem_free(rtc);
    return NULL;
}


void rtclock_uninit(rtclock_t rtc)
{
    // 检查当前进程是否是 rtclock 的所有者
    if (getprocessid() != rtc->owner_pid) {
        // 不是所有者，简单释放内存，不销毁同步原语
        mem_free(rtc);
        return;
    }

    // 本进程：正常清理流程
    UAtomicIntSet(&rtc->exit_flag, 1);

    // 唤醒线程
    pthread_mutex_lock(&rtc->mutex);
    pthread_cond_signal(&rtc->cond);
    pthread_mutex_unlock(&rtc->mutex);

    // 等待线程退出
    pthread_join(rtc->timerthread, NULL);

    // 清理资源
    pthread_cond_destroy(&rtc->cond);
    pthread_mutex_destroy(&rtc->mutex);

    // 释放内存
    mem_free(rtc);
}


int rtclock_daylight(rtclock_t rtc)
{
    return (int)rtc->daylight;
}


int rtclock_timezone(rtclock_t rtc, const char** tzfmt)
{
    if (tzfmt) {
        *tzfmt = rtc->timezonefmt;
    }
    return (int)rtc->timezone;
}


int64_t rtclock_ticktime(rtclock_t rtc, struct timespec* ticktime)
{
    // 最大到 2484 年
    // UAtomicInt64Add 返回旧值。如果要得到新值，需要 + 1
    uint64_t nanos = (uint64_t) UAtomicInt64Add(&rtc->ticknanos) + 1;

    ticktime->tv_sec = (time_t)(nanos / NANOS_OF_SECOND);
    ticktime->tv_nsec = nanos % NANOS_OF_SECOND;

    return (int64_t)ticktime->tv_sec;
}


void rtclock_localtime(int timezone, int daylight, struct tm* tmloc, struct timespec* now)
{
    getnowtimeofday(now);

    /**
     * locale time: +0800
     * UTC time: +0000
     */
    getlocaltime_safe(tmloc, now->tv_sec, timezone, daylight);

    tmloc->tm_year += 1900;
    tmloc->tm_mon += 1;
}
