/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file shmipc.c
 * @brief Shared Memory IPC for Windows and Linux
 *
 * This header provides a cross-platform shared memory IPC implementation
 * with ring buffer functionality for efficient inter-process communication.
 *
 * Features include:
 *   - Atomic operations using process mutexes
 *   - Cryptographic token protection for secure access
 *   - Semaphore-based signaling
 *   - Lock-free state management
 *   - Wrap-around ring buffer implementation
 *   - Cross-platform support for Windows and POSIX systems
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 anomura.cc All Rights Reserved.
 * @version 1.0.26
 * @since 2020-12-05 12:46:50
 * @date 2025-12-06 22:02:59
 *
 */
#include "shmipc.h"


/* Platform detection for implementation */
#if defined(PLATFORM_WINDOWS) || defined(PLATFORM_CYGWIN)

shmkey_t shmipc_keygen(const char *filename, int pid, char *keybuf, size_t bufsz)
{
    snprintf(keybuf, bufsz, "Local\\%s.%d", filename, pid);
    keybuf[bufsz - 1] = 0;
    return keybuf;
}


shmhandle_t shmipc_create(const shmkey_t key, const void *copydata, size_t copysize, size_t maxsize, size_t offset)
{
    HANDLE hMapFile;
    PVOID pvBuf;
    int err;

    if (maxsize < copysize) {
        maxsize = copysize;
    }

    hMapFile = CreateFileMappingA(
                 INVALID_HANDLE_VALUE,    // use paging file
                 NULL,                    // default security
                 PAGE_READWRITE,          // read/write access
                 (DWORD) 0,               // maximum object size (high-order DWORD)
                 (DWORD) maxsize,         // maximum object size (low-order DWORD)
                 key);                    // name of mapping object: "Local\\yourname"

    if (! hMapFile) {
        errno = GetLastError();
        return shmipc_invalid_handle;
    }

    pvBuf = MapViewOfFile(hMapFile,       // handle to map object
                FILE_MAP_ALL_ACCESS,      // read/write permission
                (DWORD) 0,
                (DWORD) offset,
                (SIZE_T) copysize);
    if (! pvBuf) {
        err = GetLastError();
        CloseHandle(hMapFile);
        errno = err;
        return shmipc_invalid_handle;
    }

    memcpy(pvBuf, copydata, copysize);

    if (! UnmapViewOfFile(pvBuf)) {
        err = GetLastError();
        CloseHandle(hMapFile);
        errno = err;
        return shmipc_invalid_handle;
    }

    return hMapFile;
}


int shmipc_read(const shmkey_t key, void *readbuf, size_t readbytes, size_t offset)
{
    HANDLE hMapFile;
    PVOID pvBuf;
    int err;

    hMapFile = OpenFileMappingA(
                    FILE_MAP_READ,   // read access
                    FALSE,           // do not inherit the name
                    key);            // name of mapping object
    if (! hMapFile) {
        errno = GetLastError();
        return -1;
    }

    pvBuf = MapViewOfFile(hMapFile,  // handle to map object
                FILE_MAP_READ,       // read permission
                (DWORD) 0,
                (DWORD) offset,
                (SIZE_T) readbytes);
    if (! pvBuf) {
        err = GetLastError();
        CloseHandle(hMapFile);
        errno = err;
        return -1;
    }

    memcpy(readbuf, pvBuf, readbytes);

    UnmapViewOfFile(pvBuf);
    CloseHandle(hMapFile);

    return 0;
}


void shmipc_destroy(shmhandle_t *hp)
{
    HANDLE h = *hp;
    if (h != shmipc_invalid_handle) {
        *hp = shmipc_invalid_handle;
        CloseHandle(h);
    }
}

#else // POSIX implementation

shmkey_t shmipc_keygen(const char *filename, int pid, char* keybuf, size_t bufsz)
{
    int pidint = pid;

    int idx = snprintf(keybuf, bufsz, "%x", pid) - 1;
    if (keybuf[idx] == '0') {
        keybuf[idx] = keybuf[0];
    }

    errno = 0;
    pidint = (int) strtol(keybuf, NULL, 16);
    if (errno) {
        perror("strtol");
    }

    /* https://man7.org/linux/man-pages/man3/ftok.3.html */
    return (shmkey_t) ftok(filename, pidint);
}


shmhandle_t shmipc_create(shmkey_t key, const void *copydata, size_t copysize, size_t maxsize, size_t offset)
{
    int shmid, err;
    void *addr;

    int flags = 0600 | IPC_CREAT | IPC_EXCL;

    if (maxsize < copysize) {
        maxsize = copysize;
    }

shm_create_always:

    shmid = shmget(key, maxsize, flags);
    if (shmid == shmipc_invalid_handle) {
        if (errno != EEXIST) {
            return (-1);
        }

        shmid = shmget(key, 0, 0);
        if (shmid == shmipc_invalid_handle) {
            return (-1);
        }

        if (shmctl(shmid, IPC_RMID, 0) == -1) {
            return (-1);
        }

        goto shm_create_always;
    }

    addr = shmat(shmid, NULL, 0);
    if (!addr) {
        err = errno;
        shmctl(shmid, IPC_RMID, 0);
        errno = err;
        return (-1);
    }

    memcpy(addr, copydata, copysize);
    shmdt(addr);
    return shmid;
}


int shmipc_read(shmkey_t key, void *readbuf, size_t readbytes, size_t offset)
{
    int shmid;
    void *addr;

    shmid = shmget(key, 0, 0);
    if (shmid == shmipc_invalid_handle) {
        return (-1);
    }

    addr = shmat(shmid, 0, 0);
    if (!addr) {
        return (-1);
    }

    memcpy(readbuf, addr + offset, readbytes);
    shmdt(addr);
    return 0;
}


void shmipc_destroy(shmhandle_t *hp)
{
    int shmid = *hp;
    if (shmid != shmipc_invalid_handle) {
        *hp = shmipc_invalid_handle;
        shmctl(shmid, IPC_RMID, 0);
    }
}

#endif // Platform-specific implementations
