/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file shmipc.h
 * @brief Shared Memory IPC for Windows and Linux
 *
 * This header provides a cross-platform shared memory IPC implementation
 * with ring buffer functionality for efficient inter-process communication.
 *
 * Features include:
 *   - Atomic operations using process mutexes
 *   - Cryptographic token protection for secure access
 *   - Semaphore-based signaling
 *   - Lock-free state management
 *   - Wrap-around ring buffer implementation
 *   - Cross-platform support for Windows and POSIX systems
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 anomura.cc All Rights Reserved.
 * @version 1.0.27
 * @since 2020-12-05 12:46:50
 * @date 2025-12-06 22:02:59
 *
 */
#ifndef SHMIPC_H__
#define SHMIPC_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "platforms.h"

/* Platform-specific type definitions */
#if defined(PLATFORM_WINDOWS) || defined(PLATFORM_CYGWIN)
    /** @brief Shared memory handle type for Windows */
    typedef HANDLE  shmhandle_t;
    /** @brief Shared memory key type for Windows (string-based) */
    typedef const char* shmkey_t;
#else // posix
    #include <sys/ipc.h>
    #include <sys/shm.h>

    /** @brief Shared memory handle type for POSIX systems */
    typedef int  shmhandle_t;
    /** @brief Shared memory key type for POSIX systems (integer-based) */
    typedef key_t shmkey_t;
#endif

    /** @brief Invalid shared memory handle value */
#define shmipc_invalid_handle   ((shmhandle_t)(-1))

/* ======================= Public API ======================= */

/**
 * @brief Generate a shared memory key
 *
 * This function generates a platform-specific key for identifying shared memory segments.
 * On Windows, it creates a named shared memory object. On POSIX systems, it uses ftok()
 * to generate a System V IPC key.
 *
 * @param filename File path used for key generation (required for POSIX systems)
 * @param pid Process ID used for key generation
 * @param keybuf Buffer to store the generated key (Windows only)
 * @param bufsz Size of the key buffer (Windows only)
 * @return Platform-specific shared memory key
 * @retval On Windows: Returns keybuf containing the generated key string
 * @retval On POSIX: Returns the generated key_t value
 *
 * @note On Windows, the key is formatted as "Local\\filename.pid"
 * @note On POSIX, the filename must be an existing, accessible file
 */
shmkey_t shmipc_keygen(const char* filename, int pid, char* keybuf, size_t bufsz);

/**
 * @brief Create a shared memory segment
 *
 * Creates a shared memory segment with the specified key and initializes it with
 * the provided data. If the segment already exists, it may be recreated depending
 * on the platform implementation.
 *
 * @param key Shared memory key obtained from shmipc_keygen()
 * @param copydata Pointer to data to copy into the shared memory segment
 * @param copysize Size of data to copy
 * @param maxsize Maximum size of the shared memory segment
 * @param offset Offset within the segment where data should be copied
 * @return Handle to the created shared memory segment
 * @retval shmipc_invalid_handle on error (check errno for details)
 *
 * @note If maxsize is smaller than copysize, it will be increased to copysize
 * @note On POSIX systems, if the segment exists, it will be removed and recreated
 */
shmhandle_t shmipc_create(const shmkey_t key, const void* copydata, size_t copysize, size_t maxsize, size_t offset);

/**
 * @brief Read data from a shared memory segment
 *
 * Reads data from the specified shared memory segment into the provided buffer.
 *
 * @param key Shared memory key obtained from shmipc_keygen()
 * @param readbuf Buffer to store the read data
 * @param readbytes Number of bytes to read
 * @param offset Offset within the segment to start reading from
 * @return Operation status
 * @retval 0 on success
 * @retval -1 on error (check errno for details)
 */
int shmipc_read(const shmkey_t key, void* readbuf, size_t readbytes, size_t offset);

/**
 * @brief Destroy a shared memory segment
 *
 * Releases resources associated with a shared memory segment and invalidates the handle.
 *
 * @param hp Pointer to the shared memory handle
 * @post The handle is set to shmipc_invalid_handle
 *
 * @note This function is safe to call multiple times on the same handle
 * @note After destruction, the handle should not be used
 */
void shmipc_destroy(shmhandle_t* hp);

#ifdef __cplusplus
}
#endif
#endif /* SHMIPC_H__ */
