/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file shmmbuf.h
 * @brief Multi-process and multi-thread safe shared memory I/O implementation
 *         for Windows(Cygwin)/Linux (POSIX.1-2008, glibc 2.12+)
 *
 * This header provides a ring buffer implementation in shared memory for efficient IPC.
 * Features include:
 *   - Atomic operations using process mutexes
 *   - Cryptographic token protection for secure access
 *   - Semaphore-based signaling
 *   - Lock-free state management
 *   - Wrap-around ring buffer implementation
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 anomura.cc All Rights Reserved.
 * @version 1.0.32
 * @since 2020-05-01 12:46:50
 * @date 2025-12-06 22:02:59
 *
 * @note Defines DEBUG_PRINT_ENABLED before inclusion to enable print for debug
 */
#ifndef SHMMBUF_H__
#define SHMMBUF_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>
#include <stdint.h>

/* Type definitions */
/** @brief 8-byte token type for cryptographic operations */
typedef uint64_t ub8token_t;

/** @brief Opaque handle to a shared memory buffer entry */
typedef struct _shmmbuf_entry_t* shmmbuf_entry;

/** @brief Opaque handle to a shared memory mapped buffer */
typedef struct _shmmap_buffer_t* shmmap_buffer;

#define SHMMBUF_FILENAME_DEFAULT   "shmmap-buffer-default"
#define SHMMBUF_FILEMODE_DEFAULT   0666

/* Return codes for buffer creation */
#define SHMMBUF_CREATE_SUCCESS      0
#define SHMMBUF_CREATE_ERROPEN     (1)
#define SHMMBUF_CREATE_ERRMMAP     (2)
#define SHMMBUF_CREATE_ERRSIZE     (3)
#define SHMMBUF_CREATE_ERRTRUNC    (4)
#define SHMMBUF_CREATE_ERRTOKEN    (5)
#define SHMMBUF_CREATE_FAILED      (-1)  /* Should never run to this! */

/* Return codes for write operations */
#define SHMMBUF_WRITE_SUCCESS     ((int)(1))
#define SHMMBUF_WRITE_AGAIN       ((int)(0))
#define SHMMBUF_WRITE_FATAL       ((int)(-1))

/* Return codes for read operations */
#define SHMMBUF_READ_NEXT         ((int)(1))
#define SHMMBUF_READ_AGAIN        ((int)(0))
#define SHMMBUF_READ_FATAL        ((int)(-1))

/* Default configuration */
#define SHMMBUF_SEMAPHORE_MAXVAL  65535

/* Core constants (should not be changed) */
#define SHMMBUF_PAGE_SIZE        ((size_t)4096)
#define SHMMBUF_INVALID_STATE    ((size_t)(-1))
#define SHMMBUF_TIMEOUT_INFINITE ((size_t)(-1))
#define SHMMBUF_TIMEOUT_NOWAIT   (0)
#define SHMMBUF_ENTRY_HDRSIZE    (sizeof(shmmbuf_entry_t))

/**
 * @brief Create or open a shared memory mapped buffer
 *
 * @param[out] outshmbuf Pointer to receive the created buffer handle
 * @param[in] shmfilename Name/path of the shared memory file
 * @param[in] filemode File permissions (POSIX only)
 * @param[in] filesize Size of the shared memory buffer (0 for existing buffers)
 * @param[in,out] token Pointer to cryptographic token (can be modified by cipher callbacks)
 * @param[in] encipher_cb Optional encryption callback function
 * @param[in] decipher_cb Optional decryption callback function
 *
 * @return Creation status code (SHMMBUF_CREATE_* constants)
 *
 * @note If filesize is 0, an existing buffer will be opened
 * @note The token is used for cryptographic verification of buffer access
 */
int shmmap_buffer_create(shmmap_buffer* outshmbuf, const char* shmfilename, int filemode, size_t filesize,
    ub8token_t* token,
    ub8token_t(*encipher_cb)(const ub8token_t magic, ub8token_t* token),
    ub8token_t(*decipher_cb)(const ub8token_t magic, ub8token_t* token));

/**
 * @brief Close and release resources for a shared memory buffer
 *
 * @param[in] shmbuf Shared memory buffer handle to close
 *
 * @note After calling this function, the handle becomes invalid
 */
void shmmap_buffer_close(shmmap_buffer shmbuf);

/**
 * @brief Delete a shared memory file
 *
 * @param[in] shmfilename Name/path of the shared memory file to delete
 *
 * @return Operation status (0 = success, -1 = failure)
 */
int shmmap_buffer_delete(const char* shmfilename);

/**
 * @brief Verify cryptographic token validity
 *
 * @param[in] shmbuf Shared memory buffer handle
 * @param[in] token Token to verify
 * @param[in] decipher_cb Optional custom decipher callback
 *
 * @return Verification result (1 = valid, 0 = invalid)
 */
int shmmap_verify_token(shmmap_buffer shmbuf, ub8token_t* token, ub8token_t(decipher_cb)(const ub8token_t, ub8token_t*));

/**
 * @brief Write data to the shared memory ring buffer
 *
 * @param[in] shmbuf Shared memory buffer handle
 * @param[in] chunk Data to write
 * @param[in] chunksz Size of data to write
 *
 * @return Write status code (SHMMBUF_WRITE_* constants)
 */
int shmmap_buffer_write(shmmap_buffer shmbuf, const void* chunk, size_t chunksz);

/**
 * @brief Read data from the shared memory ring buffer (copying to provided buffer)
 *
 * @param[in] shmbuf Shared memory buffer handle
 * @param[out] rdbuf Buffer to receive read data
 * @param[in] rdbufsz Size of the receive buffer
 *
 * @return Number of bytes read, or status code if <= 0
 * @retval >0 Number of bytes read (success)
 * @retval 0 (SHMMBUF_READ_AGAIN) Read should be retried
 * @retval -1 (SHMMBUF_READ_FATAL) Fatal read error
 *
 * @note If return value > rdbufsz, the buffer was too small (no data copied)
 */
size_t shmmap_buffer_read_copy(shmmap_buffer shmbuf, char* rdbuf, size_t rdbufsz);

/**
 * @brief Read next entry using a callback (no data copying)
 *
 * @param[in] shmbuf Shared memory buffer handle
 * @param[in] nextentry_cb Callback function to process each entry
 * @param[in] arg User context passed to the callback
 *
 * @return Read status code (SHMMBUF_READ_* constants)
 *
 * @note The callback should not modify the entry contents
 */
int shmmap_buffer_read_next(shmmap_buffer shmbuf, int (*nextentry_cb)(const shmmbuf_entry entry, void* arg), void* arg);

/**
 * @brief Read multiple entries using a callback
 *
 * @param[in] shmbuf Shared memory buffer handle
 * @param[in] nextentry_cb Callback function to process each entry
 * @param[in] arg User context passed to the callback
 * @param[in] batch Maximum number of entries to read
 *
 * @return Number of entries successfully read, or error code if negative
 */
int shmmap_buffer_read_next_batch(shmmap_buffer shmbuf, int (*nextentry_cb)(const shmmbuf_entry entry, void* arg), void* arg, int batch);

/**
 * @brief Signal semaphore (producer notification)
 *
 * @param[in] shmbuf Shared memory buffer handle
 * @param[in] timeout_us Timeout in microseconds (platform-dependent usage)
 *
 * @return Operation status (0 = success, -1 = failure)
 */
int shmmap_buffer_post(shmmap_buffer shmbuf, size_t timeout_us);

/**
 * @brief Wait on semaphore (consumer blocking)
 *
 * @param[in] shmbuf Shared memory buffer handle
 * @param[in] timeout_us Timeout in microseconds
 *
 * @return Wait result code (platform-specific)
 */
int shmmap_buffer_wait(shmmap_buffer shmbuf, size_t timeout_us);

/**
 * @brief Force unlock state locks (emergency recovery)
 *
 * @param[in] shmbuf Shared memory buffer handle
 * @param[in] statelock Lock flags to unlock (SHMMBUF_*_LOCK constants)
 *
 * @note Use with extreme caution - all applications should be paused first
 */
void shmmap_buffer_force_unlock(shmmap_buffer shmbuf, int statelock);

#ifdef __cplusplus
}
#endif

#endif /* SHMMBUF_H__ */
