/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file timeapi.h
 * @brief
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 anomura.cc All Rights Reserved.
 * @version 0.0.65
 *
 * @since 2017-08-28 11:12:10
 * @date 2025-12-06 22:02:59
 *
 * @note
 */
#ifndef TIMEAPI_H__
#define TIMEAPI_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "uatomic.h"
#include "emerglog.h"

#define TIMEZONE_FORMAT_UTC    "+0000"

/* +0000, +0800, -0200 */
#define TIMEZONE_FORMAT_SIZE   16  // at least: 6
#define DATATIME_FORMAT_SIZE   48  // at least: 24


#if defined(PLATFORM_WINDOWS)

/**
 * @brief Suspends execution for a specified number of milliseconds.
 * @param milliseconds Number of milliseconds to sleep.
 */
STATIC_INLINE void sleep_msec(int milliseconds)
{
    Sleep(milliseconds);
}

/**
 * @brief Suspends execution for a specified number of microseconds.
 * @param microseconds Number of microseconds to sleep.
 */
STATIC_INLINE void sleep_usec(int microseconds)
{
    int ms = microseconds / 1000;
    int us = microseconds % 1000;

    if (ms > 0) {
        Sleep(ms);
    }

    if (us > 0) {
        LARGE_INTEGER lval = { 0 };
        LONGLONG startTime;
        double cpuFreq, delayTimeUs = 0;

        // get cpuFreq
        if (!QueryPerformanceFrequency(&lval)) {
            return;
        }
        cpuFreq = (double)lval.QuadPart;
        if (cpuFreq < 1000) {
            return;
        }

        // get startTime
        if (!QueryPerformanceCounter(&lval)) {
            return;
        }
        startTime = lval.QuadPart;

        do {
            cpu_pause();
            if (!QueryPerformanceCounter(&lval)) {
                return;
            }
            delayTimeUs = (((double)(lval.QuadPart - startTime)) / cpuFreq) * 1000000;
        } while (delayTimeUs < us);
    }
}

#else /* non-windows: Linux or Cygwin */

/* sleep in milliseconds */
STATIC_INLINE void sleep_msec(int milliseconds)
{
    if (milliseconds > 0) {
        struct timespec ts;
        ts.tv_sec = milliseconds / 1000;
        ts.tv_nsec = (milliseconds % 1000) * 1000000;
        nanosleep(&ts, 0);
    }
}

/* sleep in micro seconds, do not use usleep */
STATIC_INLINE void sleep_usec(int microseconds)
{
    if (microseconds > 0) {
        /**
        * 1 sec = 1000 ms (millisec)
        * 1 ms = 1000 us (microsec)
        * 1 us = 1000 ns (nanosec)
        * 1 sec = 1000 000 000 ns (nanosec)
        */
        struct timespec ts;

        ts.tv_sec = microseconds / 1000000;
        ts.tv_nsec = (microseconds % 1000000) * 1000;

        // 处理可能被信号中断的情况
        while (nanosleep(&ts, &ts) == -1 && errno == EINTR) {
            continue;
        }
    }
}
#endif // End of Platform-Spec

/**
 * @brief Formats a timezone offset into a string representation.
 * @param tz Timezone offset in seconds.
 * @param tzfmt Buffer to store the formatted timezone string (minimum 6 bytes).
 * @return Pointer to the formatted timezone string.
 */
const char *timezone_format(long tz, char *tzfmt);

/**
 * @brief Computes timezone offset for a given timestamp.
 * @param ts Timestamp to compute timezone for.
 * @param tzfmt Buffer to store formatted timezone string (optional, can be NULL).
 * @return Timezone offset in seconds.
 */
long timezone_compute(time_t ts, char *tzfmt);

/**
 * @brief Determines if daylight saving time is in effect for a given timestamp.
 * @param ts Timestamp to check.
 * @return 1 if DST is in effect, 0 otherwise.
 */
int daylight_compute(time_t ts);

/**
 * @brief Gets the current time with high resolution.
 * @param now Pointer to timespec structure to store the current time.
 */
void getnowtimeofday(struct timespec *now);

/**
 * @brief Get monotonic time in microseconds
 *
 * This function returns a monotonically increasing time value that is not
 * affected by system clock adjustments. The time is measured from an
 * arbitrary point in the past and will never decrease.
 *
 * @param now Pointer to timespec structure to be filled with the current time
 * @return uint64_t Time in microseconds since an arbitrary point in the past,
 *         or (uint64_t)(-1) on error
 */
uint64_t getmonotonictime(struct timespec *now);

/**
 * @brief Converts a timestamp to local time in a thread-safe manner.
 * @param loc Pointer to tm structure to store the local time.
 * @param t Timestamp to convert.
 * @param tz Timezone offset in seconds.
 * @param dst Daylight saving time indicator (0 = not in effect, 1 = in effect).
 * @note taken from: redis/src/localtime.c
 *   Although localtime_s on windows is a bit faster than getlocaltime_safe,
 *   here we use getlocaltime_safe due to it cross-platforms.
 */
void getlocaltime_safe(struct tm *loc, int64_t t, int tz, int dst);

/**
 * @brief Calculates time difference between two timespec structures in milliseconds.
 * @param oldtms Older timepoint (NULL to use current time or single time value).
 * @param newtms Newer timepoint (NULL to use current time or single time value).
 * @return Time difference in milliseconds as 64-bit signed integer.
 */
int64_t difftime_msec(const struct timespec *oldtms, const struct timespec *newtms);

/**
 * @brief Formats the current time as a UTC timestamp string.
 * @param datefmt Buffer to store the formatted time string (minimum 24 bytes).
 * @return Pointer to the formatted time string.
 */
const char * format_nowtimeofday(char *datefmt);

/**
 * Converts 10-nanosecond units to timespec structure.
 * @param time_10ns Time in 10-nanosecond units
 * @param ts Output timespec structure
 */
void timespec_from_10ns(double time_10ns, struct timespec* ts);

/**
 * Converts timespec structure to 10-nanosecond units.
 * @param ts Input timespec structure
 * @return Time in 10-nanosecond units
 */
double timespec_to_10ns(const struct timespec* ts);

#ifdef __cplusplus
}
#endif

#endif /* TIMEAPI_H__ */
