/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file timeapi.c
 * @brief
 *
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 anomura.cc All Rights Reserved.
 * @version 0.0.66
 *
 * @since 2017-08-28 11:12:10
 * @date 2025-12-06 22:02:59
 *
 * @note
 */
#include "timeapi.h"


const char *timezone_format(long tz, char *tzfmt)
{
    DEBUG_ASSERT(TIMEZONE_FORMAT_SIZE >= 16);

    // 注意: 时区偏移的符号与常规理解相反。东时区为负值，西时区为正值
    char tzchr = '+';

    int hours = tz / 3600;
    int minutes = (tz % 3600) / 60;

    if (hours < 0) {
        hours *= -1;
        minutes *= -1;
    }
    if (tz > 0) {
        tzchr = '-';
    }

    int len = snprintf(tzfmt, TIMEZONE_FORMAT_SIZE, "%c%02d%02d", tzchr, hours, minutes);
    DEBUG_ASSERT(len == 5);

    tzfmt[len] = 0;

    return tzfmt;
}


long timezone_compute(time_t ts, char *tzfmt)
{
    struct tm utc_tm;
    time_t ut;

    // 统一实现，避免平台差异
    #if defined(PLATFORM_WINDOWS)
        if (gmtime_s(&utc_tm, &ts) != 0) {
            return -1;
        }
    #else
        if (!gmtime_r(&ts, &utc_tm)) {
            return -1;
        }
    #endif

    utc_tm.tm_isdst = 0; // 确保不考虑夏令时
    ut = mktime(&utc_tm);

    long tz = (long)difftime(ut, ts);

    if (tzfmt) {
        timezone_format(tz, tzfmt);
    }

    return tz;
}


int daylight_compute(time_t ts)
{
    struct tm tm;
    #if defined(PLATFORM_WINDOWS)
        if (localtime_s(&tm, &ts) != 0) {
            return 0; // 默认返回无夏令时
        }
    #else
        if (!localtime_r(&ts, &tm)) {
            return 0; // 默认返回无夏令时
        }
    #endif
    return tm.tm_isdst > 0 ? 1 : 0;
}

/**
 * @brief Gets the current time with high resolution.
 * @param now Pointer to timespec structure to store the current time.
 */
void getnowtimeofday(struct timespec *now)
{
#if defined(PLATFORM_WINDOWS)
    FILETIME tmfile;
    ULARGE_INTEGER _100nanos;

#if (_WIN32_WINNT >= 0x0602)
    GetSystemTimePreciseAsFileTime(&tmfile);
#else
    GetSystemTimeAsFileTime(&tmfile);
#endif
    _100nanos.LowPart   = tmfile.dwLowDateTime;
    _100nanos.HighPart  = tmfile.dwHighDateTime;
    _100nanos.QuadPart -= 0x19DB1DED53E8000ULL;  // Add ULL suffix

    uint64_t seconds = _100nanos.QuadPart / 10000000ULL;
    uint64_t remainder = _100nanos.QuadPart % 10000000ULL;

    /* 转换为Unix时间戳(从1601-01-01到1970-01-01的100纳秒间隔数) */
    now->tv_sec = (time_t) seconds;
    now->tv_nsec = (long) (remainder * 100ULL);
#else
    if (clock_gettime(CLOCK_REALTIME, now) == -1) {
        // Graceful error handling
        time_t current_time = time(NULL);
        if (current_time != (time_t)(-1)) {
            now->tv_sec = current_time;
            now->tv_nsec = 0;
        } else {
            // Fallback to epoch if time() also fails
            now->tv_sec = 0;
            now->tv_nsec = 0;
            emerglog_error_exit("timeapi.h::getnowtimeofday()", "clock_gettime(...) and time(0) failed");
        }
    }
#endif
}

/**
 * @brief Get monotonic time in microseconds
 * @param now Pointer to timespec structure to be filled with the current time
 */
uint64_t getmonotonictime(struct timespec *now)
{
    static UAtomicBool initialized = 0;

#if defined(PLATFORM_WINDOWS)
    static LARGE_INTEGER freq = {0};
    static BOOL qpfRet = FALSE;

    if (UAtomicIntCompExch(&initialized, 0, 1) == 0) {
        // First thread to enter performs initialization
        qpfRet = QueryPerformanceFrequency(&freq);
        UAtomicIntSet(&initialized, 2);
    }
    // Wait for initialization to complete
    while (UAtomicIntGet(&initialized) < 2) {
        cpu_sched_yield();  // Yield time slice: SwitchToThread()
    }

    LARGE_INTEGER counter;
    if (qpfRet && QueryPerformanceCounter(&counter)) {
        // Safe calculation to avoid integer overflow
        uint64_t remainder = counter.QuadPart % freq.QuadPart;
        now->tv_sec = counter.QuadPart / freq.QuadPart;
        now->tv_nsec = (long)((remainder * 1000000000ULL) / freq.QuadPart);
    } else {
        // Fallback to GetTickCount64 (millisecond precision)
        ULONGLONG ticks = GetTickCount64();
        now->tv_sec = ticks / 1000ULL;
        now->tv_nsec = (ticks % 1000ULL) * 1000000ULL;
    }
#else
    static clockid_t clockId = 0;

    if (UAtomicIntCompExch(&initialized, 0, 1) == 0) {
        // First thread to enter performs initialization
        // Use temporary variable for testing, don't use the input 'now' parameter
        struct timespec test;

    #ifdef CLOCK_MONOTONIC_RAW
        if (clock_gettime(CLOCK_MONOTONIC_RAW, &test) == 0) {
            clockId = CLOCK_MONOTONIC_RAW;
        } else if (clock_gettime(CLOCK_MONOTONIC, &test) == 0) {
            clockId = CLOCK_MONOTONIC;
        }
    #else
        if (clock_gettime(CLOCK_MONOTONIC, &test) == 0) {
            clockId = CLOCK_MONOTONIC;
        }
    #endif

        UAtomicIntSet(&initialized, 2);
    }

    // Wait for initialization to complete
    while (UAtomicIntGet(&initialized) < 2) {
        cpu_sched_yield();  // Yield time slice
    }

    if (!clockId || clock_gettime(clockId, now) == -1) {
        // Critical error: system monotonic clock unavailable
        return (uint64_t)(-1);
    }
#endif

    // Return time in microseconds on success
    return (uint64_t)now->tv_sec * 1000000ULL + (uint64_t)now->tv_nsec / 1000ULL;
}

/**
 * taken from: redis/src/localtime.c
 *   although localtime_s on windows is a bit faster than getlocaltime_safe,
 *   here we use getlocaltime_safe due to it cross-platforms.
 */
void getlocaltime_safe(struct tm *loc, int64_t t, int tz, int dst)
{
/**
 * A year not divisible by 4 is not leap.
 * If div by 4 and not 100 is surely leap.
 * If div by 100 *and* 400 is not leap.
 * If div by 100 and not by 400 is leap.
 */
#define YEAR_IS_LEAPYEAR(year) ((year) % 4 ? 0 : ((year) % 100 ? 1 : ((year) % 400 ? 0 : 1)))
#define SECONDS_PER_MINUTE ((time_t)60)
#define SECONDS_PER_HOUR ((time_t)3600)
#define SECONDS_PER_DAY ((time_t)86400)

    /* We need to calculate in which month and day of the month we are. To do
     * so we need to skip days according to how many days there are in each
     * month, and adjust for the leap year that has one more day in February.
     */
    static const int mean_mdays[12] = {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
    static const int leap_mdays[12] = {31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};

    /* Adjust for timezone. 0 for UTC */
    t -= tz;

    /* Adjust for daylight time. 0 default */
    t += 3600 * dst;

    /* Days passed since epoch. */
    int64_t days = t / SECONDS_PER_DAY;

    /* Remaining seconds. */
    int64_t seconds = t % SECONDS_PER_DAY;

    loc->tm_isdst = dst;
    loc->tm_hour = (int)(seconds / SECONDS_PER_HOUR);
    loc->tm_min = (int)((seconds % SECONDS_PER_HOUR) / SECONDS_PER_MINUTE);
    loc->tm_sec = (int)((seconds % SECONDS_PER_HOUR) % SECONDS_PER_MINUTE);

    /* 1/1/1970 was a Thursday, that is, day 4 from the POV of the tm structure
     * where sunday = 0, so to calculate the day of the week we have to add 4
     * and take the modulo by 7. */
    loc->tm_wday = (int)((days + 4) % 7);

    /* Calculate the current year. */
    loc->tm_year = 1970;

    while (1) {
        /* Leap years have one day more. */
        int64_t days_this_year = 365 + YEAR_IS_LEAPYEAR(loc->tm_year);
        if (days_this_year > days)
            break;
        days -= days_this_year;
        loc->tm_year++;
    }

    /* Number of day of the current year. */
    loc->tm_yday = (int)days;
    loc->tm_mon = 0;

    if (YEAR_IS_LEAPYEAR(loc->tm_year)) {
        while (days >= leap_mdays[loc->tm_mon]) {
            days -= leap_mdays[loc->tm_mon];
            loc->tm_mon++;
        }
    } else {
        while (days >= mean_mdays[loc->tm_mon]) {
            days -= mean_mdays[loc->tm_mon];
            loc->tm_mon++;
        }
    }

    /* Add 1 since our 'days' is zero-based. */
    loc->tm_mday = (int)(days + 1);

    /* Surprisingly tm_year is year-1900. */
    loc->tm_year -= 1900;

#undef SECONDS_PER_MINUTE
#undef SECONDS_PER_HOUR
#undef SECONDS_PER_DAY
#undef YEAR_IS_LEAPYEAR
}

/**
 * 计算两个timespec结构体之间的时间差（毫秒），或单个时间/当前时间的毫秒表示。
 * 参数：
 *   oldtms - 旧时间点。若与newtms同时提供，则计算两者差值；若单独提供，则返回其时间值的毫秒数。
 *   newtms - 新时间点。若与oldtms同时提供，则计算两者差值；若单独提供，则返回其时间值的毫秒数。
 *           若两者均为NULL，则返回当前时间的毫秒数。
 * 返回值：
 *   时间差或时间值的毫秒数，以sb8类型（有符号64位整数）返回，可能为负数。
 */
int64_t difftime_msec(const struct timespec *oldtms, const struct timespec *newtms)
{
    int64_t sec = 0;   // 存储秒数部分
    int64_t nsec = 0;  // 存储纳秒部分

    // 根据参数情况计算sec和nsec的值
    if (!oldtms && !newtms) {
        /* get current timestamp in ms */
        struct timespec now;
        getnowtimeofday(&now);
        sec = now.tv_sec;
        nsec = now.tv_nsec;
    } else if (oldtms && newtms) {
        sec = (int64_t)(newtms->tv_sec - oldtms->tv_sec);
        nsec = (int64_t)(newtms->tv_nsec - oldtms->tv_nsec);
    } else if (newtms) {
        sec = (int64_t)(newtms->tv_sec);
        nsec = (int64_t)(newtms->tv_nsec);
    } else if (oldtms) {
        sec = (int64_t)(oldtms->tv_sec);
        nsec = (int64_t)(oldtms->tv_nsec);
    }

    if (sec > 0) {
        if (nsec >= 0) {
            return ((sec * 1000UL) + nsec / 1000000UL);
        } else { /* nsec < 0 */
            return (sec - 1) * 1000UL + (nsec + 1000000000UL) / 1000000UL;
        }
    } else if (sec < 0) {
        if (nsec <= 0) {
            return ((sec * 1000UL) + nsec / 1000000UL);
        } else{ /* nsec > 0 */
            return (sec + 1) * 1000UL + (nsec - 1000000000UL) / 1000000UL;
        }
    } else { /* sec = 0 */
        return nsec / 1000000UL;
    }
}


const char * format_nowtimeofday(char *datefmt)
{
    struct timespec now;
    struct tm loc;

    DEBUG_ASSERT(DATATIME_FORMAT_SIZE > 23);

    getnowtimeofday(&now);
    getlocaltime_safe(&loc, now.tv_sec, 0, 0);

    int len = snprintf(datefmt, DATATIME_FORMAT_SIZE, "%04d-%02d-%02d %02d:%02d:%02d UTC",
        loc.tm_year + 1900, loc.tm_mon + 1, loc.tm_mday, loc.tm_hour, loc.tm_min, loc.tm_sec);

    DEBUG_ASSERT(len == 23);

    datefmt[len] = 0;
    return datefmt;
}


void timespec_from_10ns(double time_10ns, struct timespec *ts)
{
    if (time_10ns > 0) {
        uint64_t time_ns = (uint64_t) (time_10ns * 10);
        ts->tv_sec = (time_t) (time_ns / 1000000000ULL);
        ts->tv_nsec = (long) (time_ns % 1000000000ULL);
    } else {
        ts->tv_sec = 0;
        ts->tv_nsec = 0;
    }
}


double timespec_to_10ns(const struct timespec *ts)
{
    // 秒转换为10纳秒单位
    double to_10ns = (double)ts->tv_sec * 100000000.0;

    // 纳秒转换为10纳秒单位，使用四舍五入
    double nsec_10ns = (double) ts->tv_nsec / 10.0;

    to_10ns += nsec_10ns;

    return to_10ns;
}
