/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file uatomic.h
 * @brief CAS atomic api both for Windows and Linux, macOS
 *
 * Usage:
 *   UAtomicInt  i;
 *   UAtomicIntSet(&i, 0);
 *   UAtomicIntAdd(&i);  // 返回 i
 *
 * @author Liang Zhang <350137278@qq.com>
 * @copyright © 2024-2025 anomura.cc All Rights Reserved.
 * @version 0.1.12
 * @since 2019-12-15 12:46:50
 * @date 2025-12-06 22:02:59
 */
#ifndef UATOMIC_H__
#define UATOMIC_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "platforms.h"  // 包含平台定义和stdatomic.h检测
#include "cpu_pause.h"  // cpu_pause_backoff()

// 定义宏用于控制是否使用旧版__sync系列原子操作（默认使用新版__atomic）
#ifndef USE_LEGACY_ATOMIC_OPS
    #define USE_LEGACY_ATOMIC_OPS  0  // 0: 使用__atomic系列, 1: 使用__sync系列
#endif

// 首先检查编译器对 C11 原子的支持
//   gcc -std=c11 -dM -E - < /dev/null
#if defined(__STDC_NO_ATOMICS__)
    // 编译器明确声明不支持 C11 原子
    #define STD_ATOMIC_SUPPORTED 0
    //?/#warning "Compiler does not support <stdatomic.h>"
#else
    // 检查 C11 版本支持
    #if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
        // C11 或更新版本，尝试包含原子头文件
        #define STD_ATOMIC_SUPPORTED 1

        // 包含原子头文件
        #include <stdatomic.h>

        // 可选：检查特定的原子类型和操作是否可用
        #if !defined(ATOMIC_BOOL_LOCK_FREE) || !defined(ATOMIC_INT_LOCK_FREE)
            #warning "C11 atomic types may not be fully supported"
        #endif

        // 可选：进一步检查编译器是否真的支持原子操作
        #if defined(__GNUC__) && (__GNUC__ < 4) || (__GNUC__ == 4 && __GNUC_MINOR__ < 9)
            #warning "GCC version may have incomplete C11 atomic support"
        #endif
    #else
        // C11 之前的版本
        #define STD_ATOMIC_SUPPORTED 0
    #endif
#endif


// 编译时断言检查
#if STD_ATOMIC_SUPPORTED == 1
    // 验证基本的原子类型是否定义
    #if !defined(atomic_int) || !defined(atomic_bool)
        #error "Basic atomic types not defined after including <stdatomic.h>"
    #endif

    typedef _Atomic int  UAtomicInt;
    typedef _Atomic int64_t  UAtomicInt64;
    typedef _Atomic void* UAtomicPtr;
    typedef _Atomic uint64_t Counter64_t;

    ///////////////////////
    // UAtomicInt API
    ///////////////////////

    // 基本操作
    #define UAtomicIntSet(a, newval)     atomic_store_explicit((a), (newval), memory_order_seq_cst)
    #define UAtomicIntGet(a)             atomic_load_explicit((a), memory_order_seq_cst)
    #define UAtomicIntZero(a)            atomic_store_explicit((a), 0, memory_order_seq_cst)

    // 返回旧值
    #define UAtomicIntCompExch(a, comp, exch)  ({ \
            int expected = (comp); \
            atomic_compare_exchange_strong_explicit((a), &expected, (exch), \
                memory_order_seq_cst, memory_order_seq_cst); \
            expected; /* 返回旧值 */ \
        })

    // 返回旧值
    #define UAtomicIntAdd(a)        atomic_fetch_add_explicit((a), 1, memory_order_seq_cst)
    #define UAtomicIntSub(a)        atomic_fetch_sub_explicit((a), 1, memory_order_seq_cst)
    #define UAtomicIntAdd_n(a, n)    atomic_fetch_add_explicit((a), (n), memory_order_seq_cst)
    #define UAtomicIntSub_n(a, n)    atomic_fetch_sub_explicit((a), (n), memory_order_seq_cst)

    ///////////////////////
    // UAtomicInt64
    ///////////////////////

    // 基本操作
    #define UAtomicInt64Set(a, newval)     atomic_store_explicit((a), (newval), memory_order_seq_cst)
    #define UAtomicInt64Get(a)             atomic_load_explicit((a), memory_order_seq_cst)
    #define UAtomicInt64Zero(a)            atomic_store_explicit((a), 0, memory_order_seq_cst)

    // 返回旧值
    #define UAtomicInt64CompExch(a, comp, exch)  ({ \
            int64_t expected = (comp); \
            atomic_compare_exchange_strong_explicit((a), &expected, (exch), \
                memory_order_seq_cst, memory_order_seq_cst); \
            expected; /* 返回旧值 */ \
        })

    // 返回旧值
    #define UAtomicInt64Add(a)        atomic_fetch_add_explicit((a), 1, memory_order_seq_cst)
    #define UAtomicInt64Sub(a)        atomic_fetch_sub_explicit((a), 1, memory_order_seq_cst)
    #define UAtomicInt64Add_n(a, n)    atomic_fetch_add_explicit((a), (n), memory_order_seq_cst)
    #define UAtomicInt64Sub_n(a, n)    atomic_fetch_sub_explicit((a), (n), memory_order_seq_cst)

    ///////////////////////
    // UAtomicPtr API
    ///////////////////////

    #define UAtomicPtrSet(a, newval)     atomic_store_explicit((UAtomicPtr*)(a), (void*)(newval), memory_order_seq_cst)
    #define UAtomicPtrGet(a)             atomic_load_explicit((UAtomicPtr*)(a), memory_order_seq_cst)
    #define UAtomicPtrZero(a)            atomic_store_explicit((UAtomicPtr*)(a), NULL, memory_order_seq_cst)

    #define UAtomicPtrCompExch(a, comp, exch)  ({ \
            void* expected = (comp); \
            atomic_compare_exchange_strong_explicit((UAtomicPtr*)(a), &expected, (void*)(exch), \
                memory_order_seq_cst, memory_order_seq_cst); \
            expected; \
        })

    ///////////////////////
    // 宽松设置和取得
    ///////////////////////

    #define UAtomicIntSaveRelaxed(a, newval)     atomic_store_explicit((a), (int)(newval), memory_order_relaxed)
    #define UAtomicIntLoadRelaxed(a)             atomic_load_explicit((a), memory_order_relaxed)
    #define UAtomicInt64SaveRelaxed(a, newval)   atomic_store_explicit((a), (int64_t)(newval), memory_order_relaxed)
    #define UAtomicInt64LoadRelaxed(a)           atomic_load_explicit((a), memory_order_relaxed)

#else
    #if defined(PLATFORM_LINUX) || defined(PLATFORM_CYGWIN) || defined(PLATFORM_MACOS)
        // GCC/Clang 内置原子操作
        typedef volatile int      UAtomicInt;
        typedef volatile int64_t  UAtomicInt64;
        typedef volatile void* UAtomicPtr;
        typedef volatile uint64_t Counter64_t;

        ///////////////////////
        // UAtomicInt API
        ///////////////////////

        // 基本操作
        #if USE_LEGACY_ATOMIC_OPS
            #define UAtomicIntSet(a, newval)     __sync_lock_test_and_set((a), (newval))
            #define UAtomicIntGet(a)             __sync_fetch_and_add((a), 0)
            #define UAtomicIntZero(a)            __sync_lock_release((a))  // 注意: 此操作实际是释放锁, 语义不完全等价置零
        #else
            // 设置原子整数的值
            #define UAtomicIntSet(a, newval)       __atomic_store_n((a), (newval), __ATOMIC_SEQ_CST)
            // 获取原子整数的值
            #define UAtomicIntGet(a)               __atomic_load_n((a), __ATOMIC_SEQ_CST)
            // 将原子整数置零
            #define UAtomicIntZero(a)              __atomic_store_n((a), 0, __ATOMIC_SEQ_CST)
        #endif

        // 返回旧值
        #define UAtomicIntCompExch(a, comp, exch)  __sync_val_compare_and_swap((a), (comp), (exch))
        #define UAtomicIntAdd(a)        __sync_fetch_and_add((a), 1)
        #define UAtomicIntSub(a)        __sync_fetch_and_sub((a), 1)
        #define UAtomicIntAdd_n(a, n)   __sync_fetch_and_add((a), (int)(n))
        #define UAtomicIntSub_n(a, n)   __sync_fetch_and_sub((a), (int)(n))

        ///////////////////////
        // UAtomicInt64 API
        ///////////////////////

        // 基本操作
        #if USE_LEGACY_ATOMIC_OPS
            #define UAtomicInt64Set(a, newval)     __sync_lock_test_and_set((a), (newval))
            #define UAtomicInt64Get(a)             __sync_fetch_and_add((a), 0)
            #define UAtomicInt64Zero(a)            __sync_lock_release((a))  // 注意: 此操作实际是释放锁, 语义不完全等价置零
        #else
            // 设置原子64位整数的值
            #define UAtomicInt64Set(a, newval)       __atomic_store_n((a), (newval), __ATOMIC_SEQ_CST)
            // 获取原子64位整数的值
            #define UAtomicInt64Get(a)               __atomic_load_n((a), __ATOMIC_SEQ_CST)
            // 将原子64位整数置零
            #define UAtomicInt64Zero(a)              __atomic_store_n((a), 0LL, __ATOMIC_SEQ_CST)
        #endif

        // 返回旧值
        #define UAtomicInt64CompExch(a, comp, exch)  __sync_val_compare_and_swap((a), (comp), (exch))
        #define UAtomicInt64Add(a)        __sync_fetch_and_add((a), 1)
        #define UAtomicInt64Sub(a)        __sync_fetch_and_sub((a), 1)
        #define UAtomicInt64Add_n(a, n)    __sync_fetch_and_add((a), (int64_t)(n))
        #define UAtomicInt64Sub_n(a, n)    __sync_fetch_and_sub((a), (int64_t)(n))

        ///////////////////////
        // UAtomicPtr API
        ///////////////////////
        // 返回旧值
        #define UAtomicPtrCompExch(a, comp, exch)  __sync_val_compare_and_swap((void**)(a), (void*)(comp), (void*)(exch))

        #if USE_LEGACY_ATOMIC_OPS
            #define UAtomicPtrSet(a, newval)     __sync_lock_test_and_set((void**)(a), (void*)(newval))
            #define UAtomicPtrGet(a)             __sync_fetch_and_add((void**)(a), 0)
            #define UAtomicPtrZero(a)            __sync_lock_release((void**)(a))  // 注意: 此操作实际是释放锁, 语义不完全等价置零
        #else
            // 原子设置指针值并返回旧值
            #define UAtomicPtrSet(a, newval)     __atomic_exchange_n((void**)(a), (void*)(newval), __ATOMIC_SEQ_CST)
            // 原子获取指针当前值
            #define UAtomicPtrGet(a)             __atomic_load_n((void**)(a), __ATOMIC_SEQ_CST)
            // 原子将指针置为NULL
            #define UAtomicPtrZero(a)            __atomic_store_n((void**)(a), NULL, __ATOMIC_SEQ_CST)
        #endif

    #elif defined(PLATFORM_WINDOWS)
        // Windows Win32 API
        typedef volatile LONG    UAtomicInt;
        typedef volatile LONG64  UAtomicInt64;
        typedef volatile PVOID   UAtomicPtr;
        typedef volatile ULONG64 Counter64_t;

        ///////////////////////
        // UAtomicInt API
        ///////////////////////

        // 基本操作
        #define UAtomicIntSet(a, newval)   InterlockedExchange(a, (LONG)(newval))
        #define UAtomicIntGet(a)           InterlockedCompareExchange(a, 0, 0)
        #define UAtomicIntZero(a)          InterlockedExchange(a, 0)

        // 返回旧值
        #define UAtomicIntCompExch(a, comp, exch)    InterlockedCompareExchange(a, (exch), (comp))
        #define UAtomicIntAdd(a)   InterlockedExchangeAdd(a, 1)
        #define UAtomicIntSub(a)   InterlockedExchangeAdd(a, -1)
        #define UAtomicIntAdd_n(a, n)    InterlockedExchangeAdd(a, ((LONG)(n)))
        #define UAtomicIntSub_n(a, n)    InterlockedExchangeAdd(a, -((LONG)(n)))

        ///////////////////////
        // UAtomicInt64 API
        ///////////////////////

        // 基本操作
        #define UAtomicInt64Set(a, newval) InterlockedExchange64(a, (newval))
        #define UAtomicInt64Get(a)         InterlockedCompareExchange64(a, 0, 0)
        #define UAtomicInt64Zero(a)        InterlockedExchange64(a, 0)

        // 返回旧值
        #define UAtomicInt64CompExch(a, comp, exch)    InterlockedCompareExchange64(a, (exch), (comp))
        #define UAtomicInt64Add(a)    InterlockedExchangeAdd64(a, 1)
        #define UAtomicInt64Sub(a)    InterlockedExchangeAdd64(a, -1)
        #define UAtomicInt64Add_n(a, n)    InterlockedExchangeAdd64(a, ((LONG64)(n)))
        #define UAtomicInt64Sub_n(a, n)    InterlockedExchangeAdd64(a, -((LONG64)(n)))

        ///////////////////////
        // UAtomicPtr API
        ///////////////////////

        #define UAtomicPtrSet(a, newval)   InterlockedExchangePointer(a, (newval))
        #define UAtomicPtrGet(a)           InterlockedCompareExchangePointer(a, 0, 0)
        #define UAtomicPtrZero(a)          InterlockedExchangePointer(a, 0)
        #define UAtomicPtrCompExch(a, comp, exch)  InterlockedCompareExchangePointer(a, (exch), (comp))
    #else
        #error "Currently only Windows, Linux and macOS are supported"
    #endif

    ///////////////////////
    // 非C11平台无法真正实现
    // 宽松内存顺序
    ///////////////////////

    #define UAtomicIntSaveRelaxed  UAtomicIntSet
    #define UAtomicIntLoadRelaxed  UAtomicIntGet
    #define UAtomicInt64SaveRelaxed  UAtomicInt64Set
    #define UAtomicInt64LoadRelaxed  UAtomicInt64Get
#endif

typedef UAtomicInt  UAtomicBool;

#define Counter64Set  UAtomicInt64Set
#define Counter64Get  UAtomicInt64Get

#define Counter64SetRelaxed  UAtomicInt64SaveRelaxed
#define Counter64GetRelaxed  UAtomicInt64LoadRelaxed
#define Counter64AddOne  UAtomicInt64Add

/**
 * @brief 忙等待，获取自旋锁，一直等待直到成功
 * @param spinlockAddr 自旋锁地址
 * @param spinsMax 最大自选次数 (10)
 * @note
 *  必须成对调用:
 *    UAtomicSpinlockGrab
 *    UAtomicSpinlockFree
 */
STATIC_INLINE void UAtomicSpinlockGrab(UAtomicBool* spinlockAddr, int spinsMax)
{
    int spins = 0;
    while (UAtomicIntCompExch(spinlockAddr, 0, 1)) {
        cpu_pause_backoff(spins, 1024);
        if (spins < spinsMax) {
            ++spins;
        }
        else {
            /* 谨慎使用：sched_yield() 在高度竞争的情况下可能效果有限
                * 适度使用：只在长时间等待后使用，避免频繁的上下文切换开销
                * 性能测试：在实际工作负载中测试是否真的带来性能提升
                */
            cpu_sched_yield();
        }
    }
}

/**
 * @brief 释放自旋锁
 * @param spinlockAddr 自旋锁地址
 * @note
 *  必须成对调用:
 *    UAtomicSpinlockGrab
 *    UAtomicSpinlockFree
 */
STATIC_INLINE void UAtomicSpinlockFree(UAtomicBool* spinlockAddr)
{
    UAtomicIntZero(spinlockAddr);
}

#ifdef __cplusplus
}
#endif

#endif /* UATOMIC_H__ */
