/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file unsema.h
 *  Unnamed Semaphore API for both Windows and Linux
 *
 * @author  Liang Zhang <350137278@qq.com>
 * @copyright © 2024-2025 anomura.cc All Rights Reserved.
 * @version 0.0.21
 * @since 2019-12-12 11:32:50
 * @date 2025-12-06 22:02:59
 */
#ifndef UNSEMA_H__
#define UNSEMA_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "platforms.h"

#if defined(PLATFORM_WINDOWS)
    typedef  HANDLE unsema_t;
#else // non-windows
    #include <semaphore.h>
    typedef  sem_t  unsema_t;
#endif

STATIC_INLINE int unsema_init (unsema_t *sema, int initval)
{
    int err = -1;

#if defined(PLATFORM_WINDOWS)
    unsema_t h = CreateSemaphoreA(NULL, initval, INT32_MAX, NULL);
    if (h) {
        *sema = h;
        err = 0;
    }
#else
    err = sem_init(sema, 0, initval);
#endif

    return err;
}


STATIC_INLINE int unsema_uninit (unsema_t *sema)
{
    int err = -1;

#if defined(PLATFORM_WINDOWS)
    if (CloseHandle(*sema)) {
        *sema = NULL;
        err = 0;
    }
#else
    err = sem_destroy(sema);
#endif

    return err;
}


STATIC_INLINE int unsema_wait (unsema_t *sema)
{
    int err = -1;

#if defined(PLATFORM_WINDOWS)
    if (WAIT_OBJECT_0 == WaitForSingleObject(*sema, INFINITE)) {
        // success
        err = 0;
    } else {
        err = 1;
    }
#else
    err = sem_wait(sema);
#endif

    return err;
}


STATIC_INLINE int unsema_timedwait (unsema_t *sema, unsigned int milliseconds)
{
    int err = -1;

#if defined(PLATFORM_WINDOWS)
    if (WAIT_OBJECT_0 == WaitForSingleObject(*sema, (DWORD) milliseconds)) {
        // success
        err = 0;
    } else {
        // other errors
        err = 1;
    }
#else // Linux
    struct timespec ts;

    #ifdef UNSEMA_USES_GETTIMEOFDAY
        struct timeval tv;
        gettimeofday(&tv, 0);
        ts.tv_sec = tv.tv_sec + milliseconds/1000;
        ts.tv_nsec = tv.tv_usec * 1000 + (milliseconds % 1000) * 1000000;
    #else
        clock_gettime(CLOCK_REALTIME, &ts);
        ts.tv_sec += (milliseconds/1000);
        ts.tv_nsec += ((milliseconds % 1000) * 1000000);
    #endif

    err = sem_timedwait(sema, &ts);
#endif

    return err;
}


STATIC_INLINE int unsema_post (unsema_t *sema)
{
    int err = -1;

#if defined(PLATFORM_WINDOWS)
    if (ReleaseSemaphore(*sema, 1, NULL)) {
        // success
        err = 0;
    }
#else
    err = sem_post(sema);
#endif

    return err;
}


/**
 * get previous value and post
 */
STATIC_INLINE int unsema_postget(unsema_t *sema)
{
#if defined(PLATFORM_WINDOWS)
    LONG lCount;
    if (ReleaseSemaphore(*sema, 1, &lCount)) {
        // success
        return (int) lCount;
    }
#else
    int value;
    if (sem_getvalue(sema, &value) == 0 && sem_post(sema) == 0) {
        // success
        return value;
    }
#endif
    // error
    return (-1);
}


#ifdef __cplusplus
}
#endif

#endif /* UNSEMA_H__ */
